### ISSUE TITLE
Running integration tests: Could not find a valid Docker environment

### ISSUE THREAD

**Issue by micobarac** [jhipster/generator-jhipster#10052]
##### **Overview of the issue**

I get this error when starting integration tests:

`java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration`

I cannot find anywhere in JHipster documentation that integration tests must be run inside Docker.
When I start Docker, tests start, but comparing to older version of JHipster when integration tests were ran without Docker, the dockerized tests run painfully slow...

##### **Motivation for or Use Case**

Upgrade old JHipster project to a new one

##### **Reproduce the error**

```
2019-07-08 09:06:37.847 ERROR   --- [           main] o.t.d.DockerClientProviderStrategy       : Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
2019-07-08 09:06:37.857 ERROR   --- [           main] o.t.d.DockerClientProviderStrategy       :     UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause LastErrorException ([61] Connection refused)
2019-07-08 09:06:37.857 ERROR   --- [           main] o.t.d.DockerClientProviderStrategy       :     UnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause LastErrorException ([61] Connection refused)
2019-07-08 09:06:37.858 ERROR   --- [           main] o.t.d.DockerClientProviderStrategy       :     ProxiedUnixSocketClientProviderStrategy: failed with exception InvalidConfigurationException (ping failed). Root cause TimeoutException (null)
2019-07-08 09:06:37.858 ERROR   --- [           main] o.t.d.DockerClientProviderStrategy       :     DockerMachineClientProviderStrategy: failed with exception InvalidConfigurationException (Exception when executing docker-machine status )
2019-07-08 09:06:37.858 ERROR   --- [           main] o.t.d.DockerClientProviderStrategy       : As no valid configuration was found, execution cannot continue

Test ignored.
```

##### **Suggest a Fix**

Run the integration tests without Docker (without error)

##### **JHipster Version(s)**

`6.1.2`

##### **JHipster Version(s)**

```
openprovider@0.0.0 /Users/milan/Sites/jhipster
└── generator-jhipster@6.1.2

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.logate.openprovider"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "openprovider",
    "packageName": "com.logate.openprovider",
    "packageFolder": "com/logate/openprovider",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "cassandra",
    "devDatabaseType": "cassandra",
    "prodDatabaseType": "cassandra",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "clientPackageManager": "yarn",
    "skipClient": true
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

git version 2.21.0

node: v10.15.3

npm: 6.9.0

yeoman: 3.0.0

yarn: 1.16.0

Docker version 18.09.2, build 6247962

docker-compose version 1.23.2, build 1110ad01

##### **Browsers and Operating System**

macOS Mojave
Version 10.14.5 (18F132)

**Comment by deepu105** [comment]
Do you have Docker installed? for cassandra we use TestContainers and it requires docker to be installed

**Comment by micobarac** [comment]
I started Docker, but I have a problem with dockerized version of Cassandra container. Some tests fail to start, with error message saying that the container cannot be initialized. I used some old code from previous JHipster version with Embedded Cassandra and all tests work just fine. Btw, why is Logstash showing the error that it cannot start?

**Comment by micobarac** [comment]
Building war package I get this error:

`Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode)`

**Comment by micobarac** [comment]
#10065

**Comment by micobarac** [comment]
Any update on this?

**Comment by jdubois** [comment]
On the Docker issue (for Logstash, it seems indeed like a separate issue), you need to install Docker and run the tests through it.
I know it's annoying and slower, but there is no other choice: Datastax is making it very hard to run an embedded Cassandra server (for good reasons, and that's just the consequence), and anyway in its current release Cassandra doesn't work with JDK 11. Have a look in the older tickets, there has been a lot of work on this, and this has been directly made with direct support from Datastax, so we can't really do anything better.

**Comment by PierreBesson** [comment]
As Julien said the Cassandra tests in testcontainers are working. It's possible that you have issues with your docker environment or just the way your tests are structured because you did the upgrade. On a freshly generated app they work fine as is attested by our CI.

**Comment by micobarac** [comment]
OK, I started using Docker along with integration tests. Running Docker service as a prerequisite should be noted inside documentation, btw.

Btw, I'm still having these issues:

- timeout waiting for Cassandra docker container (happens occasionally, after repeating tests)
- Logstash error (happens all the time)

P.S.

Thank you guys for your efforts.

**Comment by DanielFran** [comment]
For the logstash error, there is already an issue opened: https://github.com/jhipster/generator-jhipster/issues/10065

**Comment by micobarac** [comment]
Regarding Cassandra container timeout inside **AbstractCassandraTest**, I increased default startup timeout from 30 to 60 seconds, and the timeout problem seems to have stopped, for now:

```
    private static void startTestcontainer() throws TTransportException, IOException {
        CASSANDRA_CONTAINER =
            new GenericContainer("cassandra:3.11.4")
                .waitingFor(Wait.forListeningPort().withStartupTimeout(Duration.ofSeconds(60)))
                .withExposedPorts(CASSANDRA_TEST_PORT);

        CASSANDRA_CONTAINER.start();
    }
```

**Comment by micobarac** [comment]
I don't see any code for stopping started container after all tests have been done. Should this be considered as a potential problem?

**Comment by PierreBesson** [comment]
@micobarac docker container management and cleanup is delegated to the testcontainer library.

**Comment by ismailrajupro** [comment]
[https://medium.com/@ismailhossainraju74/defeating-the-badrequestexception-in-testcontainers-with-docker-desktop-on-windows-c7cdfaaf7b68](https://medium.com/@ismailhossainraju74/defeating-the-badrequestexception-in-testcontainers-with-docker-desktop-on-windows-c7cdfaaf7b68)

The Solution: Two Paths to Victory
There are two ways to solve this problem: the quick local fix, and the permanent project-wide fix.

1. The Quick Fix: Override the API Version Locally

If you are stuck on an older version of Testcontainers and can’t easily upgrade your project’s dependencies, you can force the `docker-java` client to use a modern API version that Docker Desktop accepts.

You can do this by creating a properties file in your user’s home directory.

1. Navigate to your user home directory (e.g., `C:\Users\YourUser\`).
2. Create a new file named `.docker-java.properties`.
3. Add the following line to the file:

api.version=1.44

Note: Depending on your exact Docker Desktop version, you might need to try `1.43` or `1.45`, but `1.44` is currently a safe bet.

When you run your tests again, the `docker-java` client will read this file, use the newer API version, and successfully bypass the Docker Desktop proxy block.

2. The Permanent Fix: Upgrade Testcontainers

The most robust solution is simply to update the Testcontainers library in your project. The Testcontainers team is aware of these Docker Desktop changes, and newer versions default to a compatible API version.

Update your `pom.xml` or `build.gradle` to use Testcontainers version `1.21.4` or higher (or upgrade to the `2.x` series).

For Gradle(groovy):

testImplementation “org.testcontainers:testcontainers:1.21.4”
testImplementation “org.testcontainers:postgresql:1.21.4” // update related modules too

For Maven(xml):

<dependency>
<groupId>org.testcontainers</groupId>
<artifactId>testcontainers</artifactId>
<version>1.21.4</version>
<scope>test</scope>
</dependency>

Ensure TCP is Exposed

While the API version mismatch is the root cause of the `400 Bad Request`, named pipe connectivity on Windows WSL2 can sometimes be flaky. As a best practice, ensuring your Docker daemon is exposed on TCP provides a reliable fallback for Testcontainers.

1. Open Docker Desktop.
2. Go to Settings > General.
3. Check the box for ”Expose daemon on tcp://localhost:2375 without TLS”.

Debugging Docker networking on Windows can sometimes feel like chasing ghosts. In this case, an error that looked like a bad named-pipe configuration was actually an API version enforcement mechanism by Docker Desktop.

By upgrading Testcontainers or explicitly setting the `api.version` in `.docker-java.properties`, you can appease the Docker Desktop proxy and get your integration tests back to green.

My Docker version was Docker version 29.4.0, build 9d7ad9f .

Jhipster version was 8.5.0.
