### ISSUE TITLE
Avoiding lazy load exception during serialization

### ISSUE THREAD

**Issue by thiagonuic** [jhipster/generator-jhipster#1005]
I have googled it a little bit and people doesn't seem to have a good solution for that, when you what to return the entity. Sometimes you need a calculated field to be shown on the view and you don't want to create a custom DTO for that. 
Another problem is when you create such method and it depends on some properties to be loaded, and then another REST stops working throwing LazyLoad Exception.

So I came up with this solution, instead of returning the entity itself such as:

    public ResponseEntity<User> get(Long id);

or

    public User get(Long id);

You can use return like this:

    public ResponseEntity<?> get(Long id);

And in the REST controller inject a SerializationService:

    @Inject
    private SerializationService serializationService;

The implementation of such service is:

    import com.fasterxml.jackson.core.JsonProcessingException;
    import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter;
    import org.springframework.stereotype.Service;
    
    import javax.inject.Inject;
    
    @Service
    public class SerializationService
    {
        @Inject
        private MappingJackson2HttpMessageConverter mappingJackson2HttpMessageConverter;
    
        public String serialize(Object object)
        {
            try
            {
                return mappingJackson2HttpMessageConverter.getObjectMapper().writeValueAsString(object);
            }
            catch (JsonProcessingException e)
            {
                throw new RuntimeException(e);
            }
        }
    }

And to return the serialized entity do this:

    new ResponseEntity<>(serializationService.serialize(user), HttpStatus.OK);

Do you think this would be a good addition/change to JHipster?

I thought about posting this anyway since I could not find it easily.

**Comment by jdubois** [comment]
This isn't really a JHipster issue : we just provide "standard", out of the box Hibernate, which happens to have this lazy loading feature (which is great most of the time, but can be very surprising otherwise).
If you want to avoid all lazy loading exception, the best solution is to use the OSIV filter provided by Spring Boot -> I haven't used it myself, because I'd rather code my app correctly, but you can turn it on in the application.yml config file, and the end result should be the same as what you propose.
The OSIV filter is a better solution as:

- You don't mix business (service) logic and presentation logic like you have
- It's fully transparent, nothing to code
- It's a standard Spring Boot feature

**Comment by thiagonuic** [comment]
What are the drawbacks of OSIV? Why isn't it enable by default?

**Comment by jdubois** [comment]
It consumes resources. And you should work with lazy loading, not avoid it, if you want better performance.

**Comment by thiagonuic** [comment]
The ideal solution in my opinion is to use something like Java EE 7 JSON API. But the project is in an advanced state, and using such API now would take a long time, soh OSIV might be the best solution  for now.

Java EE 7 JSON API: http://www.developer.com/java/json-processing-in-java-ee7.html
