### ISSUE TITLE
Partial Update of objects using PATCH

### ISSUE THREAD

**Issue by pnujwala** [jhipster/generator-jhipster#10077]
##### **Overview of the feature request**
Currently, only post and put are supported. When put becomes costly, or business rules do not always permit, partial update of data objects is useful

##### **Motivation for or Use Case**

1. Based on authorisation rules, certain users can view/edit only some fields of the object while certain users have full access. Partial update support here becomes handy
2. Cost of large size and volume of DTOs can be minimised

##### **Related issues or PR**

PATCH method support for partial update #1315

-   [ Y ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
No more comments since you opened this ticket.

@pnujwala : what I can suggest is to create a module for that. You'll be the author of the module and maintain it. Have a look at https://www.jhipster.tech/modules/creating-a-module/
If your module is a big success, we can reconsider it.

But for now, as mentionned in the previous ticket, we won't support it in main generator-jhipster. That's why I'm closing this.

**Comment by cbornet** [comment]
There's currently work done on this
