### ISSUE TITLE
ManyToMany-Relationship not clear enough

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#10208]
##### **Overview of the feature request**

https://github.com/jhipster/jdl-samples/blob/master/blog.jh

ManyToMany-Relationship between BlogEntry and Tag is not clear enough

* tag name is not shown on BlogEntrys' view
<img width="1145" alt="Bildschirmfoto 2019-08-11 um 13 09 59" src="https://user-images.githubusercontent.com/4540661/62833100-582cce80-bc39-11e9-9d82-097d14bb2201.png">
* tag name is shown on a BlogEntry's view (which is good)
<img width="1026" alt="Bildschirmfoto 2019-08-11 um 13 07 47" src="https://user-images.githubusercontent.com/4540661/62833088-1e5bc800-bc39-11e9-81f6-96e12c5bb4bf.png">
* When creating a Tag, there is no option to (automatically) assign a pertinent blogEntry --> user maybe confused about the relationship
<img width="1149" alt="Bildschirmfoto 2019-08-11 um 13 08 10" src="https://user-images.githubusercontent.com/4540661/62833090-1e5bc800-bc39-11e9-97a6-34bbdcd07d00.png">
<img width="1131" alt="Bildschirmfoto 2019-08-11 um 13 08 16" src="https://user-images.githubusercontent.com/4540661/62833091-1e5bc800-bc39-11e9-8c8b-c256bd5bb5c4.png">

##### **Related issues or PR**

I don't know if there is a similar request already :)

**Comment by pascalgrimaud** [comment]
I don't understand your ticket. 
- is it a bug ?
- is it a feature request ?

You didn't provide all the information, required in template

**Comment by geyuqiu** [comment]
It is a feature request:

ManyToMany-Relationship between BlogEntry and Tag is not clear enough for the user.

**Comment by pascalgrimaud** [comment]
Everything is explained here: https://www.jhipster.tech/managing-relationships/#-a-many-to-many-relationship

> tag name is not shown on BlogEntrys' view

It's normal as `eagerload` is set to `false`by default. Go to API docs at http://localhost:8080/admin/docs, then try to play with `blog-entry-resource`. You can use `eagerload` to `true`, then, you'll get all the BlogEntry with tags. But you need to custom the front to have it.

> When creating a Tag, there is no option to (automatically) assign a pertinent blogEntry --> user maybe confused about the relationship

It's because it's BlogEntry which manages the relationship. Go and edit the BlogEntry, you'll be able to assign the tag.
For a business use case, it would be very strange for the user to edit a Tag if the user wants to assign a BlogEntry. But if you really want to do that, just try to change the `ManyToMany` relationship:

```
relationship ManyToMany {
  Tag{blogEntry(title)} to BlogEntry{tag}
}
```

**Comment by geyuqiu** [comment]
Thanks :) 
Cheers Yuqiu
