### ISSUE TITLE
JaCoCo .exec file format support has been deprecated in SonarJava

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#10219]
##### **Overview of the issue**

Sonar as deprecated the use of jacoco exec file in favor of xml format

##### **Motivation for or Use Case**

See https://jira.sonarsource.com/browse/MMF-1651

````txt
Drop of JaCoCo .exec file format support

This is scheduled in 6 months, around Sept 2019.
````

##### **Reproduce the error**

See for example https://travis-ci.org/jhipster/generator-jhipster/jobs/571080722#L10462
````sh
[WARNING] Property 'sonar.jacoco.reportPaths' is deprecated (JaCoCo binary format). 'sonar.coverage.jacoco.xmlReportPaths' should be used instead (JaCoCo XML format).
````

##### **Suggest a Fix**

Substitute property 'sonar.jacoco.reportPaths' by 'sonar.coverage.jacoco.xmlReportPaths' and use xml file instead.

##### **JHipster Version(s)**

latest

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
For me it's not a bug, so I'm changing the label, it's your OK @DanielFran :)

**Comment by clement26695** [comment]
I can take a look if you want, @DanielFran

**Comment by DanielFran** [comment]
@clement26695 I started looking at it, but did not have much time, so you can work on it... thanks

**Comment by phshah0116** [comment]
I'm using jacoco cli to dump the coverage into .exec file. For example,

java -jar jacococli.jar dump --port 36300 --destfile=jacoco-it.exec

However, when trying to push it to Sonar, I get following exception. Caused by: javax.xml.stream.XMLStreamException: java.nio.charset.MalformedInputException: Input length = 1

I'm not using maven so can't import jacoco coverage report in xml format. JacocoCli dump documentation doesn't have an option to specify the file format. How I can proceed to push the coverage to Sonar with dump generated using JacocoCli in .exec format or create .xml format using jacoco cli?

share  edit  undelete  flag

**Comment by robli314** [comment]
@phshah0116  I am facing the same issue. Did you find a solution?
