### ISSUE TITLE
generator - selection of java version (supported versions)

### ISSUE THREAD

**Issue by maku** [jhipster/generator-jhipster#10479]
##### **Overview of the feature request**

When I generate a project I would like to select the java version from a list of supported ones.

**Comment by pascalgrimaud** [comment]
We support Java8 and 11. So it should work for both.
I don't see any value of adding a new question because it will imply to:
- add new question
- store a new option in config
- add support in jdl-core
- add full daily builds to test more configs
- add support in all our cloud template
- update start.jhipster.tech
- etc

Too much work for no real value. 
Anyway, we'll drop java8 soon

**Comment by SudharakaP** [comment]
@maku : This has been subjected to debate particularly on the following thread; https://github.com/jhipster/generator-jhipster/issues/9934

I've added support for this initially but later (see the [following comment](https://github.com/jhipster/generator-jhipster/pull/10245#issuecomment-523674891) by @PierreBesson and the [following comment](https://github.com/jhipster/generator-jhipster/pull/10283#issuecomment-530924970) by @pascalgrimaud ) we've decided not to do this. I do see the problems that might arise due to this kind of choice; and do agree with their decision. 

Having said that; the changing of java version is not a difficult one to do manually. 😄

**Comment by maku** [comment]
@SudharakaP  Thanks for answering: https://github.com/jhipster/generator-jhipster/issues/9934 is exactly the kind of problems when "manually" changing the java version... So the first question I asked myself was what I did wrong. And honestly I found not a good answer in documentation etc. (and also in the issues). Maybe it would be a good idea to mention the steps to change the java version in the docu (and potential pitfalls)

**Comment by SudharakaP** [comment]
@maku : The afterburner warning is harmless; you can just ignor it for now. When that PR is merged and when you change the java version you won't see that reflection warning anymore. 😄

**Comment by SudharakaP** [comment]
@maku : You might also see the following warnings; https://github.com/jhipster/generator-jhipster/issues/10271.

**Comment by pascalgrimaud** [comment]
As explained, we won't add this additional question, that's why I'm closing this ticket.
