### ISSUE TITLE
Fake Data for JDL string pattern causes liquidbase error 

### ISSUE THREAD

**Issue by poolebu** [jhipster/generator-jhipster#10513]
##### **Overview of the issue**

For the following JDL descrpition:

The JDL ` String pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)` throws liquid base error when loading fake data.

```
 Reason: liquibase.exception.UnexpectedLiquibaseException: CSV file config/liquibase/fake-data/centro_de_actividad.csv Line 2 has 7 values defined, Header has 5. Numbers MUST be equal (check for unquoted string with embedded commas)
```

The attached [centro_de_actividad.txt](https://github.com/jhipster/jhipster-core/files/3665572/centro_de_actividad.txt) CSV  of fake data is produced, which gives the error, I believe because a `;` is generated in the email field:

This is the first row of the `centro_de_actividad.csv`

```
id;nombre;telefono;nombre_de_contacto;email_de_contacto
1;New York tangible Mississippi;Frozen bus;hard drive Robust Networked;7`fPr4Ps]-8c:1DV<UDz_a>dCnD>HTw">f58Aaw(X'Xbna;J2)15v_z%AIu8d=lA%{W/R}hsJm7cP@F=?#_dVFX=tt$Ncc1+2}{*,_n|WfRcyHrI?zRPHa.Dc0JC8/c9V\DE?oeO}a}>UY
```

##### **Motivation for or Use Case**

I wanted to validate email, and found that regular expression on the web.

##### **Reproduce the error**

Import the following JDL

```
entity CentroDeActividad {
	nombre String required,
    telefono String,
    nombreDeContacto String,
    emailDeContacto String pattern(/^[^@\s]+@[^@\s]+\.[^@\s]+$/)
	
}
```

##### **JHipster Version(s)**

v6.2.0

##### **JHipster configuration**

Use the JDL from above

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Use the JDL from above

##### **Browsers and Operating System**

```
Windows 10 / WSL
```
- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
I moved the issue to the generator repository as the bug and fix will be here.

The issue is that [the regex pattern generation in the fake-data/table.csv.ejs template](https://github.com/jhipster/generator-jhipster/blob/5ec57a8d11b6332558d8c838ba48d87e9600aed8/generators/entity-server/templates/src/main/resources/config/liquibase/fake-data/table.csv.ejs#L156) can generate semicolons if the regex pattern allows.  Semicolons are used as the CSV separator so it breaks.

@poolebu Until this is fixed, a simple workaround is to exclude semicolons from the email address regex.

**Comment by poolebu** [comment]
Got it! Thank You @ruddell , I did that and it works wonders.
