### ISSUE TITLE
jhipster aws seems to be broken

### ISSUE THREAD

**Issue by Simsal** [jhipster/generator-jhipster#10525]
##### **Overview of the issue**

I can't deploy my application to aws via the jhipster aws subgenerator. It fails with the following information.

```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  57.006 s
[INFO] Finished at: 2019-09-30T16:18:27+02:00
[INFO] ------------------------------------------------------------------------

Create S3 bucket
Bucket testjhipster already exists

Upload WAR to S3
War uploaded successful

Create database
Database testjhipster already exists (based on security group)

Waiting for database (This may take several minutes)
/Users/d0253800/Workspace/testjhipster/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: Resource is not in the state dBInstanceAvailable
    at Environment.error (/Users/d0253800/Workspace/testjhipster/node_modules/yeoman-environment/lib/environment.js:176:40)
    at module.exports.error (/Users/d0253800/Workspace/testjhipster/node_modules/generator-jhipster/generators/generator-base.js:1464:18)
    at rds.createDatabaseUrl (/Users/d0253800/Workspace/testjhipster/node_modules/generator-jhipster/generators/aws/index.js:213:30)
    at Response.rds.waitFor (/Users/d0253800/Workspace/testjhipster/node_modules/generator-jhipster/generators/aws/lib/rds.js:76:13)
    at Request.<anonymous> (/Users/d0253800/Workspace/testjhipster/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/d0253800/Workspace/testjhipster/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/d0253800/Workspace/testjhipster/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/d0253800/Workspace/testjhipster/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/d0253800/Workspace/testjhipster/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/d0253800/Workspace/testjhipster/node_modules/aws-sdk/lib/state_machine.js:14:12)
```
##### **Reproduce the error**

1. Generate new monolithic jhipster application
2. Follow the documentation [here](https://www.jhipster.tech/aws/)

##### **Related issues**

https://github.com/jhipster/generator-jhipster/issues/7086

##### **Suggest a Fix**

As of documentation here https://github.com/jhipster/generator-jhipster/pull/7443 it seemed to be fixed within version 5.0.0 of jhipster. For me it still occurs.

##### **JHipster Version(s)**

Freshly generated with 6.3.1

##### **JHipster configuration**

```
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
testjhipster@0.0.1-SNAPSHOT /Users/d0253800/Workspace/testjhipster
└── generator-jhipster@6.3.1

```


##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**


<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "6.3.1",
    "applicationType": "monolith",
    "baseName": "testjhipster",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "",
    "embeddableLaunchScript": false,
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": false,
    "blueprints": []
  }
}

</pre>
</details>


##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>


##### **Environment and Tools**

java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

git version 2.14.3

node: v8.11.3

npm: 6.10.1

yeoman: 3.1.0

yarn: 1.13.0
```

##### **Browsers and Operating System**

MacOS

-   [ x ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@Simsal : Thanks for reporting the issue. Let me try to recreate your issue in the evening. Both AWS sub-generators haven't been maintained for a while. And there might be some issues related to these. That being said I was working with this sub-generator around two weeks ago and it seems to work. 

As a workaround, did you try manually deleting all the resources that were created and then invoking the sub-generator again? Looking at your output it seems you have a S3 instance, and a database named "testjhipster". Chances that a fresh run might work; since we might have not handled all cases where it tries to update an existing deployment.

**Comment by Simsal** [comment]
@SudharakaP thanks for having a look at this.

Actually it was my very first try. Been looking for alternatives as my free year at another hosting site ran out.

The S3 instance gets created, but I don't see any database within my AWS console.

**Comment by SudharakaP** [comment]
@Simsal : Did you go to the RDS console, click on your database (does one exist?), then choose Instance actions -> Modify?

**Comment by Simsal** [comment]
I tried the generator with my real application and  with the testjhipster one, so there should be at least two databases available, but there is none.

**Comment by SudharakaP** [comment]
@Simsal : Okay, seems like it needs some deeper analysis. Let me try to recreate your scenario and get back to you. 😄

**Comment by SudharakaP** [comment]
@Simsal : Okay, I've recreated your error. It seems to me that from a previous run perhaps you have a Security Group that needs to be deleted manually. In your AWS account please go to EC2 and click on Security Groups; 

![image](https://user-images.githubusercontent.com/12435965/65935964-c129fa80-e3cf-11e9-899d-3e99d03c51b3.png)

My theory is that you should see two Security Groups; there's a default one and you should have another one. Delete this other security group (keep the default one; you cannot delete it anyways). The problem is we don't clear this security group when the sub-generator throws an error and fails fails. 

After deleting it please make sure you have `AWSElasticBeanstalkFullAccess`, `AmazonRDSFullAccess` and `IAMFullAccess` policies for your user. The [documentation](https://www.jhipster.tech/aws/) only mentions the `AWSElasticBeanstalkFullAccess` which might not be enough. I've made a pull request to correct the documentation. After this rerun the sub-generator and hopefully you should be able to correctly deploy. 

Let me know if you see any further issues. I will do some more testing and add some more documentation on how to clean up things in case of failures; as this might be useful.

**Comment by SudharakaP** [comment]
I've added some info on how to cleanup all the resources that are created to the documentation as well.

**Comment by Simsal** [comment]
You are right. After deleting the security group and adding the additional policies, the deployment process works.
Thank you very much for your help.

Maybe it would also be a nice hint in the documentation that the deployed application is not reachable via the instance dns address, but via the loadbalancer that also gets created at the deployment process :) .

**Comment by SudharakaP** [comment]
@Simsal : You are most welcome :smile: 

I'll leave the addition of the load balancer documentation for now but I'll revisit this in the next iteration when I do some improvements to it. :smile:
