### ISSUE TITLE
Bootstrap LESS should be excluded when bootstrap-sass is included

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1095]
In a JHipster application using SASS (and so bootstrap-sass) I tried to install [angular-bootstrap-switch](https://github.com/frapontillo/angular-bootstrap-switch), so I ran `bower install` and it installed bootstrap (LESS version) as a dependency. 

Overall my application is working but I guess I was just lucky to not encounter any conflict between the 2 versions of Bootstrap.

I think that the generator should exclude bootstrap-sass when not using SASS and bootstrap when using SASS.

I don't know if it's possible to do it in bower directly, at least it could be done in front-end build with wiredep:

~~~~javascript
wiredep: {
   app: {
        src: ['src/main/webapp/index.html', 'src/main/scss/main.scss'],
        exclude: [
        	/angular-i18n/, 
        	/swagger-ui/, 
        	// Exclude Bootstrap LESS as we use bootstrap-sass
        	'bower_components/bootstrap/'
	     ]
	   },
~~~~

I would like also that exclusions get commented, otherwise they're just black magic for newcomers.

**Comment by gmarziou** [comment]
I found this [issue](https://github.com/yeoman/generator-gulp-webapp/issues/235) from another generator where they explain how to use bower's overrides section.

**Comment by gmarziou** [comment]
Bower has a pending [PR spec](https://github.com/bower/bower.json-spec/pull/27) where they mention that some tools already do it: wiredep and grunt-bower-files

**Comment by andidev** [comment]
I think the best way to exlude files is to add a regexp to the exclude list as you mention.
While the overrides option should be used if you want to inlucde files that are not in the main property or if the main property is incorrectly setup by the package owners.

I agrre on that it is a good idea to remove the injections of the bootstrap (LESS version) if the SASS version is installed. This is cause most of the bower packages available that have bootstrap as a dependency will not have the bootstrap-sass version as a dependency which then results in that both version will be installed and injected in the code.
However the bower packages that have bootstrap-sass as a dependency will most likely be a sass package itself dependent on the sass code.
Therefore it is not necessary to exlude the bootstrap-sass dependency when a non sassy project is generated. Since there is no point in installing a sassy bower package if it cannot be compiled by sass/compass anyway since sass/compass is not configured.

Hope this makes sense, I'm a bit tired :sleepy:

**Comment by gmarziou** [comment]
Very clear, I agree with you on removing LESS version when SASS version is installed.
For the second case, don't forget that bootstrap-sass also brings static assets like fonts and js that could be doublons in different versions of the ones from the LESS version but I agree this is ot something we have to acre about.

agree that this would be a pathological case and we don't need to worry about it.

**Comment by jdubois** [comment]
This looks as an issue in the Bower dependencies -> yes excluding it makes sense, as Bootstrap is of course very common, but we shouldn't have to solve dependencies problems from other people

Can you make a PR with the exclusion, only for people using SASS? That's very few users, anyway.

**Comment by gmarziou** [comment]
OK I will

**Comment by gmarziou** [comment]
Problem is that Gruntfile.js is not a template, so in order to exclude Bootstrap LESS when SASS is enabled, I would need to turn Gruntfile.js into _Gruntfile.js. Is it the only thing to do? 

Is it OK to do it?

**Comment by andidev** [comment]
Gruntfile.js is a template. Just don't have the underscore for some reason. There are other if use Compass statements just search for compass.

**Comment by gmarziou** [comment]
Oops did not see them, thanks.

**Comment by jdubois** [comment]
Yes it's because it's one the first files I did (obviously, I began with the Gruntfile), and at that time I didn't know people usually prefix their templates with an underscore.
So no other reason than me not knowning how things work! I should refactor that.
