### ISSUE TITLE
Additional EU GDPR compliance : user account deletion

### ISSUE THREAD

**Issue by cedricms** [jhipster/generator-jhipster#11135]
##### **Overview of the feature request**

In addition to the possibility of updating one's user data in the settings, a user should be able to "delete" their account.

This would delete their personal data (login, first and last name, and e-mail) in the JHI_USER table and the "principal" column in JHI_PERSISTENT_AUDIT_EVENT could be replaced by the user id.

A commented "hook" could be placed in UserService in order to suggest additional deletion anonymization of data linked to the user.

##### **Motivation for or Use Case**

EU GDPR privacy laws give individuals the right to ask for their data to be deleted. Though the general subject is more complex than what is stated in the overview of this feature, it would be a first step for applications to manage user deletions.

##### **Related issues or PR**

As far as I've been able to check, this subject hasn't been debated yet. Feel free to consider whether the deletion should be physical or logical (and what elements should be deleted in that case).

If my proposed solution is OK, I could make a PR.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
It's an interesting feature, and all projects should consider this.

FYI, this logic is already implemented in our JHipster Online project. See https://github.com/jhipster/jhipster-online/blob/master/src/main/java/io/github/jhipster/online/service/UserService.java#L263

Then, for implementing this in the main generator, I think it's a lot of work to achieve it completely. 

Anyway, what can be done:
- implement the same html part as JHipster Online in account page
   - for Angular 
   - for React
   - for Vue.js
- add all translation files
- add an endpoint in Account Resource to delete user by login
- then, in real application, it will fail because of relationships, exactly what it is done today in administration page

What do you think @cedricms ?

**Comment by jdubois** [comment]
Also we've already discussed this many times but those audit tables should be removed. This data should go in some temporary log, not in a database. We need to work on this for JHipster 7.

**Comment by cedricms** [comment]
@pascalgrimaud : sounds good, I'll look into it as soon as I can.

@jdubois : do you consider the porting from database to logs for that data as a separate issue?

**Comment by jdubois** [comment]
@cedricms yes it's a separate issue, and we haven't worked on this at all yet. But for me this should be in a separate log file, if we keep this feature at all (I don't find it that much useful, it adds a lot of complexity, and also lowers performance at log in)

**Comment by pascalgrimaud** [comment]
Ok, I'm adding "Remove/Change Audits" in the roadmap v7

**Comment by pascalgrimaud** [comment]
did you progress on this @cedricms ?
do you need help ?

**Comment by cbornet** [comment]
Can't we just anonymize the user instead of deleting it ? IIRC anonymized data don't count as personal data anymore. Could be simple: rename user, email, login, etc... And it solves the issue with relationships. Also as for audits, I think the IP address can be considered as data that can identify a user and thus has to be removed as well...

**Comment by pascalgrimaud** [comment]
good idea @cbornet

**Comment by pascalgrimaud** [comment]
any news @cedricms ?

**Comment by cedricms** [comment]
@pascalgrimaud : sorry about that. My day job has been taking up quite a bit of my time lately. If somebody feels like taking on the task, feel free.

**Comment by pascalgrimaud** [comment]
It could be nice to have but as no one wants to work on this or code a module, let's close this ticket
