### ISSUE TITLE
Update Traefik to v2

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#11198]
##### **Overview of the feature request**

See https://docs.traefik.io/migration/v1-to-v2/

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
We have very few feedback for Traefik, so any interest to maintain and upgrade it ?

**Comment by pascalgrimaud** [comment]
@DanielFran : as we have too few feedback for Traefik, I think we should close this and stop maintaining this. We can remove this in v7. Do you agree ?

**Comment by DanielFran** [comment]
Ok for me. But in the meantime we might put in Twitter a post for this update and add @traffic team to see if someone might want to help?

**Comment by sendilkumarn** [comment]
Asked for help in the Traefik's Slack channel. We will wait for sometime, if somebody is interested in helping us :)

**Comment by pascalgrimaud** [comment]
It's opened January and no one wants to work on this.
So let's close this, for lack of interest for Traefik.

**Comment by antarus** [comment]
@pascalgrimaud 
The current implementation of traefik works very well and seems "simple" to me. But since traefik is only used in the sub generator, it might just be necessary to mention in the documentation how to use it (just the toml conf and docker compose exemple)

**Comment by pascalgrimaud** [comment]
Yes, it's very simple:
- https://github.com/jhipster/generator-jhipster/blob/master/generators/docker-compose/templates/traefik.yml.ejs
- https://github.com/jhipster/generator-jhipster/blob/master/generators/docker-compose/templates/traefik/traefik.toml.ejs

But the goal was to upgrade to v2, as the current version is 1.7.24 : https://github.com/jhipster/generator-jhipster/blob/master/generators/generator-constants.js#L78

Maybe it works well without doing nothing more than upgrading to v2, maybe not.

I closed this ticket because it was opened for too long, and no one wants to have a look on this.
@antarus : if you find interest on Traefik, you're welcome to help us here :-) Otherwise, I'll propose to remove Traefik for v7 because it is useless to keep options which are not used and maintained

**Comment by sendilkumarn** [comment]
> Maybe it works well without doing nothing more than upgrading to v2, maybe not.

No, it will not. The v2 is a huge breaking change. 

> I'll propose to remove Traefik for v7 because it is useless to keep options which are not used and maintained

I am in favour of removing it, since we are not using Traffic to its full potential and not enough contribution / usage
