### ISSUE TITLE
Allow a custom banner to be specified

### ISSUE THREAD

**Issue by lzkill** [jhipster/generator-jhipster#11206]
Currently one must manually change the banner in all the generated apps after `jdl-import`. It would be nice to have an option to pass a filepath of a custom banner.

**Comment by DanielFran** [comment]
It depends on what you want.
For example you can use _spring-banner-plugin_ so it appears a banner with the name of the aplication and few information.

**Comment by pascalgrimaud** [comment]
Thanks for suggesting this.
But to be honest, it would take you less than 10sec to copy / paste a file to replace the current banner, per project. That's why there is no value to add this feature.

Anyway, it would be against our **Policy 2: only add options when there is sufficient added-value in the generated code**

That's why I'm closing this.

**Comment by lzkill** [comment]
@pascalgrimaud you're right! Thanks anyway!
