### ISSUE TITLE
Entity generator should name configuration file in lower case

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1122]
Create an entity with `yo jhipster:entity Foo`, configuration file gets named `.jhipster.Foo.json`.

Edit configuration file to add a field.

Re-generate entity but use lower-case entity name with `yo jhipster:entity foo`, it will consider that the configuration file does not exist.

**Comment by jdubois** [comment]
the issue is only with the first character - after that you might want to have different cases, and those should be different entities. To be honest I didn't test this, and that would of course be a stupid idea to do...
-> so I will capitalize the first character, so we get the same name as the entity name, which seems logical

**Comment by gmarziou** [comment]
I can submit a PR nto only for that but I also removed duplicated filename building construction using this.filename.

**Comment by gmarziou** [comment]
The problem I see with capitaling first letter is that the doc  uses lowercase for entity name in examples so it is highly probable that existing config files would start by a lower case.

**Comment by jdubois** [comment]
oh, in that case we could start by a lower case -> that would be the "instance" name, but as you can see from the code it's more annoying to write

now I'm thinking of it: I'm using lower case because it's quicker to write, most of the time I only have lower case names. So let's do it -> I'll have a look at your PR

**Comment by jdubois** [comment]
Oh, so in your PR you capitalized the first name...

It's late, let's take some time to think about this!!!

**Comment by jdubois** [comment]
OK, back after a good night's sleep

- Having the first name capitalized is better, as it's the name of the entity -> for me it's cleaner that way, as eventually the entity is the root of everything
- The only issue is with existing config files -> anyway we have #1023 that will make us change the files location, so let's do both issues at the same time and document it
