### ISSUE TITLE
preserve lf / crlf when manually upgrading entities 

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11231]
##### **Overview of the feature request**

via jhipster entity entityName

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
What exactly is happening?

**Comment by geyuqiu** [comment]
maybe an edge case

1. generated (import-jdl) on mac
2. changed repository (crlf changed also)
3. upgrade and import jhipster entity on windows 

![image](https://user-images.githubusercontent.com/4540661/73753305-ca9ee700-4762-11ea-8d8e-847b196393c1.png)

**Comment by mshima** [comment]
@kaidohallik what do you think?

**Comment by mshima** [comment]
Is this an jhipster error? Or git is appointing that the file different?

**Comment by geyuqiu** [comment]
good question, git can not do the diff \r\n vs \n properly

**Comment by kaidohallik** [comment]
I have experienced couple of times in the past that after regeneration all files are showed as changed because of line endings difference in Windows. Maybe I used then different options in Git install or some glitch in Git. ATM I'm using autocrlf option in Git client and I haven't experienced this problem for a while.

If this happens then in comparing can look only at those files for what Git client is showing that at least 1 line is deleted or added.

Maybe it's possible to configure Git client to ignore line endings differences at all.

**Comment by mshima** [comment]
@geyuqiu are you using master or 6.6.0 release?

**Comment by geyuqiu** [comment]
yes, update to 6.6.0

**Comment by mshima** [comment]
Maybe https://github.com/jhipster/generator-jhipster/pull/11205 fixed your problem on master.

**Comment by geyuqiu** [comment]
I hope so too :)

**Comment by mshima** [comment]
Closing as we need more information about this issue.

**Comment by geyuqiu** [comment]
a mix of following "solved" line break issues with git diff on windows

```
find . -type f -print0 | xargs -0 dos2unix
git config --global core.eol lf
git config --global core.autocrlf false
# https://gist.github.com/ajdruff/16427061a41ca8c08c05992a6c74f59e

```
