### ISSUE TITLE
[Builder] enable builder pattern for Java and Typescript

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11272]
##### **Overview of the feature request**
currently: 
https://marketplace.visualstudio.com/items?itemName=FraserCrosbie.typescript-interface-to-builder-class
and lombok `@Builder`

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
The usage of Lombok has been discussed before in multiple threads; 

https://github.com/jhipster/generator-jhipster/issues?q=is%3Aissue+lombok+is%3Aclosed

For example; https://github.com/jhipster/generator-jhipster/issues/5997

**Comment by SudharakaP** [comment]
This feature is more suitable to be built as a [JHipster module](https://jhipster.tech/modules/marketplace/#/list) ([as mentioned in #5997](https://github.com/jhipster/generator-jhipster/issues/5997#issuecomment-311473531)) so that it can be evaluated first.

If the module ends up being very popular we could consider integrating it into the main project here.

Please refer the documentation on [how to build modules](https://jhipster.tech/modules/creating-a-module/) and look at some of the [existing modules](https://jhipster.tech/modules/marketplace/#/list) for inspiration. Reach out to us if you need any help like clarification on how the module system works, adding/exposing new methods for the API etc.

You can use the [JHipster module generator](https://github.com/jhipster/generator-jhipster-module) to scaffold a module.
