### ISSUE TITLE
[maven, junit5, spring boot] parameterized tests dependency are missing

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11271]
##### **Overview of the feature request**

Spring Boot 2.2.0 brings standard junit5 dependency: 
include: 
```
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
```
##### **Motivation for or Use Case**

```
@ParameterizedTest
@MethodSource
// dependencies are missing currently ?
// in junit-jupiter-params

```

-   [x] Checking this box is mandatory (this is just to show you read everything)

##### **Risks**
may break junit4 tests

**Comment by atomfrede** [comment]
We are already using junit5/jupiter for all our tests. Is there a specific issue with our current setup?

**Comment by geyuqiu** [comment]
@atomfrede corrected the issue, looks like some dependency for parameterized tests are missing

**Comment by murdos** [comment]
The generated code doesn't use parameterized tests, so this dependency is not needed.
If you want to write parameterized tests in your own code, you can just add the dependency in your generated project. 

BTW, you claim that Spring Boot 2.2.0 brings standard junit5 dependency, without details. I guess you're talking about dependency management. Because neither [spring-boot-test](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-test/2.2.4.RELEASE) nor [spring-boot-starter-test](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-test/2.2.4.RELEASE) have dependency to `junit-jupiter-params`

**Comment by geyuqiu** [comment]
btw. @murdos what I meant was more or less introduced in https://www.innoq.com/de/articles/2020/02/spring-boot-magie/
 but I didn't find the english version of the article. And I tried that with jhipster. But I didn't get quite far and currently included the lines above in pom.xml.
