### ISSUE TITLE
Support for cosmosdb using spring data

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster#11295]
Hi wonderful people,
any plans to implement the cosmosdb feature using [spring data cosmosdb](https://github.com/microsoft/spring-data-cosmosdb)?

**Comment by DanielFran** [comment]
I believe @jdubois already implement something related to cosmodb...

**Comment by amanganiello90** [comment]
Really? That could be great, I want to integrate this feature also in the nodejs blueprint. CosmosDB has a lot of useful features that works well in azure system.

**Comment by DanielFran** [comment]
@amanganiello90 take a look : https://dev.to/azure/going-full-reactive-with-spring-webflux-and-the-new-cosmosdb-api-v3-1n2a

**Comment by jdubois** [comment]
Yes I did this blog post, but it's not using JHipster, and it's not using the Spring Data CosmosDB API, but the underlying CosmosDB SDK.

What I already did with JHipster + CosmosDB was basically to replace MongoDB by CosmosDB, using the MongoDB API. Basically there is nothing to do, and it works well.

Here it's a totally different story, this is using Spring Data CosmosDB - but @amanganiello90 this is for Spring Boot users, this wouldn't work with NodeJS, so I think there might be a misunderstanding.

Then, as we are big Spring Data users, this would make sense to support this. And I have very good contacts with the CosmosDB team (insider information as I work directly with them, in fact). Let me see what I can do with Microsoft on that part.

**Comment by amanganiello90** [comment]
@jdubois I know that here it is for spring data (I have open the issue specifying it)... For nodejs I have an idea to integrate it with  typeorm, and a prompt with cosmosdb chooice it could be useful (as user-experience).

We have mongodb, why not Cosmosdb? (I thought ;)

I would like to start this feature.

**Comment by jdubois** [comment]
Oh @amanganiello90 you are very welcome to start this. We already have Couchbase and Cassandra, so it's hard to tell no to CosmosDB - even if I'm a bit afraid the templates will end up being very messy.

I'm pretty sure I can find some support from Microsoft on this (those are my direct colleagues), so if you start something please document it (at least on this ticket), because I believe I can bring some very good help.

**Comment by amanganiello90** [comment]
I have some experience with cosmosdb and azure. So I know what configuration is needed for spring data cosmosdb, I will add new templates for entity and repository classes in order to not complicate jhipster entity/repository template. Thanks, I will notice here the activity status.

**Comment by pascalgrimaud** [comment]
I discussed yesterday with @PierreBesson : it's cool to have all these new options but it will really increase too much our work to maintain it.

For example, we have some issue with Couchbase and Cassandra the last weeks/months: flaky builds related to testcontainers and cassandra drivers. I spent evenings on this, trying to find some solutions... @SudharakaP did the same. 
Same for UAA with the Registry and the flaky e2e, since more than 1 year ? No one want to fix it. 

So for me, we should:
- discuss about the options which are not enough used or maintained
- then, remove or move into module/blueprint
- so we can discuss about adding new options

The perfect example is the new module Kafka, currently developed by @fdelbrayelle and @ctamisier : Kafka is really popular and is a must have in JHipster. Our support is currently really simple, so the new features about Kafka don't need to be in the main generator-jhipster, it can work in a module, and we'll see later if it's popular or not.

Nothing against CosmoDB here :-)

I just want to propose to do a module or blueprint first, before considering adding the feature in generator-jhipster.

**Comment by amanganiello90** [comment]
Hi @pascalgrimaud , I'm agreement with you. Maybe it's better to start a blueprint **generator-jhipster-cosmosdb**, in order to manage server database configuration, versioning. usermanagement, entity and jdl. Then in future, we could merge it in jhipster.

**Comment by jdubois** [comment]
OK for a blueprint then!

**Comment by mshima** [comment]
To facilitate database only blueprints we should extract as much as possible db data into a structure.
Ex:
https://github.com/jhipster/generator-jhipster/blob/b8a973f9e38d2cd6a682f82b4e536cbd7e2f01e4/generators/server/templates/src/main/resources/config/application-dev.yml.ejs#L101-L139

We could have:
```
{
  postgres: {
    type: 'sql',
    get url() {return `jdbc:postgresql://localhost:5432/${this.baseName}`};
  },
  oracle: {
    type: 'sql',
   url: 'jdbc:oracle:thin:@localhost:1521:xe'
  }
}
```

before rendering:
`db.bind(ctx);`

at the ejs part it will be something like:
`url: <%= db.url %>`

**Comment by pascalgrimaud** [comment]
@mshima : if it can help to develop blueprint / module with new database, yes, let's improve this part

**Comment by pascalgrimaud** [comment]
About this ticket, I think we agree that it should go to module, so I'm closing this.
