### ISSUE TITLE
Customize the layout of entities through a TypeScript @View annotation

### ISSUE THREAD

**Issue by distributev** [jhipster/generator-jhipster#11359]
##### **Overview of the feature request**

Similar with the existing OpenXava's Java @view annotation

https://www.openxava.org/OpenXavaDoc/docs/view_en.html

JHipser generates a default user interface from the model.

In many simple cases this is enough, but sometimes it is necessary to model with precision the format of the user interface or view.

The TypeScript @view annotation could be used in an entity or embeddable class in order to define the layout of its members in the user interface.

##### **Motivation for or Use Case**

Users could quickly achieve a great deal of UI customization throws a simple @view annotation in TypeScript. Being in Typescript (client side) user would be allowed to quickly prototype / change the UI without recompiling all the application (only the client side would be automatically recompiled when the view is modified). The philosophy is also similar with the existing JDL.

From implementation standpoint maybe it is possible to transpile the existing OpenXava Java @View annotation in JS using a tool like http://www.gwtproject.org or Java to Kotlin conversion - https://try.kotlinlang.org/#/Kotlin%20Koans/Introduction/Java%20to%20Kotlin%20conversion/Task.kt (and then Kotlin has support to generate JS code)

##### **Related issues or PR**

I did not find a similar feature request.

- [X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
@distributev For me, the workflow should be:
  - support more than one UI in the generator
  - **not be able to choose between them in the Q&A**, so that it's a JDL-only feature (I'd hate to have more questions)
  - choose between UIs in the JDL with the option syntaxes (annotations or regular options)

**Comment by distributev** [comment]
I believe this should come after both JDL and after the existing code generator. Once the code is generated people will have this option as a TypeScript annotation or another way of providing this layout information dynamically and ideally this will work cross angular, vuejs and react frameworks (it should be possible since angular, vuejs and react don't care of the order in which the html elements are rendered on the screen)

In his talk 'JHipster side-by-side in practice' David Steiman explained how to do side by side development by extending the generated JHipster classes in order to avoid modifying the generated code and thus making it easier to upgrade JHipster later on. He said customizing the UI is still an open issue in the sense that it still requires people to fork the existing HTML generated code which makes upgrading JHipster difficult. This approach might improve a bit the situation in that sense.

**Comment by gmarziou** [comment]
I'm not convinced by this feature:

* Yes to modify UI you need to edit its code, what's wrong with that?
* Creating a cross framework annotation would only create coupling them in the generator
* Upgrading a JHipster app is not a goal in itself, you should do it very rarely and most probably never because generated code has very little value versus the code you write  to meet your business requirements.

**Comment by gmarziou** [comment]
@distributev could you give us a little background about yourself and the apps you develop so that we understand more where your  needs come from?

**Comment by distributev** [comment]
The current form of JHipster is already good and I could very well live and use the system the way it is now. 

Having this in the form of a TypeScript annotation (or something similar) will make it completely optional for the people. Like now people who want to write the HTML can ignore this feature and can continue to modify the existing HTML files. However, there might be people which would rather prefer to give small "UI hints", using a very compact DSL (maybe 5x times less code than HTML) to completely rearrange the elements on screen. Let's say that currently JHipster is generating the UI elements in a standard way one on top of the other and, in some cases, I would like to re-arrange the same elements to be displayed on 2 columns. Should I completely rewrite the HTML for that? Maybe I want to group couple of existing elements together with a common label and the rest in a 2nd group with a different label or maybe I don't want to show one element somewhere - should I completely rewrite the generated HTML for these very common and simple scenarios when I could achieve the same only by giving small UI "hints" to JHipster in the same TypeScript component which is currently responsible for importing the UI HTML code? 

The above OpenXava link which I provided can be used to get a good grasp of what kind of UI customizations can be achieved with only few small "UI hints" given through a simple DSL.
Quite complex UI customizations / rearrangements can be achieved with only few lines of code.
  
I'm professionally working with Java since 2005. I'm also building software with JavaScript, NodeJS and the PHP ecosystem. Java ecosystem is good with generating frameworks like JEE, SpringFramework and things which help people technically. PHP ecosystem is more pragmatic doesn't do things academically but provides people tools to solve their real problems quickly and effectively.

JHipster is one of the few tools in the Java ecosystem which went "the extra mile" and came with a solution which, with the help of the good SpringFramework, is helping people beyond the technical need to solve their real problems in a pragmatic and effective way. OpenXava, Apache Isis, Spring Roo are other examples of Java frameworks which went the "pragmatic" route of helping people. 

I believe this capability aligns well which how I understand that JHipster is trying to help developers.

**Comment by pascalgrimaud** [comment]
> I'm not convinced by this feature:
> - Yes to modify UI you need to edit its code, what's wrong with that?
> - Creating a cross framework annotation would only create coupling in the generator. Currently our 3 frontend implementations use Bootstrap which is not always the best solution for any real application and which is probably the first thing to change after generation
> - Upgrading a JHipster app is not a goal in itself, you should do it very rarely and most probably never because generated code has very little value versus the code you write to meet your business requirements.

Totally agree with @gmarziou 
The main goal of JHipster is not to code for you, but to provide a sample code, which you can copy / paste. You don't have to modify the existing file, you can create new files so it won't be overrided later

Then, with our module and blueprint system, you can probably do it yourself:
- have a look at https://www.jhipster.tech/modules/creating-a-module/#-creating-a-module
- start to code a module
- the module would read the JSON files
- by reading these files, you can prompt some question to the user, which UI the user wants, save answer inside a file, generate the appropriate UI etc

With a JHipster module, you can do what you want, once the project is generated.
That's why I'm proposing you to start to code a module.
Then, if your module becomes very popular, we can reconsider this, to integrate it to main generator-jhipster. Because it will mean it's a **MUST HAVE** in JHipster generator.

Don't hesitate to comment this ticket once you start the work, if you need feedback etc.
For now, as it will be too much work for us, I'm closing this as it won't be done in main generator-jhipster

Hope to see your JHipster module soon.
