### ISSUE TITLE
Remove some dependencies to reduce node_modules size

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1138]
The `node_modules` folder of a jhipster app is quite big, it takes disk space and slows down installation.
I looked at package.json and I don't understand why we depend on bower as it is installed globally and required by yo.
I removed it from package.json and it seems it had no impact.
I looked at the angular generator and they don't have it, it seems they removed it in this [PR](https://github.com/yeoman/generator/pull/201).

Same thing for grunt-cli that must be installed globally.

I don't understand also why we depend on generator-jhipster which in turn brings yo as dependency.
I also removed it.

Finally, my node_modules folder reduced from 399 MB to 173 MB !

I just tested with maven/grunt, so please try other configurations

**Comment by jdubois** [comment]
Yes, that would be awesome if we could reduce this size.

- For Bower and Grunt-cli, I had it at the beginning, as I copied from the Angular Generator -> I didn't understand at the time that you had to install them in parallel, and as you say Angular Generator removed Bower... So I guess both of them can be safely removed
- For Yo it's different: we had some dependencies issues (like having the wrong yo version). And someone (I have to do a git blame to see who did this) solved those by forcing the yo version in the dependencies. Since that period, no more errors! But to be honest, I have no idea what this dependency does, and if that's really what solved the issues....

So I would be incredibly happy to reduce the build size like you did, but I'm a bit frightened: we have so many users now, we could easily break their builds....

My proposal: can you submit a PR, and then we ask as many people as possible (on Twitter & co) to test it. And then we do a release specific just to that change: if we break stuff, doing a new version is just 5 minutes for me, and a simple "npm update" for users.

**Comment by rasheedamir** [comment]
+1 great idea.

Definitely there is no need for bower & grunt-cli in package.json as they must be installed globally as otherwise build process fails.

@jdubois that is the issue with Dockerfile as well; and there is already an issue opened there; please take a look [Issue # 3](https://github.com/jhipster/jhipster-docker/issues/3)

**Comment by gmarziou** [comment]
@jdubois do you mean a PR to remove bower and grunt-cli only, or PR also removing jhipster?

**Comment by jdubois** [comment]
I think the dependency on  generator-jhipster validates that the user as an up to date yo version, so I'm a bit frightened to remove it. Does it makes a big difference in terms of size?

**Comment by gmarziou** [comment]
I don't remember precisely, bower was the biggest one for sure.
Let's play it safe, I'll do the PR with only bower and grunt-cli

**Comment by gmarziou** [comment]
By the way, this was teh first time I used gradle and gulp. 
gulp is fast, for gradle I think the doc should give instructions about what to do after having generated your ppp, something like:

If gradle is installed on your machine just run `gradle bootRun` or use the gradle wrapper `./gradlew bootRun`

**Comment by gmarziou** [comment]
The doc explains gradle but in the 'using indev' chapter and does not mention the gradle wrapper.

**Comment by ggtools** [comment]
Seems to break the build with gradle. I did start a fresh jhipster project in 2.3.0 and compile it with gradle and it fails at the bower task:

    :bower
    module.js:338
        throw err;
              ^
    Error: Cannot find module '/Users/xtof/Documents/Dev/Ehtrace/medinv/test/newjh/node_modules/bower/bin/bower'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:278:25)
        at Function.Module.runMain (module.js:501:10)
        at startup (node.js:129:16)
        at node.js:814:3
    :bower FAILED

The .yo-rc.json is:

    {
      "generator-jhipster": {
        "baseName": "jhipster",
        "packageName": "com.mycompany.myapp",
        "packageFolder": "com/mycompany/myapp",
        "authenticationType": "oauth2",
        "hibernateCache": "no",
        "clusteredHttpSession": "no",
        "websocket": "no",
        "databaseType": "mongodb",
        "devDatabaseType": "mongodb",
        "prodDatabaseType": "mongodb",
        "useCompass": true,
        "buildTool": "gradle",
        "frontendBuilder": "grunt",
        "javaVersion": "8",
        "rememberMeKey": "d2a3ca3aa2e89ed771c561edbbc62c03c1154229"
      }
    }

**Comment by ggtools** [comment]
Ok found it ...

    task bower(dependsOn: 'npmInstall', type: NodeTask){
        script = file('node_modules/bower/bin/bower')
        args = ['install']
    }

I don't know what fix will be possible since the NodeTask requires a script argument but that's definitely it.

**Comment by gmarziou** [comment]
If gradle NodeTask is only able able to call locally installed scripts then tehre could be 2 solution:
- the one you chose which is to re-add bower to package.json
- stop using a NodeTask and call a system command to run the globally installed bower command

The second option would mean rewriting the bower task as:

~~~~
task bower(type: Exec) {
   commandLine 'bower', 'install'
}
~~~~

**Comment by ggtools** [comment]
I don't know the implication of running bower on the command line instead of using the dedicated node plugin. As a matter of fact while having a thin node_modules folder is something ok in a development environment on a continuous integration system having a minimal set of tools to install should be a good thing IMHO.

**Comment by ggtools** [comment]
However my PR is just a quick workaround as version 2.3.0  is currently broker on gradle a better solution can be planned for the next major release

**Comment by gmarziou** [comment]
Agree but at same time having different requirements for maven and gradle is not a good thing for maintenance. About CI, if you use Jenkins the NodeJS plugin lets you configure the sets of tools you want to install globally i.e. in the plugin's local own NodeJS installation that does not pollute system it is running on. That's how I documented it in [jhipster's doc](http://jhipster.github.io/setting_up_ci_linux.html)  and I think it's rather clean and safe..

**Comment by ggtools** [comment]
Works for me actually. After compiling in production mode I also discover that grunt is no longer working for the same reason. The fix suggested by the grunt plugin is to run `gradle installGrunt`. This can be easily done by adding a `grunt_build.dependsOn 'installGrunt'` however this will merely install `grunt-cli` in the `node_modules` directory. So do we also switch to command line for grunt?

**Comment by gmarziou** [comment]
Sorry, it's obvious that I don't use Gradle. I will have a look at it tonight. 
Grunt-cli is just a very thin layer above Grunt task runner, so the usual way is to install grunt-cli globally and grunt locally.

**Comment by ggtools** [comment]
No problem I have PR *almost ready* removing the `grunt-cli` plugin to be consistent with the way `bower` is handled.

**Comment by gmarziou** [comment]
Great, thanks.
