### ISSUE TITLE
Make Test Data for Entity Property More Expressive

### ISSUE THREAD

**Issue by geyuqiu** [jhipster/generator-jhipster#11382]
##### **Overview of the feature request**

make test data for entity property more expressive

current: 
```
public static final String DEFAULT_ENTITY_PROPERTY = "AAAAAAAAAA";
public static final String UPDATED_ENTITY_PROPERTY= "BBBBBBBBBB";
```

wanted: 
```
public static final String DEFAULT_ENTITY_PROPERTY = "DEFAULT_ENTITY_PROPERTY";
public static final String UPDATED_ENTITY_PROPERTY= "UPDATED_ENTITY_PROPERTY";
```

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by seraphinandrieux** [comment]
Hello @geyuqiu ,
For now, the logic used is based on the `fieldValidateRulesMaxlength` and the `fieldValidateRulesMinlength`. That's why we didn't define an expressive constant, it could change the word or crop it. Especially these values are used for UT, so we don't need a string value too much expressive :)

**Comment by wmarques** [comment]
@geyuqiu Thanks for pointing this out.
As @seraphinandrieux said, we also do some validation on String lengths to see if Spring validation is OK. Using meaningful test Strings will result in cropped values on some cases.

I prefer keeping what we have and not invest much time on this, so I'm closing this.
