### ISSUE TITLE
The generator project - Deprecate node v8 versions

### ISSUE THREAD

**Issue by MathieuAA** [jhipster/generator-jhipster#11650]
##### **Overview of the feature request**

Node v8 is not longer supported, and node v10 is in maintenance mode (v12 being the LTS version).

##### **Motivation for or Use Case**

First motivation: we can use the newer features of node (`mkdir('p', ...)`), bump (I'm talking semver-major updates) some dependencies.
Second motivation: JCore is gonna do the same.
Third motivation: remove the `mkdirp` dependency, because it won't be needed anymore.

##### **Related issues or PR**

Didn't find any.

-   [X] Yes, I do solemnly swear that I've read everything.

**Comment by SudharakaP** [comment]
This pertains to the `templates/package.json.ejs` files right ([example](https://github.com/jhipster/generator-jhipster/blob/104c4bc21ea0b4700323d21fd9084d7bf08aeee6/generators/client/templates/angular/package.json.ejs#L166)) ? I think we can safely do this since our CI already runs on Node 12. 

>     * [x]  Yes, I do solemnly swear that I've read everything.

:smile: :smile:

**Comment by MathieuAA** [comment]
@SudharakaP I should have added this little detail: I was talking about the generator.

**Comment by SudharakaP** [comment]
@MathieuAA : No problem. I think the previous PR is still valid since we need to upgrade the template version as well to 12 anyways. :smile:

**Comment by MathieuAA** [comment]
Indeed!
