### ISSUE TITLE
Support MongoDB when deploying to AWS Beanstalk

### ISSUE THREAD

**Issue by rodrigocprates** [jhipster/generator-jhipster#11676]
##### **Overview of the feature request**

Currently only RDS databases are supported to be deploy on AWS Beanstalk through ```jhipster aws```.

##### **Motivation for or Use Case**

Provide alternative to projects that do not use relational database (RDS), giving option to use MongoDB as it's the most common nosql database.

Might also give freedom to the user skip default database configs and manually setup database.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@rodrigocprates : I am not an AWS expert, but this is probably not possible with Beanstalk. Beanstalk only supports relational databases through RDS; https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.managing.db.html. If you want to run MongoDB there's two options; 

1) Use [Mongo Atlas](https://www.mongodb.com/cloud/atlas) and point your application to that. 

2) Use the aws-containers sub-generator instead so that you can deploy whatever you want on [EKS](https://aws.amazon.com/eks/). Probably suited for microservices not sure if it fits for a smaller app given the cost. 

I am closing this thread but if you do have any ideas or suggestions feel free to let us know. :smile:

**Comment by rodrigocprates** [comment]
It seems indeed that Mongo Atlas is the most straightforward solution to address it. 

Thank you @SudharakaP.

**Comment by SudharakaP** [comment]
You are welcome :smile:
