### ISSUE TITLE
Use repository absolute paths in .gitignore

### ISSUE THREAD

**Issue by ntherning** [jhipster/generator-jhipster#1168]
Having entries like `target` in the `.gitignore` file is a bad idea since it will ignore any file or folder with this name regardless of were they are in the repository. I've been bitten myself with this when I had a Java package named `target`. It took me a while to figure out why it didn't show up in `git status`! :-) Here's the `.gitignore` I use for my JHipster generated project:

```
/target
/node
/node_modules
.idea
*.iml
.classpath
.project
.settings
.tmp
.merge_file*
.sass-cache
.DS_Store
/src/main/webapp/dist
/src/main/webapp/bower_components
.gradle
/build
```

So basically just prepend the paths that should only be ignored if they are in the root of the repository with /.

**Comment by jdubois** [comment]
Yes, you are correct.

Could you provide us a PR?

**Comment by rasheedamir** [comment]
Guys, I can submit PR for this one as I have been thinking to organize different items in the `.gitignore`; and you can see the `.gitignore` that we have been using in a project that has been bootstrapped using jhipster [here](https://github.com/rasheedamir/fmu/blob/master/.gitignore)

**Comment by jdubois** [comment]
@rasheedamir it looks much better than our current file, however:

- the bower components should not be ignored (it must be commited, to have a reproductible build)
- src/main/java/ws/ must be specific to your porject

**Comment by rasheedamir** [comment]
points noted @jdubois and there will be no project specific items in it.

**Comment by jdubois** [comment]
thanks @rasheedamir can you do a PR?

**Comment by rasheedamir** [comment]
yeah! I will submit PR hopefully tonight!

**Comment by gmarziou** [comment]
It's great that you put comments in this fiile

**Comment by jmayday** [comment]
Hi,

like @ntherning I just was thinking about including `/src/main/webapp/bower_components` in `.gitignore`. @jdubois why keeping it excluded from `.gitignore` helps to have reproducible builds? Does it really help if stick to default bower versioning? In my opinion it doesn't because event if we keep bower_components versioned, and someone in the team performs update those he has different codebase. Reason for that is this ^ and ~ notations (bowers seems to use ^ as default). 

So I would say we have to have an eye on `bower.json` and after installing a package we have to remove the default ^ annotation and stick to some hardcoded versions which are up-to-date for the day we install a package.

If we follow this rule we don't have to version `bower_components` and still have reproducible builds. 

Please correct if I'm wrong.

**Comment by jdubois** [comment]
It's not ignored because Bower versions are in fact Git tags, and that some people move their tags. I know it's bad, and that those people suck, but that's just what people do.
So if you don't commit those files, your build won't be reproductible, as soon as someone moves a tag.

Hopefully, with AngularJS 2, we will move to npm, where the versions are really imutable, and that will solve the issue.

**Comment by jmayday** [comment]
@jdubois thanks for clarification!
