### ISSUE TITLE
Docker-compose memory limits

### ISSUE THREAD

**Issue by mmuruev** [jhipster/generator-jhipster#11754]
According to documentation docker-compose memory limits sets by JVM options, but new Java is docker aware, and make more sense set limits on docker container (it's also devOps) friendly and more crash-prone (case then docker limits is less then JVM setup).
Also can be a version of docker-compose file updated to v3?

**Comment by atomfrede** [comment]
You mean setting `mem_limit` and `mem_reservation` instead of `Xmx` and `Xms`, right? I think that would be a good addition. Would you like to do do a PR maybe?

**Comment by pascalgrimaud** [comment]
2 subjects here:
- add mem_limit and mem_reservation here, but I'd prefer to keep it in comments, as docker-compose files are used main in dev and not in prod, so we don't need to care about it
- upgrade to docker-compose v3

It would be nice to have, but it's really minor as it won't bring anything new.
It will be done if someone is motivated to do it.

For now, let's close this, because no one seems to want to work on this.
