### ISSUE TITLE
Fix Angular e2e tests so they don't pause for alerts

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#11766]
##### **Overview of the feature request**

Currently, running `npm run e2e` on an Angular app has pauses while it waits for alerts to disappear. On the other hand, if you run `npm run e2e` on a React app, there is no waiting, and the tests complete much faster.

##### **Motivation for or Use Case**

It's fun when the e2e tests really fly by. Not so much when there's pauses like Angular has.

##### **Related issues or PR**

No active ones that I know of.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@mraible : it's because React uses a different style of alert, so it's not consistent with Angular.
Anyway, about Angular, in our CI, we already reduces the e2e:
https://github.com/jhipster/generator-jhipster/blob/master/test-integration/scripts/23-package.sh#L19-L23

I don't know if it's what you're looking for ?

**Comment by Falydoor** [comment]
I was also thinking of looking for the alert and closing it (which is an upgrade because it will make sure the alert was shown).

**Comment by pascalgrimaud** [comment]
@Falydoor : indeed, click on the close button would be a solution too ! if we decide to implement this solution, we need to remove the change in the CI

**Comment by mraible** [comment]
I didn't know the timeout was reduced in CI. That doesn't help me as an end use though. In demos, I still have to wait.

**Comment by pascalgrimaud** [comment]
I think the best solution would be the one suggested by @Falydoor : click on close

@Falydoor : would you like to have a look and try to implement it ?

**Comment by Falydoor** [comment]
Yes I will take a look!

**Comment by Falydoor** [comment]
Closing the alert doesn't really fix the issue because Protractor still wait on the timeout. One way to disable this behavior is by using https://www.protractortest.org/#/api?view=ProtractorBrowser.prototype.waitForAngularEnabled but it breaks the tests that perform http requests.

Maybe there is a way to clear the alert's timeout?

**Comment by bagage** [comment]
Is that still an open issue? On a newly generated empty project, E2E tests last 10s and it seems alerts are dismissed without waiting timeout?

**Comment by Falydoor** [comment]
Did you create an entity? I still have the issue:

![image](https://user-images.githubusercontent.com/2212267/87797415-a3bc0500-c818-11ea-8856-51308120e6eb.png)

**Comment by mraible** [comment]
I can confirm that this is still an issue with the latest release.

```
$ jhipster --version
6.10.1
```

**Comment by DanielFran** [comment]
@mraible @pascalgrimaud  Should we continue with this issue opened since we mgrated now by default to cypress?

**Comment by pascalgrimaud** [comment]
@DanielFran : let's keep this opened for our JHipster Code next week. Then, if it's not fixed, I think we can close it, in favor of Cypress

**Comment by mshima** [comment]
@Falydoor can you confirm ng-jhipster@0.15.0 fixes the problem?

**Comment by Falydoor** [comment]
It does, awesome!
