### ISSUE TITLE
liquibase (diff) : Set default value

### ISSUE THREAD

**Issue by tomy29** [jhipster/generator-jhipster#1189]
Hi,

Is it possible, after having created an entity, to add a default value in the JPA entity, then run liquibase:diff which would then alter the mysql table.
I have tried : 
@Column(name = "nb_colis",columnDefinition="default '0'")
    private int nbColis = 0;

But liquibase:diff doesn't detect any modification in my entity compared with the database table.

Thank you!

**Comment by jdubois** [comment]
I would say Liquibase should handle this -> did you compile your app? Liquibase works on compiled code, so if you forgot to do it, it's normal it didn't work

Otherwise this is a Liquibase issue, so we can't help you -> please post this question on the Liquibase issue system, and link it here (so we know the answer, just in case!)

**Comment by roaned** [comment]
i asked here:

[link to Liquibase Issue 90](https://github.com/liquibase/liquibase-hibernate/issues/90)
