### ISSUE TITLE
Add Support for Skip CI for Dependabot Upgrades

### ISSUE THREAD

**Issue by SudharakaP** [jhipster/generator-jhipster#11962]
##### **Overview of the issue**

This is with regard to the following comment; https://github.com/jhipster/generator-jhipster/pull/11915#issuecomment-646718030

Related to: https://github.com/jhipster/generator-jhipster/issues/11914

##### **Motivation for or Use Case**

Skip CI for dependabot PRs.

##### **Suggest a Fix**

PR given below. 

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by SudharakaP** [comment]
@pascalgrimaud : In the above pull request, we will be adding a label for add dependabot created PRs (it's called `theme: dependabot-dependencies`). Then each GitHub action except the [generator action](https://github.com/jhipster/generator-jhipster/blob/master/.github/workflows/generator.yml) will skip PR's with that label. I've also simplified some logic in that was introduced in https://github.com/jhipster/generator-jhipster/pull/11800. I don't think we need to check for drafts specifically. Correct me if I am wrong. :thinking: 

cc: @mshima

**Comment by SudharakaP** [comment]
@pascalgrimaud : Also, for Azure pipelines; the easiest way is to handle this is to add a exclude trigger for `dependabot/*` branches. 

Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/release/triggers?view=azure-devops

**Comment by mshima** [comment]
@SudharakaP
Every PR is built 2 times, one at personal repository and another at jhipster repository, to reduce build triggers at jhipster repository makes sense to use `skip-ci` for drafts PRs, maybe by default.
So when I set the `skip-ci` label to draft only I was thinking about making it temporary and don't duplicate builds.

When the PR is not draft (meaning the PR is not ready to be reviewed) I don't think the label is useful, the reviewer should have the CI result every time, and the temporary `skip-ci` can falsely show that the PR built successfully by pushing the branch with `skip-ci` label and then removing it. Not a big problem since the label removal will be shown at the timeline.
So I would prefer [skip-ci] at commit message for non temporary skip-ci.

I don't disagree to make `skip-ci` non draft.
It is just less intrusive, and it's really easy to convert to draft.

**Comment by SudharakaP** [comment]
@mshima : Thanks much for the information, I understand your intention of doing it that way. I've replaced that code so that it skips ci for draft PRs.

**Comment by SudharakaP** [comment]
@pascalgrimaud : Just to be clear, I've just created a new label called; `theme: dependabot-dependencies` since otherwise this will not work; as noticed here; https://github.com/jhipster/generator-jhipster/pull/11964#issuecomment-646945098. 

Also I'll if you want me to do the Azure trigger addition; let me know I can do that if given the appropriate access to the generator pipelines.

**Comment by pascalgrimaud** [comment]
Azure builds should be ignore when there is PR from dependabot
Just an idea, maybe we can ignore it when the author is dependabot ?

**Comment by mshima** [comment]
> Azure builds should be ignore when there is PR from dependabot
> Just an idea, maybe we can ignore it when the author is dependabot ?

This will ignore when merged to master too.
Maybe we don’t want that.

**Comment by SudharakaP** [comment]
@pascalgrimaud @mshima : I have overlooked a simple way of doing it through configuration; PR submitted at, https://github.com/jhipster/generator-jhipster/pull/11966
