### ISSUE TITLE
Composing blueprints

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#12069]
##### **Overview of the issue**

I'm facing a few issues when building and composing blueprints.

We have two types of blueprints:
1. override blueprints (like vuejs, or primeng in our case...)
2. enhancement blueprints (PreAuthorize fine grained permissions blueprint)

The main difference is that type 1 replace all the generated code with new one, which for example is great for changing frameworks/languages...

On the other hand type 2 is great for small enhancements like adding annotation for fine grained permissions, or adding few files for small new features...

When building enhancement blueprints, there is no clear way to figure out (as far as I can say) to know if a replacement blueprint (has/will run before the enhancement) and we should just apply the enhancement directly, or we should call super._writing... first.

This is problematic because JHipster main generators are not run when a blueprint is present.

A workaround we found is to create a "default" blueprint that calls the code of generator-jhipster `super._writing...` for all sub generators and manually add it in the list of blueprints when no "override" blueprint is present. It's a dirty hack that doesn't always work, and we could maybe add some logic to fix this.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
When you are running a blueprint, the extended generator is called. But it's true that for some steps, we can fully override them (the writing phase in vue blueprint).

For me, for an enhancement blueprint (that I called the merge pattern in our last virtual meetup) we have to call the super.writing method and return the merge of both JHipster step and yours.

Blueprint are not made, initially, to be composed and we don't manage the way they are called. We apply blueprints in the order they are given. Also, the way the blueprints are build (merge or override patterns) is not known by the generators because we don't have the information.

I understand the problem but I have no idea  how we could change this.

**Comment by mshima** [comment]
This can be implemented with current jhipster.
Is really laking documentation:
- yeoman-generator's plugin generator.
Allows to use the running jhipster, instead of the dependency one.
- yeoman-generator's custom priority.
Allows to create custom priorities that will run before another priority.
- jhipster side-by-side blueprint.
Don't change the jhipster or normal blueprint workflow, will run side-by-side.

It's complex but can be done.

**Comment by mshima** [comment]
- Now we have others priorities (postWriting).
- The order is the parameter one `--blueprints first,second`. So you should use `--blueprints override,enhancement`

Closing.
