### ISSUE TITLE
RolesAllowed causing 403 forbidden with valid user.

### ISSUE THREAD

**Issue by mklewis** [jhipster/generator-jhipster#122]
If I change the annotation RolesAllowed to PreAuthorize it works.  
I've got Global Method Security set to allow for JSR 250 in SecurityConfiguration.java.
EnableGlobalMethodSecurity(prePostEnabled = true, jsr250Enabled = true) 

You can reproduce by creating an application, starting it, login as admin and go to sessions page.  You shouldn't see any session.  If you open the javascript console you will see the 403.

**Comment by miguelseia** [comment]
Can you help me with a clarification about security in rest controllers?

The question is related to the anotation @RolesAllowed(AuthoritiesConstants.ADMIN) in the method  findAll() of AuditResource class . 

I login in Chrome with  the user credentials and, as expected, I dont have the administration  menu active. At the same time I tried a rest client plugin for chrome and call the http://localhost:3000/api/audits/all service that  returned all elements. for this situation, shouldn't the service returned a "not authorized" response since my role was as USER?  

image:
![sans titre](https://cloud.githubusercontent.com/assets/8614836/8480350/680a39f6-20dd-11e5-8e3b-c5729a064423.png)

**Comment by dptinor** [comment]
@miguelseia 
The same happens to me.
