### ISSUE TITLE
Remove Entity Not working 

### ISSUE THREAD

**Issue by dkarthi1973** [jhipster/generator-jhipster#12320]
jhipster remove-entity entity1 - command is not working while remove entity ( error message remove-entity,entity1 is not a known command. See 'jhipster --help'. could you please advice us to remove the entity from project.

**Comment by murdos** [comment]
There's no such command. See the related discussion on https://github.com/jhipster/generator-jhipster/issues/8933

**Comment by mshima** [comment]
@murdos I think this should be relatively easy and non intrusive.
We can implement `jhipster entity Foo --remove` instead of `jhipster remove-entity Foo`.
It should:
- Remove the files, based on the generated ones
`writeFilesToDisk(files, generator, true, prefix).forEach(file => this.fs.delete(files));`
the `true` will return the files written ).
- Compose with `jhipster --with-entities` in the end to update needles.

CC @jhipster/developers

**Comment by pascalgrimaud** [comment]
It could be done but I'm not sure it is usefull.

Personally, in my real project, once an entity is already generated, if I want to remove it, I'd prefer to do it manually, rather than depending on JHipster. It would take only few minutes to do that. 

So not sure, it deserves a new flag in our entity sub gen, which is already complex.

**Comment by deepu105** [comment]
Agree with Pascal. We have had this discussion many times. Removing entity
manually using an IDE is much more easier then coding it for the generator.
Once you start customizing stuff you can't use the generator to remove
those anyway and that will be the more realistic case. So we will be
maintaining the option for no much value. To me its just overhead

**Comment by qPalee** [comment]
fuck you pascal why is there not a command to delete an entity, fuck jhipster this shit is ass

**Comment by Tcharl** [comment]
What about the `technical` data (the relationships to this entity in .jhipster/<relatedentities>.json and the .jhipster/<entitytoremove>.json? At least, it has to be explained in the tips and tricks: our users should know how to do that if they are using side-side and regular regens
