### ISSUE TITLE
Implement jhipster watch

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#12339]
##### **Overview of the feature request**

Regenerate the project when jdl, `.yo-rc.json` or `.jhipster` changes.

##### **Motivation for or Use Case**

- Useful at the beginning of a new project.
- Cool for showcasing and publicity.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
Great idea but how is it going to work with Liquibase checksums?

**Comment by mshima** [comment]
> Great idea but how is it going to work with Liquibase checksums?

@gmarziou that's ready https://github.com/jhipster/generator-jhipster/pull/12238 just needs review and be merged.

**Comment by pascalgrimaud** [comment]
At the beginning of project :
- during development, when writing JDL, the user won't want to regenerate all entities for each change, because it's not finished. The user will launch import-jdl only when the work is done. Otherwise, there will be a lot of changelogs.

When the project is already in advanced phase of development:
- it will be the same, for not erasing the modification

Maybe it's nice for demo, but in real case, I'm not convinced for the use of this, because the user wants to have full control of the generated code

**Comment by mshima** [comment]
Demo https://youtu.be/ziagUvf2ZhY

**Comment by mraible** [comment]
Is this a feature that we'll include in 7.0? If not, we should close this issue and re-open when there's a PR to support it.

**Comment by mshima** [comment]
@mraible label needs-discussion is applied so this will not happen until we discuss. 😄 
We should discuss or close, current arguments are:

Pros:
- Cool for demo.
- maybe useful for real uses (depend on developer workflow).

Cons:
- maybe not useful for real uses (depend on developer workflow).

**Comment by DanielFran** [comment]
@mraible @mshima Should we proceed with the implementation or close this issue?

**Comment by mshima** [comment]
I had this partially implemented at some point.
But since the interest was low, I’ve abandoned it.
Let’s close and reopen if there is interest.
