### ISSUE TITLE
yo generation conflicts

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#1238]
I have conflicts on those files everytime I run `yo jhipster` (I don't modify the files between 2 run of this command)
- src/test/javascript/karma.conf.js
- src/main/webapp/index.html

I think this is due to bower (I don't how) which modify those files during the "yo generation".

The modification happens in those tags:
   bower:css
   endbower

and 

   // bower:js
   // endbower

Don't you have this behavior ?

**Comment by dejewi** [comment]
Can you tell us which options did you select in wizard? It will help us to reproduce this bug

**Comment by ctamisier** [comment]
I let all the default options. (the first choice in the list)

**Comment by jdubois** [comment]
Yes, it is 'normal', let me explain what happens:

- We generate an index.html page (same thing for Karma), with no CSS/JS imported
- Then, bower comes and imports the files

So, from the Yeoman point of view:
- You have an existing file
- You replace it with a new file (the one without imports) -> conflict
- Then you insert the same JS/CSS as the existing file, but it's too late, it's done after the conflict

I agree this is bad, but I don't think there is a solution -> we can't fix this, that's why I'm closing this issue

This is very minor, as when you generate your app:

- You will add new CSS/JS with bower
- You will change many other files, for example when you run the entity sub-generator

-> so when you run the generator again, such conflicts will happen anyway. Of course, you should ignore them
-> that's also why I always ovewrite my files with Yeoman, and then do the conflict resolution with Git: those conflicts will not appear (as you have the same file in the end), you have better tools to solve 'real' conflicts, and you can also check the history so you know why you had a conflict

**Comment by ctamisier** [comment]
Yes I understand, thanks very much for your explanation.
Actually we could put the generated code in the template itself "_karma.conf.js". Bower will anyway regenerate the code inside the tags.
Unfortunately It is not the case for "_index.html" where a section is "appended" no matter the bower tags. 
But anyway it is really minor as you said and doesn't hurt. 
Regards.
