### ISSUE TITLE
Websocket errors when running grunt serve

### ISSUE THREAD

**Issue by ddewaele** [jhipster/generator-jhipster#1241]
When applying the guidelines in [Using the Java server and Grunt together](http://jhipster.github.io/development.html) there are some websocket related issues when launching the app via ```grunt serve```

```
Opening Web Socket...
sockjs.js:1213 WebSocket connection to 'ws://localhost:3000/websocket/activity/792/gnvfjsym/websocket' failed: Connection closed before receiving a handshake response
sockjs.js:807 POST http://localhost:3000/websocket/activity/792/6111uozu/xhr_streaming 403 (Forbidden)
sockjs.js:807 POST http://localhost:3000/websocket/activity/792/oekixy7i/xhr 403 (Forbidden)
stomp.min.js:8 Whoops! Lost connection to undefined
```

**Comment by Kwaq** [comment]
I've got the same error. It is caused by the lack of X-CSRF-TOKEN header in POST request.

Error response message: 
Invalid CSRF Token null was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN

**Comment by ddewaele** [comment]
The error I have is because the grunt powered frontend (running on port 3000) tries to connect to the websocket via the same port (while the websocket is hosted by the java powered backedn on port 8080).

Once that is fixed we'll indeed stumble upon the CSRF issue.

**Comment by jdubois** [comment]
Looks like you can't use Websockets with BrowserSync and CSRF.

- When SockJS tries to change protocol, BrowserSync fails to switch to Websocket: I couldn't find any documentation on this, so I guess it does not support Websocket. BTW, Websockets are not vulnerable to CSRF attacks, so if we can use WebSockets that's the end of story, no issue with the CSRF token.
- As we can't have Websockets, that means SockJS goes on polling mode, doing XHR requests: that doesn't really bother me, it's the same as when you are being a corporate proxy. This is not ideal, but still that's supposed to be a normal use case.
- The issue is that you can't add the "_csrf" parameter to SockJS (you have an "Error: Only basic urls are supported in SockJS" message), and you can't add the XSRF token in the header, as SockJS doesn't allow you to add a new header.

For the record, here is how to get the XSRF token manually:

```
$cookies[$http.defaults.xsrfCookieName]
```

So for me this is a "won't fix" issue, as long as BrowserSync does not support correctly Websockets (or as long as SockJS can't be correctly configured).

**Comment by jdubois** [comment]
I'm reopening this, as I think I've found the solution....

**Comment by jdubois** [comment]
Nope, this failing.... We will have better Websocket support with Spring Security 4, but this won't solve this issue.
