### ISSUE TITLE
Generated CI with e2e

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#12489]
##### **Overview of the issue**

Our generated CI doesn't have e2e tests.
It would be nice if it was possible

##### **Motivation for or Use Case**

Better CI/CD

##### **Reproduce the error**

- generate a project with e2e options (protractor or cypress)
- generate CI with jhipster ci-cd
- look at the generated CI file -> no e2e tests

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
@pascalgrimaud I think we need to integrate https://github.com/mshima/generator-jhipster-scripts for this.

**Comment by pascalgrimaud** [comment]
@mshima : I had a look and there are some really great ideas.
So I'm sure we can improve our generated package.json, so it will be easier to start the database/service, without thinking about:
- what do I need to start, before starting my application ? oh yes, it is postgresql and elasticsearch
- then, what is the command ? docker-compose -f src/main/docker/....
- etc

**Comment by JeroenAdam** [comment]
FWIW, I used the Jhipster 6.5.1 demo app for building my first Jenkins CI/CD pipeline. It included Protractor tests.
I went for the Docker in Docker approach with some config to keep only the latest few builds and with a cleanup of unused containers at the end of each build.

I'm not the strongest in automation, some notes I made:
 * Jenkins and Docker-in-Docker, to persist the docker permission denied issue: chmod 666 /var/run/docker.sock (should be set at boot time with sysv-rc-conf), not sure about this regarding security best-practices, but it works 
https://medium.com/swlh/quickstart-ci-with-jenkins-and-docker-in-docker-c3f7174ee9ff
https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket
 * chmod +x mvnw  as described here https://github.com/jhipster/generator-jhipster/issues/6942 
 * (manual setup done once, to avoid downloading dependencies over and over again)
   docker exec -u root -it jenkins /bin/bash
   cd /var/jenkins_home/workspace/yourproject
   chmod +x mvnw  
   ./mvnw clean package -Pprod -DskipTests
   mkdir m2prod
   mv /root/.m2 m2prod (will be moved to /var/jenkins_home/workspace/yourproject/m2prod/.m2)
   rm -Rf target && mkdir target
* (optional) pull+label openjdk image (this step because my pipeline does a cleanup of all containers except this one based on label)
* (optional continued) create Dockerfile 
   FROM openjdk:8-jre-alpine
   LABEL openjdk <openjdk>
   docker build . -t openjdk

My Jenkinsfile: https://github.com/JeroenAdam/ta3alama/blob/master/Jenkinsfile

**Comment by mshima** [comment]
https://github.com/nestybox/sysbox seems a good solution for docker-in-docker.

**Comment by DanielFran** [comment]
@mshima Is this issue fixed? Can be closed?

**Comment by mshima** [comment]
@DanielFran missing Jenkins and confirmation that it work.
