### ISSUE TITLE
angular-ui bootstrap instead of bootstrap

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1254]
Current frontend generated uses normal bootstrap JS for the widgets like modal etc, which is not the angular way, why not switch to angular-ui bootstrap which is better in angular app?

**Comment by jdubois** [comment]
I don't know why Bootstrap wouldn't be the Angular way, but we are not going to migrate to another CSS framework (and for me Angular UI is more a set of components).
Concerning Angular UI more specifically: we stick to the necessary components, but don't provide too high level components, because we want people to choose whatever they want. The work is mostly done with Bower, so you can easily install more high level components.

**Comment by deepu105** [comment]
Because the bootstrap components are used as it is, Yes angular-ui bootstrap integration may not be necessary but to be pure angular on what is generated you can at-least consider directives fro modal and collapse component

**Comment by wuethrich44** [comment]
I agree with that. Angular said a controller should not manipulate html because then the controller couldn't be unit tested. Jhipster manipulate html for example when you close a modal:
```javascript
$('#saveEntityModal').modal('hide');
```
If you use angular-ui bootstrap you can mock out the modal and its very easy to test the controller. I could provide a PR with this modifications because I use angular-ui bootstrap in my own project.

**Comment by wuethrich44** [comment]
@deepu105  This PR #1372 should solve your problem.

**Comment by deepu105** [comment]
Thanks @wuethrich44 , I have already implemented angular-bootstrap and rewrote the models :) but I have revamped the UI completely and since this didnt have much takers didnt try to contribute back

**Comment by gzsombor** [comment]
I'm curious, what you've done, probably very similar that I've started to do. Probably we could start a 'jhipster-fork' :wink:

**Comment by christophe-f** [comment]
angular-strap is probably a better choice. Easier to use, less dependencies, and better UI polish.

**Comment by verrol** [comment]
what about angular-material? It is designed for angular.

**Comment by deepu105** [comment]
@christophe-f  I have tried it before and then switched to angular-bootstrap, I found angular-bootstrap to more stable and flexible

**Comment by gzsombor** [comment]
Fortunately, angular-bootstrap is in ! :smiley: 

https://github.com/jhipster/generator-jhipster/commit/091f3c0587b5f56dec28164b320501de694e6dbb#diff-502edd32419d848619b3f13be1c735b8R14

**Comment by gmarziou** [comment]
@verrol angular-material adds a lot of directives (md-*) it's much more intrusive than a pure CSS framework.

**Comment by Jdruwe** [comment]
I agree with angular-material being a better solution.

**Comment by gmarziou** [comment]
The angular-material project is updated so frequently that it's hard to know whether it's stable or not.

**Comment by deepu105** [comment]
problem is angular material isn't exactly compatible with bootstrap and that would mean the entire front end might need to be re written which is huge and not worth maintaining as options as well

Agree with @gmarziou on the issue backlog in ui-bootstrap may be as someone else said above http://mgcrea.github.io/angular-strap/ looks much better and polished we should take a look at that

**Comment by mraible** [comment]
For a Material Design look with Bootstrap, I've used https://fezvrasta.github.io/bootstrap-material-design/. It seems to work "good enough". See www.21-points.com for an example.

**Comment by andidev** [comment]
@mraible Awesome! I think I'll try it out.
