### ISSUE TITLE
Oauth2 useless tables

### ISSUE THREAD

**Issue by aklauza** [jhipster/generator-jhipster#1257]
I just wanted to let you know that the database schema that you implemented for Oauth2 is too big.

In Oauth2ServerConfiguration you decided to keep the tokenStore in the database and the client data in memory. 
```java
public TokenStore tokenStore() {
        return new JdbcTokenStore(dataSource);
}
...
public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
        clients.inMemory()
...
```
A smart decision from my point of view. However, you have a bunch of tables that relate to the client side that are not required (because they are in memory), and you can notice they are not being used at all. You should remove all the tables from the liquibase schema and just keep these two:
```
oauth_access_token
oauth_refresh_token
```
If you decide to disable the refresh_token endpoint (https://github.com/jhipster/generator-jhipster/issues/1256), you can even remove the refresh_token table.

**Comment by seghers** [comment]
You are right that there might be too much tables. But I see jHipster as creating a start/template to a new project. When created it is much easier to remove the tables (inmemory) than to add them when changing your project to jdbc. 

I used the ```clients.jdbc(dataSource);``` because I was thinking about deploying my project on multiple server. In which case I need the tokens accessable from all points > shared db

I used loadData in liquibase to populate the table.
```
CLIENT_ID;RESOURCE_IDS;CLIENT_SECRET;SCOPE;AUTHORIZED_GRANT_TYPES;WEB_SERVER_REDIRECT_URI;AUTHORITIES;ACCESS_TOKEN_VALIDITY;REFRESH_TOKEN_VALIDITY;ADDITIONAL_INFORMATION;AUTOAPPROVE
captjehipsterapp;;mySecretOAuthSecret;read,write;password,refresh_token;;ROLE_ADMIN,ROLE_USER,ROLE_ANONYMOUS;1800;null;{};
captjehipsterandroid;;mySecretOAuthSecretsastd;read,write;password,refresh_token;;ROLE_ADMIN,ROLE_USER,ROLE_ANONYMOUS;1800;null;{};
captjehipsterios;;mySecretOAuthSecretstd;read,write;password,refresh_token;;ROLE_ADMIN,ROLE_USER,ROLE_ANONYMOUS;1800;null;{};
captjehipsterpostman;;mySecretOAuthSecretsrtsrtd;read,write;password,refresh_token;;ROLE_ADMIN,ROLE_USER,ROLE_ANONYMOUS;1800;null;{};
```

**Comment by aklauza** [comment]
Same as you, I like from the Oauth2 protocol that it can be easily escalated and distributed, and the App I am building is intended to be running on multiple servers.

However, from my understanding, you don't need more than the TokenStore in the Database. That means you can run multiple instances of the authorization (and resources) server using clients.inMemory() and get rid off all those unnecessary tables. 

I have just tested this to make sure and it works perfectly. You can reproduce my test doing the following:
1 - In OAuth2ServerConfiguration set:
```java
clients.inMemory()
```
2 - Delete (or rename temporarily) all your Oauth tables but:
```
oauth_access_token
oauth_refresh_token
```
3 - Start one instance of your app with maven from the console (it will be using the default port 8080).
```
mvn spring-boot:run
```
4 - Open your app and login (make sure to copy-paste the access token when the server returns it).
5 - Launch a second instance of the server from your IDE on a different port. You need to setup an environment variable before starting the server:
```
server.port = 9090
```
6 - Open a 3rd party rest client (curl for example). I am using Advanced Rest Client App for Chrome. And then do a request like the following to the second server:
```
Type: GET
URL: http://127.0.0.1:9090/api/users/admin
Authorization Header: Bearer {yourCopyPastedToken}
```
7 - IT WORKS. You get the response from the second server without having to login, just using the token you got from the first server. This confirms that both servers share the oauth database.

You can play shutting down one server or the other or both and restarting and it keeps working as long as the token does not expire.

The question that arises is, does it really make sense to use clients.jdbc(dataSource) ?

**Comment by seghers** [comment]
I'm using it to save the client details in one synced place (db) . You are creating these client details 2 times in memory. 

If I immediately want to drop a client's access. I can write a query to the db. You need to redeploy all instances with new source.. 
--

Met vriendelijke groet
Yours sincerely
Avec mes sincères salutations

Laurens SEGHERS

**Comment by aklauza** [comment]
In my case, you can drop user's access to the system centrally as well by just deleting his oauth_access_token in the database. 

Sure, you can do it in a more detailed level by just dropping one of the user's client (only android, only web, only ios). But in a real world, when you suspect a user's credentials have been compromised, you don't just drop his android access, but the whole token and force him to login again in every device / client. So I don't really see the advantage of dropping just a specific device over completely dropping his credentials.

On the other side, yes there are many copies of the client details in every server, but does it matter? It is just one record per client per user.

**Comment by seghers** [comment]
I did this because I had errors with multiple clients inmemory. 
So I jumped ahead and used a db.

Dropping client cred. is not to block a user, it's to block the application. And I don't know when I need to prevent access from a client. But if I need it I want it to be fast db > inmemory

**Comment by jdubois** [comment]
You both probably know better than I do what those tables do: I didn't code this part in JHipster, and I don't know OAuth2 very well.

From my understanding, those tables come from Spring Security OAuth, and indeed we probably don't use those 2 tables because we have the in-memory mechanism.

Of course it can always be useful, but I'd like to be minimalist if possible: let's only configure the tables we need at the moment. Besides, it's a bit confusing to have empty tables.

So I mostly agree with @aklauza

**Comment by jdubois** [comment]
I'm going to be annoying here, but in fact I don't want to change anything.

- We have 2 useless OAuth tables, but they might come in handy if people want to store the refresh token in them. As they are not provided by Spring Security OAuth, they would really be a pain to create in Liquibase, so that makes sense to give them out of the box to people, even if only few people really need them (and the other people can still delete them).
- For the refreshTokenValiditySeconds -> by default it is 30 days, which is OK, as it's the same thing as our "remember me" cookie. So we are as secured as our default implementation
- I've also seen the comment about using HTTPS -> here again, it's the same issue as our default implementation. If you are using HTTP, anyway, you are going to have some secrets being shown to the world, that's normal as you don't encrypt
- From what I've seen, we have people already using the refresh token -> so removing this configuration would be annoying to them
- In fact, I'd rather use those tables to store the refresh token, instead of putting it in memory, so if anybody is interested in doing a PR with this, I would be very happy to merge it

**Comment by cbornet** [comment]
@jdubois as for the token validity, I think the difference with the "remember me" token is that in the latter you have the choice as a user to use it or not. For users registering on a public computer, their refresh_token will be visible in the browser for 30 days. Maybe it would be better to have a "remember me" checkbox also for oauth2 that will decide if the refresh token can be writen in the local storage.
