### ISSUE TITLE
User with a login of "." or ".." can't be edited

### ISSUE THREAD

**Issue by Falydoor** [jhipster/generator-jhipster#12740]
##### **Overview of the issue**

After creating a User with a login of "." or "..", it is impossible to update/delete it. 

##### **Motivation for or Use Case**

It should be possible to update/delete a user after created it.

##### **Reproduce the error**

Create a user with a login of "." or ".." and then try to update/delete it.

##### **Suggest a Fix**

This is probably because the API uses the login instead of the id to find the user. Any reason why the login was used instead of the id?

Also maybe the login regex should avoid that kind of login.

##### **JHipster Version(s)**

```
jhipster@0.0.1-SNAPSHOT /Users/theo/Documents/perso/jhipster-12574
└── generator-jhipster@6.10.3

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "6.10.3",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": false,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1602648183743,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "jwt",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "clientThemeVariant": "primary",
    "useSass": true,
    "languages": ["en"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

ls: no such file or directory: .jhipster/*.json
<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "12.0.2" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.2+10)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 12 Mac OS X amd64-64-Bit Compressed References 20190915_201 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - 9984ea0dd9 based on jdk-12.0.2+10)

git version 2.28.0

node: v12.19.0

npm: 6.14.8

yeoman: 3.1.1

yarn: 1.22.10

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.27.4, build 40524192

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Jessy-BAER** [comment]
I have been able to reproduce this issue

> This is probably because the API uses the login instead of the id to find the user. Any reason why the login was used instead of the id?

It's a good question, does anyone have an explanation ? 

I can try to work either on both solutions (use id instead of login or change the login regex)

**Comment by atomfrede** [comment]
I think changing the login regex would not be a good idea as emails (e.g. foo.bar@jhipster.tech) as login would not be allowed (which was added some time ago). I have no explanation why the login is used in the path parameter.

**Comment by Jessy-BAER** [comment]
We can change the regex to exclude single dot ?  `login=.` should not be valid.

**Comment by KevM7** [comment]
The login is in path (to edit, view or delete). So the regex has to exclude all forbidden characters for URL, I thnink.

**Comment by pblanchardie** [comment]
>>>Any reason why the login was used instead of the id?
>>
>> It's a good question, does anyone have an explanation ?
>
> I have no explanation why the login is used in the path parameter.

At the very beginning, 7 years ago (!), the User  `@Id` was `String login`, see the initial 4d45fd63 commit from @jdubois.

Later, the same @jdubois switched to a technical Long `@Id` in commit 35b0e8eb, but kept the login in `UserResource.getUser`.
I admit I also prefer using the technical id, and I don't know why it hasn't been updated.

Back in the days, I remember it caused problems when using email as login, when emails were ending with `.com` and content types were disturbed.

Perhaps it's time to change?

**Comment by jdubois** [comment]
Yes there is a lot of legacy here.
Initially, I didn't want to use emails as logins (as those can change, for example when you get married, and also as they are considered as personal information - so not RGPD friendly), but in practice everybody wanted to use them. So we ended up supporting both logins and emails, which is great because it makes everybody happy, but can cause some security issues.

**Comment by pblanchardie** [comment]
Hi @jdubois, that makes sense.

From a (non-geek) user perspective, using yet another login is painful in most cases (I'm not even talking about passwords!...).

As soon as the email is well protected, not present in public DTOs and only shown to relevant users (thus not used in a path), it can comply with GDPR when used as an authentication factor and communication channel, so it was a good idea to support it.

So taking GDPR into account, do you agree that using the **id instead of the login in the path** would be a better solution?
It would also avoid showing any personal information in access and error logs!

Knowing that UUIDs are now supported out of the box, it sounds good even for those who don't like to expose sequence numbers.

**Comment by jdubois** [comment]
Initially, this was copied on the GitHub API, so you had the login in the URL (like github.com/jdubois ), and I didn't want to share internal technical information (like the internal ID). It's supposed to be easier to use for everyone, and maybe more secure. Then, using the email obviously has some GDPR issues.
That's why at the moment we accept both login & email to authenticate, and use the login in the URL. I believe this is what most websites do.

**Comment by pblanchardie** [comment]
Indeed, the problem only appears when you put an email in the login field, as allowed by the login regex.

👍 Good idea to stick with GitHub and other cool and secure geek apps, but:

> Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen.

So emails should not be allowed as logins, but only in the email field to prevent the misuse. That was the case in 2015, when `^[a-z0-9]*$` was introduced in 8e8f389a. The problem appeared in 481f9f95, because of social login? A random or guessed login could be assigned instead of the email.

Anyway, using "." or ".." as a login is weird and it should be forbidden when registering or creating a user, instead of trying to allow it in the path, as suggested by others.

**Comment by pblanchardie** [comment]
@pascalgrimaud FYI I opted for the replacement of `/admin/users/:login` with `/admin/users/:id` on both API and frontend for reasons explained above.

**Comment by pascalgrimaud** [comment]
@pblanchardie : I didn't follow exactly the discussion here. I decided to reopen all "stale" and "auto closed" tickets, so we won't hide any more these tickets

**Comment by mraible** [comment]
Closing because I think this issue is resolved. Please reopen if it isn't, or just use OIDC. 😊
