### ISSUE TITLE
What is the road map for upgrading to Angular2, Angular Material and New Router? 

### ISSUE THREAD

**Issue by tapas4java** [jhipster/generator-jhipster#1283]
I know its too early for asking support for Angular2 now but I would like to know the road map for this. I am asking because I am interested to contribute on this aspect. Being a J2EE/Spring and Angular developer, This project really excites me.

**Comment by sometxdude** [comment]
How about support for React/Flux also?

**Comment by jdubois** [comment]
@sometxdude no because our goal is AngularJS

@tapas4java we will wait until it is stable, and until there are enough 3rd party libs (we use Angular UI router & several others, we need something similar).
But early work to migrate is very good, so we know where we go.

**Comment by systemsplanet** [comment]
Is there a page we can watch for angular 2 progress updates?
Will the angular 2 option convert previously generated angular 1 project to angular 2?

**Comment by deepu105** [comment]
@sometxdude if you are interested in react support in Jhipster take a look at https://github.com/hipster-labs/generator-jhipster-react its a WIP and this module will replace angular client side with react. It has material Ui and webpack support instead of Gulp and this is our recommended approach to customize Jhipster for different use case
@tapas4java the same approach I use for above can be used for angular-material as well . I guess @sendilkumarn is working on a module for that

@systemsplanet when we upgrade to angular 2 it will be mostly a breaking change and hence a major release so I doubt we might not have bandwidth to support older apps.

**Comment by sometxdude** [comment]
Thanks, I just forked your jhipster/react project so I won't forget it.  
I will definitely be kicking the tires on it soon.

**Comment by deepu105** [comment]
You are welcome to collaborate :)

**Comment by andrey-chorniy** [comment]
@deepu105 could you please describe how to use jhipster-react ? command "yo jhipster-react" do not generate app for me

**Comment by deepu105** [comment]
Its still a work in progress and not yet released.

**Comment by kenkyee** [comment]
Will it be as simple as adding an Angular2 generator?  And if so, why isn't one being done already?

**Comment by gmarziou** [comment]
Maybe because it's hard work and we're only volunteers...

At work (not JHipster) we've started making a prototype based on angular 2 and typescript, this is a big change by itself. We tried angular-material 2 but abandoned it as it is far from being usable now, we also tried polymer but found we've had enough on our plate with ng2 to add more learning curve.

**Comment by kenkyee** [comment]
Is there an "Idiot's Guide to Writing a JHipster Generator" doc?
Most of the docs seem to be for using JHipster...

**Comment by gmarziou** [comment]
It depends on what you want to do.

For the generator itself, we have a [contributing guide](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) and of course the [yeoman docs](http://yeoman.io/authoring/).

Now if you want to build something simple, you can create jhipster module: https://jhipster.github.io/modules/creating-a-module/

**Comment by JavierFuentes** [comment]
Hi everyone,
Congratulations for this great tool.

I've seen than Angular 2 is right now in Release Candidate state...
https://github.com/angular/angular/blob/master/CHANGELOG.md

I hope you can end JHipster's integration soon... Have you got any release date in mind?

**Comment by satishav** [comment]
Final release version of Angular 2,  the full-platform successor to Angular 1 is now available ! [http://angularjs.blogspot.in/2016/09/angular2-final.html](Angular2-final)

**Comment by deepu105** [comment]
we are already working on it check #3664
