### ISSUE TITLE
Angular: use more generic unsubcriptions mechanism

### ISSUE THREAD

**Issue by chrisdns** [jhipster/generator-jhipster#12867]
##### **Overview of the feature request**
The principle is :
- to create a class that will do the unsubcription work
- all the components will extend this class and call the `unsubscribe()` method in the destroy hook

_example :_
```
export class BaseComponent {
  destroy$: Subject<> = new Subject<>();

  unsubscribe(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

export class RandomComponent implements OnInit, OnDestroy {
  something$: Observable<>;

  ngOnInit(): void {   
    this.something$.pipe(
      takeUntil(this.destroy$),
      tap(something => ...)
    ).subscribe();
  }
  
  ngOnDestroy(): void {
    this.unsubscribe();
  }
}
```

##### **Motivation for or Use Case**
I propose to use the `takeUntil` operator with base class mechanism in order to provide developers a more generic (and less verbose way) to unsubcribe from observables.
Components are no longer polluted with unsubscriptions process. 

##### **Related issues or PR**
https://github.com/jhipster/generator-jhipster/pull/12840
⚠️ I will create an other pull request in order to revert this one (which needs to be reworked) that is already merged.

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by kaidohallik** [comment]
If using base class then code in final class is as minimal as possible, but drawback is that some complexity is added (additional class generated, user must notice that class is extended from the base class, user must look at base class to see what is in this class and how to use this).

If going for base class then my suggestions:
* name base class so that it's understandable from the name for what this class is, for example `SubscriptionDestroyer`
* for `HomeComponent` use async pipe
* extend from `SubscriptionDestroyer` only where necessary, ATM 3 classes:
    - `ErrorComponent`
    - `HasAnyAuthorityDirective`
    - `TrackerComponent` (available if `websockets` option is selected)

I'm not against for adding base class for unsubscribing, but for me another option - move to `takeUntil` without base class - is equally good.

So maybe wait for couple of days to see if someone else has opinion about that. If not then can proceed with adding base class for unsubscribing.

**Comment by wmarques** [comment]
I think we should try to use the async pipe as often as possible, and then use the `takeUntil` without base class when we cannot use the async pipe.

For me using a base class for all our components is a bit too much for the benefit it provides...

**Comment by DanielFran** [comment]
Close via https://github.com/jhipster/generator-jhipster/pull/13265
