### ISSUE TITLE
i18n Error when adding new entity

### ISSUE THREAD

**Issue by red0point** [jhipster/generator-jhipster#1287]
When I add a new entity, the generator inserts the translation for the new entity at the top of the global.json file, which corrupts the JSON Object.

**Comment by wuethrich44** [comment]
I had the same error too...

**Comment by atomfrede** [comment]
Using the latest version I can't reproduce it. After adding an entity my ``global.json`` looks like this:
  ``` 
"entities": {
                "main": "Entities",
                "test": "Test",
                "additionalEntity": "JHipster will add addtional entities"
            },
  ```

**Comment by jdubois** [comment]
OK, this is because some translators (it depends on the language) didn't understand this is a technical line, and translated it (so then the generator doesn't find the line, and fail).
This is an annoying part of JSON: you can't write comments, so it's difficult to explain what you want to do.
I modified the line, and corrected all translations.

**Comment by atomfrede** [comment]
Maybe you could setup https://crowdin.com/ (its free for foss projects) to manage translations. It's quite easy to exclude certain keys from being able to be translated. Using the java client pushing new files and fetching updated translations is very easy.
