### ISSUE TITLE
entity generation: add comment

### ISSUE THREAD

**Issue by bosyak** [jhipster/generator-jhipster#1296]
Hi.
Is it possible add comment on column?
Even like "columnName, all the rest is comment", on question "What is the name of your field?"
So if you have comment it's possible to add in liquidbase like this:
{column name="name" type="varchar(255)" remarks="Это комментарий"/}
Add it to javadoc also?

After it is possible to see it in psql if execute : "\d+ t_devision"  - plus is a must

I suppose it's very desireable feature like this if you bootstrap a lot.
Thanks.

**Comment by jdubois** [comment]
I don't think we would add a lot of value, comparing to adding the comment yourself manually -> eventually it's only written in one place anyway, so it's easier to write it directly instead of using JHipster. I don't want to push the usage of JHipster if it doesn't add much value on top of the normal tools.
