### ISSUE TITLE
Feature Request: HTML 5 URLs

### ISSUE THREAD

**Issue by skpatel20** [jhipster/generator-jhipster#1297]
Now that HTML 5 URLs are becoming more common, it would be nice to have an option to opt for HTML5 URLs while creating the project. Even better, I think that could become the default choice.

Related ticket: #374

**Comment by jdubois** [comment]
Yes, I fully agree!
But I need to check how they work with Angular UI router (last time I did that was with Backbone.js!).

**Comment by jdubois** [comment]
It would be nice, but we can't do it.

For reference, here is a good explanation: http://stackoverflow.com/questions/16569841/angularjs-html5-mode-reloading-the-page-gives-wrong-get-request

Doing it is easy (no big added value by JHispter, and if you want HTML5 URLs just do this):

- Add a base tag in the index.html file:
```
<base href="/">
```

- Configure the locationProvider in the app.js file:
```
$locationProvider.html5Mode(true).hashPrefix('!');
```

My issue is that if you navigate, for example to the following page:
```
http://127.0.0.1:8080/foo/1023
```
And then hit the refresh button, the server has no way of knowing it should request http://127.0.0.1:8080/ and so you will get an error.

The solution to this, as explained in the StackOverflow question at the beginning of this comment, is to do a "catch all" to send all requests to the root. I don't like this for two reasons:

- This is going to be annoying for people who don't do single page Web apps (this is not our default configuration, but let's not forget them)
- This means we have some kind of Java router/controller, and at the moment our front-end is pure HTML: we don't need any logic to display it, and we have people serving this with a CDN for example. I like this a lot: very good for performance, very easy to use and deploy.

**Comment by gmarziou** [comment]
I really doubt this is easy with current URL scheme, especially for a gateway because we use service names as URL prefixes of our routes, this was [my point on dev list.](https://groups.google.com/forum/#!msg/jhipster-dev/1RtCU3qt3Tk/ShiBOgI5BQAJ;context-place=forum/jhipster-dev).

So either we add complexity in a zuul or servlet filter by plugging it to service registry at the risk of introducing URL conflicts between client and server or we introduce breaking changes in the gateway routes.
