### ISSUE TITLE
Add support for ManyToOne Bi directional relationships

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#13018]
##### **Overview of the feature request**

Hi, is there a reason why ManyToOne Bi directional relationships are not supported (or even implemented added by default since they are eager)?

If no, do you mind If I implement it?

Thanks.

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by MathieuAA** [comment]
Hello there! As I recall, there were technical reasons preventing us from implementing that.
Maybe @jdubois has a better memory than I.

But if implementing it is possible, go ahead! The counterpart being a one-to-many, I'm curious about the implementation differences.
If you implement it, don't forget about the doc :)

**Comment by mshima** [comment]
I am pretty sure `one-to-many` aren't eager-loaded currently.

I can see a few technical details:
- performance wise, do we need to load every back-reference? no, so we need to specify when to load them.
- jdl doesn't distinguish between `relationship OneToMany {A to B}` and `relationship ManyToOne {B to A}`.
- read-only, unless they are cascadeAll, they will be ready only.

**Comment by jdubois** [comment]
As far as I can remember, we always do bi-directional mapping (so OneToMany on one side and ManyToOne on the other). This is because we don't know your business case (it's up to you to "cut" one side if that's your business scenario), but also because that's better for performance. I think this was inspired by https://vladmihalcea.com/the-best-way-to-map-a-onetomany-association-with-jpa-and-hibernate/ (and anyway that's always a good read on that matter).
OneToMany should be lazy, as it's the default, but we also generate some eager queries when they can be useful.

You can see a ManyToOne in our sample here: https://github.com/jhipster/jhipster-sample-app/blob/main/src/main/java/io/github/jhipster/sample/domain/Operation.java#L41

**Comment by yelhouti** [comment]
After disabling the check, switching in my jdl:
```
relationship OneToMany{
	Employee{teamMember(fullname)} to Employee{manager(fullname)}
}
```
with
```
relationship ManyToOne{
	Employee{manager(fullname)} to Employee{teamMember(fullname)}
}
```
I get exactly the same code, which is exactly what I want.

The reason I prefer writing my JDL the other way, is to have an easier JDL to read:
I define below each entity, it fields then it its entities, where the lest side (in this case manager) show that there is a managerId field in employee, this is the same reasoning for OneToOne and ManyToMany with Sets. and always using ManyToOne I avoid think what is the right relationship to know.
Of course this should be used with caution the same way OneToMany with back reference is used, because calling it when the Set is two big or switching it to not lazy, has a huge cost on performance.

**Comment by Tcharl** [comment]
So, this one should be closed?

**Comment by yelhouti** [comment]
@Tcharl
