### ISSUE TITLE
Translations are missing

### ISSUE THREAD

**Issue by qmonmert** [jhipster/generator-jhipster#13025]
##### **Overview of the issue**

Translations are missing with Angular and React.

![image](https://user-images.githubusercontent.com/9989211/98840241-d84a7100-2446-11eb-8f5e-53bda9608d58.png)

##### **Motivation for or Use Case**

Translations are missing on the front end.

##### **Reproduce the error**

Generate an application with Angular or React.

##### **JHipster Version(s)**

Main branch

##### **JHipster configuration**

```
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "reactive": false,
    "baseName": "jhipster",
    "jhipsterVersion": "6.10.5",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1605110559824,
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "fr"
    },
    "serviceDiscoveryType": false,
    "authenticationType": "oauth2",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": [],
    "websocket": false,
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "react",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": true,
    "nativeLanguage": "fr",
    "packageFolder": "com/mycompany/myapp",
    "clientThemeVariant": "",
    "languages": ["fr", "en"]
  }
}
```

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
Can confirm. I experienced this yesterday on my Twitch stream when using
the main branch.

**Comment by MathieuAA** [comment]
Don't we have tests for that?

**Comment by avdev4j** [comment]
> Don't we have tests for that?

We have a bunch of tests for that -> https://github.com/jhipster/generator-jhipster/blob/main/test/languages.spec.js

Maybe we do not cover each case.

**Comment by Blklove** [comment]
really>

**Comment by kaidohallik** [comment]
If I try this command:
```
npx mocha --no-insight --forbid-only --parallel --grep languages
```
then I see couple of messages in the console:
```
yeoman-test: question languages was asked but answer was not provided
```

If I regenerate application after generation (`jhipster --force`) then this fixes translations. So it seems to be related to prompts.

**Comment by mshima** [comment]
This error occurs in one use case:
- using prompts and no language selected.

When executing languages stand alone it should just add another language.
So in this case when no language is selected at prompt, there is a bug that default value is set and the generator just ignores the new added language, supposing it was already added, because the language is already in the config.
If another native Language other than en, fr, is selected, the translation for that language is generated, but not English and French secondary languages.

I have the PR ready, updating it soon.

**Comment by kaidohallik** [comment]
FYI just in case: I finished `git bisect` and found out that first bad commit according to this issue is: https://github.com/jhipster/generator-jhipster/commit/e7eb0c690544a1f11d22beeb20df58609ec08158

**Comment by mshima** [comment]
@kaidohallik I think this was temporary fixed because default language was undefined for some hours.
If you start again, probably you will trace back to the workflow refactoring.
Test case doesn’t cover this case.

**Comment by kaidohallik** [comment]
I tested fix and now are translations available right after generation without need to regenerate, but noticed that if in native language choose default choice `en` and leave other languages empty then `fr` is automatically added to languages array:
```
"languages": ["en", "fr"]
```
Expected behaviour: `languages` array should contain only `en` if `fr` is not choosed.

**Comment by mshima** [comment]
@kaidohallik it defaults to `fr` selected like jdl, so you should deselect `fr`.
Probably that's not a good idea, I will revert that.
