### ISSUE TITLE
Webflux and Postgresql with many-to-many relationships is broken.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#13056]
##### **Overview of the issue**

`sqlfull` test case fails at postgres.
See https://github.com/jhipster/generator-jhipster/runs/1403524237

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by ctamisier** [comment]
The problem seems somewhere around this: https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/service/EntityManager.java.ejs#L179

when entity.getId() is null, the resulting request is `INSERT INTO test_many_many_pagination_dto VALUES ()` which is not valid to postgresql..
