### ISSUE TITLE
GET /api/users and GET /api/users/{login} NOT secured to ROLE_ADMIN when using OAuth2

### ISSUE THREAD

**Issue by peterboni** [jhipster/generator-jhipster#1309]
`@RolesAllowed(AuthoritiesConstants.ADMIN)` annotation on `getUser` doesn't work:

```
    /**
     * GET  /users/:login -> get the "login" user.
     */
    @RequestMapping(value = "/users/{login}",
            method = RequestMethod.GET,
            produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    @RolesAllowed(AuthoritiesConstants.ADMIN)
    ResponseEntity<User> getUser(@PathVariable String login) {
        log.debug("REST request to get User : {}", login);
        return userRepository.findOneByLogin(login)
                .map(user -> new ResponseEntity<>(user, HttpStatus.OK))
                .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }
```

Also `getAll()` doesn't even have that annotation:

```
    /**
     * GET  /users -> get all users.
     */
    @RequestMapping(value = "/users",
        method = RequestMethod.GET,
        produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    public List<User> getAll() {
        log.debug("REST request to get all Users");
        return userRepository.findAll();
    }
```

Fix: Need to add `/api/users/**` to `OAuth2ServerConfiguration`:

```
                .antMatchers("/api/logs/**").hasAnyAuthority(AuthoritiesConstants.ADMIN)
                .antMatchers("/api/users/**").hasAnyAuthority(AuthoritiesConstants.ADMIN)
                .antMatchers("/api/**").authenticated()
```

**Comment by jdubois** [comment]
You are correct. It's not working for normal authentication too.

In fact this wasn't meant to be secured, it's useful to have access to basic user information (we don't send password details, for example), and it can be easily secured (as you show).

The RolesAllowed annotation is something I forgot to remove (anyway it was stupid to secure the /api/users/login and not the /api/users ).

I modifying all this, but I see I did something specific for OAuth2, which is the root cause of the issue -> I'm first correcting this for the other security mechanisms, and I'll keep an eye on OAuth2. I'm the one who coded it, so I don't know why this was changed, I can only imagine that person had a good reason to do it.
