### ISSUE TITLE
Unable to deploy to JBoss AS 6.1.0 using glassfish jersey 2.6 for restful web service

### ISSUE THREAD

**Issue by railsstudent** [jhipster/generator-jhipster#1323]
Can application deploy to JBoss AS 6.1.0? When it was first deployed to JBoss 6.1.0, hibernate version conflicts because pom.xml specifies hibernate.version 4.3.6.Final and JBoss provides 3.6.6.Final. Should I downgrade hibernate version to 3.6.6.Final in pom.xml and redeploy?

Please kindly advise because I am very new to maven.

Thanks

**Comment by jdubois** [comment]
We have lots of reports of people successfully deploying to JBoss, but I'm not using it personally. All I can imagine is that you use an old version of JBoss, with some Glassfish jars, and with some forced older Hibernate libraries, so you probably have some conflicts there, but those are not caused by JHipster...
Please ask this kind of questions on StackOverflow, you might get answers there.
Or ask your JBoss salesperson, but as you replaced some libraries, you probably have voided your support contract anyway.
