### ISSUE TITLE
Validation when creating relationship to another entity

### ISSUE THREAD

**Issue by ddewaele** [jhipster/generator-jhipster#1327]
At the moment, there is no validation if you add a relationship to a non-existing / invalid entity, resulting in compilation errors after generation.

**Comment by jdubois** [comment]
Yes, but we can't do anything about it: if you generate a link to an entity, you are supposed to then generate that entity.

For example, you create an "author" that has a one-to-many relationship to "book". You need to generate the author first (and this is checked by JHipster), because you need the foreign key. But if then you don't generate the "book", it's not going to work.
