### ISSUE TITLE
Why not using hibernate query cache

### ISSUE THREAD

**Issue by yukinami** [jhipster/generator-jhipster#13366]
##### **Overview of the feature request**

Consider using hibernate query cache.

##### **Motivation for or Use Case**

When I created the project with **Spring cache abstraction enabeld**, I found that find methods in `UserRepository` are annotated with  `@Cacheable`. 
Why not using hibernate query cache so that we dont't have to manually invalidated relevant caches.

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by avdev4j** [comment]
hi @yukinami 
I wonder what will happen if we don't have Hibernate cache enabled. I understand your proposal and I think it makes sense while you have hibernate second level cache enabled, if we don't we should anyway manage that manually.

I think this is quite old in JHipster and maybe nobody reviewed that since this has been added in the generator.

I suppose, if we want to make it real, we need to manage 3 cases:
* We have hibernate cache enabled -> use hibernate query cache
* We have cache selected but not hibernate cache -> use Spring cache
* We don't have any caches selected -> do nothing

But it requires to check if enabling query caching will affect or not other behaviors. What happens if all queries will be cached?

It could be an improvement but with a bit more complexity in templates for more "automatic" cache management.

For m, we just need to check if it worth it or not. Would you like to suggest something?

**Comment by venustulips** [comment]
I was also surprised by Hibernate L2C not caching the entities loaded using `findAll`.

Then I came across this good blog https://blog.frankel.ch/digging-hibernate-query-cache/ which explains L2C relation with query cache.

As per the author, in order to work 'findAll' with L2C, one must do the following 2 things. 

1. Enable Hibernate query cache
2. Add `@QueryHints(QueryHint(name = HINT_CACHEABLE, value = "true"))` to the method(s).

Although I have not tested it yet with jhipster, which I am planning to do in the coming weeks, the source blog is a well-known and reliable one.

**Comment by yukinami** [comment]
Some people (like me) take jhispter as some kind of best practice. So using Spring Cache instead of query cache in reposority would be a bit confused to me. How is this sound:
1. Using hibernate cache in repository when  Hibernate L2C is enabled.
2. Move the spring cache code to the service layer  when Spring Cache enabled
3. Using `@CacheEvict` to invalidate cache instead of manualy invoke `CacheManager` for better consistency

**Comment by venustulips** [comment]
> So using Spring Cache instead of query cache in reposority would be a bit confused to me

I don't understand why you are mixing spring cache with query cache.
In my understanding, these two are totally two different things.
Spring cache abstracts away all the vendor-specific things while the query cache is just a property of hibernate.

> We have hibernate cache enabled -> use hibernate query cache
> We have cache selected but not hibernate cache -> use Spring cache

Also, query cache uses the L2C cache area to store data. Spring cache alone without L2C does not make sense to me.

**Comment by Blackdread** [comment]
Simple: Query cache should not be used for all queries.
Spring cache and query cache are different mechanism.

Read documentation would help :) [Hibernate doc](https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#caching-query)

With Spring, you would use QueryHints annotation, invalidation is different so better to read docs.

[Spring doc](https://docs.spring.io/spring-data/jpa/docs/2.4.2/reference/html/#jpa.query-hints)

So I do not recommend jHipster to add query cache by default, this should be done manually when you actually know what you are doing.

**Comment by yukinami** [comment]
I thought spring cache is more general cache while query cache is just limited to hibernate search, thus query cache could totally be replaced with spring cache. But manually invalidated cache would be tedious to me, it's very likely to forget to invalidate the cache especially collaborative development. 
Just bacause of it's neeed to manully add QueryHints to make query cache work. What's the problem to enable query cache by default? 
And when cases we could not use query cache, there goes the spring cache.

**Comment by pascalgrimaud** [comment]
Can we have you opinion on this @jdubois ? As you know this part very well

**Comment by jdubois** [comment]
I am clearly against Hibernate query cache:

- It would make us have 3 different caching mechanisms, which is a bit crazy. At the moment we have Hibernate L2 which is very performant at row level, and Spring Cache which is very good at business level, and also works for non-Hibernate scenarios. There’s little room for a 3rd one.
- Query cache is very limited in usage, and suffers from huge performance problems in common use cases. It’s only good for some specific use cases, where Spring Cache can offer a similar solution, with less performance issues. As the example above is about the user cache: with query cache, all the cache would be invalidated as soon as anyone touches an user or its authorities. With Spring Cache we only evict the data that belongs to the user being modified.

**Comment by yukinami** [comment]
Thanks for the reply. The performance problems sound reasonable. I knowed query caching introduces overhead in the area of transactional processing, but did't know how much does it influence exactly.

**Comment by jdubois** [comment]
Oh sorry I should have been clearer: the issue with query cache is invalidation. If you touch on one table that is part of the query, the whole cache is invalidated. So this only works for tables which are not updated often, like data that is updated nightly with a batch.
For all other use cases, and like the one with the User table, data will be invalidated all the time, which will result in bad performance.
L2 cache doesn’t suffer from this issue (it works at the row level), and for Spring Cache you need to manually define how cache is evicted (a bit more work, but that removes this issue).

**Comment by yukinami** [comment]
I got that.  I just reference the statement from hibernate docs
> Caching of query results introduces some overhead in terms of your applications normal transactional processing.
Anyway, thanks for the explanation.

**Comment by avdev4j** [comment]
I think we can close this ticket, now we know that it's not necessarily something we should have as a baseline.
