### ISSUE TITLE
JVM and DB Timezones are different breaking CURRENT_TIMESTAMP

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#13373]
##### **Overview of the issue**

Setting only the DBs time to UTC breaks sql time functions.

##### **Motivation for or Use Case**

Least surprise principal (Wasted a lot of time one this, a workaround is to pass an Instant as a parameter, but this should work IMO)

##### **Reproduce the error**

```
    // Test to add to HibernateTimeZoneIT

    @Test
    @Transactional
    public void assertThatSqlCurrentTimestampIsTheSameAsInstantNow() {
        dateTimeWrapperRepository.createWithCurrentTimestamp();
        List<DateTimeWrapper> allDateTimeWrappers = dateTimeWrapperRepository.findAll();
        DateTimeWrapper lastDateTimeWrapper = allDateTimeWrappers.get(allDateTimeWrappers.size() - 1);
        long diffInstant = Instant.now().getEpochSecond() - lastDateTimeWrapper.getInstant().getEpochSecond();
        assertThat(diffInstant > -60).isTrue();
        assertThat(diffInstant < 60).isTrue();
    }
```

```
@Repository
public interface DateTimeWrapperRepository extends JpaRepository<DateTimeWrapper, Long> {

    @Query(nativeQuery = true, value = "INSERT INTO jhi_date_time_wrapper (instant) VALUES CURRENT_TIMESTAMP()")
    @Modifying
    void createWithCurrentTimestamp();
}
```

##### **Related issues**

#11740 #11780 

##### **Suggest a Fix**

make the JVM match the DB, specially since servers are often now run inside containers in different parts if the world. For Devs who needs to check same day..., I guess they should code the logic in as a param and offset before checking...

##### **JHipster Version(s)**

7.0.0-beta

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by yelhouti** [comment]
@avdev4j :D

**Comment by gmarziou** [comment]
I got caught by this one as well due to db server's clock not being synchronized by NTP, now I pass the time as a query argument.

**Comment by yelhouti** [comment]
@gmarziou exactly what I do, but it's really bad, and it wastes everybody's time. We could add a compile error or something like date if one of these functions is called, explain what we are doing what we are doing, or switch the JVM to UTC. We shoudl also have link to explain what are the other choices and pros and cons for each.

**Comment by avdev4j** [comment]
hi @yelhouti 
I think there is something wrong here and could be the point why you struggled with.

We decided to set hibernate time handling to UTC to ensure we do not rely on the server or JVM timezone to store datetime fields. Because all databases doesn't have a solution to store both datetime and timezone value, storing it under UTC is the best way to use, display or manipulate your date with the time zone you want.

 Here, you are trying to execute a native SQL query with JPQL and use "CURRENT_TIMESTAMP" function. According to the [javadoc](https://www.eclipse.org/eclipselink/api/2.6/org/eclipse/persistence/jpa/jpql/parser/DateTime.html), this function uses the database server to return this value.
I did not test it but as I understand, this will not change anything to change the JVM default timezone, especially because in production you (most of the time) don't have your app and your db in the same server.
 
To make it happen, you need to force the timezone in the db server, not on the JVM.
 
Remember that If we force the JVM timezone this will affect everything like logging, and the first issue was about storing datetime fields only. This is why I'm not very confident with forcing the JVM timezone.
Anyway, this is another debate.
