### ISSUE TITLE
Package by feature

### ISSUE THREAD

**Issue by soffoalbert** [jhipster/generator-jhipster#1345]
I have noticed that the jhipster generator uses package by layer to organise its packages, according to "http://www.javapractices.com/topic/TopicAction.do?Id=205" package by feature is considered best practice. The link provided above provides some if not all of the benefits package by feature provides, and the one that stands out for me is modularity, as modern application tend to be built with the ability to be turned into micro-services at some stage.

**Comment by rasheedamir** [comment]
+1 @soffoalbert 

I also prefer package by feature and we have modified the package structure generated by jhipster to use it an application we built for a client.

Here is good use case reference app by @olivergierke [he is spring-data lead]: https://github.com/olivergierke/spring-restbucks

**Comment by jdubois** [comment]
Well, what else can I say, I just don't agree with that book... I want a domain model where everything is in the same place, not scattered all over my codebase, and not mixed with repositories, services, controllers, etc., because I find this is a huge mess.
The only benefit would be when you can have very separated modules, but:

- you can still do this in JHipster: we only put your domain objects in the "domain" package, but you could do a "domain.order" sub-package, that's a "normal" use of JHipster
- if you can do the same separation for all layers, then your application should be split up into several different applications -> you have a design problem from the start, as you have several different modules that don't interact at all, from the database to the view layer, all in the same application.

**Comment by jdubois** [comment]
I'm closing this feature request, as this is something I will not change in JHipster.

**Comment by olivergierke** [comment]
> I want a domain model where everything is in the same place...

I guess you missed one core concept of DDD then: a bounded context. Packaging by layer is basically like sorting clothes by color. Feature packages basically allow you aligning the code base with a domain design.

One obvious benefit of packaging by layer is that a lot more types can be made package protected which significantly reduces the risk of architectural degradation of a code base over time. In case you think architecturally sound code structure could still be a worthwhile improvement to jHipster, [this blog post|http://olivergierke.de/2013/01/whoops-where-did-my-architecture-go] has more details on the positive effects of this approach.

**Comment by jdubois** [comment]
Yes I know this pattern, but I don't think it's such a great idea.

**Comment by soffoalbert** [comment]
Any Reasons ?

**Comment by jdubois** [comment]
Yes, see my 1st comment...

**Comment by olivergierke** [comment]
He was asking for reason, not for opinion ;).

**Comment by jdubois** [comment]
This is just playing on words.
Code wins arguments.

**Comment by soffoalbert** [comment]
Okay Julien Dubois. Merci Pour ton opinion. i must say this is an awesome
project "JHipster" ! keep up the good work.

**Comment by jdubois** [comment]
Thanks @soffoalbert 
I've had a closer look at @olivergierke 's code, and still I don't want to mix repository, service and Web beans together.
You can still do sub-packages in the domain package, and then I'm not sure this will make such a big difference in the end: the repository package is nearly empty (thanks Spring Data), and the service layer is not mandatory (and when you need it, it's because you have something which is cross-entities, so you have the same issue).
Moving classes around is always an option anyway, as it's your IDE which is doing the refactoring -> we just generate the base class, and you need to modify them anyway, so it's always the same idea in the end, you need to take those classes and code them yourself, and JHipster is only here to help at the very beginning

**Comment by soffoalbert** [comment]
makes sense. thank you!
