### ISSUE TITLE
Correct the DockerFile build

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1353]
The DockerFile build is broken:

https://registry.hub.docker.com/u/jdubois/jhipster-docker/builds_history/5596/

We also need to check if port 3000 works with BrowserSync on Docker.

**Comment by drissamri** [comment]
The docker build was failing on npm dependency files like ***b2c418cc-oot-npm-lodash-2-4-1-package-tgz.lock.STALE***. Since I have no experience with node I did not try to get to the bottom of this issue.

I updated node version to 0.12 which solved the problem. I had to download the binaries from another repository since ppa since is no longer being updated. This was also mentioned in an [issue #4](https://github.com/jhipster/jhipster-docker/issues/4) on the jhipster-docker repository.

**Comment by jdubois** [comment]
I merged your PR and everything seems to build now

- if you have the time, more tests are always welcome!
- I didn't check if browsersync was working inside Docker -> I opened up the 3000 and 3001 ports in case

**Comment by drissamri** [comment]
I'm going to try to commit some improvements soon for the Dockerfile and will try to do some more extensive testing then.

**Comment by jdubois** [comment]
Please do! I don't have enough time for the DockerFile, this is a huge work to make correctly.
