### ISSUE TITLE
Feature Request: Add yes as default for all questions asked during entity creation

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#1385]
While creating an entity, for the question ```Do you want to add a field to your entity``` if we accidentally type anything other than ``Y`` it proceeds to ask relationship questions. This is quite frustrating when creating lot of entities by hand, can the default be yes (Unless we type N or No)? so that even if we accidentally start typing a field name we do not come out of the loop.
Else is it possible to have a menu like selector in entity generator, so that once you finish the questions you have an option to add more or edit? I think this would ease out the use of entity generator a lot, especially to people who start using hipster new
like:
1. Add field
2. Add relationship
3. Add validation
4. Finish
etc?

p.s : I'm using windows

**Comment by jdubois** [comment]
I see what you mean, and I often have the issue myself.
Unfortunately I'm not sure there is an easy solution for this -> currently I try to have a "logical" default, that is "no" for all optional answers (like validation) and "yes" otherwise.

The only real solution, as you suggest, would be to allow editing an existing answer, but that would probably be a lot of work.

**Comment by deepu105** [comment]
Im not very familiar with yo, but since its on js anyway, wont it be storing all the captured answers in a js object somewhere before you finish the stub cycle?  If so will it be possible to present that object to the user for final confirmation or edit?

**Comment by jdubois** [comment]
This can be done, but it's not how it works out of the box, so that would probably be quite a lot of work.
The Yeoman generators I know of don't provide this kind of feature, that's why we also don't provide it.

I understand your issue with the default "No" answer, because I often have the same issue myself - however if we put "Yes" by default we still have the same kind of issue: we stay in the loop, but maybe we wanted to get out of it?

So currently we don't have a good solution for this. My best solution would be to use the (currently under development) [JHipster UML project](https://github.com/jhipster/jhipster-uml), so you can modify everything before running the generator.

**Comment by deepu105** [comment]
Will you be willing to merge, if i attempt this?

**Comment by jdubois** [comment]
Thanks @deepu105 but I'm not really convinced at the moment that this would be a good idea. I'd rather wait a little bit for JHipster-UML and see if that solves some of this problem (not sure, this is of course still a work in progress)

**Comment by deepu105** [comment]
OK
