### ISSUE TITLE
OpenAPI modelPackage

### ISSUE THREAD

**Issue by Asconius** [jhipster/generator-jhipster#13995]
##### **Overview of the issue**

By default, the OpenAPI model (DTOs) is generated in the * .web.api.model package. The ArchTest checks that the services do not use any classes from the web package. It is therefore not possible for service methods to receive and return model classes.

##### **Motivation for or Use Case**

Services should be allowed to use the OpenAPI model

##### **Reproduce the error**

1. Insert Components/Schemas into api.yml
2. Generate OpenAPI files
3. Use generated DTOs in Service
4. Start ArchTest 

##### **Suggest a Fix**

The OpenAPI model should be generated in the package service.dto

From
`<modelPackage>*.web.api.model</modelPackage>`
To
`<modelPackage>*.service.dto</modelPackage>`

##### **JHipster Version(s)**

v6.10.5

##### **JHipster configuration**

OpenAPI generator must be activated when creating the project:
`Which other technologies would you like to use? API first development using OpenAPI-generator`

**Comment by pascalgrimaud** [comment]
can you have a look on this ticket plz @ecostanzi as you're our expert on this part

**Comment by atomfrede** [comment]
Should we allow to use generated web(layer) classes inside the service layer? Shouldn't we have proper dto mapping in place?

**Comment by ecostanzi** [comment]
IMHO it would be hard to strip the DTO imports from the service layer without adding another mapping layer between web and the persistence layer. In my experience being able to manipulate DTOs in the service layer is a good compromise.

I would generate the openAPI DTOs in:
`<modelPackage>*.service.api.dto</modelPackage>`

**Comment by ecostanzi** [comment]
I was about to open a PR for this but maybe I rushed to conclusions.  On one side I agree with Asconius: since Jhipster DTOs are in the service layer, also OpenAPI DTOs should be generated there. On the other hand, what @atomfrede said made me think that someone could choose to add mapping classes in the web layer or in some other package. It really depends on what developers decide.

Since users are used to having the DTOs in the web layer I prefer to keep the model Package as it is now. For those who want to change it, it's just a one-line change in the pom.xml or gradle file. Open to discussion though.

**Comment by Asconius** [comment]
Mapping is carried out by default in the service.mapper package. This can then not be used for the OpenAPI DTO Mapper.
It seems to me as if OpenAPI cannot be integrated into the existing structure.
