### ISSUE TITLE
Allow to specify in id if we want it autoGenerated

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#14108]
##### **Overview of the feature request**

The generator infers if an `@Id` should be autoGenerated bases on the field type.
##### **Motivation for or Use Case**

This prevents from having the ability of adding a UUID generated in the frontend or a Long added manually based on a manual process (from other software...)

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by king-il** [comment]
Auto generating the id is the default behavior in the Spring Data entity.

to add Ids manually just remove the annotation ```    @GeneratedValue(strategy = GenerationType.IDENTITY)``` from the id attribute in your domain class. and remove the code below from your RestController.
```
if (entityName.getId() != null) {throw new BadRequestAlertException("A new enitytName cannot already have an ID", ENTITY_NAME, "idexists"); }
```
Because changing this is simple (could be done manually or with refactoring) and seeing this in the generator will cause confusion,; I don't think this option should be added.

Regards,

**Comment by gmarziou** [comment]
@king-il this does not look as simple to me. For instance, this has impacts on client code too.

@yelhouti how would you want to implement it in client? Should the id value be entered by user? If it's a UUID, should a random value be generated?

**Comment by yelhouti** [comment]
thanks @gmarziou and indeed, changes needs to be added in liquibase frontend e2e tests... but than fully, we already have a variable field.autoGenerate that is used for String ids... (not working correctly in current version by the way) and would use that same variable to make the UUID generation. I would generate the UUID in the client to allow for easier coding of offline mode...

**Comment by mraible** [comment]
I don't think we should generate UUID's in the client because then every client implementation needs to worry about it.

**Comment by yelhouti** [comment]
@mraible this is totally optional and could be left to blueprints, for the frontend. Without this, an offline mode is much harder to implement because of relationships...

**Comment by king-il** [comment]
@mraible @gmarziou if the id is of type Long no other changes are needed except for making the id field visible (by default hidden) in the frontend then you could use any third party generators or enter it manually. 

and i think that jhipster don't allow UUID or String as pk in the JDL.
so the question here is to support custom ids in the jdl since the id field is being handled automatically.

===========================================================
the other solution is to add a uuid field in your enity beside the auto-generated id and add type validations.

**Comment by yelhouti** [comment]
@king-il the not yet release v7 allows it, I implemented the `@id` annotation in JHipster (it allows String, + UUID was added later by someone else probably mshima), the other 2 people are core team members, we all spent many hours inside the code and know what we are talking about ;) .

**Comment by king-il** [comment]
@yelhouti i didn't know the beta version allows it. I'm only using the current stable version and i thought you were talking about it.
anyway good luck :)

**Comment by yelhouti** [comment]
I am willing to make a PR if more people are interested, for now I might just do it manually.

**Comment by DanielFran** [comment]
Close by https://github.com/jhipster/generator-jhipster/pull/17837
