### ISSUE TITLE
add documentation page highlighting difference between "module" and "blueprint" and when to choose one vs the other

### ISSUE THREAD

**Issue by 62mkv** [jhipster/generator-jhipster#14157]
##### **Overview of the feature request**

Please, add documentation page into "Modules & Blueprints" section, highlighting the difference between "a module" and "a blueprint" and when to choose one vs the other

##### **Motivation for or Use Case**

For a person (like myself) who only thinks into looking at extending JHipster capabilities, it's currently plainly confusing to understand, what the differences are between modules and blueprints, I have a vague perception that a blueprint is more powerful, but that's just a guess.

I would want to see a page that would explain concisely, what each of those is, how are they different from each other, what capabilities does each of them has, what the expected use cases for both, what is the lifecycle, etc.

That might be obviuos to people with JHipster/Yeoman background, but long not for everyone who might want to look into this. 

Thanks in advance!

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by 62mkv** [comment]
I've noticed there're also pages on _Creating_ a blueprint/module, but not on how to use them, or at least not under this section. this information would also be come very handy

**Comment by pascalgrimaud** [comment]
Agree with you @62mkv - don't hesitate to ask question here, until the documentation is updated

**Comment by 62mkv** [comment]
thanks @pascalgrimaud ! As I just learned from @ecostanzi there're also so-called "needles" that might (or might not) be what I am after, (I'd like to be able to inject certain pieces of code here and there, but otherwise keep the default generators' code), and those needles seem also to not be documented on the jhipster.tech at all

**Comment by pascalgrimaud** [comment]
The needle is just a comment in the code, used for injecting specific code of module or blueprint.
If you need to add needle, feel free to open a new pull request, as it won't impact existing code, because it's just a comment

For example:
- here a needle: https://github.com/jhipster/jhipster-sample-app/blob/main/pom.xml#L15
- here the function which is used to add dependency: https://github.com/jhipster/generator-jhipster/blob/main/generators/server/needle-api/needle-server-maven.js#L50-L63

So your workflow:
- propose a pull request to add the needle
- in your module or blueprint, code a function which will replace the needle by the code you want
- use this function in your module / blueprint

**Comment by 62mkv** [comment]
cool! but _how_ does a module/blueprint leverage those needles? that's what I mean is missing from documentation

**Comment by pascalgrimaud** [comment]
The needles are here to help for finding / replacing code at the right place, there are too much needles, you need to search directly in generator-jhipster
But it's not mandatory to use them. You can use regexp to introduce the specific code where you want
Or better, you can use regexp too, to delete the code you don't like in JHipster :)

**Comment by 62mkv** [comment]
Thanks! I thought maybe there was some special API to interact with those needles) 
--
Sent from Mail.ru app for Android Thursday, 04 March 2021, 05:36pm +02:00 from Pascal Grimaud  notifications@github.com :

**Comment by mshima** [comment]
There are.
https://github.com/jhipster/generator-jhipster/blob/bcd0aaf76ab798d7d6a0e9f4f7cc907b1b9cdc05/generators/generator-base.js#L943-L966

**Comment by avdev4j** [comment]
> Thanks! I thought maybe there was some special API to interact with those needles)

Such as @mshima said, there is an API to interact with needles. You can create needles in your own blueprint if you need more (on specific parts) otherwise, it can be done under a PR here if it can benefit from other people just like @pascalgrimaud said.
Here is an example of how to add needles in a blueprint: https://github.com/entando/entando-blueprint/tree/master/generators/entity-microfrontend/needle-api

About the first subject, you can check this video we made from a JHipster live event: https://www.youtube.com/watch?v=9D2Pv2JnLDs&t=1184s

I dealt with the differences between modules and blueprints. I hope it can help you. Anyway, I think you are right, we should have better coverage about the module/blueprint documentation (spoiler: sometimes both can match with what you want to do and it's more up to you than anything else).

**Comment by 62mkv** [comment]
thanks so mucj @avdev4j ! Nice session. For the sake of history let me also paste the link to an article here: https://medium.com/@anth.viard/build-your-own-jhipster-with-modules-and-blueprints-dd7a2833a388

May I confirm, that in case when I'd like to _inject_ certain code (I am really not sure is it _extending_ or _inheriting_) to certain entity-related _client_ files (at least into _entity-component.ts_ and _entity-component.html_) *plus* create some files, also in the client folder, than `blueprint` (with _merging_ approach) is the way to go, right?

**Comment by 62mkv** [comment]
also "sharedOptions" and "commands" CLI customisations for blueprints need to be covered in the docs; I could not find any example of actual blueprints using those (I could find one for commands, probably). The PR that added those capabilities was: https://github.com/jhipster/generator-jhipster/pull/11337 by @mshima

**Comment by mshima** [comment]
> also "sharedOptions" and "commands" CLI customisations for blueprints need to be covered in the docs; I could not find any example of actual blueprints using those (I could find one for commands, probably). The PR that added those capabilities was: #11337 by @mshima

The PR your are mentioning is used by dotnetcore. https://github.com/jhipster/jhipster-dotnetcore/blob/eb9b1d59395f5d851ee693bce2a45659f924623f/generators/utils.js#L115-L121

sharedOptions AFAIK it's not used, but it was implemented to customize configuration before `app` had blueprint support.
with `app` blueprint/sbs-blueprint support, it became `useless`.
Custom commands support, I think it existed before.
The best doc for those features are the test cases: https://github.com/mshima/generator-jhipster/blob/main/test/cli/cli.spec.js.

> UPD: the reason I was looking into them: I was trying to find a "proper" way to persist blueprint configuration options; something like `.yo-rc.json` but for blueprint internal config

For blueprint configuration I recommend putting in `this.blueprintConfig` just like `this.jhipsterConfig`.
Most of the blueprints uses `this.jhipsterConfig`.
https://github.com/jhipster/generator-jhipster/blob/0fcd11871acf47957d7ef4a068b3a904a162a6e5/generators/generator-base-blueprint.js#L48-L49
The only difference is the namespace at `.yo-rc.json` file.

**Comment by 62mkv** [comment]
Thanks! 
Can blueprint write to '.yo-rc.json' as well, from prompting phase?
And what storage + API would you suggest if that blueprint config were to be defined per entity? .jhipster/entity.json ? I am not sure if "main" and "blueprint" generators could/should share configuration files...
--
Sent from Mail.ru app for Android Thursday, 18 March 2021, 10:27pm +02:00 from Marcelo Shima  ***@***.*** :

**Comment by mshima** [comment]
> Can blueprint write to '.yo-rc.json' as well, from prompting phase?

Sure, but you should use generator apis, no `require('fs')` apis, since the file should be manipulated at mem-fs only.
`this.jhipsterConfig.foo = 'bar'` will write `{"generator-jhipster": {foo: "bar}}`
While `this.blueprintConfig.foo = 'bar'` will write `{"generator-jhipster-my-blueprint-name": {foo:"bar"}}`
They can be used anywhere and anytime, and will be committed to disk only at `conflicts` priority.

> And what storage + API would you suggest if that blueprint config were to be defined per entity? .jhipster/entity.json ? I am not sure if "main" and "blueprint" generators could/should share configuration files...


- You can create a custom storage inside it entity.json: `this.createStorage(`.jhipster/entity.json`, 'generator-jhipster-my-blueprint-name')`, https://yeoman.github.io/generator/Generator.html#createStorage
- You can create a custom storage inside it .yo-rc.json `this.blueprintStorage.createStorage('entities.Entity')`
- Or just use it the entity.json, the only detail is that mixing `main` and `blueprint` config is not future proof.

I actually prefer to keep every config inside `.yo-rc.json`, anyway, this is just a organization preference.
