### ISSUE TITLE
Log4j2 Support

### ISSUE THREAD

**Issue by thekalinga** [jhipster/generator-jhipster#1430]
http://blogs.mulesoft.org/disrupting-asynchronous-loggers/

Log4j2 outperforms logback in both latency & throughput.

**Comment by lokkju** [comment]
I'll probably be starting more tickets related to this, but what about sticking with the Slf4j API, and making the implementation a configuration choice?  Log4j2 has an Slf4j API implmentation, as do most other libraries.  As well, since the Slf4j API is already being used in jhipster, no code changes should be needed in most generated classes.

**Comment by cselti** [comment]
As you wrote: "since the Slf4j API is already being used in jhipster (via logback's Slf4j API implementation), no code changes should be needed in most generated classes"
If you prefer log4j2, you can change it easily in your project. JHipster is a tool - it creates a good starting point for your project, but will not write the all application instead of you. Every application has it's own logic, lifecycle, dependencies - we can't except, that a tool like JHipster will solve every application's specific needs - but you can customize it, if want.

**Comment by thekalinga** [comment]
The only reason for the ticket is to have a good staring point (the whole point of jhipster to begin with). Besides, log4j2 have adapters to various other frameworks similar to slf4j.

Will keep this ticket open for couple of more days just incase if there is attention. Else, will close it..

Thanks

**Comment by jdubois** [comment]
Please leave it open, I need time to work on this.

**Comment by RaphaelBrugier** [comment]
Asynchronous logging will increase the throughput of your logging but has drawbacks I wouldn't except with a default logging configuration.

See https://logging.apache.org/log4j/2.x/manual/async.html for details.

By the way, if you really need very high throughput for your logging and want to stick with logback you can use the logback extension provided by the [OpenHFT project](https://github.com/OpenHFT/Chronicle-Logger).

**Comment by jdubois** [comment]
In our default configuration, we output to the console: we do not use an asynchronous logger.

This is because we follow the 12-factor methodology, which states at http://12factor.net/logs that the logger should go to the console, unbuffered. This shouldn't be our app responsibility to do this.

This is also what Dropwizard does, so we are in rather good company here.

I'll keep this opened until I have the time to see those other options, but at the moment I'm happy with following the 12-factor methodology, and this also is consistent with my own experience (sysadmins want to manage the logs themselves)

**Comment by jdubois** [comment]
As long as we don't use an async logger I don't think this is a useful change.

**Comment by erikkemperman** [comment]
@jdubois I understand that having log4j2 support by default is not something you care about especially -- but shouldn't it at least be more or less painless to drop in if we so wish? As @cselti wrote above:

> If you prefer log4j2, you can change it easily in your project. 

But that doesn't seem to be the case!?

I am pulling in some other maven modules, all of which we've set up with log4j2 some time ago and we are inheriting from those a transitive dependency on `log4j-slf4j-impl`. But it turns out that it is all slightly more complicated than just excluding the `logback-classic` artifacts in our jhipster-generated pom.

Most jhipster-generated classes correctly use the slf4j API, but the `LoggerDTO` and `LoggerResource` classes actually rely on the implementation being logback... See their `import` statements for example.

Would it therefore make sense to try and use reflection here, so these classes can correctly function without having multiple (and conflicting) implementations of sfl4j on the classpath?

**Comment by gmarziou** [comment]
As an alternative, you could implement this as a [jhipster module](http://jhipster.github.io/modules/creating-a-module/) that would take care of replacing LoggerDTO and LoggerResource classes by their equivalent for log4j2 and update the pom.xml.

**Comment by erikkemperman** [comment]
@gmarziou Thanks, that might be a better idea than a single fixed class with a lot of reflection going on.

**Comment by jdubois** [comment]
@erikkemperman but you are correct, if we don't have the right imports we must correct that, and I'm checking this right now!

**Comment by jdubois** [comment]
@erikkemperman OK in fact we only use the Logback imports for updating the logback configuration on the fly, and this is normal that we use the internal API for that.

**Comment by erikkemperman** [comment]
@jdubois That depends, I guess, on how easy it should be for people to change logging implementation... It is definitely true that the things that `LoggerDTO` and `LoggerResource` do is not possible with just the SLF4J interfaces. But implementing it with reflection, which I tried briefly, becomes quite ugly.
