### ISSUE TITLE
Application should reject incompatible profiles combinations

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#1443]
As far as I know, dev and prod profiles are mutually exclusive, so I think that Application class should throw an exception when both profiles are set. This could help newcomers.

**Comment by jdubois** [comment]
This should be linked to #1408

Here is how it was supposed to work, but I haven't checked for some time, as a user putting at the same time the "dev" and "prod" profile is definitely not doing something very logical:

- If no profile is given -> you are in "dev" profile
- If only "dev" profile is given -> "dev" profile
- If "prod" profile is given, even if there is also the "dev" profile -> "prod" profile
- If "cloud" profile is given -> this only does something in "prod", and add cloud capabilities to the "prod"
- If "fast" profile is given -> only does something in "dev", and removes some features so that we start up faster

We need to:
- Ensure those rules are logical
- Document them better -> only when starting, when there is something not logical (like "dev" and "prod"), log a warning message
- Validate that those rules work

**Comment by atomfrede** [comment]
If there is an incorrect combination detected should there only be a log message or an exception that prevends startup?

Does adding cloud to dev or fast to prod do any harm (didn't try it out)?

**Comment by gmarziou** [comment]
Personally, I prefer to get an exception with a descriptive message.

**Comment by jdubois** [comment]
Anyway the user here is just using profiles without understanding anything, so this will always end up not working well for him...

I'm going to put some clear warning messages, that should be a good starting point, already.

**Comment by jdubois** [comment]
In fact we can only check this after the application has started -> so only solution is a warning message, that something is probably wrong
