### ISSUE TITLE
CR: app generator ask for the default language

### ISSUE THREAD

**Issue by cselti** [jhipster/generator-jhipster#1447]
I know, that modifying manually later isn't too hard, but I think this is a commonly used modification (to change the default language to your own locale) so the generator could be made it.

**Comment by andidev** [comment]
+1

**Comment by jdubois** [comment]
I think we didn't do it at first because we didn't want to have too many questions in the generator.
But yes I agree that this would be a good question to ask, and this shouldn't be hard to do.

**Comment by jdubois** [comment]
And we should also correct the test when changing the default language, see #338

**Comment by thiagogcm** [comment]
I don't know if this is the right place to comment about this but in my opinion the language should be placed in the settings page with an option to save the current lang for further login.

**Comment by tporadowski** [comment]
@thiagogcm there is a pending PR #1402 for this very feature

**Comment by jdubois** [comment]
Is this really the same as #1402 ? Maybe I don't understand this correctly

**Comment by cselti** [comment]
No, it isn`t. It`s similar, but not the same.
I would like such a question in application generating phase, that I can select one of all supported language (not only from en or fr) - and then the generator will add this language to the application, and sets it as default both in spring and angular files. Of course, the English will be the base for the translations, but the selected language will be the applications default.
At now, I can achieve this, that I will add an extra language after the app generation, and I modify the source files, that this language will be the default. 
But I think, this step is common (for those apps, that are targeting different some specific nationality), so It can be included in the application generating phase.

**Comment by jdubois** [comment]
OK, this is indeed another issue (by the way, I just merged #1402 so that's already a good start).

But now I realize that something is wrong in the way language works: at the beginning of JHipster, the idea was that we were using the user's browser language as a default language. That's what I have always done, and what most website do, as it's the most logical thing to do. And if that language is not present, we switch back to English.

This solution is better, for me, as:

- It's the language of the end user, so of course it's better for him
- no need for a new question in the generator

-> is this a good solution for you too?

**Comment by cselti** [comment]
Ok, my idea was just a proposal - that solution is also good for me :)

**Comment by jdubois** [comment]
So it turns out it is not a good option to use the browser's language, as this is not reliable:
http://stackoverflow.com/questions/1043339/javascript-for-detecting-browser-language-preference

So we will stick with our current way of working, the good news is that the "preferred language" is just set in one part of the AngularJS application -> I will document this and link it to this page.

When all you have to do is change one line of configuration somewhere, we don't prompt this in the generator, as there's too little value: you will need to configure Angular Translate afterwards, but once again it's just one line of configuration to change.

**Comment by cselti** [comment]
I agree - updating/extending the documentation page will be an useful solution for this request.
