### ISSUE TITLE
Keycloak configuration with monolith Oauth2 not working

### ISSUE THREAD

**Issue by monjurmorshed793** [jhipster/generator-jhipster#14540]
##### **Overview of the issue**

Application generated as monolith and oauth2 type security is not working with keycloak (generated with Jhipster V7).

##### **Motivation for or Use Case**

When I log in as admin or as user, then after successful login when the redirection occcurs, a page is shown with json response mentioning 'unauthorized'.

##### **Reproduce the error**

My yo-rc.json is:

```json
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "EmployeeManagement",
    "jhipsterVersion": "7.0.0",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": ["cypress", "gatling", "cucumber"],
    "pages": [],
    "creationTimestamp": 1617205835913,
    "serviceDiscoveryType": false,
    "reactive": true,
    "authenticationType": "oauth2",
    "packageName": "org.morshed",
    "serverPort": "8080",
    "cacheProvider": "no",
    "enableHibernateCache": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "buildTool": "maven",
    "serverSideOptions": ["searchEngine:elasticsearch", "messageBroker:kafka", "enableSwaggerCodegen:true"],
    "websocket": false,
    "searchEngine": "elasticsearch",
    "messageBroker": "kafka",
    "enableSwaggerCodegen": true,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "org/morshed",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"]
  }
}
```

##### **Jhipser Version**

Jhipster V7

**Comment by mraible** [comment]
I tried to reproduce this error, but I could not. I installed JHipster 7, and created an app with your `.yo-rc.json`. Then, I started all the Docker containers using Oh My Zsh shortcuts.

```
jhkeycloakup
jhesup
jhkafkaup
```

Then, I started the app and was able to log in with no issues.

<img width="1296" alt="Screen Shot 2021-03-31 at 1 12 33 PM" src="https://user-images.githubusercontent.com/17892/113198298-ff9db100-9222-11eb-8976-bce5291094da.png">

To prove there aren't any issues, I ran `npm run e2e` and all tests pass. Therefore, I'm closing this issue.

<img width="1442" alt="Screen Shot 2021-03-31 at 1 13 14 PM" src="https://user-images.githubusercontent.com/17892/113198355-0e846380-9223-11eb-81e2-8ca70df261f4.png">

**Comment by monjurmorshed793** [comment]
@mraible , I have tried in windows 10 in a freshly installed machine, not working this time too (04 April, 2021). But tried in Linux, working fine. I tried to run the keycloak from dicker for windows with WSL 2.0.

**Comment by mraible** [comment]
OK, I'll reopen now that we know it's Windows related.

**Comment by jidma** [comment]
Can't reproduce on Windows 10 either.

I used the same `.yo-rc.json` as above (and Docker containers) and it worked fine.

![image](https://user-images.githubusercontent.com/2295247/113769694-cbd5f600-9710-11eb-8bd8-b0ad89ac7ff8.png)

Try cleaning your browser's localstorage and cookies (especially for localhost:9080) and try again. 
This helped me when I had some issues related to Keycloak in the past (might be because of different keycloak realms on the same host for different projects).

**Comment by pascalgrimaud** [comment]
@mraible : little tips -> you can use `npm run docker:others:up` instead. I think I'll upgrade the zsh shortcut to have this, something like:
- `jhothersup` for `npm run docker:others:up`
- `jhdbup` for `npm run docker:db:up`

@monjurmorshed793 :
- try to access to your Keycloak at localhost:9080, check if the realm JHipster is correctly imported, the users (admin/user), etc
- if not, it's because the volume was not mount, as you needed to generate your project inside c:/Users/YourName/
- if it was correct, can you check your Docker version with Windows ?
- try to upgrade to latest version, because I know some versions are broken -> https://docs.docker.com/docker-for-windows/release-notes/ specially related to WSL2 and Docker

**Comment by monjurmorshed793** [comment]
@pascalgrimaud  & @mraible , I have updated my docker for windows to latest docker version and then again tried to regenerate the application. This time, everything is okay and all are working fine. 

So the issue was related to the docker for windows .

This issue can be closed.

**Comment by mraible** [comment]
Thanks for letting us know @monjurmorshed793!

**Comment by Adri-Glez** [comment]
This is the same issue that I had in the gateway option:

https://github.com/jhipster/generator-jhipster/issues/14445

I found that the 'unauthorized'  expired certificate issue is caused  by a problem  in time synchronization in the Windows WSL after the host Hibernate or get Suspended. The solution is restart WSL and Docker or Windows.

**Comment by gmarziou** [comment]
Or maybe make sure your WSL has an NTP server configured with `ntpdate`.
