### ISSUE TITLE
use nvarchar for the entity generator Strings

### ISSUE THREAD

**Issue by ryanhamilton** [jhipster/generator-jhipster#1458]
Currently the entity generator asks for type, if string is specified it defaults to varchar(255). I suggest defaulting to nvarchar for strings. Yes it will take more space but it should reduce multi-language headaches later.

I would also like to have been prompted for text size as I bumped into the default 255 limit without realizing.

I think these suggestions would cause people the least surprises/problems later.

**Comment by jdubois** [comment]
Is this only for MySQL? I don't have this problem with Postgresql (which is the database I use)
I didn't see any issue on this yet, and we have people from all over the world, so I find this strange.

For the limit to 255, it's the default JPA size -> we always use the default for each technologies we use, because that's what we find is the less surprising.
If you select the "validation" question, then you can change this size, and it will be (obviously) validated.

**Comment by gzsombor** [comment]
AFAIK MySQL doesnt have an NVARCHAR type, it's used by the Microsoft SQL Server,

**Comment by ryanhamilton** [comment]
You are correct for postgres and mysql there is no nvarchar, unicode support is default in postgresql.
http://stackoverflow.com/questions/21925802/can-i-able-to-use-nvarchar-data-type-in-plpgsql

You may still want to make it clear when a user chooses String that it is limited to 255 chars. In postgres at least there is text for supporting longer length:
http://stackoverflow.com/questions/4848964/postgresql-difference-between-text-and-varchar-character-varying

**Comment by jdubois** [comment]
OK, so we won't do this, of course, as we don't support SQL Server.
The 255 default comes from JPA, not us.

**Comment by vudangngoc** [comment]
After 5 years, MySQL can support Nvarchar, could you please concern to reopen this ticket?

**Comment by SudharakaP** [comment]
@vudangngoc : I would suggest you create a new issue outlining your feature request and also provide a link to this issue there. :smile:
