### ISSUE TITLE
Switching langage not working (master branch)

### ISSUE THREAD

**Issue by andidev** [jhipster/generator-jhipster#1473]
There is an issue with switching language from english to french (and most probably any language added).
Generate a default jhipster app. Start the application and try switching language to french. This switches the language to french as expected. 
But after that if one tries to navigate anywhere else in the app the result seems to be that the translationns disappear and only the keys are seen.

This is how it looks after navigating to the login page and clicking on the language menu 
![screen shot 2015-05-13 at 19 57 33](https://cloud.githubusercontent.com/assets/571389/7617308/89f2c18c-f9aa-11e4-8142-e0f34bbbe2e7.png)

**Comment by andidev** [comment]
Refreshing the page seems to reload the english language

**Comment by andidev** [comment]
Could this be related to #1402

**Comment by jdubois** [comment]
I've already seen this in my app before #1402 - I don't think it's related.
But after refreshing my browser the problem was gone, so I thought it was just a JSON file which didn't load for some reason.

We need better testing here, but I think there is indeed an issue. I would say this is likely linked to Angular Translate.

**Comment by andidev** [comment]
This issue does not seem to appear on Firefox.

**Comment by andidev** [comment]
So I cleaned up the cookies and know it seems to work. So it was some cookie related issue. Not sure what though.
