### ISSUE TITLE
Use in-memory MongoDB implementation for integration testing

### ISSUE THREAD

**Issue by fabienfleureau** [jhipster/generator-jhipster#1477]
Currently, when we choose a SQL database, JHipster launch an in-memory H2 instance for its integration tests.
It would be nice to have a similar feature when we use MongoDB.
Integrating [fongo](https://github.com/fakemongo/fongo) should do the trick.

**Comment by soffoalbert** [comment]
I like the idea! +1

**Comment by jdubois** [comment]
Yes, it would be nice: FYI we also have this for Cassandra (with Cassandra Unit), so this really leaves MongoDB behind.

initial work was done with https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo but I was afraid to use a native MongoDB instance inside.

I didn't know about Fongo, but here I'm afraid it's not a real MongoDB :-)

So both solutions have their benefits and drawbacks, naturally. And none of them seem very popular: Embedded MongoDB has got 219 stars, Fongo 122 stars...

So that's why for the moment I didn't take any decision on this.

At the moment I'd rather go with Embedded MongoDB as this is what Spring Data MongoDB seems to be using, and they don't seem to have issues with it. And it's also more popular.

**Comment by soffoalbert** [comment]
I agree!

**Comment by jdubois** [comment]
As nobody has worked on this, I'm going to close it.

We have less than 10% of users on MongoDB, and I guess the current way of working is enough for them -> it's good for me too, but I found this solution better as it was closer to the way we work with SQL and Cassandra

So if anyone wants to work on this, feel free to comment & I'll reopen this ticket
