### ISSUE TITLE
Project URL Link in marketplace is wrong

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#14948]
##### **Overview of the issue**

The marked link seems to always point to https://www.jhipster.tech/modules/marketplace/ which is not correct and very confusing.

![image](https://user-images.githubusercontent.com/203401/117777892-585a6380-b23d-11eb-8a03-f07fd5d61b2a.png)

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by swarajsaaj** [comment]
Some intial findings,
- Its not just the Project URL link, the author, maintainer, version are also blank.
- npminfo call to `/latest` (https://cors-anywhere.herokuapp.com/registry.npmjs.org/generator-jhipster-dotnetcore/latest) through 'cors-anywhere' is failing as they have stopped proxying since Jan-2021 (See https://github.com/Rob--W/cors-anywhere/issues/301)

Maybe we can check to get this URL working using some workaround or some other CORS proxy
