### ISSUE TITLE
Error:java: Annotation processor 'org.mapstruct.ap.MappingProcessor' not found

### ISSUE THREAD

**Issue by shineycoding** [jhipster/generator-jhipster#1558]
Hi, I'm try to right-click on the "Application" class at the root of your Java package hierarchy, and run it directly. but the console show some error:

Information:Using javac 1.8.0_45 to compile java sources
Information:java: Errors occurred while compiling module 'bookstore'
Information:2015/6/1 18:00 - Compilation completed with 1 error and 0 warnings in 4 sec
Error:java: Annotation processor 'org.mapstruct.ap.MappingProcessor' not found

Thanks for your help

**Comment by jdubois** [comment]
What IDE are you using?

**Comment by shineycoding** [comment]
The IDE is IntelliJ IDEA 14.0.2

**Comment by jdubois** [comment]
OK, like me then :-)
I thought annotation processing was off by default, did you turn it on? I still haven't found a good way to make it work inside the IDE, so I compile with Maven instead (and if you do so, it should work)

**Comment by shineycoding** [comment]
@jdubois Turned on the annotation processing, but this problem isn't solved yet.

![1](https://cloud.githubusercontent.com/assets/12545744/7916294/cd76ce58-0837-11e5-9929-c528f2217726.png)

Yes, compile with Maven is successful.

**Comment by arsen-hakobyan** [comment]
Hello,
The same issue in IntelliJ IDEA 13.1.1

**Comment by shineycoding** [comment]
@arsen-hakobyan , you can refer to this link http://stackoverflow.com/questions/30526250/errorjava-annotation-processor-org-mapstruct-ap-mappingprocessor-not-found

**Comment by arsen-hakobyan** [comment]
@shineycoding Thank you very much.

**Comment by JCBuck** [comment]
I've researched into this issue a bit as I was relying on Intellij IDEA's compile current file `ctrl+shift+F9` to hot reload classes with jhipster loaded.... since the mapstruct annotations processor was added into jhipster (pom.xml) i was also getting the same error upon building with Intellij..

The issue stems from Intellij being unable to actually resolve the required library/package that does the annotations processing which is `mapstruct-processor` within the classpath (if chosen, as shown in the screenshot above)  

There are two ways to get it to work: Select the `processor path` option and browse through your profile's maven repo and find the mapstruct-processor folder...

OR

insert into the pom.xml (i put mine right under the regular mapstruct):
```xml
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
            <version>${mapstruct.version}</version>
            <scope>provided</scope>
        </dependency>
```
I think Intellij is able to read the pom.xml and inserts the annotation processors into the project settings / .iml (I don't remember manually checking Enable annotation processing, nor adding the fqdn of the processor into the list)

but it fails because it doesn't have the processor itself as a dependency, even though it is specified in the pom.xml when defining the processor annotation originally...  
so this is just a workaround to make it seem like a dependency to put it in the classpath  
which i verified by doing  
`mvn dependency:build-classpath`
and searching for mapstruct-processor jar

I found this workaround here http://stackoverflow.com/questions/14322904/maven-3-how-to-add-annotation-processor-dependency
the `scope` option should prevent it from actually being packaged and distributed

**Comment by jdubois** [comment]
yes @JCBuck I've also added this in my pom.xml for some time -> do you really think this is useful for everyone?

From my understanding you are trying to do hot reload, which just won't work with MapStruct, as will need Java 8, and lambdas are not supported by Spring Loaded

**Comment by JCBuck** [comment]
Ahhh right, my current project is actually using Java 7 and it seems to be working for me with jhipster loaded i suppose something might break?

But I think at least adding that will solve the original issue for the OP, just for what use case i'm not sure (Intellij compiling?)

**Comment by jdubois** [comment]
I'm using some specific Java 8 stuff in Mapstruct, so it just won't work with a Java 7 project. This could be back-ported, of course, but as Java 7 is EOL I have no interest in doing so.
For Spring Loaded, yes it breaks under several cases, and is generally quite buggy. That's why we have stopped using it.

**Comment by Panthro** [comment]
I have a Java 8 with intellij 14 and this issue has happened to my in a common run Application.main(). I guess this should be added as default in the pom.xml as many people will stumble into the same issue.
Or in the docs "for Development or Prepare IDE" should state to disable the processor or add dependency to the pom.

**Comment by jdubois** [comment]
The main issue here is OK I guess -> my only issue is @Panthro 's last comment, which is of course correct.

As by default annotation processing is not enabled, that doesn't worry me too much.
And yes, I'm going to add a line in the IDE section of the documentation -> I'm doing this for IDEA as this is what I use, no idea what it does with Eclipse (if anybody knows, please add a line in the documentation, too!)

**Comment by jdubois** [comment]
@Panthro I just tried it while I was writing the documentation, and I had no error at all! I guess it comes from a newer Idea version, or maybe we corrected something in JHipster. Anyway, I'm not adding the documentation as there is no need to!

**Comment by Panthro** [comment]
@jdubois  I'll check it again later and report the status.

**Comment by jdubois** [comment]
@Panthro I wonder if that is not linked to #1680 -> Mapstruct might now be in the classpath because of SpringFox

**Comment by Panthro** [comment]
Hummm might be, I'm currently on holidays can't check now :panda_face: 

As soon as I get into my dev env I'll try to replicate and update this issue with my findings.

**Comment by preslavrachev** [comment]
@jdubois Just to make things clear, because I just came up to the same issue (using IntelliJ CE 14). If I turn off the annotation processors, the above-mentioned error is gone, and I am able to run the application manually, as well as run tests manually, etc. 

My question is if turning off the annotation processors has negative implications on the building and running of the application? I guess I should keep compiling with Maven instead.

**Comment by henkelb** [comment]
Andrew Redko's solution from [1] worked for me
.
"Go to Idea > Settings > Annotation Processors.
For each processor profile make sure that:
Enable annotation processing is Yes;
There is no annotation processor FQ name of one you have error about (e.i. "JPAMetaModelEntityProcessor") in the list on the right side. If it is listed there, just select and click '-' minus button to remove it." - Andrew Redko


[1] http://stackoverflow.com/questions/14322904/maven-3-how-to-add-annotation-processor-dependency

**Comment by chaodhib** [comment]
Using the maven plugin `maven-compiler-plugin` (like described in the [documentation of MapStruct ](http://mapstruct.org/documentation/1.1/reference/html/index.html#configuration-options)), instead of the plugin `maven-processor-plugin` also fixes the issue, without having to do any other change.

**Comment by jdubois** [comment]
@chaodhib could you help on the doc? Looks like you have a solution, and I don't have a good one (disclaimer: I don't use DTOs! I know I should!)

**Comment by chaodhib** [comment]
@jdubois It's not about the doc. 

Up until https://github.com/mapstruct/mapstruct/pull/786, the guys at MapStruct were using the `maven-processor-plugin` in order to launch their annotation processor.

So in the pom file, projects that used MapStruct had this section:
```
<plugin>
	<groupId>org.bsc.maven</groupId>
	<artifactId>maven-processor-plugin</artifactId>
	<version>2.2.4</version>
	<configuration>
		<defaultOutputDirectory>
			${project.build.directory}/generated-sources
		</defaultOutputDirectory>
		<processors>
			<processor>org.mapstruct.ap.MappingProcessor</processor>
		</processors>
		<options>
			<mapstruct.suppressGeneratorTimestamp>true</mapstruct.suppressGeneratorTimestamp>
			<mapstruct.defaultComponentModel>spring</mapstruct.defaultComponentModel>
		</options>
	</configuration>
	<executions>
		<execution>
			<id>process</id>
			<phase>generate-sources</phase>
			<goals>
				<goal>process</goal>
			</goals>
		</execution>
	</executions>
	<dependencies>
		<dependency>
			<groupId>org.mapstruct</groupId>
			<artifactId>mapstruct-processor</artifactId>
			<version>${mapstruct.version}</version>
		</dependency>
	</dependencies>
</plugin>
```
Since then, `maven-compiler-plugin` is used:
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-compiler-plugin</artifactId>
	<version>3.5.1</version>
	<configuration>
		<source>1.8</source>
		<target>1.8</target>
		<annotationProcessorPaths>
			<path>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct-processor</artifactId>
				<version>${org.mapstruct.version}</version>
			</path>
		</annotationProcessorPaths>
	</configuration>
</plugin>
```

They did this change because of issues cf https://github.com/mapstruct/mapstruct/issues/769 (and also because it adds a stronger Eclipse support). But coincidentally, this change also solve the issue discussed here (or at least it did for me. A second opinion would be great).

**Comment by jdubois** [comment]
Oh I didn't know that, we must update the generator then! Let me have a look

**Comment by jdubois** [comment]
Indeed, this works well!! It's probably also so end of the "IDE" profile from @cbornet as it now works well out of the box.
I'll do some more tests and commit this.

**Comment by jdubois** [comment]
OK it's not so easy, I'm re-opening the ticket to remember this, and work on it later.
Help of course is welcome!
And the documentation on https://jhipster.github.io/configuring-ide-eclipse/ will need to be updated

**Comment by jdubois** [comment]
I'm still working on this: you are correct and this must be updates, but it's so hard to have a working Eclipse configuration!!!! Lots of time lost here.

**Comment by cbornet** [comment]
FYI maven-processor-plugin is still mentioned in https://jhipster.github.io/configuring-ide-eclipse/
