### ISSUE TITLE
yo jhipster loop

### ISSUE THREAD

**Issue by fontanellif** [jhipster/generator-jhipster#1562]
Hi, it seems that there is a loop when i try to execute the "yo jhipster" command:
```
? Overwrite src/main/webapp/index.html? overwrite
    force src/main/webapp/index.html
identical .editorconfig
identical .jshintrc
 conflict .gitignore
? Overwrite .gitignore? (Ynaxdh) 
```

As you can see after check the index.html file, the process restart from the .gitignore.

I get this issue using the master branch

**Comment by jdubois** [comment]
The master branch is in "development" so it really depends when you pulled the code.

Currently it's not in a very clean mode, as we are migrating to Yeoman 0.20.1 and it's a lot of trouble. 

And at the moment I can't reproduce your bug.

That's why I don't consider this as an issue for the moment, we will see that when the upgrade is complete.

If you want to use a stable version, please use a tag. If you want to help debug the current master branch, please do, it's really a lot of work at the moment.

**Comment by fontanellif** [comment]
@jdubois thank you for the explanation, but i don't know Yeoman and it's difficult for me debug this behavior, i will try and i will let you know.

**Comment by jdubois** [comment]
Currently the build is stable, so you might want to do a "git pull" and "npm link" to test again.
