### ISSUE TITLE
Chinese character encoding error problem

### ISSUE THREAD

**Issue by Qinwroks** [jhipster/generator-jhipster#1590]
here is how i get this problem:
1:  `mkdir bookstore`
2: `yo jhipster` --> create bookstore by following the default steps
3: `mvn spring:boot run`
4: choose nav 'Account --> Settings ' . fill the last name input with Chinese character '管理员' , click Save
5: reload the page the last name input was wrong encoded with `'???????'`
6: check database and turns out the last_name value was `'??????'` too. 
7:  add` 'System.out.println(lastName)' ` in `UserService.updateUserInformation` method,  change the last name agine. and very strange it prints '管理员', correct character!

all afternoon i was stucked. and i think the error encoding was happened during persist to database.but i do not know when does this happens.

SO I PUT IT HERE, encase somebody knows.

I USE 
`JHIPSTER 2.15.2`
`MYSQL 5.6`
`DATABASE CHARSET SET TO UTF-8`
(I ALSO TRY `GBK` OR `GB2312-2`, PROBLM STILL THERE)

**Comment by Qinwroks** [comment]
i use `yo jhipster:languages` add Chinese Support, and switch language to chinese. did not solve the problem.

**Comment by jdubois** [comment]
Adding the Chinese language won't change any configuration, it just adds some new translation, so that's "normal" it doesn't help.

The issue might be on your database, but as you probably also use a 2nd level cache, you need to check what's in your cache.

An easy way to test: restart your app server, this will clear the cache.

If the encoding is wrong in your database, it is probably a database misconfiguration, or maybe even an OS issue (I've seen OSes which didn't have the Chinese encodings). Can you try inserting data manually in your database?

**Comment by Qinwroks** [comment]
OK i think i solved!

By change
`jdbc:mysql://192.168.99.100:32769/srlic_dev`
TO
`jdbc:mysql://192.168.99.100:32769/srlic_dev?useUnicode=true&characterEncoding=utf8`

@jdubois this should be a serious bug

**Comment by jdubois** [comment]
Oh yes I've already seen that!!!

**Comment by Qinwroks** [comment]
fixed!
https://github.com/jhipster/generator-jhipster/pull/1621
