### ISSUE TITLE
Why use Tomcat instead of Undertown in Prod profile?

### ISSUE THREAD

**Issue by phouverneyuff** [jhipster/generator-jhipster#1596]
Undertown is better than tomcat.
https://www.techempower.com/benchmarks/#section=data-r10&hw=ec2&test=update&l=3k&c=5&d=6n

Why we using tomcat in Prod profile Prod?
There are some reason for this?

<profile>
            <id>prod</id>
            <dependencies>
                        <dependency>
                                    <groupId>org.springframework.boot</groupId>
                                    <artifactId>spring-boot-starter-tomcat</artifactId>
                        </dependency>
            </dependencies>
...

In fast profile we are already using undertown.

**Comment by gmarziou** [comment]
Undertow dev team is still rather small (mainly one man), it had some compatiblity bugs (I reported and fixed few of them) with Tomcat which is the reference implementation for servlet API.
I have an application in production using it because I have been forced to use WildFly app server.

Last, doing it yourself is easy, just follow the instructions of the spring-boot doc.

**Comment by phouverney** [comment]
Thank you @gmarziou

**Comment by jdubois** [comment]
Same answer has @gmarziou : I'd love to use Undertow has it's faster to start (that's why I put it in the fast profile), but I've already had some issues with it, and it doesn't look production ready yet.
It might replace Tomcat in the future, it's just too early.
