### ISSUE TITLE
More frequent releases

### ISSUE THREAD

**Issue by egvimo** [jhipster/generator-jhipster#15963]
##### **Overview of the feature request**

It would be nice if the releases of the generator could be published more often.

##### **Motivation for or Use Case**

- Users would benefit from the various bug fixes faster
- The Upgrades of the app would be smaller resulting in less migration difficulties
- Faster feature delivery

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by gmarziou** [comment]
I suspect this is due to summer holidays.

**Comment by mraible** [comment]
I agree with @gmarziou. Things really slow down around here in July and August.

**Comment by egvimo** [comment]
If I'm not mistaken, a release requires some manual work to be done. Maybe it is worth it to automate the release process. So the only thing needs to be done is to set a tag and Github workflow takes care of the rest. Would automation help to release more frequently?

Some history for reference: 😄 

| Release      | Date         | Changes | Previous Release |
| ------------ | ------------ | ------- | ---------------- |
| Next         | ?            | ~ 200 | ~ 2 Month        |
| 7.1.0        | Jun 18       | 817     | ~ 1,5 Month      |
| 7.0.1        | Apr 2        | 153     | ~ 0,5 Month      |
| 7.0.0        | Mar 21       | 825     | ~ 2 Month        |
| 7.0.0-beta.1 | Jan 17       | 227     | ~ 1 Month        |
| 7.0.0-beta.0 | Dec 21, 2020 | 1322    | ~ 1 Month        |
| 6.10.5       | Nov 7, 2020  |         |                  |

**Comment by gmarziou** [comment]
@egvimo please precise what you mean by "more often"?

**Comment by egvimo** [comment]
I was thinking about one (feature) release per month and maybe bugfix releases in between. In my opinion 2+ months is a bit too long, especially for the many bugfixes that are often included.

**Comment by yangliuyu** [comment]
The latest release of JHipster (7.1.0) support Sprint Boot 2.4.7 by default, hope Sprint Boot 2.5.4 and subsequent version can be integrated soon(maybe in 1 month after upstream release). Also I found some version downgrade in package.json and pom.xml with jhipster main branch code, is there some reason to do it, like version compatible?

**Comment by mraible** [comment]
The main branch was upgraded to Spring Boot 2.5.4 yesterday. https://github.com/jhipster/generator-jhipster/pull/16017

**Comment by egvimo** [comment]
> @pascalgrimaud is on vacation, jhipster 7.2.0 will be released when he returns.

Another reason to automate the release process, so that anyone of the team can trigger a release (e.g. by simply setting a tag).

**Comment by pascalgrimaud** [comment]
Hello @egvimo 

I understand your needs and I'd like to automate the full release process, but it's not possible. I can explain why. Some steps are automated, helped by https://github.com/jhipster/jhipster-ansible but other are not, because it depends on Maven Central, Docker Hub etc. I need to wait long long time...

When there is a new release, I need to do all these steps:

### JHipster Bom

- release jhipster-bom and publish to maven central -> it is automated
- wait few hours -> hard to automate :man_dancing: 
- do a pull request to generator-jhipster once the new version is available (hard to automate because of waiting)
- wait the CI of the pull request :man_dancing: 
- merge the pull request
- wait the CI in main branch :man_dancing: 

### React JHipster

- release react-jhipster -> automated
- do a pull request to generator-jhipster with the new version (not automated yet)
- wait the CI :man_dancing: 
- merge the pull request
- wait the CI in main branch :man_dancing: 

### JHipster Registry

- release jhipster-registry
- wait few hours too, because of Docker Hub :man_dancing: 
- do a pull request to generator-jhipster with this new version
- wait the CI :man_dancing: 
- merge the pull request
- wait the CI in main branch :man_dancing: 

### JHipster Control Center

- release jhipster-control-center -> automated
- wait few hours too, because of Docker Hub :man_dancing: 
- do a pull request to generator-jhipster with this new version
- wait the CI :man_dancing: 
- merge the pull request
- wait the CI in main branch :man_dancing: 

### Release Note

- see jhipster.github.io project
- totally done manually today, maybe it can be improved

### generator-jhipster

- once all CI passed and all pull request merged, I can do release
- these few commands are already automated

### documentation-archive

- launch the task to archive docs, already automated

### generate all sample projects

- same, already automated

### release JHipster Online

- not automated yet, but it tooks only few minutes, to change version, tag and push

### release DevBox

- same than JHipster Online

**Comment by egvimo** [comment]
@pascalgrimaud That's a lot of work for a release. Now I understand why the releases are not as frequent. Thank you for your effort clarifying this (and of cause for your effort doing the releases 🙂).

Some thoughts:

- If the individual projects would be decoupled, you wouldn't have to wait for the release of them. For example use a separate release and development cycle for JHipster Bom. This way it would be just another dependency, which would be updated like all the others. I can imagine that not all projects have changes for every release.
- The "waiting" part could also be done [via Ansible](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#retrying-a-task-until-a-condition-is-met) (if it is not too long). I can help with that (and other Ansible stuff), I have some experience with Ansible. GitHub CLI has also some handy features which could be used in automation ([exapmle](https://github.blog/2021-04-15-work-with-github-actions-in-your-terminal-with-github-cli/)).
- The release notes could be automated with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) and [Conventional Changelog](https://github.com/conventional-changelog/conventional-changelog). This would also be beneficial for the versioning part, which could be derived from the commit messages to determine the next version number ([Semantic Versioning](https://semver.org/)).
- Some "post release" projects like documentation or samples could be done via Webhook or nightly schedule.

Even if the release could not be entirely automated (but I am optimistic), there is potential for improvement which could you save a lot of time.
What do you think?

**Comment by pascalgrimaud** [comment]
The best would be the individual projects are released more often. But it depends on the Stream Lead.
And as it's an open source project, everyone works for free, so we simply do our best :-)

Not sure the waiting part in Ansible is needed. As it depends too much on Maven Central / Docker Hub / Github Actions etc.
Sometimes, it tooks 1 hour or 2 hours. Sometimes a full day... It's totally random lol

**Comment by jdubois** [comment]
I agree it's a lot of work to do a release, as I used to do this before @pascalgrimaud !!!
But we have a ton of PRs and projects to synchronize, and remember we're not a company, so we can't commit on any dates.

It's just not possible to ask us to do regular releases, we do this when the sub projects are ready, and when we have time. That's the downside of using an Open Source project that is totally free and community-driven.
