### ISSUE TITLE
Successful Login results in three different audit entries 

### ISSUE THREAD

**Issue by geoaxis** [jhipster/generator-jhipster#1618]
I did a PoC to show last 5 audit entries (with HTTP auth). It seems that when I do a fresh login I get three entries for one event (i.e. AUTHENTICATION_SUCCESS).

Expected would be one success per login.

It seems that some times though.

See the following audit logs for admin user 

    Jun 17, 2015 6:18:12 PM	admin	AUTHENTICATION_SUCCESS	Remote Address: 127.0.0.1
    Jun 17, 2015 6:18:11 PM	admin	AUTHENTICATION_SUCCESS	Remote Address: 127.0.0.1
    Jun 17, 2015 6:18:11 PM	admin	AUTHENTICATION_SUCCESS	Remote Address: 127.0.0.1
    Jun 17, 2015 6:05:16 PM	admin	AUTHENTICATION_SUCCESS	Remote Address: 127.0.0.1
    Jun 17, 2015 6:00:15 PM	admin	AUTHENTICATION_SUCCESS	Remote Address:      0:0:0:0:0:0:0:1

**Comment by jdubois** [comment]
This is `normal` - I'm not saying this is good, I'm just saying this is expected.

I guess you have session-based authentication with the remember-me cookie, as that's what people usually have (if you don't, then please give your settings next time!)

So when you come back to your application, your browser does multiple requests to some protected URLs - at least it's calling the backend API.

Some of those calls will be in parallel.

Then, as you have the remember me cookie, each of those calls will authenticate you (as you are authenticated yet).

This is why you have several "authentication success" logs.

Once again, I'm not saying this good, I'm just saying that I expect this to happen, and I don't think there's a good solution for that (otherwise you don't have parallel calls, and performance will be bad)
