### ISSUE TITLE
CSRF cookies root path causes issues with multiple apps on different context paths

### ISSUE THREAD

**Issue by pmarrone** [jhipster/generator-jhipster#1627]
While running multiple JHipster based apps with different context paths on the same tomcat instance, you can only log in into one application.

This seems to be caused by CSRF cookies being shared at the site level ('/'), since two applications won´t share their HTTP sessions, but each will try to overwrite the single CSRF-TOKEN shared across the site, causing the token to be valid only for one of them.

**EDIT**
The issue is still valid, though my solution seems to be wrong. I'm working on it. Sorry.

**Incorrect solution**

Changing this line in CsrfCookieGeneratorFilter from

    cookie.setPath("/");

to

    cookie.setPath(request.getServletContext().getContextPath());

allowed me to work around this issue for my particular case, but may be a quite rigid solution for others. Maybe the path should be configurable?

**Comment by jdubois** [comment]
That's a good point!

Yes the issue is that for people doing exactly what I'm doing at the moment:

- I have a Hapijs front-end reverse proxy
- I have several "back-end" JHipster applications, each running in their own JVM -> they are Spring Boot executable JAR files, and hence they run on the "root" context

So I have the same issue as you, but I can't use the same solution!

I guess we could configure it in the YAML config file, but that's one more configuration to know. I don't think there's a standard Spring Boot configuration property for that, but that would be the best solution.

**Comment by gmarziou** [comment]
What does bring Hapijs over nginx or apache httpd?

**Comment by jdubois** [comment]
@gmarziou it's node.js, so it's hipster :-)

It's mostly because I'd like to have the same technology (node) as our front-end code, so we don't have too many different stacks. I would like to do this in Java, but I'm not satisfied with the solutions I've seen.

- This is mostly an experiment, I have no idea what this will produce. I might create a specific JHipster sub-project for this
- It also kind of competes with Zuul or Ribbon, so this wouldn't fit with the Netflix OSS stack, but it's so much simpler to use (and I'd say much more performant)

This idea mostly come from my current gig, where we have the same kind of front-end coded in Python, and I find this is a good approach.

**Comment by gmarziou** [comment]
Interesting

**Comment by pmarrone** [comment]
Well, if all applications are each on separate domains on their own ROOT context, which I agree would be the standard use case (IMHO, going for service.mydomain.sth saves some headaches you get when you go for mydomain.sth/service instead), wouldn't each application server context just resolve to "/"?

I was thinking that using the servlet context as the default path at least would solve this issue when deploying multiple wars on the same tomcat instance, while at the same time keeping ROOT applications working just the same as they are now. I tested this with multiple applications on their own contexts and one application on ROOT and it seems to work as expected.

Are there cases where, in a JHipster app that works OK today, going for the context path would break it? 

Does the servlet context path resolves into something else when running from an executable Spring Boot JAR?

About variable configuration... I was only imagining corner cases in which the server configuration might lead to expectable weird behaviour (e.g.: proxying only some paths to a tomcat ROOT context. I have seen an apache server which was configured to serve a wordpress site on domain.sth/ and was proxied to a tomcat instance on domain.sth/somepath/)

**Comment by jdubois** [comment]
@pmarrone I'm not sure there is an easy solution to this, unless the token is issued by the front-end (for example, by Hapijs).
I'm closing this as we can't fix this, unless you have a new idea?

**Comment by pmarrone** [comment]
This is what worked for me.
I changed this line in CsrfCookieGeneratorFilter from this

    cookie.setPath("/");

to this
            
     String applicationPath = request.getServletContext().getContextPath();
     if (applicationPath.isEmpty()) {
         applicationPath = "/";
     }
     cookie.setPath(applicationPath);

This way, the generated cookies are valid only for the given context path, and it also worked for applications on the ROOT path sharing the domain name with other applications with a specific context path.
