### ISSUE TITLE
[WARNING] An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by tsendee0409** [jhipster/generator-jhipster#16319]
I generated a simple microservice application by Jhipster 7.2.0, it has warnings when the app running.

![image](https://user-images.githubusercontent.com/8222265/133714169-cf91ff89-a63b-4ae2-8055-3bfddffa35bb.png)

`WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.hazelcast.internal.networking.nio.SelectorOptimizer (file:/home/jhipster/.m2/repository/com/hazelcast/hazelcast/4.1.5/hazelcast-4.1.5.jar) to field sun.nio.ch.SelectorImpl.selectedKeys
WARNING: Please consider reporting this to the maintainers of com.hazelcast.internal.networking.nio.SelectorOptimizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

![image](https://user-images.githubusercontent.com/8222265/133714440-9f825320-0305-4a24-82da-641b9a1ffbb2.png)

**Comment by tsendee0409** [comment]
Please check this out.
https://docs.hazelcast.com/imdg/4.1/installation/running-in-modular-java.html

**Comment by pmverma** [comment]
The best is to document or add a tip page rather than adding JVM options in JHipster as there are many to provide JVM options and many ways to run the app in both dev/prod environments.
Anyway, I believe users also will definitely be providing those options rather than using default or without any options.
So the user is the best responsible person for this.

**Comment by pmverma** [comment]
Keep it open
