### ISSUE TITLE
Generate without security

### ISSUE THREAD

**Issue by myspivey** [jhipster/generator-jhipster#1634]
Interested in a method for generating project without any built in security enabled. Looking at integrating Stormpath (https://github.com/stormpath/stormpath-spring-boot-tutorial) as the security and ability to generate without security removes a lot of the overhead from the end scaffolded structure. Is there a way to do this currently?

**Comment by jdubois** [comment]
No, at the moment you can't generate without security: this is one of our "basic requirements", as we thought everybody would want it.
Then, I had the same idea for i18n, and since the last version it's not a requirement anymore, so things may change!
I'm not sure it's really difficult to remove, just don't secure your URLs -> you will still have the Spring Security JARs and configuration, but I don't think they do much overhead (at least they don't show as one of our main issues when I do profiling)
