### ISSUE TITLE
Overwrite source field question should have answer "never"

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#16520]
##### **Overview of the feature request**

The request whether to overwrite previously existing generated source files should retrieve an additional option "never" next to the exisiting "no" option.
When "never" is chosen, write that info somewhere so it get's commited to the SCM and when the next regenerate run is started, read that file and automatically skip the files specified in that new configuration file (or store it in the Entity.json file where the source file is generated from).

##### **Motivation for or Use Case**
When I regenerate entities for while I made manual changes to source files for other entities which I generated before, I get asked all the time whether I want to overwrite certain files. This takes a lot of time to answer every time.

I want to speed up development and also avoid the risk of accidentally overwriting custom code changes I made to generated classes

##### **Related issues or PR**

I don't know
- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Cc @mshima 
Is it possible to have this support directly in yeoman?

**Comment by mshima** [comment]
@pascalgrimaud this feature requires changes in 3 projects:
- mem-fs-editor is done https://github.com/SBoudrias/mem-fs-editor/pull/189
- yeoman-environment is pending https://github.com/mshima/environment/commit/23b9831e1d266e4c60621912ffad0a646cba305e
- adjust generator-jhipster custom commit

I need to review yeoman-environment changes. 
See how difficult is to add tests and if it worths.
Since I already took a look now, I will finish in the next few days.

**Comment by pascalgrimaud** [comment]
Oh nice to know it's doable. It will help a lot all our users!!!

**Comment by CodingSpiderFox** [comment]
ping

**Comment by mshima** [comment]
Required yeoman-environment is released.
PR is based on https://github.com/jhipster/generator-jhipster/pull/16930.
Waiting to be merged.
