### ISSUE TITLE
Expired Token - Login redirect

### ISSUE THREAD

**Issue by vkoop** [jhipster/generator-jhipster#1662]
User should be redirected to login after expiration of their session token, if trying to open a protected area. At the moment the data doesn't load but the user doesn't get any feedback that the session expired.

**Comment by jdubois** [comment]
It's already the case, I guess you are on an older version (next time, please read the guidelines, and give your version number)

**Comment by vkoop** [comment]
It didn't work with the latest checkout from the "master" branch from yesterday. Sorry, i will have an other look at the guidelines.

**Comment by jdubois** [comment]
Oh, if you are with version 2.17.0 it should be OK -> then that's a bug, but it's surprising as this was a new feature not so long ago.
Can you check this out? I'm reopening it as I guess you have a newer version.

**Comment by jdubois** [comment]
Fixed by #1663

**Comment by jdubois** [comment]
As #1663 was reverted, opening this again

**Comment by myspivey** [comment]
Is there a way instead of forcing a fresh login everytime we can refresh the token? For example Facebook uses OAuth2 but does not force a log out, they simply refresh the token. This seems like a valid use case for many apps that have extended usage or entry especially concerning POST type transactions.
