### ISSUE TITLE
Consider making naming consistent for CustomLocalDateSerializer and ISO8601LocalDateDeserializer

### ISSUE THREAD

**Issue by michaelisvy** [jhipster/generator-jhipster#1671]
I understand those 2 classes are meant to be used together such as in the below code sample:

```java
@Type(type = "org.jadira.usertype.dateandtime.joda.PersistentLocalDate")
    @JsonSerialize(using = CustomLocalDateSerializer.class)
    @JsonDeserialize(using = ISO8601LocalDateDeserializer.class)
    @Column(name = "birth_date")
    private LocalDate birthDate;
```

Wouldn't it make more sense to have consistent naming for both classes?
We could call them CustomLocalDateSerializer and CustomLocalDateDeserializer
(and mention as a comment that they are meant to work basedon ISO8601 format).

**Comment by jdubois** [comment]
That's because we use a ISO08601 format on one side, but not on the other!
So for me the class names are correct, but I don't remember why I don't have the same format on both side.
Anyway, I did a better documentation for this: https://github.com/jhipster/generator-jhipster/commit/9da4966e8a661865fe064aba714b0c5dc9b0e1d0
