### ISSUE TITLE
When your mapper have more than one mapping should add @Mappings({ @Mapping(),... })

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#1695]
Ex:
@Mappings({
        @Mapping(source = "map.id", target = "mapId"),
        @Mapping(source = "appGroup.id", target = "appGroupId")
    })

**Comment by jdubois** [comment]
I don't see why would do that, it adds more lines -> do you have a specific bug here?
I'm sorry, but you don't provide enough information to understand what you want to do, can you follow our guidelines, please?

**Comment by outis10** [comment]
when you have more than one @Mapping like in the example  the compiler throws an output error. 
 but when you have only one @Mapping there is ok,  

This is strange because in the mapstruc documentation there is a TIP  saying 

"Tip! When using Java 8 or later, you can omit the @Mappings wrapper annotation and directly specify several @Mapping annotations on one method".
I fix the error lke @marcelinobadin  did too.

**Comment by jdubois** [comment]
Oh, that explains the issue!
This normally works, indeed. This might be linked to a recent issue with Springfox, can you test again when our next version is released ? This should out be very soon.

**Comment by marcelinobadin** [comment]
Sorry that I couldn't be clear at firts. Thank you @outis10 for your better explanations. I am using Java 8 but I always have to go mapper by mapper and do the change to use @Mappings.

I will test also and give you feedback @jdubois .

Thank you guys.

**Comment by jdubois** [comment]
This is really strange -> please, don't hesitate to send feedback with the new version (should 2.18.0, I'm currently doing my last tests on this release) and I'll re-open the ticket

**Comment by marcelinobadin** [comment]
It worked on 2.18.0. Thanks!

**Comment by yogi-oc** [comment]
@Mappings worked for me as well.
