### ISSUE TITLE
Jhipster conflicts with all entities after adding a new property to an entity

### ISSUE THREAD

**Issue by sulaiman-allemyar** [jhipster/generator-jhipster#17006]
After adding a new property to an entity, the Jhipster conflicts with all entities and you must resolve all conflicts which is too much time consuming. for example if you have two entities Product and Stock, then after adding a new property to Product the Jhipster conflicts with Stock also.

I have also used older versions of Jhipster 6.x.x but this issue was not on those versions.
Is there any solution to this issue?
I am Jhipster monolithic architecture.

**Comment by Tcharl** [comment]
Hi,

Sorry but I'm not able to reproduce: are you customizing your entity in a way?

**Comment by pascalgrimaud** [comment]
@Tcharl : it is similar to these tickets
- https://github.com/jhipster/generator-jhipster/issues/13365
- https://github.com/jhipster/generator-jhipster/issues/14678
- https://github.com/jhipster/generator-jhipster/issues/13833

First, using jdl + json only flag, then using jhipster entity with single entity should do the job

**Comment by sulaimanallemyar** [comment]
I developed a project with Jhipster 7.0.1 and have still this issue and could not find the solution for this problem.
I have more than 55 entities, after adding a new entity/field Jhipster conflicts with all 55 entities.
This issue is in Jhipster 7.x.x series, not 6.x.x series.
The Jhipster even conflicts with those entities which has no changes and is same as Jhipster generated them.
