### ISSUE TITLE
No documentation for npmw

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#17016]
##### **Overview of the issue**

In JHipster 7.3.1, a new script `npmw` has been added but I couldn't find any doc about it, I searched generated README.md and jhipster.tech.
Even in the file itself there's no comments.

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
We are really bad for updating our documentation. We focus on adding new features :-(
Same thing for yo-resolve, incremental changelog (not enough), modernizer plugin, microfrontend, entity by package etc etc.

**Comment by mshima** [comment]
> Same thing for yo-resolve, incremental changelog (not enough), modernizer plugin, microfrontend, entity by package etc etc.

yo-resolve documentation would be better to be on yeoman site, but the documentation there was outdated before I've become a contributor. And unfortunately I am the only one active there (because jhipster). Maybe jhipster should consider to do some arrangement with yeoman.
I think we should always generate `.yo-resolve` with comment on how it works.
And explain the generated files and file structure on README.

What kind of documentation are you missing on incremental changelog?
Maybe it should be the default for jhipster 8.

I will add some documentation on microfrontend.

entityPackageName is an annotation, so it's just an entity field (jhipster internal structure). Lots of customizations can be done by using annotations.
The documentation should be linked to a jsdoc.
I wanted to publish jsdoc for jhipster 7, but the file structure rework and jsdoc entries was not done.
Planned for jhipster 8.
