### ISSUE TITLE
@Version for jpa entities

### ISSUE THREAD

**Issue by krishnakumarp** [jhipster/generator-jhipster#1764]
Currently the jpa entities generated using JHipster does not contain @version annotation. This is very commonly used for optimistic locking. 

Please add @Version field to jpa entities optionally.

**Comment by jdubois** [comment]
Yes it's a very useful annotation, I used to do a lot of Spring Webflow + JSF and this was really great (yes, I'm a big fan of JSF, that must surprise many hipsters here!)

By default we only generate the "basic" JPA mapping, so we won't do "version" by default, of course.

It could of course be an option, but we only do options if we add a real added-value. If that's asking a new question, just so you don't type one line, we believe it's not worth it -> here I'm not sure, I would need to do a small test or proof of concept before, to see if we can add some value here

**Comment by phouverneyuff** [comment]
+1

**Comment by krishnakumarp** [comment]
I think @Version is required for all entities that have a edit option on UI, since without this, users could overwrite changes made by other users (without optimistic locking).

**Comment by jdubois** [comment]
This happens mostly if you have some long-running Hibernate sessions -> this is exactly why I was using it, as I was using Spring Webflow with them.

Otherwise, it kinds of depends on your business case, and I wouldn't use them by default.

Besides, for each technology we use its default configuration, and:

- only override it if there is a serious issue for us (for example, because of our AngularJS UI), and here it is not the case.
- or had it as an option if we provide some significant added value, which is also not the case here (it's really easy to add this manually)
