### ISSUE TITLE
Mismatch settings with the test application.yml

### ISSUE THREAD

**Issue by lchenaction** [jhipster/generator-jhipster#1768]
This issue is related to #759

When you choose MySQL, the test application.yml is still using H2. that's why they are running differently with the CLOB.

Could you make the test application.yml to follow the dev one?

**Comment by gmarziou** [comment]
Could you please propose a pull request?

**Comment by lchenaction** [comment]
What is a full request?

**Comment by gmarziou** [comment]
Yes but it seems you are a test environment ready for validating a fix, I thought you would like to contribute.

**Comment by deepu105** [comment]
@gmarziou but in the test setup isnt it better to have H2 as test scripsts will insert lot of data as part of gatling tests, which would be not ideal in the actual test mysql DB

**Comment by jdubois** [comment]
@lchenaction do you mean with our new support for the BLOB type?

**Comment by gmarziou** [comment]
@deepu105 yes h2 is simpler in the sense that nothing is persisted. On another hand, if an app uses some database specificities, it would be better to test with same db engine but it means using another database instance as the tests must be isolated from modifications in dev.

**Comment by lchenaction** [comment]
This all makes sense. It's a trade off. The problem is H2 and MySQL does treat the CLOB differently. Or the hibernate complains about. What I did is just copy the dev settings to test. I think we can leave the choice to developers.

**Comment by jdubois** [comment]
The aim here is to have H2 in test, with Hibernate doing the persistence work -> in theory, this is the easiest option for developers.
Then, it's our job (JHipster) to make sure it works smoothly for developers -> as far as I'm concerned it has always been working fine, until we added the BLOB type, which is very new, and that's why it still has the BETA tag.
-> I don't think we have anything to do here, that's why I'm closing this
