### ISSUE TITLE
notification system refactoring

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#1785]
@deepu105 @gzsombor 

I'm not happy with having a new top-level "api" package. Is it only used in the "web.rest.errors" package? Then that class should be moved there.

**Comment by deepu105** [comment]
@jdubois I guess it can be moved but i think @gzsombor might have put it there with the future jhipster jar on mind,  am i right @gzsombor?

**Comment by deepu105** [comment]
note to self: and also need to write filed names to error section in global json when generating entities
cc @gzsombor

**Comment by jdubois** [comment]
I also don't like some parts of the UI:

- It is not the same as what we have in the "admin" pages -> we need to be consistent across all pages
- We should normally use only the normal Bootstrap classes, so that people can use their own theme. Here, the "alert" class is even changed -> this should be done like the in "password.html" page, for example

**Comment by deepu105** [comment]
@jdubois the consistency part needs to be done I agree(we can remove the html alert at other page level and use the `AlertService`, this will also help to remove some markup and if else logic from those pages). The change to Alert class is done only for the positioning to make it appear like a toast, that too only when within `.alerts` and not altering appearance and hence it will work with any bootstrap theme. and for the alert to be less intrusive toast style would be more appropriate i guess. If we choose to do the password page style then we would need to place the directive at individual page instead of the index.html. what do you think?
