### ISSUE TITLE
SOAP in jHipster?

### ISSUE THREAD

**Issue by wzomer** [jhipster/generator-jhipster#1787]
What do you recommend as a solution to consume SOAP webservices in a jHipster application? Jax-ws or Spring WS?

Thanks.

**Comment by jdubois** [comment]
This should rather go to Stackoverflow, it is not a bug or feature request.

I would recommend (since you ask) CXF:

- Spring WS doesn't seem very active anymore
- I've had a very good experience with CXF recently, with a JHipster + Cassandra application (I just changed the REST endpoints to use CXF instead): easy to use, no bugs, good performance, and a happy customer!

**Comment by wzomer** [comment]
Right! Thanks for your reply.

**Comment by eater2** [comment]
Hi Julien, could You please share the spring boot / pom.xml configuration for Apache CXF in Jhipster ?

**Comment by gmarziou** [comment]
I have started from this:

https://github.com/spring-projects/spring-boot/pull/3104

**Comment by jdubois** [comment]
@eater2 no, it's a code I did for a client, I can't share it.

**Comment by eater2** [comment]
Do You know if CXF SOAP webservice can coexist with JHipster MVC Rest WS-es ?
Looks like if i add cxf to pom.xml , it overloads the spring mvc rest annotations, or am i doing it wrong ?

**Comment by gmarziou** [comment]
There's no problem doing so, I did it.
I mapped REST controllers on /api (as usual in JHipster) and CXF on /services

**Comment by eater2** [comment]
could You please share the project configuration You did ?
pom.xml and WebServiceConfiguration.java ?

**Comment by gmarziou** [comment]
I can't share this but I already shared the link with the project that got me started.

**Comment by jdubois** [comment]
@eater2 please follow the project's guidelines and ask this type of question to Stackoverflow
