### ISSUE TITLE
better app layer separation

### ISSUE THREAD

**Issue by mir333** [jhipster/generator-jhipster#1823]
Hi 
Currently the rest layer has injects of services (business logic layer) and repositories (persistence layer). It be good to have a option to enforce a clean layer separation during project generation and/or entity generation. 
If enabled the rest layer would have only inject of services and the repositories will be hidden under the service layer.
This change will contribute to cleaner code and decrease the cyclomatic complexity.

**Comment by jdubois** [comment]
Hi,
This might be a matter of personal preference, but I do not want to have Spring services in my application without a good reason (this is explained [in the service sub-generator documentation](http://jhipster.github.io/creating_a_service.html)), so this design is in fact on purpose.
For me, the real persistence layer is in fact the JPA implementation (being some sort of giant DAO), and I don't think injecting a repository in a controller is an issue.
Anyway, the goal of JHipster is to help you to create the application the way you prefer (and not the way I prefer!), and this is why the service sub-generator is here for you:

- by default we have a "simple" CRUD application
- if you need it (or, in your case, if you believe it is better!), you can call the service sub-generator -> it is a bit more work (not a lot), and it will fit your purpose

At the moment this is the first time I see this asked, and this is why I'm closing this, but if more people have the same requirement, please step ahead! This could be a new option in the entity sub-generator (it wouldn't be hard to do, and it wouldn't have much consequences, so it's really not a big issue)

**Comment by gzsombor** [comment]
I always generate a separate service class for each of the entities. This way transaction handling is more clear(no more problems with lazy loading) - much harder to accidentally create 2 transactions for one REST call. And, obviously, if you put your business logic into services,instead of REST controllers, then you can more easily re-use it in other parts of your system (otherwise you have to inject a controller into another controller - which I think would be strange)
 I've never tried to push these kind of changes into JHipster, because I saw the strong statement "no separate service for entities" on the home page, so I thought that it will be hard to convince you about the opposite :wink: 
 Otherwise, you just put the logic, and transaction handling into controller,and occassionally just refactor it to a common service?

**Comment by jdubois** [comment]
Yes, let me elaborate a little bit more:

- The basic idea is that we do a CRUD app, as simple as possible
- Indeed, you need to know how Hibernate is working, but that's a pre-requisite for using JHipster (I know most people can't understand how it works...)

The way I work, indeed, is generating the CRUD entity, and then add a service and refactor when I need it.

**Comment by deepu105** [comment]
@jdubois even i would kind of agree with @gzsombor on this. currently as my application grow im having a service for each of my controller and for large business centric applications that would be a  necessity. The current service sub gen is kind of useless for me as i can do a class creation faster in Intellij/eclipse, I wouldnt need a code generator for that, so the service generator would actually add value if it was an option in entity generator where we can wire it up with repository and resource properly

**Comment by deepu105** [comment]
@jdubois i wanted to propose this earlier but i was afraid that you would reject it straight away due to the same statement on the documentation site :wink:

**Comment by jdubois** [comment]
Anyway, I don't want this as the default:

- by default, for a CRUD entity, this would just be an extra useless layer
- normally, you use a service when you want to coordinate some logic between several repositories, so here it wouldn't be a good use case anyway

Two options for me here:

- add a new "service" option in the entity sub-generator -> I'm not a big fan but that's easy to do and won't have much consequences
- improve the current service sub-generator -> this would be more useful, but it's also more difficult to make

**Comment by mir333** [comment]
I would go with extending the entity sub generator. It makes the code generation easier. It's just it's just one enter press more for the user. 
The second approach would require 2 generator calls and the second call would need to overwrite the first generator's result.

**Comment by jdubois** [comment]
OK, let's make this an option of the entity sub-generator, it's indeed much easier.

I'm marking this as "will do later" as this isn't an urgent need -> if more people are interested by this, don't hesitate to participate, or even propose a PR!

**Comment by jdubois** [comment]
I don't know if anybody is going to work on this... At least I would recommend not doing it before we remove Java 7 support.

Anybody has time to work on this? Otherwise I will close this next month.

**Comment by deepu105** [comment]
ill work on this after our Java 7 decom

On Sat, Sep 19, 2015 at 9:23 PM, Julien Dubois <notifications@github.com>
wrote:

> I don't know if anybody is going to work on this... At least I would
> recommend not doing it before we remove Java 7 support.
>
> Anybody has time to work on this? Otherwise I will close this next month.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/1823#issuecomment-141667856>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by gzsombor** [comment]
It was a bit more complicated than I expected, but finally, I could finish it. It's not 100% complete, yet, but it could be a first step, for this feature. I've added a separate template - the _EntityResourceWithService.java - because the _EntityResource.java template is already nightmarishly complex, and it seemed much simpler and clearer. Hope, it's understandable.
I haven't implemented the filtering for 'relationshipName'-is-null, which was done in the resource class - I think that should happen inside the database, not in the java app. (Btw we should start using JpaSpecificationExecutors and the hibernate-jpamodelgen annotation processor, to have strongly typed, dynamic queries, which is far better than to write JPA queries - but that will be a different story :wink: )
 The other problem is that with cassandra, there is no paging implemented in the repository level, so some hacks would be needed.

**Comment by jdubois** [comment]
This is merged!

**Comment by vladimirvs** [comment]
So what's then the meaning of Repository and Service in your view? I am looking at the default UserResource and I can see sometimes userRepository is being called and sometimes userService ??? So if I add a new operation, where do I add it? In repository or service?

**Comment by gmarziou** [comment]
@vladimirvs this is our issue tracker, it's not the right place to ask questions. Please go to stackoverflow.com or gitter

**Comment by vladimirvs** [comment]
Thanks. Sorry
