### ISSUE TITLE
Error in the location response when creating an asset leading to performance test failures

### ISSUE THREAD

**Issue by PrashanthRaghu** [jhipster/generator-jhipster#1831]
When we try to create an entity from the web client, I observed that the Location header in the response is returned as null rather than the ID assigned to the entity object. 

It's because the create method for each entity uses the ID from the DTO obtained from the client where the ID is obviously null. This causes all the performance tests in gatling to fail when they are getting the object created.

On assigning the ID from the result DTO after saving the issue gets rectified as shown in image below.

![response-jhipster](https://cloud.githubusercontent.com/assets/348456/9134986/dbb25572-3d26-11e5-8836-f618d575653e.png)

**Comment by jdubois** [comment]
Is it only when using the DTO, with MapStruct?

**Comment by jdubois** [comment]
I've tested with MapStruct and:

- I can't reproduce the issue
- the code is indeed correct, it's fetching the id from the entity

I think your real issue is a validation issue: have a look at the logs, you will see why your entity was rejected.
I'm going to improve the documentation on that part, as this isn't trivial.
