### ISSUE TITLE
CSRF protection

### ISSUE THREAD

**Issue by wutgit** [jhipster/generator-jhipster#1832]
I encounter slight issues with CSRF protection. I've read that big 965 issue comments and still do not have the full picture what is correct way to fix it.

Workflow:

1. Login into application
2. Stop server, start server again.
3. Now, when issuing any POST request, browser sends current CSRF token (which was valid before server stop). 
4. Server responds with 403, because there is no CSRF token on server yet. Issuing any get request, e.g. navigation, get the new token and applicatoin works correctly from there.

Exact message is: "Invalid CSRF Token '94a9dd4e-4bcd-4a4e-94b4-e8de43666a2e' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'."

Main question is, what is correct way to handle such issues? I did try e.g. to logout user in case of 403, but in this case, logout won't work, and when showing login page, login will not work too, as there is no token on server without issuing GET request.

There seems to be some 'to get a new csrf token call the api' in auth.session.service.js, but this is done only on successful logout, which it is not, because logout is POST, and it will fail due to missing CSRF on server.

Only current way is to make manual GET request, be it browser refresh, or just some navigation.

**Comment by jdubois** [comment]
Yes, it seems logical that we have a worflow issue here.
I'm not sure how we should handle this (I'm only using the "default" authentication), maybe refresh the browser?

**Comment by Herisson-88** [comment]
It seems I have the same issue when server session time out and I call an Ajax POST request.
Same message.
Refresh browser fix but that's not very nice for users

**Comment by Herisson-88** [comment]
Little workaround with an interceptor which catch the 403, call the Principal.identity(true), and recall...
BUT to avoid loop I made a restriction off just ONE reauthentification call : so it doesn't resolve the case of multiple simultaneous call getting 403, but for my own usage it is OK.
Inspired from the last example of http://www.webdeveasy.com/interceptors-in-angularjs-and-useful-examples/

**Comment by deepu105** [comment]
@Herisson-88 can you do a PR with your fix?

**Comment by Herisson-88** [comment]
@deepu105 I will do this asap : I have to test my -very- little fix on last version of jhipster. The version I patched had no http interceptor, now there is one so there is very few code... Has I noticed, it can solve a simple $http call wich get a 403 from server (because session time out or server reboot) the patch catch the 403 call Principal.identity(true) and recall : it seems to the end user that session is "infinite".
Nice for a page still open on navigator during a long time, when a user click on a button calling $http : it avoid the effect "403 and nothing happend" and no more to refresh page. Not solve issue of multiple simultaneous call getting 403.

I have to test but it should be something like that (that's a very quick merge...)

https://github.com/jhipster/generator-jhipster/blob/master/app/templates/src/main/webapp/scripts/components/interceptor/_auth.interceptor.js

```javascript
<% if (authenticationType == 'session') { %>
    .factory('authExpiredInterceptor', function ($rootScope, $q, $injector, localStorageService) {
	
		$rootScope.callReloadKO403 = false;
	
        return {
            responseError: function(response) {

                if (response.status == 403 && !$rootScope.callReloadKO403) {
                    var Principal = $injector.get('Principal');
                    if(Principal.isIdentityResolved()) {
                        $rootScope.callReloadKO403 = true;
                        
                        var deferred = $q.defer();

                        Principal.identity(true).then(function() {
                            if(Principal.isAuthenticated) {
                                 deferred.resolve();
                            } else {
                                 deferred.reject();
                            }
                        }, deferred.reject);

                        var $http = $injector.get('$http');

                        return deferred.promise.then(function () {
                            $rootScope.callReloadKO403 = false;
                            return $http(response.config)
                        });
                    }
                }
			
                // If we have an unauthorized request we redirect to the login page
                // Don't do this check on the account API to avoid infinite loop
                if (response.status == 401 && response.data.path !== undefined && response.data.path.indexOf("/api/account") == -1){
                    var Auth = $injector.get('Auth');
                    var $state = $injector.get('$state');
                    var to = $rootScope.toState;
                    var params = $rootScope.toStateParams;
                    Auth.logout();
                    $rootScope.previousStateName = to;
                    $rootScope.previousStateNameParams = params;
                    $state.go('login');
                }
                return $q.reject(response);
            }
        };
    })<% } %>;
```

**Comment by deepu105** [comment]
@Herisson-88 are you doing this?

**Comment by Herisson-88** [comment]
sorry, I'm quite busy on this moment, No time for me and mine and further
for extra job coding... Sorry. (But in fact I'have allready post the code
you can use as you like - and in fact it's a very simple and stupid
unpretentious idea - I'm not an expert - it just solved my problem)

2015-11-25 12:08 GMT+01:00 Deepu k Sasidharan <notifications@github.com>:

**Comment by hyuan** [comment]
The above solution will work fine with a 403 caused by CsrfException. But other types of AccessDeniedException will cause dead loops.

I found another solution: let the server side remove the CSRF cookie in addition to sending 403 status code when CsrfException happened. The browser side will check if this cookie is deleted when receiving a 403. If so, then try to obtain the new CSRF token, and then retry the operation automatically.

Here is the PR: https://github.com/jhipster/generator-jhipster/pull/2480

**Comment by Herisson-88** [comment]
Far better ! I will test and use it ! Thanks...

2015-12-14 5:52 GMT+01:00 Anthony Yuan <notifications@github.com>:

**Comment by jdubois** [comment]
The PR #2480 from @hyuan seems to solve this issue nicely!!!

I'll merge this soon as this looks like the right solution, at least it's better than what we currently have (nothing!).

This needs to be tested with OAuth2 and token authent (which shouldn't be impacted, but there is always a risk)

**Comment by hyuan** [comment]
@jdubois Just a reminder, the above PR won't solve this issue for a direct page post, such as what Social-Sign-In is doing. Because it's out of Angular's control. I haven't found a better solution. But I think it can be solved in this way:

1. use JavaScript to do the post for Social Sign In with Accept Content Type being set to application/json only
2. customize the ProviderSignInController.signIn() a bit to return a JSON response when the Accept Content Type is application/json only. (Right now it always does a 302 redirect when success. This makes it hard to handle the flow by JavaScript)
3. JavaScript obtains the generated OAuth URL from the response and forward the page to social network side

If you are OK with this solution, I will submit another PR to solve this,

**Comment by jdubois** [comment]
@hyuan you seem to know this better than me, so I'm trusting you!!!

-> I'm closing this as for my tests it works fine, if you have a PR that adds more features it's of course welcome (just be careful with the formatting!)
