### ISSUE TITLE
NullPointerException when execute 'mvn liquibase:diff'

### ISSUE THREAD

**Issue by cgagne** [jhipster/generator-jhipster#1838]
We have a null pointer exception when I run the mvn command line liquibase:diff on a @manyToMany relationship defined below please see: 
http://stackoverflow.com/questions/31808537/nullpointerexception-when-execute-mvn-liquibasediff

The proposed work arround is to downgrade liquibase version to 3.3.1 (from 3.3.2).

From my undestanding it was supposed to be fix in 3.3.2 see:
https://github.com/jhipster/generator-jhipster/issues/754

Related liquibase issue:
https://github.com/liquibase/liquibase-hibernate/issues/76

It seems to be more an issue with liquibase but do you have a better workaround as proposed on stackoverflow for now.

Thanks (hips is great!)

PS: For my part I am working on 
jhipster: v 1.4.7
MAC OSX: Yosemite 10.10.4
Apache Maven 3.3.3
Java version: 1.8.0_45, vendor: Oracle Corporation

POM.XML working solution
    liquibase-hibernate4.version: 3.5
    liquibase-slf4j.version: 1.2.1
    liquibase.version: 3.3.1

**Comment by jdubois** [comment]
Yes I remember this NPE issue but that is supposed to be fixed.
Can you also open an issue on Liquibase and link it here?

**Comment by cgagne** [comment]
Bonjour, as requested I will open an issue at Liquibase. Thanks

**Comment by jdubois** [comment]
I'm closing this as:

- This is a Liquibase issue
- This is on a very old version of JHipster, and in the [stackoverflow related question](http://stackoverflow.com/questions/31808537/nullpointerexception-when-execute-mvn-liquibasediff) they say you need to downgrade from Liquibase 3.3.2 to 3.3.1. But we are using 3.4.1!!! So this is definitely a bug with an older version, which has been corrected since.
