### ISSUE TITLE
Add column filters on list form columns

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#18954]
##### **Overview of the feature request**

Could be nice to enhance the list form by adding column filters.
The user could for example click on a column label which will transform in an input text, letting the user to filter rows.
Could work for pagination when jpafilters are set, but also on frontend side for non-paginated options.

##### **Motivation for or Use Case**

I'm pretty convinced that UI improvement would boost jhipster adoption.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by Rapster** [comment]
> The user could for example click on a column label which will transform in an input text, letting the user to filter rows.

Or maybe something as "simple" as Filter Row showcase of PrimeNG: https://www.primefaces.org/primeng/table/filter

**Comment by gmarziou** [comment]
> I'm pretty convinced that UI improvement would boost jhipster adoption.

UI generated by JHipster is mostly no longer relevant due to lack of good tables.

PrimeNG or ag-grid are so much more powerful that I suspect that non trivial projects start by throwing away JHipster tables and replace them by PrimeNG or ag-grid. This should be a question for next survey.

The JHipster team's position so far has always been to avoid such 3rd party UI components and to prefer developing in-house components, this is a mistake in my opinion.

**Comment by paris0120** [comment]
> 

How to install PrimeNG. I always get conflicts of dependencies.

**Comment by gmarziou** [comment]
@paris0120 I simply followed their docs. https://www.primefaces.org/primeng/setup

Although, it's a bit old you can have a look at my example: 
https://github.com/gmarziou/jhipster-ui-libs/commit/cbfbd1854f77b3389582e610c260e73c474b13bd

**Comment by Tcharl** [comment]
> > I'm pretty convinced that UI improvement would boost jhipster adoption.
> 
> UI generated by JHipster is mostly no longer relevant due to lack of good tables.
> 
> PrimeNG or ag-grid are so much more powerful that I suspect that non trivial projects start by throwing away JHipster tables and replace them by PrimeNG or ag-grid. This should be a question for next survey.
> 
> The JHipster team's position so far has always been to avoid such 3rd party UI components and to prefer developing in-house components, this is a mistake in my opinion.

We're using bootstrap, aren't we? :-p

**Comment by gmarziou** [comment]
> We're using bootstrap, aren't we? 

I can understand you want to avoid PrimeNG because it's too far away from Bootstrap but then is there anything preventing JHipster from using ag-grid with Bootstrap?

At work, we started a project with JHipster 2 years ago and replaced Bootstrap by PrimeNG from day 1 and never regretted it. It's not a big work when you don't rely on user management pages.

**Comment by Tcharl** [comment]
Not saying anything like this (my personal opinion would have been to mat-ui ;-)), Primeng looks good :-).
I guess that the choice was made because of the need of identical UI for Angular, React and Vue.
If prime does support it, and it looks it does, we can start integrating some useful components I guess
