### ISSUE TITLE
Switch to ESM.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#19113]
##### **Overview of the feature request**

- [ ] app
- [ ] base
- [ ] bootstrap
- [ ] bootstrap-application
- [ ] ci-cd
- [ ] client
- [ ] common
- [ ] cypress
- [ ] database-changelog
- [ ] database-changelog-liquibase
- [ ] docker-compose
- [ ] generate-blueprint
- [ ] gradle
- [ ] heroku
- [ ] kubernetes
- [ ] java
- [ ] languages
- [ ] maven
- [ ] project-name
- [ ] server
- [ ] spring-boot
- [ ] upgrade
- [ ] workspaces

##### **Motivation for or Use Case**

Follow javascript standards

##### **Related issues or PR**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by Tcharl** [comment]
Reopened: the jhipster cli is not working anymore due to a dependecy to constants.cjs, which itself needs jdl/validation.mjs...

**Comment by mshima** [comment]
The generator has already switched to esm and every bit is esm except jdl and cli.

The cli problem is related to mocking, which I am working on.
The jdl can be switched except some definitions that the cli uses.

Please open a new issue to track cli and jdl switch to esm.

**Comment by Tcharl** [comment]
The issue was labelled 'switch to ESM', thus wasn't mentioning that it was only targeting generator, still, the content did.

Why not reopening to get the complete picture? What's the added value of two tickets ?

I saw your current repo: great ambition which would really help, keep on rockin'! I'm trying through a simpler way, but not sure to succeed.

Best regards,

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/123269

**Comment by DanielFran** [comment]
@mshima approved
