### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by thiagogcm** [jhipster/generator-jhipster#1938]
Just noted that Jhipster holds 100% of one core. Tested with a fresh project using the following config:

{
  "generator-jhipster": {
    "baseName": "jhipster",
    "packageName": "br.jhipster",
    "packageFolder": "br/jhipster",
    "authenticationType": "xauth",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "postgresql",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "gradle",
    "frontendBuilder": "gulp",
    "javaVersion": "8",
    "enableTranslation": true,
    "rememberMeKey": "e8e1c74b5c54ebf85bacb75b0a6dccfadf37d724"
  }
}

Running on a up-to-date ArchLinux machine

Is that a normal behavior ?

**Comment by jdubois** [comment]
I'm guessing you speak just of the default generation, as the sub-generators usually run so quickly you wouldn't notice it.
During generation we are mostly I/O bound, and there is a lot of network waiting (for NPM, Bower, Maven), so I wouldn't say we should use 100% of one core. It also depends of the phase you are running, for example when Maven builds, it is working on multiple cores, and when NPM is running it is (obviously) working on just one core.
So this doesn't look "normal" to me, then it probably depends on your hardware.
It might also be related to your node version, and maybe your JHipster version, but as you didn't provide those I can't help you on that.

**Comment by gmarziou** [comment]
Yes gradle first build can be really much slower than maven as it is not able to work in parallel unline what maven does during dependency resolution. If you wait long enough, next build will be fast.

**Comment by thiagogcm** [comment]
Sorry.. I wasnt't clear enough

I'm talking about a fresh running application (after gradlew bootRun), not during building process.
more info:
Jhipster 2.20.0
node v0.12.7

**Comment by jdubois** [comment]
You mean Spring Boot using 100% of your CPU? This isn't a JHipster issue then.

**Comment by atomfrede** [comment]
@thiagogcm I have here ~9% cpu usage using ``gradlew bootRun`` and running on latest arch (little different config: no hazelcast and mysql instead of psql).

**Comment by deepu105** [comment]
@gmarziou the gradle deamon and parellel setting is definitely working for
me in windows, im seeing faster builds first time as well as consecutive.
And when the same deamon does a second build its very fast. Now the only
thing that slows dows seems to be the the bower and grunt tasks running
from within gradle once i disable them my normal bootrun is 30 to 40 second
max and my app has a lot of code and 100+ entities

You mean Spring Boot using 100% of your CPU? This isn't a JHipster issue
then.

—
Reply to this email directly or view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/1938#issuecomment-135159707>
.

**Comment by jodevan** [comment]
My $0.02: I have a similar issue. If I generate a brand new project using JHipster and then I run the application, it uses 100% of one of my CPU cores (My processor is a Intel i5) during its whole execution. I'm currently using JHipster 2.18.0. I tested it on Linux and Windows and found the same issue. At least in my case, the problem seems to be caused by Hazelcast, because if I comment out the method initClusteredHttpSessionFilter() in WebConfigurer.java, then the application behaves okay.
P.S.: By coincidence, I just scrolled up to check @thiagogcm's configuration and found that his application also uses Hazelcast. I think this seconds my hypothesis.

**Comment by jdubois** [comment]
Thanks @jodevan : as I'm not using Hazelcast there can be a link, indeed! Maybe we should upgrade the Hazelcast version? @deepu105 I know you're doing a lot of Hazelcast, any thoughts?

**Comment by deepu105** [comment]
Yes im using Hazelcast and i never had this issue till now both in windows
and linux but in using gradle, i never tried maven

**Comment by jodevan** [comment]
I tested some scenarios and according to them, the issue happens when we select the option "Do you want to use clustered HTTP sessions?" and we choose "Yes, with Hazelcast".
So the simple fact of choosing to use Hazelcast as Hibernate 2nd level cache is not enough to cause this issue. It seems the actual culprit is using clustered HTTP sessions with Hazelcast.
![screenshot from 2015-09-12 13 11 35](https://cloud.githubusercontent.com/assets/8137280/9832405/2d858fe6-5950-11e5-964c-92337c1bf014.png)

**Comment by deepu105** [comment]
Oh ok I have never used that myself, just 2nd level cache, my app server
takes care of session clustering

**Comment by gmarziou** [comment]
Could it be related to https://github.com/hazelcast/hazelcast/issues/81 ?
If so it seems that updating to Hazelcast 3.5.2-SNAPSHOT would solve the issue.
Could you try?

**Comment by jodevan** [comment]
Touché!!!
I've uncommented the method initClusteredHttpSessionFilter(), which uses the Hazelcast web filter and the application runs smooth. The Java process is taking less than 0,5% of CPU.
You guys rock!

Thanks!

**Comment by thiagogcm** [comment]
Sorry for the late reply on this issue.. I tested my application on another machine (Linux) and I didn't have any problem.. Back to my machine with hazelcast up-to-date the issue is gone as well. Thanks !
