### ISSUE TITLE
Guava is used in generated application but is not declared in pom.xml

### ISSUE THREAD

**Issue by gaelrenoux** [jhipster/generator-jhipster#1960]
In the generated Application.java class, the Joiner class from Google Guava is used. However, the Guava library is not explicitely declared in the pom.xml (it comes from the transitive dependencies). 

Furthermore, the version of Guava brought in this way cannot be deployed on JEE servers (see https://code.google.com/p/guava-libraries/issues/detail?id=1527). I added Guava 18.0 as an explicit dependency and it solved the problem for me.

**Comment by deepu105** [comment]
It works fine on tomcat and jboss eap 6.3 with gradle build haven't tried
maven

**Comment by jdubois** [comment]
- It is normal that we use transitive dependencies. We always do, unless there is a good reason not to do so.
- We are already using Guava 1.8 -> I guess you have an older version
- Your issue is not with all "JEE Servers". It looks like you are running JBoss, but we also have lots of people using JHipster on JBoss without any trouble, so I'm guessing it depends on your version of JBoss

Anyway, I don't like that we depend on Guava, that is provided by Swagger, just for doing this little syntaxic sugar. I understand that many people don't want to use Swagger, and this is going to be annoying for them.

-> I'd like to recode this without Guava, and remove this issue totally. I think this is how I coded it in the first place, I need to look at the history.

**Comment by gaelrenoux** [comment]
You are right, I am using JBoss 6 (it's not my call). And I have not tested on other servers, but the bug report about Guava seemed to indicate the problem was present on all JEE 6 servers. Sorry about that.

I generated my project with JHipster 2.16.1.

As for using transitive dependencies : not a big fan of that, as it makes it hard to control what version you are using. But I can see that it would add a lot more dependencies to the pom.

**Comment by jdubois** [comment]
For transitive dependencies: we use the ones from Spring Boot normally, and here this comes from Swagger.

For Spring Boot: we are based on it, and they do a great job at validating the transitive dependencies in their BOM file. So for us it's a huge win to rely on them.

Here, as it comes from Swagger, it's really a different story, and in that case it might not be a good idea, indeed.

Anyway, let's remove that code from JHipster :-)
