### ISSUE TITLE
Separate gradle build logic (and other features)

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#19615]
##### **Overview of the feature request**

I think our gradle part could have little make over for v8. In particular I am thinking of using some (precompiled) conventions, which reside in `buildSrc` directory. Having this the generated build.gradle file would in an optimal case just apply a few plugins and thats it.

Furthermore I would like to introduce gradle version catalogs to centralize the versions in an idiomatic gradle way.

##### **Motivation for or Use Case**

When talking to the gradle guys in the last couple of years they always suggested to have specific jhipster plugins. We (or me specific me) have always rejected this, because it would have created huge maintenance burden I was not willing to take. Moreover with everything generated we could easily provide workarounds for our users. Compared to having really dedicated plugins we would require both a release of the plugin and the generator.

With using convention plugins in buildSrc directory we can have best of both approaches. We clearly separate specific build logic, dependencies and plugins for specific jhipster configurations and as all is generated users can see everything and opt-out or replace stuff if needed.

This would also simplify our templates as we would try to have e.g. frontend specific stuff inside a dedicated conventions plugin and not different if/else switches inside the main build.gradle template file. 

This requires also changes to internal apis and needles as such I would consider this a breaking change and would like to do in v8. This will also most likely make a lot of blueprints not compatible with gradle anymore (thinking about the native blueprint), but I hope the required changes are quite small. 

I would try to implement a first prototype for first/initial discussion so we know everyone is happy with the outcome/result.

CC @mraible @jdubois @DanielFran @mshima @deepu105  Your view in this is highly appreciated.

**Comment by deepu105** [comment]
I'm all for simplifying and improving the gradle builds. I think we could
go the direction of generating pligins in buildSrc, i personally don't see
a big issue

**Comment by thetric** [comment]
Further documentation to the mentions Gradle features:

* conventions: https://docs.gradle.org/current/samples/sample_convention_plugins.html#compiling_convention_plugins
* version catalog: https://docs.gradle.org/current/userguide/platforms.html
** might be in TOML format instead residing inside `settings.gradle`: https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

**Comment by atomfrede** [comment]
@mshima @DanielFran I would start with extracting the versions into a version catalog. I hope we can reuse the existing toml file which we use for dependabot already and generate it for an application. With regards to convention plugins I think we might start by creating a convention plugin for gatling for example.

**Comment by mshima** [comment]
I don't know how a `convention plugin` looks like but sounds ok.
The toml file can be built from scratch using an external lib
https://github.com/jhipster/generator-jhipster/blob/0a8150c9ae4256f4fe28a02d0e9c2ec6f66d12a1/generators/server/support/dependabot-gradle.mts#L19

**Comment by mshima** [comment]
@atomfrede we already have a grade sub-gen, but it's quite different of maven due to design.
We are mostly writing a gradle script file for each tech and injecting it.
Gradle needles are:
https://github.com/jhipster/generator-jhipster/blob/433413f1e9436f08c34e9404a2152a1d002bee77/generators/gradle/generator.mts#L70-L75

And dependencies are split in separated files instead of api calls:
- Cache:
file: https://github.com/jhipster/generator-jhipster/blob/main/generators/spring-cache/templates/gradle/cache.gradle.ejs
injection: https://github.com/jhipster/generator-jhipster/blob/433413f1e9436f08c34e9404a2152a1d002bee77/generators/spring-cache/generator.mts#L102
- Kafka:
file: https://github.com/jhipster/generator-jhipster/blob/main/generators/spring-cloud-stream/templates/gradle/kafka.gradle.ejs
injection: https://github.com/jhipster/generator-jhipster/blob/433413f1e9436f08c34e9404a2152a1d002bee77/generators/spring-cloud-stream/generator.mts#L80
- Pulsar:
file: https://github.com/jhipster/generator-jhipster/blob/main/generators/spring-cloud-stream/templates/gradle/pulsar.gradle.ejs
injection: https://github.com/jhipster/generator-jhipster/blob/433413f1e9436f08c34e9404a2152a1d002bee77/generators/spring-cloud-stream/generator.mts#L131
- Liquibase:
file: https://github.com/jhipster/generator-jhipster/blob/main/generators/liquibase/templates/gradle/liquibase.gradle.ejs
injection: https://github.com/jhipster/generator-jhipster/blob/433413f1e9436f08c34e9404a2152a1d002bee77/generators/liquibase/generator.mts#L396-L412

Database are not split yet.
I am not a gradle expert, maybe you can improve even further.

**Comment by atomfrede** [comment]
Nice idea with the injection. Maybe we can use the mentioned gradle plugin mechanism for that. I will try something.

**Comment by atomfrede** [comment]
@mshima I think we can really leverage the current modularization approach and define and generate convention plugins which are than applied. That looks cleaner and easier to me compared to the apply from approach. Let me try something tonight

**Comment by atomfrede** [comment]
I really like the thing with the convention plugins. You can have look here. Need to figured out how to proceed with the node stuff and the dev/prod profile right now, but in general it looks very nice (for example)

```groovy
plugins {
    id "com.github.node-gradle.node"
    id 'jhipster.common-conventions'
    id 'jhipster.gatling-conventions'
    id 'jhipster.cucumber-conventions'
    id 'jhipster.test-conventions'
    id 'jhipster.sonar-conventions'
    id 'jhipster.cache-conventions'
    id 'jhipster.docker-conventions'
    id 'jhipster.code-quality-conventions'
    id 'jhipster.liquibase-conventions'
    // jhipster-needle-gradle-plugins - JHipster will add additional gradle plugins here
}
```

Will try to create a PR in the next couple of days.

@mshima As we have removed deprecated deployments, can I safely remove the `gae` "profile" from gradle?

```
  gae: {
    desc: 'Deploy the current application to Google App Engine',
    removed: removedV8,
  },
```

**Comment by mshima** [comment]
@atomfrede I think we can close this.
Not everything migrated to convention plugins but it's enough.
Next step is probably open api generator that can be reused in micronaut blueprint.

**Comment by atomfrede** [comment]
Yes let's close it and open dedicated issues for the remaining things.
