### ISSUE TITLE
Entity generator test

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#1965]
It would be great to have a reference .jhipster directory with entities containing all types of fields, relationships and options (DTO, pagination, ...) that we can use when testing the entity generator.
It could also be used by the jhipster-automated-samples and build CI.

**Comment by deepu105** [comment]
Yes +1 also a shell script or something to trigger them in sequence

**Comment by jdubois** [comment]
It's already done here: https://github.com/jhipster/jhipster-automated-samples

Of course the sample app could be more complex, but we already have one-to-many, many-to-one and many-to-many relationships, so that's already a good start.

At the moment I'd rather have tests, both for JS and the Java parts: our test coverage is too low.

**Comment by cbornet** [comment]
@jdubois So what is in your opinion the reference .jhipster directory ? I found one in https://github.com/jhipster/jhipster-sample-app/tree/master/.jhipster but it is missing a lot of entity types.

**Comment by jdubois** [comment]
Yes that's the one, and I admit it is not complete.

- I would first like to have more unit tests, both JS and Java -> there is no need to add lots of entities if our test coverage isn't good anyway
- And yes we could generate at least one big entity with all the types, at least for the main sample app, the Cassandra app and the MongoDB app (not sure if this would add an extra value to have it on all apps, but it might be simpler to manage)
