### ISSUE TITLE
Allow TEXT fields in entity sub-generator

### ISSUE THREAD

**Issue by natalia-pokrovskaya** [jhipster/generator-jhipster#1974]
For the moment, the only "text" field which is possible is String, which has a very limited length. I've seen that liquibase allow CLOB (TEXT) fields. I think it can be useful.

Thanks!

**Comment by jdubois** [comment]
- You can have a longer text if you select the "max" validator, or if you configure the database column yourself -> by default we use the default of the underlying technology, this is our [Policy 1](http://jhipster.github.io/policies.html), but of course this can be changed or reconfigured
- If you need something bigger we have the BLOB type -> at the moment it supports only binary or images (the difference is for the front end, not the database), I guess it could also support "TEXT"

Now I haven't looked at this closely yet, my concerns are:
- Is it supported by our databases correctly? I remember I had issues with Oracle 8i in 2000, but I'm sure they have improved it since that time :-)
- Is it supported by Hibernate?

**Comment by deepu105** [comment]
Oracle supports clob

**Comment by deepu105** [comment]
Im using clob on a JH app and can confirm that its supported by hibernate, oracle, h2, mysql, jpa, spring data and liquibase
So might be a worthy addition

**Comment by piedrahitac** [comment]
Hibernate does support TEXT columns by using String and max length of 65535.

I use it on MySQL, but I don't know if other databases have a TEXT type.
