### ISSUE TITLE
Move All non contextual code to respectives libraries

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#20081]
##### **Overview of the feature request**

The goal being to slim down a bit the generator and to make things simpler for everyone.

 - Move all frontend non templated code (i.e. admin forms, constants, interceptors, ...) to their respective frontend libraries (react-jhipster, ng-jhipster, ...), in small, overridable file on generated side
 - Create a jhipster-boot libraries with some @Conditional and few lines of codes (one for each database, reactive, cache, ...) and some jhipster-boot-starter with depependency list.
 - Move non templated common backend code to jhipster-framework lib (UserVM, ...)

##### **Motivation for or Use Case**

Multiple
 - Simplify templates, generator and maintenance
 - Reuse between jhipster-lite and jhipster-classic
 - Reuse in non-jhipster projects :-p
 - Developer experience (non only metamodelers will be able to contribute)

##### **Related issues or PR**

 - Many discussion from @jdubois, and some issues from me too ('member at least one on jhipster-lite).

@deepu105 @pascalgrimaud @mshima @DanielFran your thought?

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by atomfrede** [comment]
Just my 2 cents, I always liked that jhipster does not hide anything/much from the user. So one is able to change everything and can easily see what's going on. From a developer perspective I can totally understand the point to have less code in the generator, but I also think we need to keep in mind that in case we need to change something this involves at least two releases, one for a lib and one afterwards for the main generator.

Not sure whats the best approach. Maybe as the generator has grown much from its early days root we might go for more library approach.

**Comment by DanielFran** [comment]
I am not fan of libraries in jhipster because it create dependencies between projects and maintenance a little more complicated.
In fact this is why ng-jhipster has been deprecated
Also moving the ng-jhipster code to the generator allow user to change everything he wants

**Comment by mshima** [comment]
Agree with @DanielFran and @atomfrede.

`ng-jhipster` was deprecated due to maintenance burden and to make contributions easier.
I am not whiling to maintain a `ng-jhipster` or an external lib exclusive to jhipster. I maintain a few generic node libs that are used by jhipster.

Do we need a `jhipster-boot`?
IMO no, there is spring-boot for auto configuration and jhipster-framework for other purposes.

Should we generate less code?
Yes, we probably can simplify the generated code by using new spring-boot features like https://github.com/jhipster/generator-jhipster/pull/20066.

On the other hand, I would agree to have JHipsterDefault configurations at jhipster-framework.
Eg: moving https://github.com/mshima/generator-jhipster/blob/skip_ci-jwt_sb3/generators/server/templates/src/main/java/package/config/OpenApiConfiguration.java.ejs to jhipster-framework and call it JHipsterApiFistOpenApiDefaultConfiguration.
Import that config at the application configuration. Using a manual import and only a conditional on bean name. AutoConfigure is really difficult to debug, we should avoid that.

The decision about lib vs generated should be done on each case.
I would move to jhipster-framework:
https://github.com/mshima/generator-jhipster/tree/skip_ci-jwt_sb3/generators/server/templates/src/main/java/package/client
https://github.com/mshima/generator-jhipster/tree/skip_ci-jwt_sb3/generators/server/templates/src/main/java/package/management

We should not add more lib so we don't have to worry about depending on sporadic contributors.

**Comment by jdubois** [comment]
I am indeed a huge fan of this approach: put as much code as possible in a third party library, so it's hidden to people (less code, less complexity and less maintenance). That's how Spring Boot works, and for example in Azure we have our own Spring Boot starters which are very useful and popular (you just drop them and it works, and re-configuration is much easier). This would also help a lot to bridge the gap between JHipster and JHipster Lite.

**Comment by DamnClin** [comment]
I don't like this approach, the users I'm talking don't want to user JHipster because it is adding a dependency to a JHipster specific dependency (last discussion on that: today with 2 power users from a very big french company).

> Reuse between jhipster-lite and jhipster-classic

I don't really understand this part. jhipster-lite and jhipster-classic generated code are not really close, the plan is to create JHLite modules to add the new dependencies?

**Comment by jdubois** [comment]
I believe we should have some shared code, it’s all the same project and concepts on top of Spring Boot. The security part (mostly for JWT), the database optimization code (for UTC, some bug fixes) should be the same. Maybe some entity code, or configuration too.

Generated code always give more maintenance and security issues: I would limit it only to what people would normally modify (entities being the most obvious).

For the rest, let’s take an example : JWT.
- Are you sure those users understand how Spring Boot auto configuration works? It’s very easy to modify and extend.
- Are they aware of the security and maintenance impact? With our library we can easily and quickly patch a CVE. For generated code, it’s totally up to them and they won’t be notified in advance (only us get the CVE reports, fix them and then publish them - so typically if you use something like dependabot you have very limited risk)

**Comment by mshima** [comment]
> > The security part (mostly for JWT)
> 
> It's actually totally different code on this part and I don't really understand why it should be the same. In fact, it can't be the same since code generated by one framework won't work with the other one.

The generator uses a base64 encoded HS512 algorithm by default, the spring-boot default is to use certificates.
I couldn't find a spring-boot properties support to configure a hmac secret key, just for certificate based.
I doubt jhipster-lite uses HS512.

> > Generated code always give more maintenance and security issues
> 
> I disagree, in fact I'm seeing the opposite since you only have the code you need and not a lot of things you don't need and that will cause problems.

We don't update spring-boot minor/patch releases if there is a newer spring-boot version.
To fix a security issue, the user will have to regenerate using a new jhipster release or will have to override jhipster-dependencies with every security update.
IMO it's easier to maintain an all generated application.

**Comment by DamnClin** [comment]
> I doubt jhipster-lite uses HS512.

Why do you doubt that? Can you point to the faulty code?

**Comment by mshima** [comment]
> > I doubt jhipster-lite uses HS512.
> 
> Why do you doubt that? Can you point to the faulty code?

@DamnClin bad assumption, no faulty code. Using certificates may use less custom configuration.
Just saw the jwt implementation at jhipster-lite side, it very close from what we had before https://github.com/jhipster/generator-jhipster/pull/20066.
We have switch to use spring-boot builtin support. I may try to take a look and implement at jhipster-lite if you want.

**Comment by DamnClin** [comment]
>  may try to take a look and implement at jhipster-lite if you want.

Would be awesome!

**Comment by Tcharl** [comment]
> Just my 2 cents, I always liked that jhipster does not hide anything/much from the user. So one is able to change everything and can easily see what's going on. From a developer perspective I can totally understand the point to have less code in the generator, but I also think we need to keep in mind that in case we need to change something this involves at least two releases, one for a lib and one afterwards for the main generator.
> 
> Not sure whats the best approach. Maybe as the generator has grown much from its early days root we might go for more library approach.

First @atomfrede sorry to forgot to mention your handle.

My guess on that part is that we can try hard to split the code the right way, so that user can just copy the class he wants from the dependency sources and instantiate it in his project if needed: maybe the introduction of a facade+factory pattern can help the end user to achieve it easily, with the according guidance (he'll just have to update the facade's implementation).

Regarding the 'two releases' I guess that it can be automated in some way: I had some quite good 'developer experience happiness' moment using maven-release-plugin, it's far from being undoubtedly.

@mshima jhipster-boot-x would be used for combination of tech (I.e. database l2 cache)

@mshima @DamnClin the debate around jwt impl on this ticket, even if it polluted the discussion, illustrates to me the need of such dependency:  both projects would have benefit from the new implementation without even the need of an exchange on the topic.

Finally, it would also ease patch management on the user side if we follow the proper semver semantic: a lazy one could just update patch version in order to keep being cve-free (or most) whereas hipster will be able to upgrade their majors version  one by one, in an incremental process

**Comment by DamnClin** [comment]
The direction on JHLite on that will not be really easy to do in a dep: https://github.com/jhipster/jhipster-lite/issues/4113 

Of course, it is doable with configuration to disable some parts BUT it's way easier to understand with 2 modules in JHLite (and lighter code)
