### ISSUE TITLE
supporting flyway

### ISSUE THREAD

**Issue by hbakhtiyor** [jhipster/generator-jhipster#2019]
will be nice to add support to additional option of flyway db migration

**Comment by gmarziou** [comment]
Could you elaborate a little about what would be the benefits?

**Comment by jdubois** [comment]
- we can't support everything
- we rely a lot on Liquibase's features, for example the ability to do a diff of the JPA model with the database (which is something Flyway doesn't have)

So as far as I'm concerned we will not do it, as it would also break our current dev workflows.

**Comment by jdubois** [comment]
I'm closing this as I don't think this can ever be done, at least not in the short term, and as I don't understand the added value compared to Liquibase.

**Comment by unkndev** [comment]
The Spring documentation says: 
" In general we prefer Flyway because it is easier on the eyes, and it isn’t very common to need platform independence: usually only one or at most couple of platforms is needed."

https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html#howto-use-a-higher-level-database-migration-tool

**Comment by atomfrede** [comment]
Please don't comment on old tickets. Flyway doesn't support a diff against exising databases, wo we will not support flyway in the near future.
