### ISSUE TITLE
JH + BrowserSync not refreshing with content changes

### ISSUE THREAD

**Issue by craigryan** [jhipster/generator-jhipster#2047]
Hi guys, to avoid repeating myself I've added the link to an issue already logged with BS with full details. Basically a vanilla / fresh jhipster running app and I altered the footer text and Welcome text to see BS in action but when the page refreshes in chrome (port 3000) the new text appears briefly, then the old content loads. Any idea what may cause this and how to fix it?

https://github.com/BrowserSync/grunt-browser-sync/issues/123

**Comment by jdubois** [comment]
Yes, this is super-annoying.

- I confirm this used to work perfectly, and at some point BrowserSync really messed up something -> if you have any news from them, please do post it!!!! I've lost a lot of time of this, with no luck.
- The solution, as noted in the "tips" at http://jhipster.github.io/development.html is to have the dev console opened -> this should work without issue, otherwise please don't hesitate to mention it here, as once again this is really really annoying

-> if anyone has better solution, don't hesitate to post it here

I'm closing this as we have a workaround written in the doc, but I confirm this is very, very annoying

**Comment by craigryan** [comment]
Thanks for the pointer Julien,

I will post anything I discover, in the meantime while I chat to the BS
guys, when you say this used to work can you give me some details pls? What
BS version, any differences to JH generated gruntfile.js since it was
working? Anything that may help them towards a solution?

thanks,
Craig.

**Comment by craigryan** [comment]
by the way, disabling cache in dev tools made no difference

**Comment by andidev** [comment]
Are you sure? Did you keep the devtools open during the browser refresh?

**Comment by craigryan** [comment]
yes, and the main.html GET  (Network  -> Response tab) shows the new
content but the page still shows the cached version.

**Comment by craigryan** [comment]
OK two days of pain and it came down to I18N. I parked my 'real' JH app and
generated a fresh one to look into the BS issue. Seems I selected yes to
lang support along the way. The result of which makes markup like "<p
translate="footer">This is your footer dude</p>" ignore the p text and
refresh with text buried down in global.json. I'm sure there's a logic
reason for even generating default text with i18n enabled but it caught me
out. At least if the generated text was plainly obvious I would of spotted
it immediately. "<p translate="footer">Your default footer not taken from
I18N json</p>" for example, or maybe a tooltip to help guide.

Now I'm slightly back on track but facing yet more issues, had to hack
gruntfile to fix
https://github.com/BrowserSync/grunt-browser-sync/issues/120 not refreshing
main.html. It seems this is a well know issue and has been for a month,
would it not make sense to have JH generate the workaround gruntfile mods
(with some kind of comment to indicate its a workaround) while BS get their
act together rather than leaving it to newbies like me to work it out the
hard way? That'd be my preference anyway, so I can concentrate on learning
JH and not fixing bugs.

regards,
Craig.

**Comment by jdubois** [comment]
OK, 2 different things here:

- The i18n issue: you are not the first one to have a problem here. This is how angular-translate works, and if you select i18n then you are using it... I'm not saying it's obvious (once again you are not the first one), but that's how it's supposed to work. Maybe we should improve the documentation here?
- The browser-sync issue: from my understand the workaround is working, so that's OK for the moment. I'm indeed hoping a new BrowserSync version will solve this, as it's really a pain.
