### ISSUE TITLE
Bug: Cannot resolve TimeUUID when generating a Cassandra based domain class in a fresh project

### ISSUE THREAD

**Issue by vbhatt** [jhipster/generator-jhipster#2049]
error: cannot find symbol
    private TimeUUID timeuuidvalue;
            ^
  symbol:   class TimeUUID

for a generated TimeUUID attribute below
       {
            "fieldId": 3,
            "fieldName": "timeuuidvalue",
            "fieldType": "TimeUUID"
        }

**Comment by jdubois** [comment]
I guess the import is wrong -> can you provide a PR on this?
I can of course do it, but it will take some time.

**Comment by jdubois** [comment]
OK, I was wrong (I worked too long with Hector, in fact)

The issue is that TimeUUID and UUID are the same in Java (with the CQL driver), and inside JHipster we always use the Java type...

- from what I see, TimeUUID in JHipster doesn't provide much value (we only use the type in the CQL, nothing elsewhere as it's UUID everywhere)
- and so we have an internal issue, as we use the Java type everywhere

-> my current feeling is that we should remove the TimeUUID type. If someone wants to use it, it's just a matter of changing UUID by TimeUUID in the CQL file.

It's a bit sad as time series are so useful in Cassandra -> what's your opinion?

**Comment by vbhatt** [comment]
Thanks for your response. I agree with your assessment and that's what I ended up doing using UUID in java and timeuuid for storage.

**Comment by jdubois** [comment]
OK, I'm not happy with this solution, but indeed that's the only logical one at the moment.

**Comment by vbhatt** [comment]
On a separate note, does the datepicker widget in angularjs not work correctly with cassandra generated application? It just does not show for date fields.
