### ISSUE TITLE
What about removing databaseType option?

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#20679]
##### **Overview of the feature request**

Hi experts,
What about removing the 'databaseType' jdl entry and prompt?

##### **Motivation for or Use Case**

This property can be guessed from `devDatabaseType` `prodDatabaseType` for sure: less entries means best DX and less code to maintain ;-)

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by dpalic** [comment]
for me it is not even clear for what the databaseType is used at all?

**Comment by mshima** [comment]
I would drop the prodDatabaseType, rename devDatabaseType to something like embeddedDatabase.
And maybe make the embeddedDatabase as no by default.

**Comment by Tcharl** [comment]
I like the dev vs ci principle, and you're right, the 'prod' prefix is confusing.
May be an in-between with what we have: `devDatabaseType` + `databaseType` (e.g. just removing the prodatabasetype) could make the thing: jdl won't change that much, only generator code

**Comment by mshima** [comment]
`prodDatabaseType` and `devDatabaseType` were dropped from server generator and are only implemented at sql related generators like `spring-data-relational` and `liquibase`.
Different dev and prod databases were never supported for non sql and only supported for h2(disk/memory) as dev value.

Using specific database (postgres, mysql, etc) at `databaseType` will require server generator to know those values.
So `sql` will route to the sql generators, it can be omitted because is the default.

I suppose we can close this.
