### ISSUE TITLE
jpaGeneratedValue configuration for Id field 

### ISSUE THREAD

**Issue by namtuanbk** [jhipster/generator-jhipster#20725]
##### **Overview of the feature request**

   In the JDL file, there is no way to configure Id filed with the jpaGeneratedValue identity type. Please support the new configuration option for the jpaGeneratedValue identity type.
##### **Motivation for or Use Case**

    In some cases, I want to use @GeneratedValue(strategy = GenerationType.IDENTITY) for the id field of the entity.
    It is always set to 

         @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "sequenceGenerator")
         @SequenceGenerator(name = "sequenceGenerator")

##### **Related issues or PR**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by dpalic** [comment]
having a similar question...

I would like to define in JDL the strategy.
But I have neither a clue how to setup the configurations. The code looks like it supports it?

https://github.com/jhipster/generator-jhipster/blob/v7.9.3/generators/server/templates/src/main/java/package/domain/PersistentToken.java.ejs#L114

https://github.com/jhipster/generator-jhipster/blob/v7.9.3/generators/entity-server/templates/src/main/java/package/domain/Entity.java.jhi.javax_persistence.ejs#L39

Any hints how to use this code either via configuration or even better via JDL?

**Comment by juarezmax** [comment]
Which *production* database did you select ?
I modified 'prodDatabaseType' from 'mariadb' to 'mysql'. I'm using jhipster 7.9.3.

**Comment by juarezmax** [comment]
According to this comment https://github.com/jhipster/generator-jhipster/issues/4725#issuecomment-268497771, it was previously decided to use IDENTITY with MySQL/MariaDB and SEQUENCE with any other db.

But since support for sequences was introduced in MariaDB 10.3, jhipster team decided to use IDENTITY for MySQL only. https://github.com/jhipster/generator-jhipster/issues/12981

So I'm thinking this can't be configured.
