### ISSUE TITLE
Postgres locks in Cloudfoundry

### ISSUE THREAD

**Issue by krishna383** [jhipster/generator-jhipster#2079]
I have my JHipster based application deployed in cloudfoundry for over 3 months. So far I had 3 such occurrences of DB lock.

None of these occurrences happened during the server start up/deploying the changes. They happened when the application was running for few days and all of a sudden my site goes down. After troubleshooting found that there is a lock entry in DATABASECHANGELOGLOCK.

I see similar issues with Heroku, but see them majorly during startup. I didnt see any issue related to cloudfoundry. I tried troubleshoot, but having no clue why the DB lock is happening when the application was running and no changes were deployed.

Here is log to one such incident.
https://www.dropbox.com/s/ads1378atrswl4s/1.txt?dl=0

**Comment by jdubois** [comment]
OK, first of all thanks because this is really a great feedback from real-world usage.

What happens to you is quite common in dev, and I didn't expect it in prod. At startup, Liquibase locks the database to perform its updates, and it timesout... So yes you need to remove the lock manually (troublesome), and if you need a quick workaround you need to disable the Liquibase bean (but then, no more automatic database updates).

- I will update the documentation to explain this more clearly, as this is a common issue
- I'll try to think of a better solution, but I'm not sure there is one -> disabling Liquibase is also annoying, of course

Now for a crazy idea: when we have this lock, have an option to force it at startup (in the application.yml file)

**Comment by deepu105** [comment]
@jdubois if there is a way to force this that would be great, coz when working with a shared DB with many dev it is really annoying as someone might do a kill midway and this would end up being locked. another annoying thing is the liquibase checksum error when the xml has any changes, even for a formatting change. so in dev it would be nice to have an option to force rebuild of DB

**Comment by jdubois** [comment]
OK, so we could have 2 options:

- Don't use Liquibase (easy)
- Kill the lock (at least to solve a locking issue)

**Comment by deepu105** [comment]
In production I have disabled liquibase already and I personally think its better that way, But in dev its would be nice to have a rebuild or kill lock

**Comment by jdubois** [comment]
OK, then we could have some specific options in the application.yml:

    jhipster:
        liquibase:
            shouldRun: true|false
            async: true|false
            force: true|false # Release the lock if it exists

**Comment by krishna383** [comment]
@jdubois I like the application.yml configuration, this way, when ever I have database updates, I can turn these on and keep it off for the rest of the time. So that it crashes and restarts it does not create the lock.

Also, I am looking to scale the app to 2 nodes, need to see how liquibase would try to do the DB updates, do you have any insight on that?

**Comment by jdubois** [comment]
OK, I just added the remaining standard properties from Spring Boot to our Liquibase configuration:
https://github.com/jhipster/generator-jhipster/commit/44f427c4b5309d344beb015cdecb35c1877f890b

So now you can enable or not Liquibase using the standard "enable" property, so that's really easy to use and set up.

Concerning the 2 other options:

- Async mode is not configurable: by default it is on in "dev" mode and off in "prod" mode. That can be discussed (and it's easy to change), but I don't want to have too many options if they are not necessary, and this looks like a logical configuration
- There is no way to force the lock, excepted by doing some SQL request before running Liquibase, which looks quite complex to set up. Of course you can release the lock manually (using an SQL query), but the "normal" way to do is to run the "releaseLocks" Maven goal, which looks pretty logical and easy to use -> so I don't think we need anything more, as per our Policy 1, we don't change the normal behavior of underlying technologies if we don't have a good reason to do so

If you want to use the add on 2 nodes, then that's a different question -> please follow the guidelines, and go to SO for that. But yes you should disable Liquibase on one node, in my opinion.
