### ISSUE TITLE
Add Maven Wrapper for Maven projects

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#2080]
We currently include the Gradle Wrapper with Gradle projects. It'd be good to include the Maven wrapper as well.

https://github.com/bdemers/maven-wrapper

This way, developers can start with JHipster without having to install Maven. 

Spring Initializr added this recently:

https://github.com/spring-io/initializr/commit/be8ee1964fa02a2ca726e6d768869bd757ff8968

**Comment by jdubois** [comment]
I didn't know about this one!!!

- Really, really cool project
- But I'd rather have something official from Maven -> here we would rely on a project that doesn't look very active, so that might be dangerous for us in the long run

@bdemers as I see on Github that you have an Apache email, any chances that your wrapper becomes officially part of Maven? (and kudos for the great idea, by the way!)

**Comment by bdemers** [comment]
@jdubois yeah, I've been meaning to play around with it more, but haven't had the time.  Luckily though @jvanzyl picked up under Takari org: https://github.com/takari/maven-wrapper.

I'll put a link in the README on my fork, and a few other related notes to avoid the confusion.  Thanks for the interest in the project!
