### ISSUE TITLE
Migrate XAuth to Spring Security JWT

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2100]
Following the discussion from #2095 , study the migration to Spring Security JWT.

**Comment by amit2103** [comment]
@jdubois are you working on this? If not I can work on this.

**Comment by jdubois** [comment]
No I'm working on the Spring Boot 1.3 migration at the moment -> feel free to work on this!!

**Comment by amit2103** [comment]
@jdubois  I will start working on this.

**Comment by JStumpp** [comment]
+1

**Comment by amit2103** [comment]
Hi Guys..I have studied this (am still doing so )...I have more or less understood how to proceed with the JAVA part when using JWT. I have identified the changes that needs to be done in the config package and those in the security package. Now I have two doubts/questions, which I am having trouble understanding myself due to my unfamiliarity with the project.
1) In case of the current implementation of xauth is it expected that the client will send in the correct token the first time? 
2) If 1 is not true, can anyone point me where the first authentication is done for the first time (for stateless apps, I understood how Session based authentication works).
If 1 is true, then is there some code in current Javascript that we will have to change as well?

**Comment by jdubois** [comment]
Yes you need to migrate also the JavaScript part -> do a grep on "XAuth" on the generator, you should see 102 results, showing you everywhere where this code is.
It currently looks like quite a lot of code, however if this is already implemented by Spring Security I expect it's mostly removing old code.

**Comment by amit2103** [comment]
Yes, I too think that it will be mostly be code removal in the JS side. However the Client side generating the login credentials needs to be changed perhaps.

**Comment by JStumpp** [comment]
Have you considered using the project sattelizer (Token-based authentication module for AngularJS with OAuth Support): https://github.com/sahat/satellizer
It is really simple to use and could also solve the social login effort https://github.com/jhipster/generator-jhipster/issues/1649

**Comment by amit2103** [comment]
@JStumpp  I had mainly looked into the server side code that we need to change. I think I more or less have completed it.  I will start looking into the client side. I will take a look at satellite. Thanks for the suggestion.  Someone however is working on the social integration. 

I plan to do this phasewise, in my branch I first plan to complete the server side code and get it reviewed. Then I plan to code the client side. That way someone like @jdubois  , you or others will have an easier time reviewing it too.

**Comment by JStumpp** [comment]
Sure, looking forward to the server side code!

**Comment by francoisledroff** [comment]
well we could have both, right oAuth2 and JWT cf https://github.com/spring-projects/spring-security-oauth/blob/master/docs/oauth2.md#jwt-tokens

**Comment by deepu105** [comment]
@jdubois isnt this already done?

**Comment by jdubois** [comment]
@deepu105 no, no news from this!
Are you wanna do this?

**Comment by amit2103** [comment]
@jdubois Sorry for the delay was in a holiday...created a pull request with java changes...Will update the JS changes soon

**Comment by fodaley** [comment]
Happy new year. @amit2103 is there any update on this?

**Comment by amit2103** [comment]
Sorry was in a Holiday for 2 weeks..started work on this again..Will give an update soon
