### ISSUE TITLE
CORS support lacking in oAuth based apps

### ISSUE THREAD

**Issue by jvence** [jhipster/generator-jhipster#2109]
Basically if you don't generate a session based authentication app, the CsrfCookieGeneratorFilter is not created so you need to manually add a filter to set the appropriate headers for CORS support. Instructions on http://jhipster.github.io/tips/006_tips_enable_cross_origin_requests.html are NOT valid for non-session based apps.

**Comment by jdubois** [comment]
If you don't have a session, then you don't have a cookie, so you shouldn't be vulnerable to CSRF attacks -> that looks logical to me that the CSRF filter is turned off, but please note that I didn't code both OAuth and Token mechanisms, so maybe I'm missing something. Can you elaborate on that issue?

**Comment by jvence** [comment]
That's fine but the instructions to enable CORS support (which would apply any type of authentication) depends on CsrfCookieGeneratorFilter (which as you correctly pointed out is not needed in an oAuth based app). Firstly instructions must be updated but also it would be nice to auto-generate a filter to enable CORS support on any type of generated app.

**Comment by gmarziou** [comment]
This tip will be obsolete as soon as we use Spring Boot 1.3 by using new annotation [@CrossOrigin introduced in Spring 4.2](https://spring.io/blog/2015/06/08/cors-support-in-spring-framework)

**Comment by jvence** [comment]
Great so I will close this issue.

**Comment by cbornet** [comment]
Since we upgraded to spring boot 1.3 , I reopen this issue.
The tip is indeed incorrect as a dedicated filter should be used for Cors and it doesn't deal with the pre-flight OPTIONS requests.
I have tried to use the method from [here](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/spring-boot-features.adoc#cors-support) but that was not successful. To make it fully work I had to add the following bean to my conf
```java
@Bean
    public CorsFilter corsFilter() {
        UrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
        CorsConfiguration config = new CorsConfiguration();
        config.setAllowCredentials(true);
        config.addAllowedOrigin("*");
        config.addAllowedHeader("*");
        config.setAllowedMethods(Arrays.asList(new String[]{"GET", "PUT", "POST", "DELETE"}));
        source.registerCorsConfiguration("/api/**", config);
        source.registerCorsConfiguration("/v2/api-docs", config);
        source.registerCorsConfiguration("/oauth/**", config);
        return new CorsFilter(source);
    }
```
@jdubois I know that for performance reasons you don't want to add a filter that will not be used in most of the case but we could add it when a property jhipster.cors.allowed-origins is set to not empty (if left blanck which would be the yml default, we do not register the filter).

**Comment by mraible** [comment]
Spring Boot 1.3 depends on Spring 4.2, which has a @CrossOrigin annotation that can be used.

https://spring.io/blog/2015/06/08/cors-support-in-spring-framework <https://spring.io/blog/2015/06/08/cors-support-in-spring-framework>

**Comment by cbornet** [comment]
Yes, the ```@CrossOrigin``` is for fine grained configuration of controllers and requestmappings.
The bean I gave is for global configuration of CORS.
