### ISSUE TITLE
Support pnpm as a client package manager

### ISSUE THREAD

**Issue by bhadreshdesai** [jhipster/generator-jhipster#21785]
##### **Overview of the feature request**

pnpm is a fast, disk space efficient package manager relying on hard links and symlinks to save only one copy of a module/version regardless of how many projects you have using the same version of a module or library. Read more about it at https://pnpm.js.org/

Using pnpm as a package manager will speedup the initial project creation and will use reduced disk space.

##### **Motivation for or Use Case**

I experiment a lot with jhipster to create micro services projects.

With the introduction of micro frontends multiple micro services will use the same package dependencies in all the micro services projects.
As pnpm will reuse already dowloaded dependencies, using pnpm as a package manager will make the initial project creation faster. It will also reduce the disk space used by the project. 

##### **Related issues or PR**

I appreciate that the yarn support was removed in favour of reducing the complexity and maintenance overhead.
https://github.com/jhipster/generator-jhipster/issues/12135
https://github.com/jhipster/generator-jhipster/pull/12134

Adding pnpm or even replacing it as a package manager will be very beneficial for everyone.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
npm is bundled in node, if node changes its default package manager, we should follow.

pnpm support won't officially happen due to complexity.
pnpm can be implemented as a blueprint.

A customization repository was in my todo for quite a long time.
I've created it with some of you customizations as start point: https://github.com/mshima/local-blueprints-samples/
