### ISSUE TITLE
This is a feature request unique fields 

### ISSUE THREAD

**Issue by vsarabu** [jhipster/generator-jhipster#2199]
while generating the new jhipster project entity using cmd prompt,
can you please include one more option asking for unique values.

Ex: yo jhipster:entity author
Answer the next questions concerning the fields of this entity, the author has:
a "name" of type "String"
*********do you want this filed as unique: ?*******

I am asking this feature because, if i do it manually by changing the code @unique= true its not working. so i need to do find all and compare the names

It's working fine for taking only unique names but alert message is not showing up.

if you have any solution for this please share your valuable suggestions

I also seen Similar type of qus by  https://github.com/jhipster/generator-jhipster/issues/2139 for unique

**Comment by jdubois** [comment]
We can't make a field "unique" in the UI that easily, because you need a round trip from the server-side -> you would first need to check if the field exists

This is rather a business need, it's out of scope for us at the moment.

On the database level it's a different issue, and as you say it's just adding a parameter -> we would not do it as it's against our guidelines (policy 2 at http://jhipster.github.io/policies.html , we don't add any value)
