### ISSUE TITLE
Travis test for jhipster-docker is failing

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2203]
Our Travis build for jhipster-docker is failing:
https://travis-ci.org/jhipster/jhipster-docker

The complete log is here:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/87033352/log.txt

It looks to me that it is in fact working fine, but the curl command is running too quickly, or doesn't retry enough.

@pascalgrimaud as you coded the Travis build, can you have a look?

**Comment by pascalgrimaud** [comment]
Oh, you're right and I'm sorry !
Since the migration to spring boot 1.3, there are much dependencies to download. Starting an app take more time the first time. I got the same problems when I worked on https://github.com/jhipster/generator-jhipster/issues/2182 and I forgot completely the travis build for jhipster-docker.

I will rework on this travis build asap.
