### ISSUE TITLE
OpenID Support

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#2204]
I use JHipster but I have to implement login through OpenID provider. Will OpenID connection implemented in the future?
Or can you explain how to realize it the best way?

**Comment by cbornet** [comment]
The newly 2.23 release of jhipster supports social login using spring-social. Since spring-social seems to support OpenID (https://github.com/spring-projects/spring-social/wiki/Api-Providers) it should work out-of-the-box. Can you try and give your feedback ?

**Comment by cbornet** [comment]
Well. I spoke too quickly. Seems that we only support Facebook,Twitter and Google for now.You will need to add your own provider in src/main/java/${package}/config/social/SocialConfiguration.java

**Comment by jdubois** [comment]
Yes you need to check what Spring Social provides: it's probably provided out of the box, so we don't really need to support anything here

**Comment by delverdev** [comment]
Seems like Spring Social provides only the OAuth. I didn't find examples or information about this. But how to implement login through OpenID? When I was trying to implement this in SecurityConfiguration (adding http.openidLogin and custom UserDetailsService), it redirect me to #/login page after go to #/login/openid?openid_identifier=anyidentifier. In my other projects (w/o JHipster) it works. I also disabled csrf and deleted http.formLogin.

**Comment by cbornet** [comment]
The Spring social extension for OpenID is https://github.com/molindo/spring-social-openid/
I recommend you to read the Spring Social [Quick-Start](https://github.com/spring-projects/spring-social/wiki/Quick-Start) then it should be as simple as adding the spring-social-openid dependency and configuring SocialConfiguration.java

**Comment by cbornet** [comment]
Try to add this to SocialConfiguration::addConnectionFactories() :
```
connectionFactoryConfigurer.addConnectionFactory( new OpenIdConnectionFactory() )`;
``

**Comment by delverdev** [comment]
I have tried to add dependency of the extension:
```
<dependency>
        <groupId>at.molindo.social</groupId>
        <artifactId>spring-social-openid</artifactId>
        <version>1.1.0.RELEASE</version>
</dependency>
```
I've also added connectionFactoryConfigurer.addConnectionFactory(new OpenIdConnectionFactory()); at the end of the SocialConfiguration::addConnectionFactories() method.

I receive an error. Here is the [logs](http://pastebin.com/Ti1thy1N).

**Comment by cbornet** [comment]
Arf ! Not so out-of-the-box after all... 
We use configuration classes from spring-social that don't know about the openid extension
See https://github.com/spring-projects/spring-social/blob/master/spring-social-config/src/main/java/org/springframework/social/config/annotation/SocialConfiguration.java
We use ```@Enable``` which imports SocialConfiguration which configures ConnectionFactoryLocator  with uses SecurityEnabledConnectionFactoryConfigurer which only supports oauth1 and oauth2
So you will have to somehow pass your own ConnectionFactoryConfigurer modeled on SecurityEnabledConnectionFactoryConfigurer (let's call it CustomConnectionFactoryConfigurer) but that will use OpenIdAuthenticationService to wrap OpenIdConnectionFactory in its wrapAsSocialAuthenticationService() method. Then you can try to override the connectionFactoryLocator bean with your own
```java
    @Bean
    @Primary
	public ConnectionFactoryLocator connectionFactoryLocator() {
		if (securityEnabled) {
			SecurityEnabledConnectionFactoryConfigurer cfConfig = new CustomConnectionFactoryConfigurer();
			for (SocialConfigurer socialConfigurer : socialConfigurers) {
				socialConfigurer.addConnectionFactories(cfConfig, environment);
			}
			return cfConfig.getConnectionFactoryLocator();
		} else {
			DefaultConnectionFactoryConfigurer cfConfig = new DefaultConnectionFactoryConfigurer();
			for (SocialConfigurer socialConfigurer : socialConfigurers) {
				socialConfigurer.addConnectionFactories(cfConfig, environment);
			}
			return cfConfig.getConnectionFactoryLocator();
		}
	}
```
I haven't tried this code but hopefully with the Primary annotation your bean will be used instead of the one from SocialConfiguration.
If this doesn't work you could also remove the Enable annotation and provide your own copy of SocialConfiguration.
Good luck :wink:  !

**Comment by cbornet** [comment]
@delverdev Did you manage to make it work ?

**Comment by cbornet** [comment]
Also, just to be sure : you are talking about "openID", not "openID connect" ?

**Comment by delverdev** [comment]
I've postponed it. I'm talking about login to the site. http.openIdLogin() from security configuration usually implements it.

**Comment by jdubois** [comment]
As @delverdev has postponed this, and as we already support so many authentication options, I'm closing this as this won't be done in the near future.
