### ISSUE TITLE
Generating an invalid code from enum in JDL

### ISSUE THREAD

**Issue by vw98075** [jhipster/generator-jhipster#22192]
##### **Overview of the issue**

In JDL,
```
enum Currency {
	USD("USD")   
}
```
The generated Java code will be 
```
/**
 * The Currency enumeration.
 */
public enum Currency {
    USD;

    private final String value;

    Currency(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
```
The code isn't valid.

##### **JHipster Version(s)**

7.9.3

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by hide212131** [comment]
It seems appropriate to change the current code so that an enum is deemed to not have a custom value when its key equals its value:

https://github.com/jhipster/generator-jhipster/blob/06faa52ac18d70a6201cb8c444c63c5760ee8dc3/generators/base-application/support/enum.mjs#L22-L24

If there's no disagreement, I plan to submit a Pull Request for this.
