### ISSUE TITLE
John Papa Style Guide Implementations

### ISSUE THREAD

**Issue by RGFnaGFuIEd1bmF5** [jhipster/generator-jhipster#2271]
Topic #2256 

- [x] app files
- [x] - Entity files
- [x] - components
- [x]  - Account
- [x]  - Admin
- [x]  - home, layout
- [x] - ~~Structure modification~~ done
- [x] - services

- [x] run https://github.com/Gillespie59/eslint-plugin-angular after completion to check

**Comment by Vaelyr** [comment]
Few remarks after reviewing the changes:

Targeting new entity files.

As per Papa's guide:
* No need for module variables, use setter. [Style Y022]
* I don't understand the purpose of xxx.module.js - [Style Y165]
* $inject already protects from minification, no need for explicit @ngInject [Style Y100]
* Folder structure is against the style; package by feature; no need for controllers/services etc separately - it's A LOT easier to manage when having all related files in one folder side by side, that would actually also include test files!
* Resolve dependencies in route resolver. This loadAll/load method in list controllers is a headache and completely redundant, especially together with ng-init in the view (eww). Resolving list and details in route resolver prevents from dealing with emtpy arrays or objects. Returning **promise** from resolve won't render the controller before **all** the resolves are solved. Loading manually should only remain for paging purpose, but initially it should not be used and is ugly, because you rarely want to see entity pages before data is loaded. NB! That is not case for metrics/health controllers, these should remain async! [Style Y081]

As we are already at it, another suggestion for CRUD operations would be reduce the amount of server hits for each operation. Currently almost every operation does new server call.

Since Spring REST controllers return the result of each operation, along with the modified entity, why not use that result to update the view instead of making new query all the time to refresh. That would mean using two separate services for model data and actions, thus not keeping the data in scope, buy in service model. This is very common and very good practice as well.

It would add a bit more complexity, but I think it would be worth the effort to achieve better design.

More about it: 
* http://www.johnpapa.net/sharing-data-in-an-angular-controller-or-an-angular-service/
* http://www.webdeveasy.com/angularjs-data-model/

**Comment by gzsombor** [comment]
The loadAll / load methods are very useful methods : when you are using paging, or implement filtering, so I wouldn't remove them.

**Comment by Vaelyr** [comment]
Yes I mentioned paging, but initial data query isn't views job or shouldn't be done in activate method either. For that only it should be there, but its only purpose would be to handle paging or use it for manual refresh button if required.

**Comment by deepu105** [comment]
Also  i dont think we should re structure folder structure now, lets implement style guide on existing structure and then later we can discuss about folder structure

**Comment by jdubois** [comment]
yes, the structure is more complex to move, and at the moment it doesn't seem wrong to me (but I'm not an expert in John Papa's style)

**Comment by Vaelyr** [comment]
Current structure is fine and pretty much the same. The PR has changed the structure which shouldn't be changed :)

**Comment by deepu105** [comment]
anyone working on this?

**Comment by geraldhumphries** [comment]
+1 for making this a priority.

**Comment by deepu105** [comment]
I dont think anyone is working on this?

**Comment by deepu105** [comment]
I have also started to feel that it might be better to invest time to
migrate to angular2 rather than this

**Comment by deepu105** [comment]
@RGFnaGFuIEd1bmF5 are you working on this?

**Comment by deepu105** [comment]
@jhipster/developers hey guys since we are breaking stuff can we change the angular js folder structure to below as per John papa style [Y141](https://github.com/johnpapa/angular-styleguide#locate), [Y152](https://github.com/johnpapa/angular-styleguide#folders-by-feature-structure) etc

```
src
|__main
      |__client (was webapp)
           |__content (was assets)
           |__i18n
           |__swagger-ui
           |__bower_components 
           |__app  (was scripts)
                |__app.module.js
                |__app.config.js
                |__app.constants.js
                |__components
                     |__alert
                     |__form
                     |__interceptor
                     |__language
                     |__util
                |__services
                     |__admin
                     |__auth
                     |__user
                     |__entities
                |__layouts
                     |__navbar
                     |__error
                     |__login
               |__account
               |__admin
               |__entities
               |__home(was main)          
           |__index.html
           ....

```

what do you guys think, if you guys are ok ill take the lead on this and change the structure

**Comment by pascalgrimaud** [comment]
Ok for me @deepu105

**Comment by jdubois** [comment]
Yes that's the right time to do this.
I didn't study the guide well enough so I'm trusting you on this. Only issue for me is the "webapp" folder, which comes from the standard Maven layout, so this might cause trouble and has to be discussed.

**Comment by deepu105** [comment]
Oh I didnt think of that, then may be lets keep that folder name the same.

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
@gmarziou @gzsombor @atomfrede @Vaelyr you guys do a lot of angular i suppose. so what do you think of this structure,may be the webapp folder we should keep the same as Julien suggested.

**Comment by jdubois** [comment]
OK then!

**Comment by atomfrede** [comment]
Yes keeping ``webapp`` is much easier. Folder structure looks fine to me.

**Comment by pascalgrimaud** [comment]
So maybe our modules must be updated too, right?

**Comment by jdubois** [comment]
Yes, we will have some version issues here! That's why it's a major release, we have breaking changes.

**Comment by deepu105** [comment]
yup it all paths would need update

anyway as of now most modules are from us, so we can make new release as soon as JH 3.0 is out

**Comment by deepu105** [comment]
it should be just changing paths in the copy and template instructions

**Comment by deepu105** [comment]
I have a question @jdubois should we change only the generated apps structure or should we also change our template folder structure to be the same as above for angular templates?

**Comment by jdubois** [comment]
Oh yes we should also change our template structure : it's much easier to understand if they look the same.

**Comment by deepu105** [comment]
ok

**Comment by gmarziou** [comment]
Works for me.

**Comment by deepu105** [comment]
ok so majority agrees, i would take that as yes :)

Thanks & Regards,
Deepu

**Comment by andidev** [comment]
Maybe we could follow more John Papa styles in the next major version. I could help with the refactoring.

**Comment by jdubois** [comment]
Yes of course! First we do the layout, then the code, as otherwise it'll be complex to merge. And any help is welcome, keeping in mind that I'm a Java guy and I suck at JavaScript :-)

**Comment by deepu105** [comment]
im almost done refactoring layouts :) need lots of help in review and testing :joy:

**Comment by jdubois** [comment]
I'm not too worried about reviewing and testing, there are a lot of us :-)
And I'm soon going to have a second full-time trainee, we can make them both work on that if that's necessary

**Comment by deepu105** [comment]
that was a lot of refactoring,my eyes hurt :sob: plz review guys

**Comment by deepu105** [comment]
i did all the basic testings,npm test, grunt test, gulp test, gradle dev and prod build and its ok

**Comment by dancancro** [comment]
Would anyone with intimate familiarity with this structure be interested in adding a column for it [here](https://docs.google.com/spreadsheets/d/1I6VZNgnodju5KO3C07Ut3GLDvpZVYh0pBlUf2jYDsV0/edit#gid=1103163354)?

Is this sort of structure dissection and comparison useful?

If you have any questions let me know. Thanks.

**Comment by deepu105** [comment]
this would be nice to have for 3.0 @wmarques are you interested to take this up? since @jdubois mentioned that your interest is in client side stuff!

**Comment by wmarques** [comment]
@deepu105 Yes I started working on it. Should i do a pull request for each rule I applied ? Or should I do a big pull request once I've done applying all the rules ?

**Comment by cbornet** [comment]
I'd say incremental. Big PR is big trouble.

**Comment by deepu105** [comment]
Incremental plz, may be do one module at a time like in the issues title
comments. Do entity templates first. Then do admin modules and then
everything else

**Comment by deepu105** [comment]
@wmarques ill work on the main app.module and app.config files as per #2986
