### ISSUE TITLE
Add relations for mongodb documents

### ISSUE THREAD

**Issue by rreitmann** [jhipster/generator-jhipster#2279]
Hi,

the entity sub generator does currently not offer the option to specify relations between mongo db documents. Spring Data has such a support and with Spring Data Rest and Hateoas we could even get links for the resulting resources. Are you planning to implement these features?

**Comment by jdubois** [comment]
I'm not going to implement this personally, as I don't use MongoDB myself -> is anyone interested in implementing this? Or at least giving some help/guidelines (as I don't know MongoDB good enough)?

**Comment by rreitmann** [comment]
How long would it take for an experienced user? My Boss says we could spent some money for this :-)

**Comment by jdubois** [comment]
Hey, your boss is great!!!!
I don't think it should be much difficult, have you had a look at how our templating system works?
Have a look at https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md

-> it might seem a bit difficult at first, but we have now more than 150 contributors, and that's because it's quite easy to participate. That's clearly one of the biggest success factor for the project.

**Comment by rreitmann** [comment]
Hey,

yes it looks manageable but how bosses are, we have just decided to go with Postgres and thus there is no motivation left :-(

**Comment by jdubois** [comment]
Ah, too bad!

I'm closing this issue then: I'd love to have this, but if nobody is ready to work on it, it won't be done.
