### ISSUE TITLE
Generate source map for minified js files in prod

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2282]
Becoz debugging issues in production is extremely difficult given clinet side has more code now.

Since we use uglify js it should be easy to do

http://blog.getsentry.com/2015/10/29/debuggable-javascript-with-source-maps.html

**Comment by piedrahitac** [comment]
:+1: This would be really helpful!

**Comment by deepu105** [comment]
Not very familiar with uglify so if someone wants to PR this you are welcome, else ill try

**Comment by gmarziou** [comment]
Not only for JS files, it can be done also for SASS

**Comment by deepu105** [comment]
@gmarziou I know how to do it in gulp, but havent tried in grunt, do you have any sample?

**Comment by gmarziou** [comment]
I have switched to gulp 6 months ago, so I don't know either for grunt.

**Comment by deepu105** [comment]
Damn if Grunt was easy as gulp :(

On Sun, Jan 3, 2016 at 8:01 PM, Gaël Marziou <notifications@github.com>
wrote:

> I have switched to gulp 6 months ago, so I don't know either for grunt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/2282#issuecomment-168491890>
> .
>



-- 
thank you,
Deepu.k.s

**Comment by ngasull** [comment]
As I warned in https://github.com/jhipster/generator-jhipster/pull/2686, please beware of source maps: depending on source maps configuration, they can actually reflect the full original code and file tree. We use them in my company in integration builds only as we don't want users to have our full source.

Do you think there should be a flag that users should change by themselves in gulpfile/Gruntfile in order to let them enable source map if they want this feature?

**Comment by jdubois** [comment]
@ngasull yes there could be a flag which has the maps turned on by default, but as it's running on the client-side I'm not too worried by the security risk -> this code shouldn't have anything to hide anyway, I only want the minification for performance, not security

**Comment by ngasull** [comment]
@jdubois fair enough then, let's just make it clear to jhipster users :) I may have a look to both Gruntfile and gulpfile on spare time then. That would at least make my past source map struggles worth a good cause!

**Comment by deepu105** [comment]
@ngasull I guess the point of having sourcemap is to debug issues in prod otherwise current config is sufficient, if someone doesn't want they can simply change the boolean to false in gulp or grunt file.
What is the use of generating it if its not available in client?

I added the boolean config to grunt and it generated sourcemaps but chrome isnt loading it and im still seeing ugly code. So need to see whats going on.

**Comment by deepu105** [comment]
@ngasull let me know if you got it working in either grunt or gulp

**Comment by ngasull** [comment]
sure @deepu105 ! My point was we can actually add source maps manually to source code in browsers. However I agree it's more convenient to have them directly loaded ;-)

**Comment by erikkemperman** [comment]
From earlier experience with sourcemaps: I used to get the `sourceRoot` wrong... It is relative to the `.map` file; which is (usually) the same folder as the minified output.

For gulp: see [this](https://github.com/floridoo/gulp-sourcemaps) which is what various other sourcemap-aware plugins use.

Would love to see this working!

**Comment by deepu105** [comment]
@erikkemperman have you got this working? Im trying but chrome doesnt seem to load it

**Comment by erikkemperman** [comment]
@deepu105 Not in a jhipster project, no. I'm quite new around here... But in other projects it works like a charm, once you get some gotchas out of the way, one of which is that this sourceRoot option (well, it was to me).

What you want to do is check if the closing comment in the minified file (js/css) correctly points to the .map, and then in the map if its reference correctly points to the original.

**Comment by jdubois** [comment]
When this is done, we should also consider removing all "dev" files from the production build. This will of course be another discussion.

**Comment by deepu105** [comment]
@erikkemperman can you look at the grunt or gulp file generated and see if you can get it working?

**Comment by erikkemperman** [comment]
@deepu I might have some time tonight.

**Comment by deepu105** [comment]
yes plz any help is appreciated

Thanks & Regards,
Deepu

**Comment by erikkemperman** [comment]
@deepu105 Oh dear, I haven't done any sourcemaps stuff in the context of `usemin` -- looks like that might complicate things compared to what I know. I'll give it a try but can't promise anything...

**Comment by erikkemperman** [comment]
@deepu105 I haven't had a lot of time -- and won't for the next couple days, unfortunately -- but I figured I'd report that `usemin` does indeed complicate things, relative to what I know about sourcemaps. It looks like it screws up the `file.base` property somehow, but will need to dig into that further.

**Comment by ngasull** [comment]
@deepu105 @erikkemperman finally had some time tonight to check this out :D I could make sourcemaps working with `gulp-sourcemaps`, see the PR https://github.com/jhipster/generator-jhipster/pull/2742

Important notes for you @deepu105 to confirm:
* I made the sourcemaps be generated in the same folder as the JS output
* I disabled uglify's mangling in order to preserve variable names, therefore the JS takes a little more space (from 43kB to 56kB in a fresh project). Sourcemaps don't support mapping variable names and debugging with mangled variables is awful.

**Comment by deepu105** [comment]
@ngasull the mangled variable issue might be a chrome issue https://code.google.com/p/chromium/issues/detail?id=327092

I think the generated sourcemaps will have actual variable name mapping as well

btw, i found this as well https://github.com/floridoo/gulp-sourcemaps/issues/168

**Comment by ngasull** [comment]
@deepu105 this is a very interesting point! However is it a good idea to force users use Firefox to debug production? I think Chrome DevTools are way more efficient for debugging than Firefox's (now except for variable names mapping ;) ) and maybe we should wait until the feature is implemented

**Comment by deepu105** [comment]
Ya you are right we could live with few extra kb for sometime. We should
remember to remove this when chrome fixes this

**Comment by erikkemperman** [comment]
@ngasull @deepu105 
I think we might have different understanding of what sourcemaps are supposed to do here...

From my point of view, the merged patch does not do what I hoped it would. It generates maps, but the references from within the map to the original sources doesn't work.

For instance, the `app-xxxxx.js.map` contains an array of sources, such as `src/main/webapp/app/app.module.js` and many others. The browser then tries to combine these with the listed `sourceRoot`, which currently gets the default value `/source/`. So it wants therefore to get the original source from `http://[host:port]/source/src/main/webapp/app/app.module.js`, which will fail.

The reason it appears to be more or less working, is that the mangle option was set to false. This should not be necessary with a correctly set up sourcemap configuration -- and actually almost completely defeats the purpose of minification altogether!

The linked issue about being able to enter original variable names in the console on a production build is a separate issue, it seems to me. All we want from sourcemaps here is that it accurately maps back line numbers and column indices, so that stacktraces remain meaningful. I would argue that if we are going to interact with the console in this way, that's what the dev build is for.

I hope this makes sense, apologies if I am misunderstanding your efforts here.

**Comment by erikkemperman** [comment]
@ngasull @deepu105
Sorry, in the spirit of being constructive, I should mention that I am working on a PR that would address this :-) But I really have to get some sleep now and will have to get back to you on this tomorrow.

**Comment by deepu105** [comment]
Actually you do make sense, i dont think its necessary to debug on a prod build, if we get correct stack trace and line numbers thats good enough i guess, debugging should be done on dev build anyway. So if you can get stacktrace part and line numbers working with mangling plz do a PR and @ngasull if you feel otherwise plz feel free to comment.

Ill keep this issue opened untill we have a decision

**Comment by deepu105** [comment]
Btw this is not required for grunt anymore https://github.com/jhipster/generator-jhipster/issues/2749

**Comment by erikkemperman** [comment]
> Btw this is not required for grunt anymore #2749

That's good, from my selfish point of view -- I would have had no idea how to do it for grunt, and can not justify spending the bosses time on it as we prefer gulp :-)

**Comment by erikkemperman** [comment]
@deepu105 I'm working on the sourcemaps now, but I am a bit confused by the `.tmp` directory. What is its purpose, exactly, in the context of a gulp build? It kinda looks like an artefact of porting a Gruntfile to gulpfile but since I'm new around here I thought I'd better check.

**Comment by ngasull** [comment]
> debugging should be done on dev build anyway

@deepu105 I agree, that was my initial point, but now we have the feature to offer! ;-)

> The browser then tries to combine these with the listed sourceRoot, which currently gets the default value /source/. So it wants therefore to get the original source from http://[host:port]/source/src/main/webapp/app/app.module.js, which will fail

@erikkemperman Actually, [`sourceRoot` is an optional parameter](https://github.com/mozilla/source-map#new-sourcemapconsumerrawsourcemap): if the browser has no `sourceRoot` provided, it will look relatively to the current source file, which is the main scenario.

> the merged patch does not [...] generate maps, but the references from within the map to the original sources doesn't work

@erikkemperman could you list here the steps you had sourcemaps not working please? I actually have no issue on my side and maybe I missed a common case where sourcemaps would not work.

> @ngasull the mangled variable issue might be a chrome issue https://code.google.com/p/chromium/issues/detail?id=327092

@deepu105 I tried to debug mangled source with Firefox with no more success than Chrome ([see](https://drive.google.com/open?id=0Bwvg-qHvvAIabjFQc3k2d0RHaGc)). I'd really like to know what's the right way to achieve that, if one. In the meantime, for working sourcemaps, I still suggest not to mangle, otherwise the interest is limited.

**Comment by erikkemperman** [comment]
I am having trouble putting into words what I mean, sorry about that.

The confusing thing is that, when you open chrome's dev panel and go to 'Sources', you will probably see something like a "directory" called `/source/src/webapp/app`, with all your "original" javascript files.

Looks good, but the browser is actually only pretending that it can access these files -- it is reconstructing from the maps with embedded contents.

Which is functionally what we want, but in a very inefficient way...

> Actually, sourceRoot is an optional parameter: if the browser has no sourceRoot provided, it will look relatively to the current source file, which is the main scenario.

The `sourceRoot` option of the [gulp-sourcemaps](gulp-sourcemaps plugin) that is used, however, gets a default value of `'/source/'` when undefined (see line 190 in linked script) in case the `includeContent` option is truthy, which it is by default.

If you check the very end of your `dist/app/app-revxxx.js.map`, I suspect you will find it there, something like `"sourceRoot":"/source/"`?

In any case, `includeContent` is not ideal, it seems to me -- the original un-uglified source is already packaged into in our war, so there should be no need to duplicate it by embedding it into the maps.

Combined with the disabling of `mangle`, which I also maintain should be unnecessary, this makes quite a bit of difference in size:
 
```sh
$ # ---- current master gulpfile

$ gulp build
$ ls -hl src/main/webapp/dist/app/*.js
-rw-r--r--  1 erik  staff    48K Feb  1 23:26 src/main/webapp/dist/app/app-4ae76ddafe.js
-rw-r--r--  1 erik  staff   758K Feb  1 23:26 src/main/webapp/dist/app/vendor-889c1a1094.js
$ ls -hl src/main/webapp/dist/app/*.js.map
-rw-r--r--  1 erik  staff   134K Feb  1 23:26 src/main/webapp/dist/app/app-4ae76ddafe.js.map
-rw-r--r--  1 erik  staff   4.8M Feb  1 23:26 src/main/webapp/dist/app/vendor-889c1a1094.js.map

$ # --- uglify with { mangle: true }, sourcemaps.write with { includeContents: false }
$ gulp build
...
$ ls -hl src/main/webapp/dist/app/*.js
-rw-r--r--  1 erik  staff    37K Feb  1 23:31 src/main/webapp/dist/app/app-d879378a3d.js
-rw-r--r--  1 erik  staff   493K Feb  1 23:31 src/main/webapp/dist/app/vendor-ace6d0291d.js
$ ls -hl src/main/webapp/dist/app/*.js.map
-rw-r--r--  1 erik  staff    43K Feb  1 23:31 src/main/webapp/dist/app/app-d879378a3d.js.map
-rw-r--r--  1 erik  staff   678K Feb  1 23:31 src/main/webapp/dist/app/vendor-ace6d0291d.js.map
```

But now we need to link, accurately, to the un-uglified source files, by fixing the combination of the various `"sources":[...]` in the beginning of the `.js.map` file and the `sourceRoot` property at the end.

Unfortunately the usual way of doing this, which is to set `file.base` on the vinyl object, doesn't work. Something about `usemin` seems to be messing with that property, but I haven't figured it out yet.

Again, sorry I'm not able to explain myself properly... :-)

**Comment by deepu105** [comment]
Yes for gulp its not required you can rewrite that

**Comment by deepu105** [comment]
@ngasull @erikkemperman Im not a gulp expert I just started learning it a month back since it was awesome, so plz do what you think is better than the current setup. And ya 4.8MB .map file seems scary

**Comment by ngasull** [comment]
> I am having trouble putting into words what I mean, sorry about that

No problem @erikkemperman, I will try to sum our discussion up :-) (please tell me if I misunderstood)

There are 2 ways of generating source maps:

1. By only mapping symbols to the original source files (traditional process)
2. By inlining source files contents into the `.map` file itself

The advantage of method 1. is that it feels more natural, by downloading the original sources from internet: first, the browser will download the map located at the place commented in the output bundle, then it will find the map and will see a `sourceRoot` attribute which is a web url. Finally it will do the mappings by downloading the original sources relatively to this `sourceRoot`.

Method 2. doesn't rely on `sourceRoot` at all. Instead, it consists in bundling the mappings + contents directly in source map's `sourcesContent`. That explains why the source map is way bigger in this format this way: it contains all the bundle's original sources *(NB: `.map` file is only downloaded while debugging)*

For me the advantages of method 2. over the taditional are that:

* There is no mess dealing with `sourceRoot` which can become confusing. Instead, handling a single `.map` file is way more convinient and maintainable
* A source map will always map to the right contents. If a `sourceRoot` points to outdated sources, this could be extremely confusing while attempting to debug.
* There is no need to copy and expose all the source files tree to the internet, which lowers the risk to accidentally copy private files into a public root.

@erikkemperman @deepu105 This is only my point of view, please feel free to give us yours!

**Comment by ngasull** [comment]
> @ngasull @erikkemperman Im not a gulp expert I just started learning it a month back since it was awesome, so plz do what you think is better than the current setup.

@deepu105 For gulp in general, I would simply recomment not using `usemin` which ties HTML to all the assets and reduces flexibility. I think this could be a future improvement to replace it by traditional asset generation, but this isn't a priority according to me.

We could also talk about using webpack whom puropose is to bundle webapps with assets, plus incredible features like hot JS code reloading without page refresh (to be investigate in JHipster's stack)

**Comment by deepu105** [comment]
@ngasull we just dropped grunt to move to gulp thats a huge step for us
(majority of our community is from java) so webpack will take time as its
too drastic to switch. Btw im exploring webpack for my [jhipster-react](
https://github.com/hipster-labs/generator-jhipster-react) module

Im ok with either options you specified as long us below requirements are
met.
1. Need to keep minified file size low
2. If possible to achieve mangling that's a priority
3. We dont need source debugging ability we just need proper stack trace so
that we can debug the line in dev environment
4. This shouldn't add any overhead to normal prod users

**Comment by erikkemperman** [comment]
@ngasull Thanks a lot, that's a pretty accurate and concise description of the situation. Very helpful.

So yeah, maybe I'm a bit old-fashioned but obviously I was advocating the "traditional" method, mostly because I'm trying to keep my war file skinny.

> There is no mess dealing with sourceRoot which can become confusing. Instead, handling a single .map file is way more convinient and maintainable
True, it's kind of tricky to get it right, but on the other hand this would all be set up by generator-jhipster and end users shouldn't notice it.

> A source map will always map to the right contents. If a sourceRoot points to outdated sources, this could be extremely confusing while attempting to debug.
Maybe I misunderstand, but it seems to me that in a deployed production build -- which to my mind is what we're trying to address here -- there should be basically zero potential for outdated sources? How do you see that going wrong?

> There is no need to copy and expose all the source files tree to the internet, which lowers the risk to accidentally copy private files into a public root.
I suppose this is a matter of opinion, but I would say that it is not jhipster's job to protect people from themselves in this way? Everything you put in `webapp` should be considered public.

I completely agree that `usemin` is a bit awkward in combination with gulp. Perhaps this is something that could be reconsidered / refactored when gulp 4 finally sees the light and all these things have to be adapted anyway :-)

**Comment by deepu105** [comment]
@erikkemperman i would also prefer the traditional approach more so if you can get that working +1 from me

**Comment by ngasull** [comment]
@deepu105 @erikkemperman I still don't exactly get what the benefits of traditional approach are (and would like to know!) but I respect your point of view and will try to give it a shot when I get some spare time.

> 1/ Need to keep minified file size low
> 4/ This shouldn't add any overhead to normal prod users

Note that inlining sources in the `.map` file doesn't take more space than having a copy of web sources directly in the war, maybe the opposite because we could compress it in the future. No overhead in any case since normal users don't open dev tools.

> 3/ We dont need source debugging ability we just need proper stack trace so
that we can debug the line in dev environment

I'm afraid this would only be possible with source maps. And having non-mangled/de-mangled variables would be really useful to avoid errors of the type `Cannot read property t of c (undefined)`

>  in a deployed production build [...] there should be basically zero potential for outdated sources?

@erikkemperman actually there could be a risk if a deploy happens while the webapp is open, and that the debug tools are open after/during the deploy. Chances are very low though, but the result would be ultra-confusing. As I tend to be perfectionist, I don't like to risk this kind of chances ^^

Gonna have one more look into de-mangling asap.

**Comment by erikkemperman** [comment]
@ngasull 
It doesn't take more space than a copy of web sources -- but it does take more space than __no copy__ of the web sources. Notice that the original source files are always packaged into the war, regardless of profile. My plan was to link back to those from the sourcemaps.

About the deployment scenario, if the sources change, then the `rev` should generate a different hash, and so even in the case you describe I believe it will be all right? Or am I not understanding your example properly?

**Comment by ngasull** [comment]
@erikkemperman I doubt that sources are currently packaged in the war on purpose. They are not source-mappable as-is anyway.

I though that we were looking for the best sourcemaps solution here, but if current topic becomes shrinking the war, I suggest to have a look at its contents:

```
156K   ./i18n
44M    ./WEB-INF
28K	   ./swagger-ui
216K   ./assets
616K   ./scripts
4,0K   ./META-INF
24M    ./bower_components
8,2M   ./dist
76M	   . (all)
```

Both `scripts` and `bower_components` contain front-end resources. Because `bower_components` contain lots of unneeded resources, the war gains 50% in size. We could find some smart (or not) way to filter only the resources that are used by the app, move them smartly along with `scripts` in a public root without breaking source mapping so we could debug using `sourceRoot`.

Or: we could simply remove `scripts` and `bower_components` from the war, use inline source maps and save 1/3 of current output size \o/

Don't you think that we could avoid a lot of trouble this way?

**Comment by gmarziou** [comment]
bower_components should not be packaged as-is, maybe we could extract only what is required using [main-bower-files](https://github.com/ck86/main-bower-files) but I guess it should be tracked a new issue with other PR.

**Comment by erikkemperman** [comment]
It seemed intentional to me, to have bower_components under webapp and not strip any of it from the war..? But of course you're both right, we only really need the files referenced (directly or indirectly) in index.html after wiredep.

And actually, now that there's only gulp, the setup with wiredep/usemin feels awkward. Maybe use gulp-inject and friends (like main-bower-files)?

Anyway, as long as there's little or no duplication in the war, and there are informative stack traces etc, embedding in maps would no longer be an issue for me.

**Comment by ngasull** [comment]
I wrote my last post both nervous and in a hurry, I have been imprecise on some points and I'm sorry for that.

`bower_components` and `scripts` probably are in the war not to confuse the users. Imagine this scenario: user adds bootstrap via bower for its cool gyphicons. Result: no gyphicons in production, because they rely on font files which are in `bower_components/bootstrap`. Other case if he create an asynchronous `.js` in `scripts`: he's like to load it dynamically after the webapp loaded, but then same, if we directly remove `scripts`, they won't have the fil probablye.

@gmarziou I think `main-bower-files` would not solve the first scenario above automatically/without manual configuration. I'll think about a way to keep only the files actually used by all the sources, including bower assets. I know this is possible with webpack, I'll see if there is some way with gulp too :) I tell you when I know more.

**Comment by ngasull** [comment]
Back on source maps: I've managed to use traditional mapping :) (without inline content) but it as expected it doesn't help with mangled variables :( (no debug variable names or stack traces neither in Chrome or Firefox)

**Comment by deepu105** [comment]
@ngasull @erikkemperman both of you have some good points, from JHipster point of view below would our concerns and needs in order of priority, some of below should be tracked as new issues

1. Prod should be as optimized as possible (so if there is anyway to achieve mangling with a usable stack trace that should be highest priority, we need not worry about having source in public, you shouldnt be writing sensitive content in JS anyway, or source becoming out of date etc, these should not happen if build works properly)
2. currently prod stack trace are literally un usable, so we need at least proper line number and meaningfull trace
3. if we can find a way to package only required bower files we should do it, i think we need not worry about below

> bower_components and scripts probably are in the war not to confuse the users. Imagine this scenario: user adds bootstrap via bower for its cool gyphicons. Result: no gyphicons in production, because they rely on font files which are in bower_components/bootstrap. Other case if he create an asynchronous .js in scripts: he's like to load it dynamically after the webapp loaded, but then same, if we directly remove scripts, they won't have the fil probablye.

if user adds new bower component with `--save` wiredep should take care of it, if user wants to do async stuff s/he needs to handle adding them to package as well, we cannot support every use case, our idea is to support most wideley used use case

4. if it can be achived by not adding inline maps that should be better as we already have source in the war
5. if you guys think `use-min` is a blocker and have a way to do the same stuff without `use-min` plz go ahead as long as current behavior is achieved its fine
6. we could explore using `includeSource`, `gulp-inject` kind of plugins instead of wiredep if needed, this could help to remove [some code](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/index.js#L470) from main generator as well, angular-fullstack does this way

7. we can also explore some parallel, sequence stuff to increase speed

**Comment by erikkemperman** [comment]
@ngasull @deepu105
I have non-embedded source maps more or less working, including useful stack trace, [here](https://github.com/erikkemperman/generator-jhipster/tree/feature-sourcemaps)...

But there's a few things I'm not happy with. The css pipe and js pipe look basically the same but need different sourceRoot for some reason. I couldn't figure out why yet, maybe you see it?

Also, because of current directory structure, I had to add a servlet filter. Works, but adds a little overhead to all other requests as well.

**Comment by jdubois** [comment]
I've looked at your code @erikkemperman and it looks quite good to me:

- Yes there is [this side effect](https://github.com/erikkemperman/generator-jhipster/commit/2f6d7877b5be797e3769336fabaab47a522bee68#commitcomment-15879533) but I'm not sure of the impact
- For the servlet filter: in fact you use the current filter, you just widen the way it is being used to include the source map

**Comment by erikkemperman** [comment]
@jdubois 
Thanks!

That side-effect means the browser will not only get the minified CSS but also the entire map file, regardless of whether or not the brower's debug panel is open. Not good...

I haven't been able to figure out where this quirk is originating. But rather than spend a lot of time tracking it down, I figured it might be better spent moving forward to a setup with `gulp-inject` and friends. With any luck this strange side-effect doesn't happen then.

The filter is not really a big problem, I agree, but I wanted to point out that it is only necessary because `dist` is nested as a child within the web source, rather than a sibling to it.

**Comment by deepu105** [comment]
Yes download of that map file for all is not a good thing, i would rather
have current sourcemap behaviour with mangle disabled. If you can get the
gulp-inject to work that would be a better solution i guess.

**Comment by erikkemperman** [comment]
Agreed, that's why I haven't submitted this as a PR... Unfortunately I am kind of busy with other stuff now. Stay tuned :-)

**Comment by deepu105** [comment]
closing this as its done to an extend improvement discussion will continue in #2869 and #2889
