### ISSUE TITLE
Postgis and hibernate spatial support

### ISSUE THREAD

**Issue by superandrew** [jhipster/generator-jhipster#2285]
Hello, I am trying to integrate postgis and hibernate spatial to work with jhipster. Is it supposed to work? Right now I have problems with the jdbc connections, and `setUrl` method in DatabaseConfiguration.java.

Is this even supposed to work anyway? Just to know if there is any working example somewhere or if this is a known bug with hikari and `org.hibernate.spatial.dialect.postgis.PostgisDialect`

**Comment by deepu105** [comment]
We dont support postgis directly so you can ask this in SO as you will have better chance of getting answer there. Tag it with Jhipster

**Comment by mallim** [comment]
You are talking about two issues here. I'm not sure about the postgis. But you will be getting hikari related error if you used a similar configuration like below even as of 2.23.0 (the latest release) :

````
    datasource:
        url: jdbc:postgresql://ip_address:5432/databasename
        username: username
        password: password
````

In order to resolve the Hikari error, I modified DatabaseConfiguration to support an additional configuration as follows:

````
jhipster:
    datasource: # JHipster-specific configuration, in addition to the standard spring.datasource properties
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
````
