### ISSUE TITLE
Fonts extensions now allowed by default

### ISSUE THREAD

**Issue by yelhouti** [jhipster/generator-jhipster#22855]
The new Security Config block everything by default which is great.
However, some extensions are still missing.

I think there should be a better way for allowing static resources, by securing only requests that go to the controller and redirect anything with an extension that is not /api and /management to fetch a resource.

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mraible** [comment]
I like how it is now because you have to be intentional about adding new extensions. I don't think changing one line is too difficult:

https://github.com/jhipster/generator-jhipster/blob/main/generators/server/templates/src/main/java/package/config/SecurityConfiguration_imperative.java.ejs#L171

FWIW, I'll be going on vacation tomorrow for a month. I'd be happy to review something when I get back.

**Comment by dinu0000** [comment]
@mraible could you please take a look
