### ISSUE TITLE
Generated html column for entity fields with many-to-many relationship is empty

### ISSUE THREAD

**Issue by mhicauber** [jhipster/generator-jhipster#2290]
Hi

First of all kudos to the team for this awesome tool.

When defining an entity A with a many-to-many relationship on another entity B, the generated html table for the A entity is missing the column for this particular relationship. Well, there's a `<th></th>`  column generated to be precise.

See here : https://github.com/jhipster/jhipster-sample-app/blob/3f6135171b90ba6b2709536b62206e910b3184eb/src/main/webapp/scripts/app/entities/operation/operations.html#L23

Is it expected not to generate, let's say, a comma-separated list to show other entity values ?

In case this is just a new feature, I'll try to take this PR. In case this is expected, why ?

Thank you.

**Comment by jdubois** [comment]
That last <th> is because we have the buttons in the <td> afterwards, not for the many-to-many items.

This is basically on purpose, as by default they are lazy-loaded by Hibernate (have a look at the generated Spring Data JPA repository, there is a specific query to get them eager loaded, that can be handy!).

So yes this is on purpose: we are only generating a simple CRUD screen, and as those are lazy loaded by default we don't bother to get them.

This could be discussed, but this isn't a bug, and I'm not sure we should go to far on this screen as we can't know what people will want to do in the end.

**Comment by mhicauber** [comment]
Agree; that's really specific to my case :-)

-- 

*Mon ordinateur fonctionne à l'énergie 100% verte, renouvelable, fournie
par ENERCOOP*
http://www.enercoop.fr/

2015-11-05 23:22 GMT+01:00 Julien Dubois <notifications@github.com>:
