### ISSUE TITLE
H2 console is not working.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster#23109]
##### **Overview of the issue**

H2 console fails to load.

##### **Reproduce the error**

Generate a project with h2.
Ex: `jhipster --defaults`

##### **Suggest a Fix**

`h2-console` must be added to SpaFilter, but it's not enough to fix the problem.

##### **JHipster Version(s)**

main

##### **Browsers and Operating System**

- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by hide212131** [comment]
Upon analysis, it seems the issue is that the 'h2-console' path is mistakenly recognized as an incorrect contextPath. The solution appears to involve using AntPathRequestMatcher.
https://github.com/spring-projects/spring-security/issues/12546#issuecomment-1382891839
I've tested it, and it worked fine. If no one else is already working on a PR, I'll go ahead and create one.

**Comment by hide212131** [comment]
bounty claimd https://opencollective.com/generator-jhipster/expenses/178944
