### ISSUE TITLE
[Feature request] cookieconsent2 plugin to the EU Cookie Law

### ISSUE THREAD

**Issue by dalbelap** [jhipster/generator-jhipster#2320]
Hi,

Perhaps it might be interesting to include alert users about the use of cookies on the jhipster website according to the EU Cookie Law.

I just added [cookieconsent2](https://github.com/silktide/cookieconsent2) plugin in this branch: https://github.com/dalbelap/generator-jhipster/tree/feature-cookieconsent2

The plugin was configures below the google javascript code:
```javascript
<!-- Begin Cookie Consent plugin -->
<script>
       var pagecookiepolicy = "/#/cookiepolicy";
       var message = "This website uses cookies to ensure you get the best experience on our website";
       var gotit = "Got it!";
       var learnMore = "More info";
       window.cookieconsent_options = {"message": message,
            "dismiss": gotit, "learnMore": learnMore, "link": pagecookiepolicy, "theme": "light-floating"};
</script>
<!-- End Cookie Consent plugin -->
```

Also it was created a new page in [scripts/app/cookiepolicy/](https://github.com/dalbelap/generator-jhipster/tree/feature-cookieconsent2/app/templates/src/main/webapp/scripts/app/cookiepolicy) and [cookiepolicy.json](https://github.com/dalbelap/generator-jhipster/blob/feature-cookieconsent2/app/templates/src/main/webapp/i18n/en/cookiepolicy.json) for the i18n in all languages (only English, French, Galician and Spanish translated).

**Comment by gzsombor** [comment]
Good idea !

**Comment by deepu105** [comment]
does it have an angular js version? or atleast a bower managed version? else it will be better to do this as a simple popover using ui-bootstrap we already have

**Comment by atomfrede** [comment]
@dalbelap  Is this correct, that the message (that is not on the seperate page) is not translated?

**Comment by dalbelap** [comment]
@atomfrede yes, the javascript code inside index.html is not translated.
@deepu105 It could do with ui-angular [boostrap modal](https://angular-ui.github.io/bootstrap/#/modal)

**Comment by deepu105** [comment]
@dalbelap my only concerns are below if those are addressed im ok with the plugin
1. it needs to be bower manageable
2. it should be bootstrap compatible
3. it should be atleast compatible with angular without too much tweaks
4. it should be i18n supported or compatible with angular-translate

From your sample it looks easy to write a wrapper directive to make it work with angular translate, so that leaves point 1 and 2 from above

**Comment by deepu105** [comment]
@dalbelap since this is just addition to index JS and may not be worth adding as a new option in generator(I dont think we can have it on by default as everyone might not want it) why dont you submit it as a [tip](http://jhipster.github.io/tips.html) in our [documentation project](https://github.com/jhipster/jhipster.github.io)

**Comment by dalbelap** [comment]
@deepu105 you are right, it's better explain this as a tip. I close this feature and will create a PR for the documentation project in the next days. Thanks a lot!

**Comment by cicoub13** [comment]
Any documentation or integration in jHipster ? I couldn't find it.

**Comment by deepu105** [comment]
Nothing added yet. You can add a tip or module if required

**Comment by atomfrede** [comment]
I looks like the perfect thing for a module. I'll see if I create one.
