### ISSUE TITLE
French is auto-selected when choosing additional languages

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#24125]
##### **Overview of the issue**

I was updating one of my tutorials this evening, and I noticed that French is pre-selected when you're prompted for additional languages.

<img width="1682" alt="Screenshot 2023-11-06 at 9 36 02 PM" src="https://github.com/jhipster/generator-jhipster/assets/17892/d926bf6d-14a2-4228-a5a0-da4acfba1e2d">

##### **Motivation for or Use Case**

In previous versions, we did not pre-select any additional languages. 

##### **Reproduce the error**

Create a new app with v8 and the `jhipster` command.

##### **JHipster Version(s)**

8.0.0

**Comment by mraible** [comment]
I just noticed that even if I de-select French and select Spanish, French is still selected and written to `.yo-rc.json`. 

```json
"languages": ["en", "fr", "es"],
```

Is this an Easter Egg from @jdubois ?! 😅

**Comment by jdubois** [comment]
Ah ah no I have no idea why this happens! Then as I'm testing with French, it probably explains why I haven't noticed it.

**Comment by mraible** [comment]
I'd like to see this fixed before 8.0.1 because it seems like a blocker for my JHipster 8 blog tutorial and screencast.

I searched for a .yo-rc.json in my home directory and in the parent directory but didn't find anything. Can anyone else reproduce?

**Comment by mshima** [comment]
The bug is that we are adding a non-selected language.
Bringing 'en' and 'fr' as additional languages is currently the correct behavior unless we decide to don't add any additional language if i18n is enabled.
https://github.com/jhipster/generator-jhipster/blob/80b511d76321beb209e6f4316aa5dce663ac37d9/jdl/jhipster/default-application-options.ts#L168
Translation enabled with only one language is quite useless.
