### ISSUE TITLE
Allow editing/deleting when viewing a row.

### ISSUE THREAD

**Issue by RomainGailleton** [jhipster/generator-jhipster#2429]
When viewing a particular row from an entity the only option is to go back to the list of rows in the entity.

![image](https://cloud.githubusercontent.com/assets/286859/11562865/e5e9232a-99d0-11e5-8b38-eeb9cb867efc.png)

Accessing the edit and delete options right from this view would save navigation time.

**Comment by deepu105** [comment]
We already have routes for that its fairly easy to add buttons for that

**Comment by jdubois** [comment]
This view is only for "viewing" the entity, if you want to edit it there is the edit dialog screen for that.

I understand the UI/UX might not be good for everyone, but this is just the default pages, then you need to modify them and code according to your needs: that's why there is "simple view" and an "editable view", as those are the two most common use cases, and they should help you to get started.

**Comment by cbornet** [comment]
I think the idea is to have a button to open the edit view from the simple view
