### ISSUE TITLE
Remove docker-compose feature

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#2509]
Hello,

With the new [JHipster marketplace](https://jhipster.github.io/modules/marketplace.html) and the module [generator-jhipster-docker](https://github.com/pascalgrimaud/generator-jhipster-docker), I would like
to remove the docker-compose files, generated by JHipster. I don't know if a lot of people use this feature, but you can go on by using the sub module.

In my opinion, the use of Docker is **optional**, so it should be separated from the generator-jhipster :
* mandatory => generator-jhipster
* optional => module

As Travis Build used these docker-compose files, I will recode the Travis build for running directly docker to start container, instead of using docker-compose.

What do you think ?

**Comment by jdubois** [comment]
Not sure if it's not "mandatory".
For development, the more we use external services (like MySQL and Elasticsearch), the more it will be useful.

**Comment by atomfrede** [comment]
Same for me. I use only docker compose during development. A friend of mine started a project based on jhipster and I told her to use docker compose (she didn't know docker before) and is absolutely flashed by the ease of use, so I would consider docker compose support somehow mandatory. 
At least all I know will use docker compose. 

But the idea to but everything not mandatory (or core feature) sounds good to me.

**Comment by pascalgrimaud** [comment]
Thanks for feedback and both, you're right :+1: 

I'll update the current docker-compose :musical_note:

**Comment by Panthro** [comment]
quick comment on this:

The same thing happened to me, I'm using jhipster and docker for quite a while, when I referred jhipster to a friend he had troubles because his company has strict policies about installing new software and they have to use VMs for a lot of things.

When I told him to use docker he was AMAZED and it was really nice.

Also, to another friend that I referred jhipster, when he asked me what were those `docker` related files and I explained, again, amazed and use docker every day. :feelsgood:
