### ISSUE TITLE
Add tip for idea documentation

### ISSUE THREAD

**Issue by mihaisimi** [jhipster/generator-jhipster#2520]
I suggest adding a tip in the Idea configuration section.

If we change the logback-spring.xml pattern to this:
<pattern>%highlight(%-5level) %d{yyyy-MM-dd'T'HH:mm:ss.SSS} %yellow([%thread]) %blue(%logger{36}\(%class{0}.java:%line\)) %msg%n</pattern>

We get clickable class names in Idea 14/15 ( per http://stackoverflow.com/questions/7930844/is-it-possible-to-have-clickable-class-names-in-console-output-in-intellij/29881239#29881239)
<img width="1449" alt="screenshot 2015-12-22 18 28 46" src="https://cloud.githubusercontent.com/assets/736493/11960202/226fc8fe-a8da-11e5-85a2-c8806636f869.png">

**Comment by Panthro** [comment]
The suggestion is to add what where? It's not clear for me.

Can you share your logback-spring.xml?

**Comment by mihaisimi** [comment]
For easier debugging in IDEA >=14 the CONSOLE appender in the logback-spring.xml could be changed into something like this (provides clickable class names, color coding and threads):

  <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <charset>utf-8</charset>
            
            <pattern>%highlight(%-5level) %d{yyyy-MM-dd'T'HH:mm:ss.SSS} %yellow([%thread]) %blue(%logger{36}\(%class{0}.java:%line\)) %msg%n</pattern>
        </encoder>
    </appender>

Sorry for the lack of details in my original post.

**Comment by gmarziou** [comment]
With this you get only clickable links for your own classes, I prefer adding %caller{1} at the end of the pattern to be able to click on any class

**Comment by jdubois** [comment]
Yes you can add the tip to our website (you need to do a PR to https://github.com/jhipster/jhipster.github.io ), it's nice for IDEA users.

Of course we can't put this in the main generator, as we don't have anything specific for an IDE (at least that's the current decision, as otherwise we would have too many files generated, for all IDEs...).

For the main project, I'd also like to stick to the "standard" Spring Boot logs as there are tools now that start to support it.
