### ISSUE TITLE
Moving from Bootstrap to Angular Material 

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#2525]
Suggest we move from bootstrap to angular material for UI components. If okay let me do a PR for that.

**Comment by mihaisimi** [comment]
+1 (if the user gets a choice between bootstrap and angular material).

**Comment by gmarziou** [comment]
Angular Material is a big change over Bootstrap as it's much more than a CSS framework.
Personally, I like how it looks and how it encourages more semantic markup.

Markup is so different that supporting both would mean 2 templates per view and it's not sure that there won't be any impact in controllers. I don't think JHipster team can support both but I'm wondering whether it could be done as a module.

**Comment by jdubois** [comment]
- clearly we can't support both, it's too much work
- I have many users and customers who chose JHipster because of Bootstrap, which is by far the most popular CSS framework

So for me this doesn't look something that could (or should) be done.

**Comment by sendilkumarn** [comment]
@gmarziou obviously thats my point angular material just released their 1.0 and they look great and different.

In case of bootstrap, if they move to bootstrap4 then we have to again change a lot.  Just a suggestion, if we can use angular material we can remove few components because things like datepicker comes in built and I think code will be much cleaner.

**Comment by gzsombor** [comment]
We had bad experience with angular-material in a couple of months ago, in a project,which I'm working on,so we had remove that components. The problem is they are targeting chrome,so it had lot's of problem on firefox/safari.Especially on iPhone. Probably they will fix it in the future.
 Maybe as a separate generator, there could be a material-skin, but I guess, it would be a huge job

**Comment by Panthro** [comment]
+1 for keeping bootstrap.

**Comment by deepu105** [comment]
I would also keep bootstrap as angular material would mean all new
templates, it could be a module which will replace our generated templates.
Sendil, ill be working on something similar for audit, so let me discuss
this with you when I'm back, i have an idea on how to do this as a module
so that you can do and own it as well.

**Comment by roblight** [comment]
Just to help others that are wanting Material Design (albeit not Angular Material), an option is to use:

http://fezvrasta.github.io/bootstrap-material-design/

See Matt Raible's talk for now to setup it up (very easy):

https://www.youtube.com/watch?feature=player_detailpage&v=baVOGuFIe9M#t=2748

**Comment by arbach** [comment]
@roblight  this will not work with angular 4, and angular 1.6 requires  earlier version of node.
