### ISSUE TITLE
Expose generator-jhipster/test/support folder for blueprints

### ISSUE THREAD

**Issue by dwarakaprasad** [jhipster/generator-jhipster#25384]
##### **Overview of the feature request**
I am creating a blueprint that will extend angular and server generator. It will be really helpful in unit testing if blueprints have access to generator-jhipster/test/**

jhipster's generator spec for example [angular](https://github.com/jhipster/generator-jhipster/blob/9df8549899c800df34a93ec4357a7fdcc86af570/generators/angular/generator.spec.ts#L7) builds config samples with possible combinations using this test support. This makes writing unit tests extremely fast and super simple (thanks to @mshima), but unfortunately these test supports are not exposed.

Currently all possible combinations will have to be created manually which seems redundant.  

##### **Related issues or PR**

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by mshima** [comment]
The main reason for the matrix at main generator is to test files snapshots during refactoring.
Blueprints have a much smaller feature matrix.
If prettier/eslint is enabled during tests (not enabled at main generator due to slowness) you could check if the files are valid.

Feel free to raise a PR moving the matrix from test folder to testing (already exposed) folder.

**Comment by dwarakaprasad** [comment]
@mshima , I did not move the files into testing as that will require a good deal of import refactoring, so left theme as is but exposed them tro /testing.
