### ISSUE TITLE
Use a global NPM repository to speed up the builds

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2542]
As mentioned in https://github.com/jhipster/jhipster-devbox/issues/21 we could use [this tip](https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md) to install NPM packages locally, using the user's rights.

- This would allow us to use NPM the same way we use Maven, with a global repository
- This would speed up builds for both Docker and the devbox

@pascalgrimaud what do you think about this?

**Comment by pascalgrimaud** [comment]
@jdubois : I don't think it's the same subject

This tips seems to be used for :
- users who are not root on the machine
- using `npm install -g <package>` (globally)
This tips will use a personal directory instead of `/usr/lib/node_modules` (for example) which requires to be root to write on this dir

For generating a JHipster project, we use `npm install` locally so npm will :
- read the package.json
- download lib to a new `jhipster/node_modules/`
- the new personnal directory is not used here...

I think this tips will not speed up the build, only allow using `npm install -g` without sudo

**Comment by jdubois** [comment]
OK, my bad!
