### ISSUE TITLE
swagger api ui performance is very slow

### ISSUE THREAD

**Issue by TonyLuo** [jhipster/generator-jhipster#2601]
the swagger api ui takes minutes to show every time, it seems scan the annotation every time when access it. is any configuration can be done to enabled it scan the api annotation once and then cache all api info?

**Comment by gmarziou** [comment]
Please follow [our guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) about submitting a

**Comment by cbornet** [comment]
The scan should only occur once at startup. You activate swagger debug logs to confirm that.

**Comment by deepu105** [comment]
please provide more info next time

**Comment by egiovanni85** [comment]
Hi this method worked form me with jhipster!!! I found it after 2 weeks :-D
The problem is jhipster without mapstruct dto.... 

Dto * with mapstruct   ------ is required
Add this  dependencies    

1-------------------------------------------------------------------------------


<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>2.9.2</version>
</dependency>

2------------------------------------------------------------------------------------


<dependency>
    <groupId>com.github.caspar-chen</groupId>
    <artifactId>swagger-ui-layer</artifactId>
    <version>1.1.3</version>
</dependency>


Update progect and restart!!!
You can find swagger ui at:
http://localhost:xxxx/swagger-ui.html#/
