### ISSUE TITLE
Oauth2 OIDC - claims - BuiltInUserEntity

### ISSUE THREAD

**Issue by ndywicki** [jhipster/generator-jhipster#26152]
Hi,

In the last Jhipster versions v8, I noticed on monolithic applications with the OAuth2 OIDC option, this is the template [AccountResource_skipUserManagement.java.ejs](https://github.com/jhipster/generator-jhipster/blob/197560acdb622d17c875b57002feb6291309a026/generators/server/templates/src/main/java/_package_/web/rest/AccountResource_skipUserManagement.java.ejs) which is used by default (ie. with the `UserVM`: login and authorities)

And no [AccountResource_oauth2.java.ejs](https://github.com/jhipster/generator-jhipster/blob/197560acdb622d17c875b57002feb6291309a026/generators/server/templates/src/main/java/_package_/web/rest/AccountResource_oauth2.java.ejs) which involves the use of `UserService` and in particular all the claims attributes mapped from the token (ie. with `UserDTO`)

By searching in the code I saw that the generation of `AccountResource_oauth2.java.ejs` is conditionned by `generateBuiltInUserEntity` and depend of `syncUserWithIdp` option:

https://github.com/jhipster/generator-jhipster/blob/1e17884d075c1c6d598029de3e38d692e58f565f/generators/bootstrap-application-base/generator.ts#L193

The command-line help states:
`
--sync-user-with-idp Allow relationships with User for oauth2 applications
`

For me it is not very clear: 
When I choose the Oauth2 OIDC option I think I have complete recovery of IDP claims independently of synchronization in database and/or the possibility of creating relationships between Users and other entities.

Is this the behavior that was intended?

Note: The documentation [Command-line options](https://www.jhipster.tech/creating-an-app/#3) is no longer up to date with the new options 😉 

Thanks

**Comment by mraible** [comment]
I don't think anything has changed in JHipster's OAuth/OIDC implementations since v7. I'm not sure I understand your question. Can you please rephrase it?

**Comment by mshima** [comment]
I confirm the bug.
OAuth2 token is not correctly mapped to the spring security authentication without `syncUserWithIdp` option.

This option is required in ionic blueprint:
https://github.com/jhipster/generator-jhipster-ionic/blob/c4c2a30002fe3fd5f2ef6a6f402dc21fc2d0ba04/.blueprint/generate-sample/templates/samples/reactive-oauth2.jdl#L12
Otherwise this test fails:
https://github.com/jhipster/generator-jhipster-ionic/blob/c4c2a30002fe3fd5f2ef6a6f402dc21fc2d0ba04/generators/ionic/resources/oauth2/cypress/e2e/login.cy.ts#L22

**Comment by dwarakaprasad** [comment]
@mshima I couldn't fully understand the bug here, I am willing to contribute to this one. Let me start with what i understand,

1. With this pr #24632, oauth2 option will by default not generate user related code unless one of this is set gnerateUserManagement or syncUserWithIdp or an entity relating to User built in entity.

2. Currently irrespective of the 'syncUserWithIdp' feature, the endpoint to return account exists (pulls data from the IDP and constructs userVM). This should go away if 'syncUserWithIdp' is not requested. 

Also, on the blueprint side, user related code needs to be conditionally generated based on the 'syncUserWithIdp', which is why ionic blueprint started [failing ](https://github.com/jhipster/generator-jhipster-ionic/blob/c4c2a30002fe3fd5f2ef6a6f402dc21fc2d0ba04/generators/ionic/resources/oauth2/cypress/e2e/login.cy.ts#L22)when migrated to v8.4.0. 

I can default the 'syncUserWithIdpP' similar to [nodejs](https://github.com/jhipster/generator-jhipster-nodejs/blob/cadfeccbb9f3deaf9c7dc1c6252aaa73aff7365c/generators/bootstrap-application/generator.js#L27) for now until its implemented. 

Please let me know.

**Comment by mshima** [comment]
@dwarakaprasad
If syncUserWithIdp is true, this `api/account` is used:
https://github.com/jhipster/generator-jhipster/blob/9c885f10d5477dec40d0b3d127f3e2a26e6ea054/generators/server/templates/src/main/java/_package_/web/rest/AccountResource_oauth2.java.ejs#L75-L80


As stated in the issue description UserService does not exists without `syncUserWithIdp` so this other `api/account` is used:
https://github.com/jhipster/generator-jhipster/blob/9c885f10d5477dec40d0b3d127f3e2a26e6ea054/generators/server/templates/src/main/java/_package_/web/rest/AccountResource_skipUserManagement.java.ejs#L119-L125

UserVM has these attributes:
https://github.com/jhipster/generator-jhipster/blob/9c885f10d5477dec40d0b3d127f3e2a26e6ea054/generators/server/templates/src/main/java/_package_/web/rest/AccountResource_skipUserManagement.java.ejs#L158-L161


While User has much more info:
https://github.com/jhipster/generator-jhipster/blob/9c885f10d5477dec40d0b3d127f3e2a26e6ea054/generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/UserService.java.ejs#L1029-L1088

**Comment by ndywicki** [comment]
@mshima This is my point.
By default with OAuth2, only basic claims feed `api/account` response via `UserVM`. 
To have other attributs from IDP (give_name, imageUrl, etc), we need pass the extra `--sync-user-with-idp` parameter option to use the `AccountResource_oauth2.java.ejs` that call `userService.getUserFromAuthentication()` and which of course contain the user sync mechanism. 

I couldn't find in the history if there was a reason not to include `userservice.getUserFromAuthentication()` by default and move the `syncUserWithIdp` condition here:
https://github.com/jhipster/generator-jhipster/blob/9c885f10d5477dec40d0b3d127f3e2a26e6ea054/generators/spring-boot/templates/src/main/java/_package_/_entityPackage_/service/UserService.java.ejs#L1024

This is not really a problem for me, we noticed it because we use a blueprint which takes into account the user's avatar when the IDP is Entra ID (via MS Graph endpoint) and this has changed compared to the version v7 of JHipster (`--skip-user-management`  vs `--sync-user-with-idp`)

**Comment by mshima** [comment]
Entire UserService is implemented for `syncUserWithIdp`.
It checks and saves current User at each page visit.
So IMO:
- `syncUserWithIdp` should be done only once per session.
- Account should be retrieved from authentication token even with `syncUserWithIdp` instead of retrieving from database.
