### ISSUE TITLE
Hibernate dialect misconfigured for cloudfoundry deployment

### ISSUE THREAD

**Issue by lourai** [jhipster/generator-jhipster#2636]
we use with success cloudfroundry from pivotal as deployment plateforme for our projects, but as we use mysql for dev (locally) and elephantSql as database service when deploying, we're getting error :
...
OUT org.postgresql.util.PSQLException: ERROR: LIMIT #,# syntax is not supported
...

The reason is simple : the dialect used and configured in application-dev (or prod) yaml configuration file is MySQL. Using PostgreSQL dialect is working fiel (we didn't use xxxx.domain.util.FixedPostgreSQL82Dialect, but org.hibernate.dialect.PosgreSQLInnoDBDialect). i assume that people who did their jhipster conf direclty with PostgreSQL will not be affected, but i didn't try with other SGBD.

Before uploading (witch is not working when using windows : must use path.sep and avoid *.war in cloudfoundryPush function. Push request incoming) we did simple conf change in application-dev.yml (cause prod not working, other issue incoming :D). in directory use to build the war, repack the war then upload. Dunno how to do this in a clean way, any sought ?

**Comment by jdubois** [comment]
This is an option we have removed a few months ago: it's not really logical to develop on MySQL and deploy on Postgresql....
So if you have selected MySQL on production, but you deploy on Postgresql, that's quite logical don't have the correct dialect.
I'm sorry but this isn't a bug from JHipster, it's an option that we don't provide because that's not a very common requirement.
