### ISSUE TITLE
Jhipster Deployment in Weblogic 

### ISSUE THREAD

**Issue by vikasmadineni** [jhipster/generator-jhipster#2646]
Hi team,

Can u please help me how to deploy jhipster application in weblogic middleware server.

regards,
vikas

**Comment by deepu105** [comment]
@vikasmadineni we do not officially support weblogic, but given that you can generate a war out of a jhipster app its definetely possible to do so, I have deployed to Jboss and have heard about people deploying to other containers as well. Just try to deploy it like any other war

But since we dont not support this officially please take this to stack overflow and tag it with JHipster and the community will sureley help you

**Comment by jdubois** [comment]
As we generate a Spring Boot application, and that those applications are supposed to work on Weblogic, you shouldn't have any issue deploying to Weblogic.
Of course it depends on your version numbers, for that you need to check with your Weblogic documentation and the Spring Boot documentation.
If you have any feedback on those, please don't hesitate to post it here.

**Comment by tvd27285** [comment]
@vikasmadineni
Do you can to deploy jhipster on oracle weblogic 12c?

**Comment by dhoffer** [comment]
I have the same question/issue...how to deploy jhipster war to Weblogic, I'm getting a number of errors in doing so.  My WL version is 12.1.3.0.0.

**Comment by jdubois** [comment]
It depends on your JHipster version, on the options you selected, and on the errors you have!
I'm sorry but just telling you are "getting errors" is not enough.

Anyway, why don't you ask your Weblogic support first?
