### ISSUE TITLE
Painful paginated entity navigation

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#2657]
* **Overview of the issue**
When an entity has "pagination" pagination and you view an item, clicking on "back" sends you to the first page instead of the page you were on before viewing the item

* **Motivation for or Use Case** 
This is really painful when you want to see item details one item by one item of a very long list.

* **JHipster Version(s)** 
2.26.2

* **JHipster configuration, a `.yo-rc.json` file generated in the root folder** 
```json
{
  "generator-jhipster": {
    "baseName": "jhipsterstandard",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "postgresql",
    "searchEngine": "no",
    "useSass": false,
    "buildTool": "maven",
    "frontendBuilder": "grunt",
    "enableTranslation": true,
    "enableSocialSignIn": false,
    "rememberMeKey": "5e77ac8064a0afdbff55ed4240fd6493ffffffff",
    "testFrameworks": [
      "gatling"
    ]
  }
```

* **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory** 
Foo.json
```json
{
    "relationships": [],
    "fields": [
        {
            "fieldId": 1,
            "fieldName": "foo",
            "fieldType": "String"
        }
    ],
    "changelogDate": "20160119161144",
    "dto": "no",
    "service": "no",
    "pagination": "pagination"
}
```
* **Browsers and Operating System** 
Firefox 42, probably all browsers

* **Reproduce the error** 
* Connect to h2 console
* Create some foo items
```sql
INSERT INTO FOO(foo) VALUES ('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo'),('foo');
```
* Go to Entities -> Foo
* Go to page 2
* Select id 22
* Click on "back" --> the item list is on page 1 whereas the user would want to be on page 2

**Comment by PierreBesson** [comment]
I have reproduced your bug. When clicking the "back" button, it actually does a window.history.back() so it has no way to know on which page it was before.
So your bug could be solved by doing a pushState and changing the URL on a page switch (for example : #/foos/2).
It seems that the pager provided by Angular-UI Bootstrap does not change the page URL by itself, but some people have managed to add the feature.
https://github.com/angular-ui/bootstrap/issues/620

However I think we must be careful as there are many use cases where we would not need to keep track of the current page in the URL.
Alternatively there could be other ways to achieve the smart "back" functionality without resorting to the URL.

**Comment by geraldhumphries** [comment]
What about using query parameters in ui-router and transitioning states on page change/sort/etc.?

I have not worked out all the kinks, but here is a working implementation:
https://gist.github.com/geraldhumphries/e1adec511d9fc43ad665

Supports back/forward buttons on the browser.

**Comment by jdubois** [comment]
Yes that looks like a neat solution !

**Comment by geraldhumphries** [comment]
One problem I'm running into is that Bootstrap's pagination directive keeps resetting `page` to 1. This is because it checks the total number of pages and will set the `current` page to the last page if `current > total`. See http://stackoverflow.com/questions/27911740/ui-bootstrap-pagination-resetting-current-page-on-initialization

On state transition, `totalItems` is undefined because the `loadAll` query hasn't resolved. One solution is to load data and set `links`/`totalItems` in the route resolver as suggested by @Vaelyr as good practice in #2271.

What do you think?

**Comment by geraldhumphries** [comment]
I've updated the gist. Everything is working except the sorting icons in the table headers.

https://gist.github.com/geraldhumphries/e1adec511d9fc43ad665

I've added my thoughts on the changes as comments in the code. Let me know how it looks.

**Comment by jdubois** [comment]
If it also fixes #2387 that's definitely a good enhancement!!

**Comment by geraldhumphries** [comment]
I realized that I don't need to move the querying to resolve. 

I did some testing with a simulated 5 second delay (just `Thread.sleep(5000)` in the resource) and have concluded that it's much nicer to load data in the controller instead of resolve *for long requests* so the state loads right away.

Upsides of not using resolve:
* Slightly nicer UX, since the page loads right away and the table is filled once the request is finished. It's way better for long requests. A loading icon should be added to the table for when the promise hasn't resolved.
* With resolve/promises: On success, the handler will have just the data, but the controller also needs the headers. To solve this I had to use transformResponse to add the headers to the data. On fail, the handler will have the whole response. This inconsistency means I had to make another modification to transform response so it won't modify the data on error (httpStatus >= 400). Without using resolve I don't need to use transformResponse (the success callback has data and headers already)

Gist: https://gist.github.com/geraldhumphries/5e0a64a4b718760b8179

Upsides of using resolve:
* Data handling is abstracted away from the controller, so we don't need to handle success/failure there. This leads to much more streamlined controller code.
* If there's an error when transitioning, ui-router will simply not transition and a `stateChangeError` event is thrown. We can set up a handler to handle all stateChangeError events (and do something like `AlertService.error`). Additionally there are other events thrown like stateChangeStart which could be super useful... ex. we show some kind of "loading" icon. See [here.](https://github.com/angular-ui/ui-router/wiki#state-change-events) This could be a great feature!

Gist: https://gist.github.com/geraldhumphries/e1adec511d9fc43ad665

This is basically style [Y080](https://github.com/johnpapa/angular-styleguide#style-y080) vs [Y081](https://github.com/johnpapa/angular-styleguide#style-y081).

**Comment by geraldhumphries** [comment]
More questions:

1. Should I add `pagingParams` to the controller's scope and use it directly, instead of adding each of its attributes individually?
1. Should I separate the `sort` param into `predicate` and `direction` so I don't need to separate them out of the string?

**Comment by deepu105** [comment]
I wouldn't want long requests in resolve without a proper loading page. So
if we are doing it there we need to do proper loading page for the state as
well.

Also is it really the routers responsibility to handle data? Im bit
confused on that

**Comment by geraldhumphries** [comment]
I looked into it, we are already using the angular-loading-bar directive. I thought it was a Chrome feature until now.

It is not necessarily the router's responsibility, no. But it is the purpose of `resolve`. These are two different styles each with upsides and downsides, see johnpapa [Y080](https://github.com/johnpapa/angular-styleguide#style-y080) vs [Y081](https://github.com/johnpapa/angular-styleguide#style-y081). 

Here is an example of handling errors thrown in resolve (in app.js):
```
$rootScope.$on('$stateChangeError', function(event, toState, toParams, fromState, fromParams, error) {
    AlertService.error(error.data.message);
});
```

**Comment by hirro** [comment]
Speaking pagination and of long delays:

When testing with different paginations alternative, I noticed no-pagination makes the page unresponsive until all entities are loaded. This takes ~8-10 seconds for 2000 rows. This pagination is visually similar to infinite pagination, maybe just remove the no-paging option?

Btw,  fixing #2387 takes a bit longer than expected due to the templating and DTO (rest is done). So if anyone wants to take over please do so. Testing takes a lot of time and I don't want to break any of the  generator options.

I am using the my  project "jHipster test generator" on https://github.com/hirro/jhipster-test-projects.git (using it to test  #2387 ) to setup different test cases where I can test the different pagers with pre-populated pages. There are 2000 entries atm. Requires the elasticsearch re-indexer. It is almost done, but one manual step still required to add the testdata.xml to master.xml (liquibase). Anyway this tool has been useful for me in any change that relates to the entity tables.

**Comment by jdubois** [comment]
Very interesting points @geraldhumphries !!
It's hard to decide which option is best, at the moment I have a preference for NOT using resolve as:

- The UI would be better -> the end-user are more important than the beauty of our code :-)
- Here we only generate simple screens, but for more complex screens, with several different entities, it seems more logical to me to handle them in the controller, and handle the errors there.

**Comment by deepu105** [comment]
Ya lets do it in controller as it easier to follow even for novice
developers

**Comment by geraldhumphries** [comment]
Any ideas for what to do with infinite scroll?

**Comment by geraldhumphries** [comment]
I am working on this now. Since this issue will introduce significant differences in the controller between `pager/pagination`, `infinite-scroll`, and `simple`, I am splitting the controller contents into EJS files so they are easier to manage. Does anyone have any objections?

**Comment by deepu105** [comment]
i think ok as long as it doesnt become overly complex

Thanks & Regards,
Deepu
