### ISSUE TITLE
New file .yo-rc-global.json keeps package name in the home folder

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2658]
There's a new .yo-rc-global.json file, which I guess was added during the codebase refactoring by @deepu105 , which is in the user's home directory.
This file currently stores the package name: that means we have by default the same package name for all generated applications.

This isn't necessarily bad: the default package name isn't useful anyway, so our best guess as a default package name would be the last one that was previously used.

But this can be a bit surprising to users: what do you think, should we keep it that way?

**Comment by deepu105** [comment]
Hi Julien,

I think it is from the store property I added on the package name promt
sorry, that was suppose to be another PR but i pushed it there I guess.
Anyways its just a an improvment so that you dont have to type the pacakge
name again and again, it will remember what you typed last and you can type
something new if you want to override. So its actually a good thing in my
opinion

May be you should mention it in release notes

**Comment by pascalgrimaud** [comment]
It's this line : https://github.com/jhipster/generator-jhipster/blob/master/app/index.js#L219
The .yo-rc-global.json can be created by another generator, which use "store"

Honestly, it's very interesting to store some basic information, no need to put them the next time.

So my opinion is to keep them. But if we decide to remove it, another generator (for example modules) can use them... So the file will be created

**Comment by jdubois** [comment]
OK, let's keep it this way, but we need to document this -> I'm keeping this opened until we have documented this somewhere on the website

**Comment by deepu105** [comment]
Ill document it on the app creation page
