### ISSUE TITLE
[Enhancement Request] Add more fields to existing entity

### ISSUE THREAD

**Issue by amitjindal** [jhipster/generator-jhipster#2668]
**Overview of the issue**
I would like a way to add more fields to an entity. Currently Once have generated an entity there is no way to add additional fields (columns) unless done manually which is error prone.

**Motivation for or Use Case**
 In any ongoing project it is common in my humble opinion that fields will be missed or may need a change.  hence an option that allows us to continue adding more fields to the entity will be very beneficial to all.

An example will be lets say we have a customer entity that already has 5 fields added earlier. Invoking the generator in 'add' mode should allow continuing the add field loop by loading existing file and adjusting internal structure to next index.

```
yo jhipster:entity customer --add
```
or
```
yo jhipster:entity customer -a
```
Asks (# 6 for representation only):
```
Do you want to add more fields to this entity (# 6) (Y/n)?
```

**Comment by deepu105** [comment]
This has been asked many times before and yes i agree that its a very
useful feature, but having said that its also very difficult to add to
existing code without breaking anything coz existing code might have
undergone manual change, another easier way would be to give this option
then just regenerate everything for that entity which is easier to achive

**Comment by cbornet** [comment]
@amitjindal have you tried jhipster-uml ?

**Comment by gmarziou** [comment]
Have you read this answer?

http://stackoverflow.com/questions/28216307/how-to-modify-existing-entity-generated-with-jhipster

**Comment by amitjindal** [comment]
@deepu105
I would expect anyone using JHipster to atleast have git and be able to reconcile the changes. :-)
The problem we faced is that I am using this in a project where we have tables with 50+ columns. This has relations with several tables. As the project has progressed, fields and relations are added. Now if I have to add 4-5 fields to this or add a relation, its a nightmare to redo the entity. I am sure this will be a use case of several other members.

Moreover this should not be default so I would guess someone invoking would know what they are doing.

Quite frankly I have an edited version of jhipster that we customised for that project and got the addition working. However that was a while ago and since then the project has changed a lot. So I am requesting this be a core feature done properly rather than our amateur hack.

@cbornet 
No I have not. And really thanks because I did not realise this was even possible. I am going to try this right away!

@gmarziou 
Thanks for the link. Yes I am aware of that but its really painful doing this manually by hand for a large sized project: 70+ tables, lots of relations etc.

**Comment by deepu105** [comment]
Ok Amit, I do understand your pain thats why I havent closed this issue :)

@jhipster/developers doing this as a command line option should be feasible
and if im not wrong shouldn't be too much of a change, let me take a look
and post what needs to be done and if everyone agrees we can do it

**Comment by amitjindal** [comment]
Great. Thanks for your kind consideration.

Here's what I did (attached as a patch). See if this helps. This is from early Oct so probably won't apply directly but it has been working for me for a while now.

Doing this the problem we see is Liquidbase file is regenerated with a new name and liquid base fails because it complaints table already exists (doh). We have to manually remove the older file from master.xml

After this I get:
```
yo jhipster:entity employee     (Generates new entity. If entity already exists, it regenerates the same as it works currently)
yo jhipster:entity employee --add    (Starts adding more fields)
```

[patch.diff.txt](https://github.com/jhipster/generator-jhipster/files/101708/patch.diff.txt)

**Comment by deepu105** [comment]
@amitjindal we will consider if others in our team agrees otherwise sorry

**Comment by amitjindal** [comment]
Sure. That's okay.

**Comment by pascalgrimaud** [comment]
From my point of view, it's a very interesting feature request!

I see 2 ways how we can work:
- directly in core
    - it should not break our current sub entity generator
    - it should be tested on all db (mysql, psql, oracle, mongo, cassandra)
    - as it is complex, we can have a lot of tickets about it, so a lot of work
- as a module
    - maybe @amitjindal you want to lead this module or @deepu105
    - something like generator-jhipster-entity-v2 ? same functionnalies but can add additional fields ?
    - as soon as it's totally ready, it can be proposed to integrate to core sub generator

What do you think ?

**Comment by amitjindal** [comment]
I didn't think of this as a module but that might work. All we need is ability to add and regenerate. However asking the same questions again with all dependencies will be duplicated work. I don't know how to write such a module but will read about that.

**Comment by deepu105** [comment]
I too think that a module will be a lot of duplicated work

**Comment by jdubois** [comment]
Indeed, this has been asked many times, and is a bit difficult for us as we expect people have modified their code, so we could have all kind of issues. So 2 solutions here:

- We re-generate the code with the new attribute -> then the user will have to do the merging himself. This is the safest option for us, as we send all the burden of merging to the user :-)
- Use the new needles we worked on for the module system, so there are new needles for adding an attribute, its getter/setters, etc... -> that's quite a lot of new needles, but that could be easier for the end-user

-> I would go for the first option, it's safest for us, and less needles everywhere

And yes I would do this is directly in the entity sub-generator, that's the most logical place. 2 solutions here also:

- Provide a specific flag to add this new field -> could be a bit tricky for the users to use
- Read the entity configuration again, and then add the ability to add, edit, or even delete attributes (and maybe relationships in a second time)

I would go with the second option, as this would also facilitate the work of people who did a mistake when typing their entity, which is another of our big issues.

Here is how I see it, for an existing entity called Foo:

- We read the .jhipster/Foo.json file (like we already do)
- If the user did a "yo jhipster:entity Foo --force" we regenerate it directly (like we already do)
- Otherwise ask a new question: "do you want to Add, Remove or Edit an attribute? (A/R/E, default is Add)"
- If Add or Edit is selected, use the current options for creating an attribute. If Remove is selected, remove the attribute (obviously)
- Then ask "Are you finished modifying the attributes of your entity? (Y/n)" and do a loop if the user want to change another attribute

**Comment by deepu105** [comment]
@jdubois

"Read the entity configuration again, and then add the ability to add,
edit, or even delete attributes (and maybe relationships in a second time)"

this is exactly something i asked as a feature when i was new to Jhipster :)

Ill take look at the feasibility later, i think should be doable

**Comment by jdubois** [comment]
@deepu105 yes, to me this looks a bit complex to do, so I've always been reluctant to do this, but maybe with your new refactoring, and some clever code, this could be done with a few lines of code

**Comment by deepu105** [comment]
Its done :)

**Comment by deepu105** [comment]
@jdubois this was done with few methods but along with this I moved some common methods out from promting section and renamed all constant variables , so the diffs will show a lot of change

**Comment by amitjindal** [comment]
Thank you @deepu105 and JHipster team!

**Comment by gmarziou** [comment]
I answered to a user who had problems with Liquibase changes checksums after having added a field to an entity, maybe we could solve this by checking the existence of a migration file named .*_added_entity_.*.xml and then try to create a new migration which alters the existing table.

https://stackoverflow.com/questions/40328840/add-new-field-to-existing-entity-with-jhipster/40329781
