### ISSUE TITLE
Could not resolve dependencies for sample project 

### ISSUE THREAD

**Issue by hobong** [jhipster/generator-jhipster#2741]
[ERROR] Failed to execute goal on project sampletoken: Could not resolve dependencies for project com.mycompany.myapp:sampletoken:war:0.0.1-SNAPSHOT: Could not find artifact org.springframework.data:spring-data-commons:jar:1.11.2.RELEASE in spring-milestones (http://repo.spring.io/milestone)

**Comment by gmarziou** [comment]
Please follow our [guidelines on how to submit an issue](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-submission-guidelines).

Your problem seems to be in your environment, missing artifact can be found on maven central, your project looks for it in spring-milestones, so I suspect that your maven settings.xml references it or you need to cleanup your .m2 directory.

**Comment by hobong** [comment]
Thank you,
I have steep start with Java/SpringBoot/JHipster..etc. , sorry for
ignorance.
I've learned a bit more now about maven and rechecked my config (on Win10
machine unfortunately).

I am pretty sure this repo spring-milestones is generated from
jhipster-generator...
If it persist some time I would articulate better the issue.

Greetings,
Marian Porwol

2016-01-31 2:32 GMT+01:00 Gaël Marziou <notifications@github.com>:

> Closed #2741 <https://github.com/jhipster/generator-jhipster/issues/2741>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/2741#event-532743939>
> .
>



-- 
http://en.gasq.org/registration/find-an-auditor.html?tx_drowcdb_piEntries%5Bdetail%5D=10695&cHash=8c29cb430478f5adc677db241d822f6a
