### ISSUE TITLE
docker-compose : improve documentation for Windows/OSX

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#2747]
The discussion started here https://github.com/jhipster/generator-jhipster/issues/2735

**Comment by andidev** [comment]
Using docker inspect I found the following `"IPAddress": "172.17.0.2"`

I'm then setting datasource to `url: jdbc:postgresql://172.17.0.2:5432/jhpg` it in `application-dev.yml`

This causes `Caused by: org.postgresql.util.PSQLException: Connection attempt timed out.`.

I retried with casandra and changed the IP there as well and then I got:
`Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.3:9042 (com.datastax.driver.core.TransportException: [/172.17.0.3:9042] Cannot connect))`

I'm done for today but I'll try some more tomorrow if time allows.

**Comment by pascalgrimaud** [comment]
My bad... `docker inspect` is used for local, and you're not because you use a VM on OSX!
This command should show the IP of your VM : `docker-machine env default`
Try to use it in `application-dev.yml` (hope it will work now)

**Comment by andidev** [comment]
Yes that works! We should probably document this. I guess the issue is there for Windows as well?

**Comment by pascalgrimaud** [comment]
oh great news! Yes same for Windows I think
I keep this ticket open until I document it !

Thanks for testing and feedback @andidev
