### ISSUE TITLE
update all dependency

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2774]
Just a reminder to update the below before next release

- [x] maven/gradle dependencies
- [x] npm dependencies for core 
- [x] npm dependency for generated project
- [x] bower dependencies
- [x] docker image dependencies
- [x] travis dependencies

**Comment by phouverneyuff** [comment]
docker images too

**Comment by pascalgrimaud** [comment]
what docker images are you talking about, @phouverneyuff ?

**Comment by phouverneyuff** [comment]
Mysql to 5.7.10 or latest -> https://hub.docker.com/_/mysql/
Postgres to 9.5.0 or latest -> https://hub.docker.com/_/postgres/
Mongo to 3.2.1 or latest -> https://hub.docker.com/_/mongo/
Elasticsearch to 1.7.5, or 1.7, or 2.2.0 (latest) -> https://hub.docker.com/_/elasticsearch/
Sonar we're discussing here #2780

**Comment by phouverneyuff** [comment]
We can use only two digits for always get the bugfix.
E.g: use 5.7 in mysql

**Comment by pascalgrimaud** [comment]
Like in package.json, I prefer use specific version instead of latest => see my old PR https://github.com/jhipster/generator-jhipster/pull/2217
> use an official tags version, instead of the latest (to avoid a new update version of database/service which we didn't test)

I dont like 2 digits too : if I have low connection and during a demo, if mysql:5.7 has been updated on docker hub, it will trigger a new download to replace my image

I prefer this workflow :
- use fix version for database X.Y.Z
- when there is a new version, we must test it
- if it works, go PR

I tested some images 1 month ago, if I remember well, JHipster not compatible with Elasticsearch 2+, Cassandra 3+

**Comment by phouverneyuff** [comment]
OK @pascalgrimaud. I understand your point of view.

**Comment by jdubois** [comment]
I'm updating the NPM dependencies, the commit will be referenced here soon.
We should do this now, and then do a freeze: JHipster 3.0 is coming closer and closer, and we can't move all the libraries all the time.

**Comment by mraible** [comment]
@jdubois Do you have a particular date in mind for releasing JHipster 3.0? I'd be happy to help with documentation. Maybe we should create tickets for that?

**Comment by jdubois** [comment]
Yes, I have a date in mind: I would like to release it 1 month before Devoxx FR, so we have time to prepare our talks and debug stuff :-)

- That means March, 21th
- My trainees @PierreBesson @wmarques will also perform some intensive performance tests of the micro-services architecture before the release, so that should be ready for March, 14th
- We already have some documentation like at https://github.com/jhipster/jhipster-registry but it's clearly not enough, and must be merged in the main website (by the way, we have a special tag for that, see https://github.com/jhipster/jhipster.github.io/tree/v3_preparation )

So yes, help and tickets are welcome!

**Comment by deepu105** [comment]
@mraible we have a specific documentation ticket #2785 here

**Comment by deepu105** [comment]
@jdubois I thinks its good to set a freeze date else we might just keep on adding stuff

**Comment by jdubois** [comment]
So I updated NPM, Bower, Maven, Gradle -> we are only left with Travis and Docker, @pascalgrimaud can you have a look? But for me this can be closed now!

**Comment by pascalgrimaud** [comment]
yes I will look it tonight to know if we could update our docker-compose files
it won't change anything just to be "hipster" and use the latest version as possible

**Comment by pascalgrimaud** [comment]
Oh I have to update jhipster-travis-build too !

**Comment by pascalgrimaud** [comment]
Docker images have been update : https://github.com/jhipster/generator-jhipster/pull/2983
[jhipster-travis-build](https://github.com/jhipster/jhipster-travis-build) has been updated too, to keep only gulp libs (I removed all grunt libs) -> hope it won't break anything. I can't test tonight because Travis is tired

**Comment by deepu105** [comment]
@jdubois did you update npm of the generated project template as well?

**Comment by jdubois** [comment]
@deepu105 yes everything should have been updated!
