### ISSUE TITLE
Use the latest version of Sonar in docker-compose

### ISSUE THREAD

**Issue by phouverneyuff** [jhipster/generator-jhipster#2780]
Currently, in sonar.yml, the image points to version 4.5.6.

I guess the better is to point for the latest version instead points to old version.
Or to point to LTS, but we are HIPSTER. We use the latest of latest of latest ...

https://hub.docker.com/_/sonarqube/

But, I don't know how Sonar will behaviour when change the version. The history will lost?
If anyone have experience, please write here. If don't, I'll test it.

**Comment by pascalgrimaud** [comment]
1) about version
The use of LTS was intentional, like all version of database which use fix versions.
My goal was : I don't want a big change from sonarqube in their latest image and mvn sonar:sonar  doesn't work because of the latest. So I prefered to use a LTS version
For example, if I remember well, Cassandra 3.0 doesn't work with JHipster, so we can't use latest

Anyway, I provide in my [Docker module](https://github.com/pascalgrimaud/generator-jhipster-docker/) the latest version of sonarqube

But for Sonarqube, it's very minor, I think we can use latest instead of LTS

2) about data
this sonar.yml is just a sample to start very quickly a Sonarqube instance. It can be improved !
- use volume to keep data
- use a real database, instead of H2 embedded database

**Comment by phouverneyuff** [comment]
I'll do a PR to update for the latest version and persist the data in h2 using file.
OK?

**Comment by pascalgrimaud** [comment]
Ok for latest version

About persist data, you mean volume on `/opt/sonarqube/data`, right ? In that case, you can add it but in comment plz. The user have to know what he does if he wants to use volume (choice of folder, permissions, etc.)
