### ISSUE TITLE
Add an option to generate only the frontend

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#2810]
Like we have --skip-client to generate only the back-end, we should have --skip-server to generate only the front-end.
This is important for microservices : the front-end will be generated only on the gateway. And the microservices will just have the back-end.

**Comment by deepu105** [comment]
Thats easy to add coz we already have a jhipster:client generator

Since the client generation needs to know what is the authType, cache,
dbType etc to generate properly these can be passed as cli options to the
sub like `jhipster:client --auth jwt`

So if we are skipping it from main generator we should provide some
sensible default.

What defaults would you prefer for below

Authentication -this is used to create auth files
Social sign in - to have social buttons
Dev database - used in metrics and health
Prod database - used in metrics and health
Hibernate cache - used in metrics
Build tool - used in gulp task to read app version
Websocket - for the tracker module

Or should we remove all the above when skip server is enabled?

**Comment by deepu105** [comment]
done :+1: 

we need to just add the defaults

**Comment by cbornet** [comment]
As for metrics and health, I guess there will be a dedicated component in micro services.

**Comment by gmarziou** [comment]
Gulp util parseVersion() fails when using --skip-server flag

Using master, I generated an app using --skip-server flag, gulp fails in parseVersion() because it tries to parse build.gradle to extract project version.
As build.gradle has not been generated, it fails.

When --skip-server flag is enabled, I think parseVersion() should not be called nor generated in gulp/utils.js and the version should be hard coded in the Gulpfile.js

If OK, I can submit a PR.

**Comment by gmarziou** [comment]
Another possibility which would be less intrusive for Gulpfile.js would be to implement parseVersion() as returning a constant.

**Comment by gmarziou** [comment]
I found another issue with `--skip-server` flag: as we did not ask to select the authentication scheme during the generation, the client code is missing the `auth` folder completely.

So the authentication question should be asked but then what should be used as the base URL for `/api` calls?

**Comment by deepu105** [comment]
Yes, if you are skipping server you need to pass the auth flag with any one
of the auth type. We need to document those well and you are right about
parse version

**Comment by deepu105** [comment]
@gmarziou thanks for testing

**Comment by gmarziou** [comment]
I must admit that I'm a bit confused by these new flags, in particular it's nto clear for me whether they are supposed to be run by end users directly or only indirectly through modules.

**Comment by deepu105** [comment]
Yes, these might be a bit overwhelming for our normal users, but its
supposed to be used by modules and power users so should be ok

**Comment by gmarziou** [comment]
@deepu105 I tried these options:

   yo jhipster --skip-server --auth oauth2

Is this how the auth flag is supposed to be used? 

The app generated without errors but failed in browser:

`Error: [$injector:unpr] Unknown provider: authExpiredInterceptorProvider <- authExpiredInterceptor <- $http
`

**Comment by deepu105** [comment]
Yes thats how it needs to passed. Ill see whats causing error

**Comment by roytruelove** [comment]
+1 on auth not being generated with`--skip-server`.  I ran `yo` with `authenticationType` set to `jwt` in my `.yo-rc.json`

**Comment by sjalouali** [comment]
+1 Hello, same problem when  generate separate  front-end.

"Unknown provider: authExpiredInterceptorProvider <- authExpiredInterceptor <- $http <- $templateFactory <- $view <- $state"

Someone has an idea ?
Thanks

**Comment by vikreinok** [comment]
+1

JHipster Generator v3.12.2
Same issue: 
I had to copy .yo-rc.json from server directory to client directory.
Otherwise yo jhipster:import-jdl ../domain.jh ../client.jh  (last file contains skipClient for *) did not work.
 
Error: [$injector:unpr] Unknown provider: authExpiredInterceptorProvider <- authExpiredInterceptor <- $http
