### ISSUE TITLE
Rename getter for boolean fields from getXXX to isXXX

### ISSUE THREAD

**Issue by epikuruz** [jhipster/generator-jhipster#2844]
Consider changing the following convention for entities:
class X
{ 
   private Boolean a;
   ..
   public getA(){ return a};
}

to

class X
{ 
   private Boolean a;

   public isA(){ return a};
}

**Comment by deepu105** [comment]
I think thats good. Do you want to do a PR?

**Comment by jdubois** [comment]
Yes that's the correct way of doing JavaBeans -> however I remember doing the getXXX as not every framework knows about this (some stuff is poorly coded!) and I had some integration issues.
I don't remember exactly the problem, and that was 2 years ago (at the beginning of the project), so let's try this.

**Comment by DiegoEP** [comment]
I've facing some problems because this. I'm using default Spring and Hibernate:  

Could not autowire field: **private** 
org.springframework.data.mapping.PropertyReferenceException: No property desc found for type Boolean! Traversed path: StorageUnit.defaultUnit.

In my classe I have:
private Boolean defaultUnit;
public Boolean isDefaultUnit() {
        return defaultUnit;
}
This class were generated by importing a idl file via command line.

So, looks like JPA doesn't maps a Boolean wrapper by isXXX notation. It'll be annoying to manually rename each property. :-(

**Comment by notflorian** [comment]
Hello @DiegoEP, could you open a new issue with all the required informations of the template, and I will look into it. Thanks

**Comment by DiegoEP** [comment]
My bad, @notflorian. There is no problem with IsXXX notation for Boolean wrappers. In my case, the problem was a method in the repository called findTopByDefaultUnit(). In this case it's necessary to pass the boolean value as parameter or at least put the suffix True or False to the method name, indicating the value. So, I replaced the method name to findTopByDefaultUnitTrue() and it worked. So, please disregard my previous report. Thanks!

**Comment by cbornet** [comment]
According to the JavaBean spec the "is" is for boolean, not for the Boolean wrapper.
Here is what is generated by IDEA for instance:
```java
    public Boolean getTest() {
        return test;
    }

    public void setTest(Boolean test) {
        this.test = test;
    }

    public boolean isTest2() {
        return test2;
    }

    public void setTest2(boolean test2) {
        this.test2 = test2;
    }
```

**Comment by notflorian** [comment]
I'm sorry to disagree @cbornet, but I didn't find in the [JavaBeans Specification 1.01 section 8.3.2](http://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/) any example with Boolean object properties. For me, without clear guideline, what should prime is the consistency of the methods naming.

However, the Jetbrain team in this [IntelliJ issue](https://youtrack.jetbrains.com/issue/IDEA-25268) did this change in 2010, so maybe we should also follow this convention.

Are you aware of issues in JHipster because of this? (maybe with JPA, mapstruct or Liquidbase)

**Comment by cbornet** [comment]
I had a look and the with the current implementation of java.beans.PropertyDescriptor any isXXX is accepted as getter for any type (even non boolean/Boolean) and it even takes priority over the getXXX if you have both in the bean ! I don't think this was intended in the first place but it makes the current isXXX for Boolean OK...

**Comment by notflorian** [comment]
Ok, thanks :)
