### ISSUE TITLE
Social Login Support for stateless Authentication

### ISSUE THREAD

**Issue by BhawaniSingh** [jhipster/generator-jhipster#2848]
Enabling social login support for oAuth and x-auth should be done

**Comment by deepu105** [comment]
@moifort

**Comment by moifort** [comment]
@deepu105  @jdubois I was thinking if it will not better to migrate all the social authentification to a module and remove it from the jhipster app?

**Comment by cicoub13** [comment]
:+1: for the request and for the module

**Comment by jdubois** [comment]
I'm happy to have this in the main generator, I guess a lot of people want this, and it doesn't look annoying to maintain (never had any issue for that)

**Comment by deepu105** [comment]
I'm fine either way :)

Thanks & Regards,
Deepu

**Comment by BhawaniSingh** [comment]
So anyone planning to work on this?

**Comment by moifort** [comment]
Normally me, but I do not have much time right now.

**Comment by amitjindal** [comment]
@moifort Could you please guide us if we were to start a JWT project and add some classes to support Social auth, how would we go about that?
Or any other alternate way to do this in a JWT project.

Thanks!

**Comment by amitjindal** [comment]
Here's what I did:

I created a JWT project. Then manually edited the .yo-rc.json and set:
`"enableSocialSignIn": true,`

After that when I regenerated, I am able to get the register with Google+ Working. However the login is not working (expected). The social login is not getting registered in Spring security. I think I need to make some changes in SecurityConfiguration.java to get this to work (possibly).

**Comment by jdubois** [comment]
Great news @amitjindal -> can you share work with @moifort on this?

**Comment by amitjindal** [comment]
@jdubois Actually it did not work. I tried a lot of ways. I can share what I did but the problem seems to be that I am not finding where to set the JWT token when social authentication succeeds. Because from what I could understand the authentication is some sort of form based and its returning RedirectViews. I cannot figure out where is the response object that I can set the JWT to get this working.

I am on my way home. I will type up what I have tried so far. Most likely its very easy but I am just not familiar enough with this.

**Comment by mraible** [comment]
This could be similar to the problem I had with Ionic 2. To fix it, I had
to add the token to the response body.

**Comment by amitjindal** [comment]
@mraible Actually I am trying to figure out how to get a response object :-(
I am probably missing something very basic that I don't yet understand.

**Comment by mraible** [comment]
In the current implementation of JWT on master, there is no response body.

**Comment by amitjindal** [comment]
So here's what I have done so far:

**Step 1: Created a new project with JWT as the authentication.**

**Step 2: Edited `.yo-rc.json` and enabled `"enableSocialSignIn": true,`**
At this point I can login normal (via JWT). I can Register via Google Auth. However when I try to login, it redirects me to login. This seems to be happening because of `JWTFilter::doFilter`

**Trial 1: Setting JWT**
I tried to create a JWT so that I can return via headers as it is doing in method: `UserJWTController::authorize` namely:
```java
        Authentication authentication = this.authenticationManager.authenticate(authenticationToken);
        SecurityContextHolder.getContext().setAuthentication(authentication);
        String jwt = tokenProvider.createToken(authentication, rememberMe);
        response.addHeader(JWTConfigurer.AUTHORIZATION_HEADER, "Bearer " + jwt);
```

When I try to do the same here: `CustomSignInAdapter::signIn` I cannot because this method returns a String which is a redirect url. Further at this point I do not have a `HttpResponse` to set the JWT header which could have possibly resolved the issue.

**Trial 2: Adding a post processor**
Tried to do something similar as here: http://blog.jdriven.com/2015/01/stateless-spring-security-part-3-jwt-social-authentication/
However I don't have a SpringSocialConfigurer. I tried extending the existing class: `SocialConfiguration` from SpringSocialConfigurer but it was not getting called. I do not have a good understanding of Spring security to understand this at present.

**Trial 3 (Hack): Thought of adding a service that could be request scope and set the Authentication**
This may work if I try to set this in JWTFilter but seems completely wrong.

**Trial 4: Reverse way. Created a project starting with Social Auth and then add JWT**
I added the JWTFIlter but I could not figure out how to make this stateless. Also the filter was not getting called. I lack the knowledge to get this working.

At this point I do not have any other things left to try. Need guidance to proceed.

**Comment by moifort** [comment]
Sorry, but I am quite busy in this time, I will see if we can do something next week. 

Thibaut.

**Comment by amitjindal** [comment]
@moifort Sure. I understand. Will wait.

**Comment by moifort** [comment]
I working on it now

**Comment by moifort** [comment]
Okey, I just finish the social authentication for JWT, it was not easy... I will make a first PR tonight

**Comment by moifort** [comment]
@amitjindal If you want you can see my work on the PR #3116

**Comment by amitjindal** [comment]
@moifort Thanks!
I checked and it seemed to work great. I will keep playing with this a bit to see if I find any problem.
PS: In `CustomSignInAdapter.java` around line 18 the import for TokenProvider is hardcoded to `com.mycompany.myapp.security.jwt.TokenProvider` which is incorrect. I only needed to correct that to get this working.

**Comment by moifort** [comment]
Thanks for the import problem. If you have any remark or improve to my current code tell me!

**Comment by amitjindal** [comment]
Hi @moifort 
I tested the following scenarios:
(After removing the username validation so I can use email as username)

#### Case 1: I sign in as a G+ user.
This creates an account with email as username. Then I logged out and clicked forgot password. This allowed me to change password. Now I am able to login via G+ as well as email (as username) and password.

#### Case 2: I created an account using my email address.
Then activated the account. Logged in. Logged out. After than when I try to login via G+ (same email address) I can and it connects the account (via email).

So I think this is working great and even allows connecting accounts as long as email is same.

#### Few things I noticed:
1. After first time registration it comes back to registration success page and not auto login.
1. As admin, I cannot delete a user who was created via Social.

**Comment by moifort** [comment]
@amitjindal thanks for your feedback :+1: !

**Case 1 and case 2:** Yes, I allow this case when I begin to develop the social functionality (hope is not a security leak), maybe it can be cool to make like Stackverflow and associate several social account to one account through a screen.

1. Yes, it will be a better user experience if it's auto login at the first time.
2. I didn't notice, I will investigate.

Thanks!

**Comment by lazaropj** [comment]
First, thank you.
I am hoping so eagerly.
1) I can use to login with Facebook?
2) I already have a project in production. How do I upgrade to this change?

**Comment by moifort** [comment]
@lazaropj you're welcome :)

1) Yes it's work for facebook, but for Http session and JWT authentication only (oAuth is not implemented yet)
2) It's always a difficult part, the simple way (for me) it's to see the PR  #3116 and #3183, go to *Files changed* tab and make the change directly in your project.

**Comment by deepu105** [comment]
@moifort are you planning to do this for Oauth as well or can we close this?

**Comment by moifort** [comment]
Yes i Will plan it, that's why I didn't close the ticket. 

Thibaut.

**Comment by jdubois** [comment]
As the PR is merged I'm closing this

**Comment by deepu105** [comment]
I guess its not done for oauth yet

**Comment by jdubois** [comment]
Social login with OAuth2, I didn't know about this.

**Comment by gnoopy** [comment]
May I ask you about your roadmap on Social login support with OAuth2 ?
