### ISSUE TITLE
set html5 mode as default

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#2965]
As part of 3.0 should we set `$locationProvider.html5Mode(true);` for angular urlmode

we already have a tip for this http://jhipster.github.io/tips/010_tip_configuring_html_5_mode.html

It seems that this mode is better for SEO and analytics what do you guys think?

@brevleq you wrote the tip any comments on this?

**Comment by cicoub13** [comment]
👍

**Comment by jdubois** [comment]
I'm not a big fan of having this controller in the code - I'm not sure how it's going to be used, what are the impacts in terms of performance and maintenance?
For SEO I have no idea if it does anything.

**Comment by deepu105** [comment]
I was reading some articles which claims that html5mode clean urls are
better for SEO and stuff. I dont think there is any performance impact

Thanks & Regards,
Deepu

**Comment by brevleq** [comment]
I've created that tip because of SEO. The first time I published my project, it was simply "ignored" by Google, Bing, etc. In that time, the only way to get SEO was make the server process the web crawler requests in a different way. You can see more in these links: 
[http://stackoverflow.com/questions/7655634/hashbang-and-google-seo](url)
[https://www.mobomo.com/2014/09/seo-for-single-page-applications/](url)
I used [https://prerender.io/](url), and my page became poorly listed in Bing and Yahoo, but was not listed in Google.
In October of 2015, Google changed the recommendation for hashbang SEO, and I resolved abandon prerender.io and clean the URL. Finally my project was listed decently in Google, of course I need improve the SEO, but you can search for "consami" (or consami.com.br) in google and you will see my project listed.
SEO has a big impact, don't doubt this. I was warned before to not create the project using single page application frameworks (like AngularJS) because of SEO, and I was thinking in abandon JHipster for projects that need SEO after the nightmare of not being listed in Google.
The approach I used in my tip, works. The only problem I saw in my tip is that I need add the urls manually. I've tried a lot find a kind of "master URL sentence", but I didn't found a sentence that would forward the pages urls without affect "/api/" calls, css and js download, so I decided add the urls I need forward one by one.
About the performance that @jdubois is afraid, I didn't see any performance issue in my project.
Hope I helped in your decision.

**Comment by ruddell** [comment]
I didn't post this because it isn't specifically generator related but when following this tip, any gulp reload on a path other than '/' gives an error such as:  `Cannot GET /register` Directly navigating to /register works for port 8080 but not port 9000 which gulp uses.  So just a heads up that gulp would need changes.

And as mentioned above, you have to manually add paths for any added pages like entities or custom pages.

**Comment by gmarziou** [comment]
Another reason for doing it is that it's the default mode in angular 2.

**Comment by jdubois** [comment]
I know SEO is important, and that's why we have Thymeleaf -> if you want top notch SEO, do a real Web page.
Concerning the controller, I'm worried if we have to modify it for each new page, and if we have to modify Gulp... Seems like a lot of trouble to me, but if there is a clean solution for that no problem for me.

**Comment by deepu105** [comment]
I dont think we need to do for each controller, it meeds to be set only
once for front end, only thing is to find out a way to do a generic url
rewriting pattern on backend.

Anyone interested to try?

**Comment by deepu105** [comment]
does anyone want to try this? else we can close it

**Comment by deepu105** [comment]
@wmarques do you wanna give it a shot?

**Comment by wmarques** [comment]
Yes I can try to do this ! But I have no idea how to rewrite URL in backend...

**Comment by wmarques** [comment]
I've found a solution on[ this guide](https://spring.io/blog/2015/05/13/modularizing-the-client-angular-js-and-spring-security-part-vii), but I don't know in which file I have to implement it, or if I have to create a new file, where I should put it in the project. For the moment I put it in config package and it seems to work. But as mentioned in the tip, /health and /monitoring routes have to be renamed.

```
@Controller
public class AngularJSForwardController {
    @RequestMapping(value = "/{[path:[^\\.]*}")
    public String redirect() {
        return "forward:/";
    }
}
```

**Comment by wmarques** [comment]
If anyone can tell me where should I put this code I can PR this tomorrow morning after testing it. @jdubois @deepu105 ?

**Comment by notflorian** [comment]
Maybe you can put this controller with the others REST controllers, in [generators/server/templates/src/main/java/package/web/rest/](https://github.com/jhipster/generator-jhipster/tree/master/generators/server/templates/src/main/java/package/web/rest) ?

**Comment by deepu105** [comment]
Yes should be in the rest folder

**Comment by wmarques** [comment]
Alright it's done, I've few problems on test I'm fixing this. 
But as there is no more` /#/`, some spring endpoints are accessible via URL and can enter in conflict if the user generates for example a `health` or `info` entity. I've thought about adding `RESERVED_WORDS_SPRING` constant array in entity generator, what do you think ?

**Comment by gmarziou** [comment]
I did not understand this would cause conflicts, we have many endpoints that come from [spring-boot actuator](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-endpoints), they could be customized.

I think we should consider either rolling back to `/#/` or name space the angular URLs with a prefix like `/client` or `/ui`

**Comment by notflorian** [comment]
Instead, we can easily change the root path of the actuator endpoints with the following configuration key in `application-dev.yml `and `application-prod.yml` : 
```
management:
    context-path: /actuator
```
By doing so, the health endpoint will be : `/actuator/health`, and same for info or configprops

**Comment by wmarques** [comment]
Personally I would either rollback into `/#/`, if we add a namespace it's better to keep the default one imo. Or customizing Spring endpoints would be a nice trick to prevent conflicts.

**Comment by jdubois** [comment]
I didn't know that configuration @notflorian 

-> I think we must do it anyway, as it will make our endpoints much more easy to secure!!!! That would remove a lot of lines from SecurityConfiguration

**Comment by gmarziou** [comment]
@notflorian and @jdubois if we do so we will have to add this to all our application.yml:

~~~yaml
eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
~~~

**Comment by deepu105** [comment]
if its too much trouble lets not do this now and lets do it sometime later as a minor release

**Comment by jdubois** [comment]
Yes this looks tricky to me, and I don't want to take risks now.

Can we put it as a tip first, on http://jhipster.github.io/tips/ -> @wmarques can you do this in our "3.0" branch on the website?

And then, after our 3.0 release, in a couple of months, let's open this again and work on it again.

**Comment by deepu105** [comment]
There is a tip on our site already for this. May be @wmarques
<https://github.com/wmarques> can update that

Thanks & Regards,
Deepu

**Comment by wmarques** [comment]
Yes I'm updating this.

**Comment by delverdev** [comment]
@wmarques, your solution doesn't work when refresh inner states, for example '/example/123'. It returns 'Your request cannot be processed (not found)'.

**Comment by gmarziou** [comment]
I really doubt this is easy with current URL scheme, especially for a gateway because we use service names as URL prefixes of our routes, this was [my point on dev list.](https://groups.google.com/forum/#!msg/jhipster-dev/1RtCU3qt3Tk/ShiBOgI5BQAJ;context-place=forum/jhipster-dev).

So either we add complexity in a zuul or servlet filter by plugging it to service registry at the risk of introducing URL conflicts between client and server or we introduce breaking changes in the gateway routes.

**Comment by jobehi** [comment]
Hello, I'm using the htm5 mode and it's working like charm. this guide is perfect but it misses one little thing. As @delverdev  mentioned for the example '/example/123', it doesn't work when refreshing the browser. This can be corrected by adding all the dynamic URLs in the **RequestMapping**  in the **AngularJSForwardController** class. @wmarques code become as bellow : 
`@Controller
public class AngularJSForwardController {
    @RequestMapping(value = {"/{[path:[^\\.]*}","example/*","anotherexample/*",})
    public String redirect() {
        return "forward:/";
    }
}`

**Comment by jdubois** [comment]
Yes we never had the time to finish this -> if you have a working solution (most importantly for Angular 4!), could you provide a PR? I think that will cause issue with our gateways, so there's something to discuss here, but for that please create a new ticket

**Comment by jobehi** [comment]
I only tested the solution with AngularJs, I'll see for Angular 4 very soon before the end of the month

**Comment by gmarziou** [comment]
As I explained above this solution has some important drawbacks:
- the list of URL prefix is longer than you might first think
- it does not work for gateways because we use service name as prefixes, so the list of prefixes is not static and should be dynamically built from registry fetching
