### ISSUE TITLE
Replace jshint by eslint

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#2972]
In recent PR, we had some some issues with indentation in js files.

For an Ionic project, I used [eslint](http://eslint.org/) rather than jshint and it was able to enforce indentation rules, it was also better in other aspects. There's also [an angular plugin](https://github.com/Gillespie59/eslint-plugin-angular) which checks few John Papa's Guidelines.

Any comment?

**Comment by atomfrede** [comment]
We have replaced jshint by eslint. Its much easier to setup and to configure, so I vote +1

**Comment by deepu105** [comment]
+1

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
OK +1 then, but we need to freeze our librairies ASAP for our 3.0 version

**Comment by gmarziou** [comment]
OK, I can work on this on Friday, I'll make a status then.

**Comment by cicoub13** [comment]
I've just tested eslint with eslint-plugin-angular and there is **16448 errors** and 2548 warnings (simple monolithic application without entities) !!!

Most encountered errors :
* You should use the angular.toJson method instead of JSON.stringify
* You should not use directly the "undefined" keyword. Prefer angular.isUndefined or angular.isDefined  angular/definedundefined
* You should use the $document service instead of the default document object angular/document-service
* You should use the $window service instead of the default window object angular/window-service
* You should use the "log" method of the AngularJS Service $log instead of the console object  angular/log

**Comment by gmarziou** [comment]
Well I didn't expect our code to be that far from the default rules. Anyway, these are valid rules, I'll see whether we can phase their adoption.

**Comment by cicoub13** [comment]
My bad, only **1470** errors and 142 warnings (i was including bower_components :-1: ).

A lot of "Use controllerAs to set properties on $scope" ([here](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y031))

**Comment by deepu105** [comment]
that work is underway

Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
I guess we should include the https://github.com/Gillespie59/eslint-plugin-angular plugin as well what say @gmarziou

**Comment by gmarziou** [comment]
Yes I'll try to see if reaching errors is possible, otherwise we may disbale some rules temporarily until we fix our code.

**Comment by deepu105** [comment]
it will be great if we can time this with #2271 so that we can validate both

**Comment by deepu105** [comment]
closed via #3007
