### ISSUE TITLE
[Gateway] /swagger-resources conflicts with Springfox

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3018]
Just for clarity, I open this issue to track a problem that was reported as part of the discussion in #2990.

To clarify: the gateway overrides a URL /swagger-resources provided by Springfox but sometimes it does not work. after discussion with Springfox team we have[ a clean solution](springfox/springfox#1191) that requires version 2.4.0 of Springfox which should be released within days.

Once 2.4.0  is released,we can merge my PR #3019

**Comment by gmarziou** [comment]
By the way, there will be some little rework  for springfox 2.4.1 in few weeks due to this change:

springfox/springfox/issues#1203

**Comment by varghgeorge** [comment]
@gmarziou 
I am trying to create a service for swagger (based on different threads related to aggregated swagger documentation) which will return the list of swagger json URLs so that one single instance of swagger can display details of all services (similar to ApiResourceController). 

Test project: https://github.com/varghgeorge/swagger-single

Is this something you are currently working on? If yes, can you please share the details or point me to the location which I can refer to?

**Comment by gmarziou** [comment]
This is just one class: [GatewaySwaggerResourcesProvider](https://github.com/gmarziou/generator-jhipster/blob/90e256c4bc201587ac05c6e2ed65080fd1d1093c/generators/server/templates/src/main/java/package/config/apidoc/_GatewaySwaggerResourcesProvider.java) that of course uses the Eureka registry, we will have to refactor it a little for springfox 2.4.1 and also we are going to implement a Zuul filter to adjust API path in proxified JSOnN swagger specs.

**Comment by varghgeorge** [comment]
Thanks @gmarziou. I have it working now with a static list of resources. 

Ran into some issues using Zuul. Looks like ProxyRouteLocator is not available in the latest cloud version? Didn't get a chance to investigate further. Will check and update.

**Comment by gmarziou** [comment]
Yes, downgrade to 1.1.0 M4, we haven't yet migrated to M5
