### ISSUE TITLE
 [FEATURE] Domain User to implement UserDetails

### ISSUE THREAD

**Issue by netblue** [jhipster/generator-jhipster#3026]
##### **Overview of the issue**

I'd like to have a user's id available in a standard way to check a user's ownership of custom entities when a user may be trying to edit data. 

I'm new to JHipster, and somewhat new to Java and Spring, so there may be a better way to get the user's id than what I'm trying to do.

##### **Motivation for or Use Case** 
For example, I have a site in which the user subscribes to notifications on particular topics.  I have a notifications table and relationship by user id.  When the user edits a notification, I wish to check ownership before saving.  Or I'd like to get a user's notifications when they want to view their settings.

I'd like to just be able to do something like:

List<Notification> notifications = notificationRepository.findByUserId(SecurityUtils.getCurrentUser().getId());

So, I went down the path of having the domain User object implement user details and then having UserDetailService and Security Utils return the domain User rather than the default Spring User.  It appears to function as desired, though I don't know if this is the best way to achieve what I'm trying to do.

**Comment by jdubois** [comment]
It's more a question for StackOverflow, so you should ask it there -> this is because I think you have something specific for your needs, and for that you can configure JHipster/Spring/Spring Security the way that suits you.
Now for JHipster specifically, we do not link the User ("domain object") to the UserDetails ("security object"), as in some parts of JHipster we use the security when the domain object is not available. This is true, for example, in microservices (this is JHipster 3.0), when you have an authenticated user, but no User domain object.
I've seen lots of discussions on doing it the way you do (merging the domain object and the security object), and that was what I was doing initially. Now I don't think this is mandatory, and I have much more flexibility by having those two concepts separated.
Concerning your example, you could do this with just the UserDetails, as you get the login of the user, and that should be enough.
