### ISSUE TITLE
Swagger PathMapping in micro service should not be hard coded

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#3046]
JH 3.0 master: when generating a micro service, the path mapping in SwaggerConfiguration is hard coded to the name of the service, it should be configurable.

Here the name of the service is "tester".

~~~java
        Docket docket = new Docket(DocumentationType.SWAGGER_2)
            .apiInfo(apiInfo)
            .pathMapping("/tester")
~~~

I propose to add it to JHipsterProperties.Swagger so that it can be configured in application properties and managed in config server.

~~~yaml
jhipster:
    swagger:
        pathMapping: /${spring.application.name}
~~~

Or it could be set to `/${eureka.instance.appname}`

So the code to use it would be:

~~~java
        Docket docket = new Docket(DocumentationType.SWAGGER_2)
            .apiInfo(apiInfo)
            .pathMapping(jHipsterProperties.getSwagger().getPathMapping())
~~~

**Comment by gmarziou** [comment]
Another way would be to change the path property in the /v2/api-docs response using a Zuul filter. This way the service swagger spec could be also used without the gateway.

https://github.com/spring-cloud/spring-cloud-netflix/issues/8

**Comment by gmarziou** [comment]
@jdubois and @PierreBesson, any comment?

**Comment by jdubois** [comment]
I didn't know about this configuration, so my opinion is probably not very good.
For me, using `${eureka.instance.appname}` looks easier: no extra configuration, and the name can be easily found

**Comment by PierreBesson** [comment]
I agree that something should be done as the current situation is only a workaround.
I think replacing baseName by eureka.instance.appname or spring.application.name is not enough because the "route path" can be configured to be different than the app name. For example:
```
zuul:
     routes:
         # sample microservice route
         route1:
             path: /app1/**
             serviceId: app1-v1
```
This is an use case that we want to support.

I like the Zuul filter solution as in the end, only the gateway knows about the existing routes.
I know how to do it because I just wrote the AccessControl Zuul filter. Then I will use Jolt to rewrite the following JSON, basePath with the correct route to the microservice.

GET http://localhost:8080/jhipster/v2/api-docs
```
{"swagger":"2.0","info":{"description":"jhipster API documentation","version":"0.0.1",
"title":"jhipster API","contact":{},"license":{}},"host":"localhost:8080","basePath":"/"}
```

@jdubois, @gmarziou, if it's OK with you I will do a PR next week.

**Comment by gmarziou** [comment]
I'd like also to review the API routes as discussed here: https://groups.google.com/forum/#!topic/jhipster-dev/krdM25gyj6k

**Comment by PierreBesson** [comment]
@gmarziou, I've got the response rewritting filter to work, removed the hardcoded pathmapping and everything works. I have used Jackson's ObjectMapper to manipulate the JSON instead of the Jolt library that you suggested.
I am doing the PR now.

**Comment by gmarziou** [comment]
Great.
I only proposed Jolt because I thought it would not require defining a POJO (json to java to json) but I admit I never used it.
