### ISSUE TITLE
Registry sub generator

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3087]
What should be our recommended approach to get the registry for development? should it be 
1. cloning the repo and running it locally
2. get the docker image and run it
3. get from maven central

I guess option 2 is pretty much done but if option 1 and 3 are also recommended then it might be worth providing a sub generator `yo jhipster:registry` which would download the repo and set it up for development.

what do you guys think? cc @jdubois @PierreBesson @pascalgrimaud @gmarziou

**Comment by pascalgrimaud** [comment]
Option 1 is just 3 commands:
```
git clone https://github.com/jhipster/jhipster-registry.git
cd jhipster-registry
./mvnw
```
I don't think it is worth to write sub generator to do it

Option 2 is already done at [Docker Hub](https://hub.docker.com/r/jhipster/jhipster-registry/)

About Option 3, I don't see how it is supposed to be integrated and launched with gateway / microservice app.

**Comment by jdubois** [comment]
Hi,

Doing a sub-generator is overkill, we have everything working as a runtime
without anything to generate

Now for your 3 questions:

1. cloning the repo and running it locally -> it already works, and it
works like any other JHipster application, so that will work for everyone
2. get the docker image and run it -> it already works, and for me it's
easier than option 1, if you have Docker running. We need it as we are
going to have a full Docker Compose configuration, so that running the
whole microservices+gateway+registry is very easy.
3. get from maven central -> I haven't done it yet, but I plan to do this.
That would be an easy way of distributing our WAR. It might be better for
companies instead of using option 1, so they have a "certified build" from
us, instead of building it themselves.


On Sun, Mar 6, 2016 at 9:34 AM, Pascal Grimaud <notifications@github.com>
wrote:

> Option 1 is just 3 commands:
>
> git clone https://github.com/jhipster/jhipster-registry.git
> cd jhipster-registry
> ./mvnw
>
> I don't think it is worth to write sub generator to do it
>
> Option 2 is already done at Docker Hub
> <https://hub.docker.com/r/jhipster/jhipster-registry/>
>
> About Option 3, I don't see how it is supposed to be integrated and
> launched with gateway / microservice app.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jhipster/generator-jhipster/issues/3087#issuecomment-192830065>
> .
>



-- 
Julien Dubois

Twitter: @juliendubois <http://twitter.com/#!/juliendubois>
Phone: +33 (0)6 25 02 34 18

**Comment by deepu105** [comment]
Fair enough
