### ISSUE TITLE
Use id instead of login in UserManager controller 

### ISSUE THREAD

**Issue by moifort** [jhipster/generator-jhipster#3169]
After my PR #3116, @amitjindal report a problem about deleting a social user through user management screen.

Since we removed the format rule of `login` field in `User` entity, we can create login with special character. The problem is, when we create a social user without login we set it with his email, and if you want to delete it, we send DELETE url with the email address in query param and it's didn't work because Spring Rest remove the ".com" of the login parameter.

I propose to fix this kind of problem by using the user Id instead of the Login. I remember a discussion about it, but I didn't find it. I don't remember if it's a security leak or something.

If you have an other solution tell me, and will make the fix!

**Comment by andidev** [comment]
+1
I also do remember this

**Comment by BhawaniSingh** [comment]
Hmm we can send email in request body too, I know its not common practice but its not discouraged by the specs

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

**Comment by amitjindal** [comment]
I think delete should have been done with ID to begin with. Not sure why it was done with username?
I can't imagine a security leak with this. If you think bruteforce, that can be done via a dictionary attack also against the delete API. And for such concerns we have UUID primary keys.

Using ID also falls into the same entity pattern used in all the rest controllers, so I think this should be considered.

**Comment by jdubois** [comment]
Yes the ID is supposed to be an internal, technical ID, so when we do a "delete" we use the login -> this has been done like that at the beginning and this looks like a good decision to me, so I would like to keep it that way.
I know the issue with the ".com" in the URL, we already have had it, and it's already been solved, have a look [here](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/web/rest/_UserResource.java#L217). Besides, those APIs should be consistent, so that good that they both use the login with the same configuration.

**Comment by moifort** [comment]
@jdubois oh my bad!
