### ISSUE TITLE
Remove the "dev" Docker and Docker Compose configurations

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3180]
This ticket comes from [this conversation](https://github.com/jhipster/generator-jhipster/issues/3154#issuecomment-197182011).

The idea is from @erikkemperman and I'd like to have feedback from at least @pascalgrimaud as he's the expert of this part.

- Having a "dev" packaged WAR file doesn't have any usage, and in fact it could be an issue as people could deploy it in "prod" by mistake -> so the original idea is to have only one "prod" packaged WAR file, and that should be enough
- The same thing occurs for Docker and Docker Compose. The whole idea is to have the same configuration everywhere -> we should only have "prod" images that we use to test and run in prod

So I would like to delete the app.dev.yml and db.dev.yml files, as well as all references to "dev" profiles in the Docker and Docker Compose configuration.

**Comment by pascalgrimaud** [comment]
I will read all conversations and answer it tonight

**Comment by erikkemperman** [comment]
Perhaps to avoid misunderstandings... I was thinking to set the maven/gradle profile used when building the war as the default spring profile when running/deploying that war.

So if I do `mvn -Pprod package` then I would like to get the `prod` profile when I run `java -jar target/xxx.war` (or deploying it) without having to specify `--spring.profiles.active=prod` (or `-Dspring.profiles.active=prod`).

Of course, this was already working as expected for `dev`, because it is default active profile both in maven/gradle and spring.

So I think what I am proposing is actually different from "remove `dev`" as stated in this issue...?

I believe this is the best way forward for war files -- make a sane default, but don't make it impossible to make a `dev` war.

I'm not sure if this makes sense for Docker though.

**Comment by jdubois** [comment]
Oh, maybe I'm going to far here....

OK, the current system is working well, I've never heard complaints about it: let's not break it now that the 3.0 release is approaching.

I'm closing this, but this is something we should think of in the future.

**Comment by erikkemperman** [comment]
So you're just closing this issue of "removing `dev`" -- but do you still agree that the default profile for running the war should be the one that was used to build it? If not please let me know, then I won't spend any time on that :-)

**Comment by jdubois** [comment]
Yes the default profile is the one used to generate the war -> maybe we should write this in the war name, otherwise you can't know if a war is for prod or dev, and that can lead to errors

**Comment by deepu105** [comment]
Thats exactly what i did in my last app I appended the profile to war name
so that i know what war goes were, I had dev, sit, uat, dr and prod
environment with different db and service urls

**Comment by pascalgrimaud** [comment]
**About packaging**. These use cases is for development:
- `mvn` => **dev** profile
- `mvn -Pdev` => **dev** profile
- `mvn -Pprod` => **prod** profile
- start main() in IDE => **dev** profile

When packaging
- `app.war` => like suggested by @erikkemperman, it should depend on the profile which has been used for packaging

I like the @deepu105's idea. I think it should be:
- `mvn package` or `mvn package -Pprod` => `app.war` (prod profile by default)
- `mvn package -Pdev` => `app-dev.war`

**About docker-compose files**:
- currently:
    - h2/mysql, h2/psql => `db.prod.yml`
    - mysql/mysql, psql/psql => `db.dev.yml`, `db.prod.yml` (same file, except when there is elasticsearch)
    - mongo => `db.dev.yml`, `db.prod.yml` (same file, except container name)
    - cassandra (little bit different) => `db.dev.yml`, `db.prod.yml` and other files
- proposition:
    - h2/mysql => `mysql.yml`
    - mysql/mysql => `mysql.yml` (the user will use the same database in dev/prod profile)
    - h2/psql, psql/psql => `psql.yml`
    - mongo => `mongo.yml`
    - cassandra => `cassandra.yml`, `cassandra-cluster.yml` + other files
    - elasticsearch => `elasticsearch.yml`

- about containerize gateway/microservice application
    - imo, it's useless to have `app.dev.yml`
    - we should have only 1 file: `app.yml`
- proposition:
    - `app.yml` only, use production profile by default

It will impact the [generator-jhipster-docker-compose](https://github.com/jhipster/generator-jhipster-docker-compose) but easy to deal with. And less work in future, because we will use only prod profile when deploying containers

**Comment by erikkemperman** [comment]
Thanks for the detailed response!

I'm not sure if it's possible to have `dev` be the default for the `spring-boot:run` goal while `prod` is the default for the `package` goal... I think that's just not how the `activeByDefault` switch works in maven?

I've tried yesterday to "promote" the maven profile into a spring profile, but I could only come up with a pretty ugly method... Maybe someone has a better idea:

- have a properties file like `src/main/resources/.build.xml` with a value in it like `@profile@` to be filled in from a maven/gradle property.
- read this file in a static initializer; it has to be done very early, before spring goes to look for `application-<profile>.yml`. I think this means it has to be read manually, can't use spring to do this for us.
- if the value starts and ends with @ then don't use it as spring profile but as hint to do `setDocumentRoot` (I.e. Instead of the current check with source location protocol, if this value wasn't substituted we know we're not running from war).
- otherwise set it as active spring profile.

I think I could get this working but it feels kludgy... Thoughts?

**Comment by pascalgrimaud** [comment]
JH3.0 is so closed... so, @erikkemperman, I think it can be done later
The only thing to be sure is to test that all use cases work

About renaming docker-compose files, what do you think ? cc @PierreBesson @wmarques

**Comment by wmarques** [comment]
I like your idea @pascalgrimaud. So now the docker-compose files will only be about the prod profile right ?

**Comment by erikkemperman** [comment]
Well, I think there has to at least be some solution for the `setDocumentRoot` trouble. Maybe the best immediate thing to do is remove it altogether. That would break the case of running prod profile from the IDE, but everything else should work.

**Comment by jdubois** [comment]
Hi guys,

- All the propositions from @pascalgrimaud are good for me -> I have the time to do it today, so I'm going to start this
- I'm also writing the v3 documentation at https://github.com/jhipster/jhipster.github.io/tree/v3_preparation so this need to be in sync
- I don't understand the `setDocumentRoot` issue very well, but for me it's important to be able to run the prod profile from the IDE, so you can test it easily

**Comment by jdubois** [comment]
I've done the Docker migration, so we now have mysql.yml, mongodb.yml....
But I have afterthoughts, it would be better to have all services in a 'services.yml': otherwise it's impossible to do the global Docker Compose for microservices, as we don't know which files we will need. Anyway, it's always easier to have the same file everywhere.

**Comment by pascalgrimaud** [comment]
all services in  ̀services.yml` is a good idea too
