### ISSUE TITLE
setDocumentRoot breaks apps in cloudfoundry

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#3220]
This is a tracking ticket for issue discussed in commit https://github.com/jhipster/generator-jhipster/commit/c9f5949654d4f6d6fd01e296a85ae47f72ed9ef7#commitcomment-16742432

This is actually a blocking issue for cloudfoundry deployment and we need to do something for this

cc @jdubois @atomfrede @erikkemperman 

My suggestion is to do something like below as a workaround for now, this would only affect the case where someone runs the app from the IDE with prod profile, in that case they would have to set an additional profile param `spring.profiles.active=prod,debug`

```
if (env.acceptsProfiles(Constants.SPRING_PROFILE_PRODUCTION) && env.acceptsProfiles(Constants.PROD_DEBUG)) {
        container.setDocumentRoot(new File("build/www/"));
}
```

**Comment by erikkemperman** [comment]
I still think it should be possible to accurately detect whether we're running from a war or not, without a separate profile, but unfortunately I have very little time these days. So this proposal of `prod,debug` looks awkward to me but is obviously better than current broken situation.

**Comment by jdubois** [comment]
I'm sorry I didn't follow this closely enough -> why do we have setDocumentRoot in the first place? I looked in the code and couldn't find an explanation (oh, and this should be documented, also)
We didn't have this before, and it seems that it's causing quite a lot of issues

**Comment by erikkemperman** [comment]
It's needed when running prod profile outside of the war (eg IDE or spring-boot:run) because the optimized web assets are no longer in the default location at `src/main/webapp`. Before they were in `src/main/webapp/dist` and there was a server filter to append the last bit of that path.

The problem is that `setDocumentRoot` shouldn't be called when running inside of the war: it is unnecessary because the assets are packaged along, and actually breaks things if we do call it. But we haven't figured out a nice way yet to detect accurately if this is the case.

The latest attempt, checking the protocol of the source location, is obviously not working out very well; it fixed the case for `java -jar target/foo.war` but not for deploying the war (eg to cloud foundry).

I don't have a lot of time to try this out, but now I'm wondering if we couldn't simply check, in between creating the File object and calling `setDocumentRoot`, if the directory exists? Not sure why I didn't think of that earlier, but it just might solve the whole thing.

By the way, @deepu105  mentioned me in a locked conversation... I've tried to reply by mail but not sure if that works for locked issues: where should I look for updating documentation about the changed directory layout?

**Comment by jdubois** [comment]
OK, thanks for the explanation @erikkemperman 
Indeed, this looks buggy, and we will have issues with other app servers or clouds... So the `setDocumentRoot` should be avoided.
I don't like to have a new profile, it's complication things, and "prod_debug" is strange, when you already have a "dev" profile.
As this is a blocker issue, and there is no easy solution, I have 2 proposals:

- Go back to the servlet filter: it's a bit stupid to have it in prod, but it doesn't do any harm (the perf impact should be very very low), and it's been working without any issues for years...
- Keep it like today but remove the `setDocumentRoot`, so basically won't be able to run in prod mode from your IDE. I don't know if many people do this, so here the impact is that we might have many unhappy people. What's difficult is that I don't know how many.

As this is blocking us for 3.0, I'd be conservative and go back to the servlet filter. It works, it's easy... And then we can take time in later release to see how we can improve it.

**Comment by erikkemperman** [comment]
I don't see how a servlet filter could fix the situation, without also reverting the directory layout changes and the gulp build.

I still hope for an easy solution though... I'm going to try if the simple file existence check I mentioned works. I think it might solve the whole thing,  and the experiment shouldn't take a long time.

**Comment by jdubois** [comment]
Yes, when I mentioned the Servlet filter, I meant going back to the previous situation.

I'm not saying I want to remove this forever, just that we need more time to find a solution.

**Comment by erikkemperman** [comment]
@jdubois I believe I have finally figured out a more or less decent test, made a [PR](https://github.com/jhipster/generator-jhipster/pull/3222).

**Comment by deepu105** [comment]
Finally it works :)
