### ISSUE TITLE
Add Spring @Cacheable abstraction

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3308]
Add support for Spring's [cache abstraction](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html).

Currently we only support Hibernate's second level cache, this works at a higher level, as it can cache Spring Bean methods:

- we should have this default configuration working
- I also want to have caching of REST endpoints -> warning, for security we also need to check the user's authentication, so this might be a bit more complex (doing a GET on `/account` should give the account of the current user, so the user's login must be used in the cache key)

We should support 4 caches:

- [Cafeine](https://github.com/ben-manes/caffeine) as this look very performant for a local cache
- Ehcache as we already have it for Hibernate
- Hazelcast (same reason, we have it for Hibernate), with its clustered configuration for microservices (using Eureka, see it's microservices configuration)
- Memcached -> I want this so we can use a cache with Heroku, see the [cache add-ons here](https://elements.heroku.com/addons#caching). As we can't use Hazelcast on Heroku (as the Hazelcast port is blocked), that's the only way to have a scalable cache with Heroku, so that's very important

**Comment by ouyangshixiong** [comment]
Thanks @jdubois , this feature is just what i want.
I have tried to config self defined ehcache follow this guide : [https://spring.io/blog/2015/06/15/cache-auto-configuration-in-spring-boot-1-3](url) 
Unfortunately, I think jhipster(2.27) can not support this feature.

**Comment by PierreBesson** [comment]
@ouyangshixiong, right now, we are lacking resources to develop better cache support. You are welcome to contribute :smiley:.

**Comment by ouyangshixiong** [comment]
@PierreBesson  I am glad to try it.

**Comment by deepu105** [comment]
And plz try it on katest master :) and dont worry about 2.x versions

**Comment by ben-manes** [comment]
Please let me know if there is anything I can do to help for integrating Caffeine. Integration with Hibernate will probably be when they add JCache (jsr107) support.

**Comment by ouyangshixiong** [comment]
Sorry, I do not think spring boot 1.3+ 's document work for jhipster
_By default, Spring Boot provides cache statistics for EhCache, Hazelcast, Infinispan, JCache and Guava. _ 
I will need more time to figure it out.

**Comment by deepu105** [comment]
I guess thats coz we use a custom implementation for ehcache and hazelcast.
Needs some refactoring ill give this a shot

**Comment by deepu105** [comment]
ok this is definitely tougher than I thought, somehow the spring boot auto configuration doesnt seem to work for ehcahe or hazelcast, might have something to do with all the customization we do for both

**Comment by deepu105** [comment]
I have wasted few hours on this, this doesn't seem to work properly on the resource layer so Im giving up for now, if someone can get it to work let me know

**Comment by ouyangshixiong** [comment]
I will continue to work on the issue. @deepu105

**Comment by ouyangshixiong** [comment]
I spent much time working on this issue.  But I am sorry to say I did not find a possible way to custom spring boot cache auto configuration to fit our jhipster framework.
I even write a simple project original from spring-boot-sample-cache.
I think the problem is : I can find a way to custom spring boot auto configed CacheManager.
the code like this:
`
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.boot.autoconfigure.cache.CacheAutoConfiguration;
import org.springframework.cache.CacheManager;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@AutoConfigureAfter({ CacheAutoConfiguration.class })
public class CacheConfiguration {
	
	@Autowired
	private CacheManager cacheManager;
	
	@Bean
	public CacheManager doSomeCustomize(){
		System.out.println(cacheManager.getClass().getName());
		return this.cacheManager;
	}

}
`
In Configuration class -- CacheConfiguration, the cacheManager autowired is always null.
`
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.cache.CacheManager;
import org.springframework.stereotype.Component;

@Component
public class CacheManagerCheck implements CommandLineRunner {

	private static final Logger logger = LoggerFactory.getLogger(CacheManagerCheck.class);

	@Autowired
	private CacheManager cacheManager;

	public CacheManagerCheck() {
	}

	@Override
	public void run(String... strings) throws Exception {
		logger.info("\n\n" + "=========================================================\n"
				+ "Using cache manager: " + this.cacheManager.getClass().getName() + "\n"
				+ "=========================================================\n\n");
	}

}
`
In the component Class - CacheManagerCheck ,I can get the autoWired cacheManager as I need.
I think spring boot may not initialize the bean at Configuration stage.

But jhipster(CacheConfiguration.java) need to customize cacheManager to fit for io.dropwizard.metrics . If i can not get cacheManger instance at Configuration stage, I can do nothing more.  
Any Suggestion? 
@deepu105

**Comment by deepu105** [comment]
Nope it ate up lot of my time as well :(

**Comment by jdubois** [comment]
I will have a go at this as soon as I have some free time. I've already implemented it several times, I'm sure I can make it work :-)
First release should focus first on Memcached as:

- That's what's supported in cloud providers like Heroku
- It's a different technology to Hazelcast and Ehcache, so we'll have less integration issues

**Comment by PierreBesson** [comment]
@jdubois, when I did my research on memcached. I thought that we should be using: [spymemcached](https://github.com/couchbase/spymemcached) rather than xmemcached or other solutions as spymemcached is now maintained by couchbase and seems more "active" than the alternatives.

For us, the best way to integrate memcached would certainly be using [spring memcached](https://github.com/ragnor/simple-spring-memcached) as it seems to be compatible with Spring Cache abstraction.
For us, the best way to integrate memcached would certainly be using [spring memcached](https://github.com/ragnor/simple-spring-memcached) as it seems to be compatible with Spring Cache abstraction.

**Comment by jdubois** [comment]
There are 3 different things here:

- Hibernate 2nd level cache -> this has worked since the beginning of JHipster. We only support Ehcache/Hazelcast, but that's good enough. So this not an issue for me.
- Having a normal Spring Cache. Using the Spring Cache abstraction works perfectly well, you just need to add the JAR and then use the Spring Cache annotations.
This works with Ehcache/Hazelcast/Cafeine -> I don't think we add any big improvement over what is provided by default, so we should not do it, according to our [Policy 2](http://jhipster.github.io/policies/). I several comments on this, please have a look at how Spring Cache should be configured.
- Have a cache for REST endpoints. This, in fact, is the only scenario where Memcached would fit well. That's a very specific cache, that could only work on gateways, when using microservices. I've had a quick look at it, and it's doable -> as this is something very specific, I'm going to add a specific ticket for that

As the first two issues are solved (for me!) and the third one is going to have a specific ticket, I'm closing this one.

**Comment by deepu105** [comment]
I tried to have the spring cache abstraction with ehcache/hazelcast but it
wasnt working I guess there was some conflicts due to the custom cache
config we have for ehcache/hazelcast. It would appear to work but if you
check your actual method hits and inspect you will see that its always
calling the method. I didn't investigate further.

**Comment by jdubois** [comment]
I just coded with ehcache, no issue at all.

Here what you need to do:

- have a look at [the Spring Cache guide](https://spring.io/guides/gs/caching/)
- In your main App class, add @EnableCaching
- Select the method you want to cache: I created an entity, with a service layer, and annotated the `findOne` method with `@Cacheable("foos")`
- This should be automatically selected, but just to be sure I added `spring.cache.type=ehcache` in my Spring Boot config
- Add the "foos" cache to the `ehcache.xml` configuration (just copy another cache and change its name)

And that's all, now my method is cached...

**Comment by deepu105** [comment]
Ok I guess i didn't do the last step you mentioned. Ill give it a try.
