### ISSUE TITLE
Migration to Spring Cloud RC1 makes JWT token fail in microservices

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3326]
This is in the master branch, it looks like since we upgraded to the latest Spring Cloud RC1 the JWT tokens are not working anymore (for our 3.0.0 release we were using Spring Cloud M5).

This is because the "Authorization" header is viewed as sensitive (in the ZuulProperties), so it is not forwarded anymore to the microservices.

**Comment by gmarziou** [comment]
I think it should be tested also with #3320 as we were pulling wrong version of some dependencies.

**Comment by jdubois** [comment]
OK this is explained [here](http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html) in the "Cookies and Sensitive Headers" section.
That's logical, and indeed I didn't like it that much that we fowarded the JWT tokens, in some cases it could be a security issue.
In our case, I don't think this can be a security issue, but of course this could be challenged.

Now we have 2 simple solutions:

- Set explicitly the headers in each route (that's the "sensitiveHeaders" property). Problem is that we would need to set it for each route, so we can't create routes automatically anymore
- Use another header: problem is that we wouldn't use the standard "Authorization" header anymore

And a more complex one:

- Do a mapping between an "external JWT" token and an "internal JWT" token. That's basically what happens with OAuth2, when internally we use JWT. But then that's more work on the gateway, basically for nothing...

**Comment by jdubois** [comment]
I believe this was coded by @spencergibb -> Spencer, we don't know each other, but I believe we will meet at Devoxx France in a couple of weeks (I'll look for you at the speaker's dinner). Could we have a talk about this?

**Comment by jdubois** [comment]
As a temporary solution I propose we use another header, like "X-JHipster-authentication"

- that quickly solves the issue in master branch, so we have still a working dev environment
- it works the same way as the v3.0.0 release (but with another header), so we don't lose much

Of course this should be discussed, if anyone has better solution?

**Comment by gmarziou** [comment]
Having an external and internal token/header could also bring some benefit: being able to use 2 gateways with different authentication types so you can be sure a token from one gateway cannot be used on the other one.

**Comment by jdubois** [comment]
@gmarziou good point!! I'm not really managing this here, but you'll see it's going to be easier to do with what I'm planning.

So here is what I'm planning to do:

- A new Zuul filter for handling an "internal JWT token" in a specific header
- If we are already using a JWT token, I'm just forwarding it to the new header, as there is no need to change it

As to reach this Zuul filter, you need to be authenticated by Spring Security:

- This gives a new layer of indirection, so if you are just using JWT you could do a new token, for example with new claims
- If you are authenticating a user with another method, you can create a JWT token here -> that means it will be helpful with other authentication methods, like session-based or social login (and I guess with OAuth2 we have something similar already)

As the new "internal JWT token" is only internal, I'm going to do a *big change*: the microservices are not going to validate it. That means:

- A huge security risk if they are accessed directly. They should not, but you need to be aware of that risk.
- No more JWT secret key to copy everywhere, so it's much easier to set up

Any comments?

**Comment by xetys** [comment]
i think there is some research to do, since Spring is referring zuul have special oauth2 solution built in inside. The documentation itself is telling about a built in access token relay, with an option to use the gateway as an Sso, which binds to spring session, and automatically forwarding tokens to the services behind.

it would suprise me, if the new release is really cutting in its own benefits...i will try that out


btw. i am quite sure, that everything was still working after update on RC1 at work...but i will check this

**Comment by xetys** [comment]
maybe #3329 helps with this?

**Comment by srnm** [comment]
I think you _should_ be able to override the default sensitiveHeaders value for all your routes:

https://github.com/spring-cloud/spring-cloud-netflix/blob/5d2065b3e764fcbbbba1d19994b983ea1c8de263/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/ZuulProperties.java

"It's OK to remove those from the list if the downstream service is part of the same system as the proxy, so they are sharing authentication data." 

Even better would be a way to distinguish between internal/trusted downstream services and external/untrusted downstream services.

**Comment by xetys** [comment]
@srnm the distinction is easily possible with oauth2. 

I think the best solution is actually using this TokenRelayFilter in #3329, since it turns the gateway working as at M5. It may make sense to filter the authorization headers, if you don't use it, or a general bypass is acceptable, because the internal/uaa servers will check the headers by their own and fail properly on wrong headers.

But when any kind of distinction is needed by reading authorizations, it is even simple to implement this logic at the TokenRelayFilter. Until there is no solution or idea, in which way the "ignore" decision should be taken, keep it bypassing is ok. The specification can be done at any time later, without letting this issue lead into big changes on microservice generator.

as an idea on that: read the token on the gateway, verify it with the secret key, and set ignore authorization header when this was successfully. a bit more request overhead, but secure, since it only pass the authorization header when the bearer token is generated using the only one valid secret key...

actually, it wouldn't take to much time for me to add this to my PR, if you say you need this little extra

**Comment by srnm** [comment]
@xetys I agree that TokenRelayFilter looks like a fix that works without having to wait for changes to Spring Cloud -- and avoids the more intrusive jh work-arounds proposed above.

**Comment by jdubois** [comment]
Yes agreed, I'm merging it.
