### ISSUE TITLE
Creating a microservise jhipster entity having a realtionship with the gateway user entity

### ISSUE THREAD

**Issue by khouloudkhadija** [jhipster/generator-jhipster#3348]
I want to generate a jhipster microservice entity having a relationship with the user entity but this seems not possible since the user entity does not exist in the jhipster microservices application. How can I deal with this problem.

**Comment by jdubois** [comment]
That's not possible, as the entity is "somewhere else".
What you could do is have a "userLogin" column in your microservice. Of course you wouldn't have a "foreign key" on that login, so you could have consistency issues.

**Comment by khouloudkhadija** [comment]
In my case I created a maven parent project regrouping my microservices and my gateway, so I  thought to extract the database gateway files , so that these file can be seen by all microservices, is it possible to do it ??

**Comment by gmarziou** [comment]
Not with current design.

You must remember that this is the idea behind microservices architecture: each service has its own database. As an example you could also imagine that your access control in gateway could be based on an external service that may store users in an LDAP directory or UAA or KeyCloak.

With current design, microservices have access to user's login and roles through the decrypted JWT token.

**Comment by sugarissimo** [comment]
Hi guyz,

Is there is any new solution about that issue. I am trying to find a way to send request from Gateway to Microservice? Or at least send some more user information (Phone number, email ...) to microservice.

What i wanted to do is basically when an user are just freshly registered, i want to send a request from the gateway to microservice in order to create for example TaxiLocation if the authority of the user is taxi, or create a shop if the user is a Shop manager ...

Thanks for your help.

**Comment by gmarziou** [comment]
@sugarissimo  Please follow our guidelines, this is an issue tracker not a forum for questions.
Your a question should be on stackoverflow and you have already cross posted to i where we answered yout: https://stackoverflow.com/questions/44202383/jhipster-how-to-send-request-information-from-gateway-to-microservice
