### ISSUE TITLE
Choosing a native language doesn't work

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#3491]
When choosing a non-"en" native language in the main generator, the generated application fails. There are many 404 errors on the main page, as it's trying to load "en" localization files.

- This works if you you run the generator again (doing `yo jhipster --force` is a temporary fix), so this can only be tested on a fresh generation
- This is normal, as when the internationalization questions are asked, the "client" and "server" questions have already been asked, so they don't have the internationalization variables set up. And this works when you run the generator again, as those variables are read in the .yo-rc.json at the beginning

@andidev @deepu105 I know you both work on the new "native language" question, can you have a look at this? I've spent the whole evening on it and couldn't find a good solution. My current thought is that the internationalization questions must be asked at the beginning.

**Comment by andidev** [comment]
This has not been a problem for me in the 3.0 release. Is this a new issue caused by some recent commit?

**Comment by jdubois** [comment]
I discovered it this week (I thought there has already been a bug report on it, but couldn't find it again).
I'm pretty sure this existed from the start, as the variables are not set up.

**Comment by andidev** [comment]
Is this the error you are getting?
```
TypeError: insight.trackEvent is not a function
    at Insight.insight.trackWithEvent (/Users/anders/Workspace/generator-jhipster/generators/generator-base.js:1163:17)
    at module.exports.JhipsterServerGenerator.extend.configuring.insight (/Users/anders/Workspace/generator-jhipster/generators/server/index.js:714:21)
    at Object.<anonymous> (/Users/anders/Workspace/generator-jhipster/node_modules/yeoman-generator/lib/base.js:436:25)
    at /Users/anders/Workspace/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:26:25
    at /Users/anders/Workspace/generator-jhipster/node_modules/yeoman-generator/node_modules/run-async/index.js:25:19
    at /Users/anders/Workspace/generator-jhipster/node_modules/yeoman-generator/lib/base.js:448:8
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

**Comment by jdubois** [comment]
No, the app looks OK when I generate it. But when I run it, and go to the main page, it tries to load the "en" language (as the variables where not set up), and I got lots of 404 errors.
Unfortunately I can't give you my `.yo-rc.json` file, as it works if you generate it from a file. You need to generate an new app, with all default options, but choose "fr" as native language, and don't add any additional language. Then run the app and try to access it.

**Comment by andidev** [comment]
Okey so my error is related to a package.json update. Sorry I'm a bit out of date.

**Comment by andidev** [comment]
I can confirm that this was an issue in the 3.0 release.

The problem seems to be that `nativeLanguageShortName` is incorrectly set to 'en' instead of 'fr' for some reason, nativeLanguage is correctly 'fr'.

I really don't understand how this has not yet been discovered.

**Comment by deepu105** [comment]
Ill fix it today

**Comment by deepu105** [comment]
I guess most people where using english as primary language

**Comment by andidev** [comment]
@deepu105 
The problem seems to be that `this.nativeLanguage` is `undefined` in 
[generators/client/index.js](https://github.com/jhipster/generator-jhipster/blob/3db2eccec86a47a3456b2af08e0ea0c1e499e3ad/generators/client/index.js#L230)
and
[generators/server/index.js](https://github.com/jhipster/generator-jhipster/blob/fe51a3c53226c114dfba6528bc2864b48930d393/generators/server/index.js#L840)

and it seems that `nativeLanguage` is not stored in the `configOptions` so it is not available in the `configuring` context

**Comment by deepu105** [comment]
im looking into this

**Comment by deepu105** [comment]
or do you wanna do it @andidev ?

**Comment by andidev** [comment]
If you have time please do help with this. I think you have more knowledge about how the the configuration is passed along the subgenerators than me. I must say I'm a bit confused about how it works.

**Comment by deepu105** [comment]
@jdubois @andidev I have fixed it. Not sure who added the `nativeLanguageShortName` but the concept of shared config is something like this.

Even when we use different generators to compose something together, yeoman actually groups each run phase together and runs them in sequence. It means all the `prompting` phase are run one after other in the composed order, then followed by `default` phase and then `writing` phase. SO in order to share options selected in various composed sub generators the values needs to be set in a global `configOptions` object in the `setSharedConfigOptions` method in each of the sub gen, which can be read only in the `getSharedConfigOptions` method of any sub gen. I have placed these method locations carefully so that the values are availabel in all the sub generators when the `getSharedConfigOptions` method is run. and since this method comes before writing anything you obtain here will be availabel for templates.

To fix current issue I just had to move the line `this.nativeLanguageShortName = this.enableTranslation && this.nativeLanguage ? this.nativeLanguage.split('-')[0] : 'en';` to the `getSharedConfigOptions` since `this.nativeLanguage` will not be undefined here.

@jdubois please let me know if this solves the issue for you, I have tried to create fresh app with different nativeLanguage and it works

**Comment by andidev** [comment]
I think I'm the guilty one here. Sorry for that. 
Thanks for the explanation!

**Comment by deepu105** [comment]
Fault is on my side as well I should have explained this to you guys earlier :smile_cat: 

@jhipster/developers FYI please, something to note on using shared variables in the generator

> Even when we use different generators to compose something together, yeoman actually groups each run phase together and runs them in sequence. It means all the `prompting` phase are run one after other in the composed order, then followed by `default` phase and then `writing` phase. SO in order to share options selected in various composed sub generators the values needs to be set in a global `configOptions` object in the `setSharedConfigOptions` method in each of the sub gen, which can be read only in the `getSharedConfigOptions` method of any sub gen. I have placed these method locations carefully so that the values are availabel in all the sub generators when the `getSharedConfigOptions` method is run. and since this method comes before writing anything you obtain here will be availabel for templates.

**Comment by jdubois** [comment]
Thanks @deepu105 @andidev !!!
As this is quite a big issue, I'm going to do a new release for this, probably on Monday.

**Comment by deepu105** [comment]
A patch release should be fine :+1:

**Comment by pascalgrimaud** [comment]
So my fault too :)
I will make change to our travis build next week and cover better languages options

**Comment by deepu105** [comment]
@jdubois I guess we might have to do a minor release as we have 2 important changes in current master
1. https://github.com/jhipster/generator-jhipster/pull/3403
2. https://github.com/jhipster/generator-jhipster/pull/3324

All other commits are fixes and improvements

**Comment by deepu105** [comment]
we need to update documents as well for the above 2 items

**Comment by jdubois** [comment]
You are right this would be more than just a bug fix release.
I also wanted to add security on the JHipster Registry....

**Comment by deepu105** [comment]
doc for the wiredep part https://github.com/jhipster/jhipster.github.io/pull/259
