### ISSUE TITLE
[FEATURE] Add ability to assert the SQL statement count generated by Hibernate

### ISSUE THREAD

**Issue by ykushch** [jhipster/generator-jhipster#3500]
##### **Overview of the issue**

It would be great if there will be an ability to verify SQL statement count generated by Hibernate in tests.

##### **Motivation for or Use Case** 

Tests should also take care of side effects in SQL performance. Accidentally modifying logic could bring easily additional queries which could lead to performance issues in future but tests would be green anyway.

##### **Suggest a Fix** 

Implement separate test mechanism for verifying SQL statement count generated by Hibernate. 
I could start working on implementation.

**Comment by deepu105** [comment]
You are welcome to add more tests

**Comment by jdubois** [comment]
Yes improvements in tests is always welcome, but:

- For performance tests I don't think this could/should be done in our Unit Tests. It's not the right place to do performance testing, and this is why we have the Gatling tests.
- For the number of statements I don't know how this could be counted. Besides, those could vary depending on many parameters, it's really to hard to know wether it's a good or bad thing. For example, I often do a lot of lazy-loading on collections, which do the famous n+1 requests, but I'm doing this on purpose as I know I have a 2nd level cache, and that in real life this is be much more performant than a eager relationship (which would always do an outer join)

**Comment by ykushch** [comment]
@jdubois Yes, I'm definitely agree that unit tests are not the right place for it. But that could be done in integration tests as well. This is not the replacement for `Gatling` tests. This is some kind of addition that will help to verify the count that Hibernate generates. Of course, this is just a suggestion.
For example, we've created a method for getting users. And we want to verify that no more than 8 `SELECT` queries are involved. In future this could be a lot easier to spot this before code review and in this case to consult with others regarding generated queries.

**Comment by jdubois** [comment]
OK, but still I don't know if it's a such a good idea to count those requests, and maybe this should be in a testing framework, like in Spring Test Context ?
If you have some working code, or want to do a PR, it's of course welcome. You could also do your own module, if you have a lot of code (because this looks quite a specific use case, and I don't want to generate too much specific code, and have to maintain it afterwards).
I'm closing this because I think we all agree that adding some new tests is good, so we'll discuss again your specific code when you have some -> have also a look at modules, so that you don't rely on us too much.
