### ISSUE TITLE
JSR310 support for Cassandra

### ISSUE THREAD

**Issue by cbornet** [jhipster/generator-jhipster#3548]
I would like to add JSR310 dates support for Cassandra. The 3.0 version of the datastax driver has built-in support for this so it would be quite easy if we upgrade the driver.
To note is that ZonedDateTime is mapped to CQL ```tuple<timestamp,varchar>``` to keep the timezone information and it is Instant that is mapped to CQL timestamp.

Actually, for datetime we currently use ZonedDateTime but I think it would be better to use Instant instead since we don't store the timezone information and we always convert to UTC before storage.

So some questions before implementing:
- should we drop ZonedDateTime and use Instant (breaking change) ?
- or should we have both ZonedDateTime and Instant in parallel (kinda redundant) ?
- or should we use ZonedDateTime also for Cassandra ? In this case, do we use the datastax codec or do we write our own that maps to a simple timestamp (more compact than tuple<timestamp,varchar>) ?

**Comment by cbornet** [comment]
@jhipster/developers opinion is welcome :smile: !

**Comment by pascalgrimaud** [comment]
ping @raphaelbrugier too

**Comment by pascalgrimaud** [comment]
By upgrading to datastax driver 3.0, we should be able to use Cassandra 3.0, right?
And users should be able to use older version of Cassandra, 2.0, 2.1 etc => http://datastax.github.io/java-driver/manual/native_protocol/

**Comment by cbornet** [comment]
Yes but currently, I'm having a hard time with spring-data-cassandra as it doesn't support C* 3.0.
I'm not sure why we have the dependency on spring-data-cassandra since we use the driver directly. I will have a look.

**Comment by pascalgrimaud** [comment]
Strange! And our documentation http://jhipster.github.io/using-cassandra/ said :
> The Cassandra CQL driver is used to access the database. We don't use Spring Data Cassandra, as we prefer to use the driver directly. As a result, the repositories contain quite a lot of code

**Comment by cbornet** [comment]
Yes, I don't know why we don't use spring-data-cassandra. @jdubois ?

**Comment by raphaelbrugier** [comment]
Yes, the C* 3.0 driver will support read/write to a 2.x version.

I haven't use the C* 3.0 driver, so I don't know much about the new extra library.
For reference, the javadoc for the codecs you mentioned @cbornet is [here](http://docs.datastax.com/en/drivers/java/3.0/index.html?com/datastax/driver/extras/codecs/jdk8/LocalDateCodec.html).

I don't know if the `ZonedDateTime -> tuple<timestamp, varchar>` could work for timeseries.
In that case, if you want to use a temporal as the primary key you would have to use an Instant in the Java class.

Btw, why did you choose to have only the ZonedDateTime type to store a dateTime when creating an entity? 

And I just realized there is no `time only` type also. Is this not supported because not contributed yet or because you discussed it to be to complicated to support?

**Comment by cbornet** [comment]
I have something working using spring-cql instead of spring-data-cassandra and C* v3.0 :smile:

**Comment by cbornet** [comment]
So I had a look and there is a [pending PR](https://github.com/spring-projects/spring-data-cassandra/pull/52) in spring-data-cassandra for the 3.0 datastax driver support.

Currently, we only use spring-data-cassandra integrated in SB for 3 things:
* Initializing the session with a thread-safe singleton
* Autoconfiguring the driver from properties
* The actuator health check

So the solutions are:
1) wait for a new release of spring-data-cassandra supporting the 3.0 driver and hope it is still compatible with SB (or else we have to wait for SB to integrate it) --> the process can be quite long
2) upgrade the driver and keep current SDC version --> it doesn't work with spring-data-cassandra because of API incompatibility. It works with spring-cql since we would only use the session factorybean. We would have to rewrite the health check. The spring-cql would only half work (for instance, I'm not sure that the cqlTemplate would work correctly)
3) remove all dependencies to spring-data-cassandra/spring-cql and upgrade the driver. We would have to rewrite the session bean, the cluster conf and the health check.

I'm in favor of solution 3 since :
* it's not much work to do and it removes a dependency that we don't really use.
* it gives back all the cluster settings that we lost when migrating to SB 1.3 (such as protocolVersion). 
* it makes us compatible with C* v3 (and still with V2)
* we can use the JSR310 codecs and implement this issue

Opinion, cassandra users ?

**Comment by jdubois** [comment]
Yes we should go with 3, and remove Spring Data Cassandra totally: it's not supported (by the Spring team and Datastax, this is done by some external people), and each time I looked at it I wasn't happy with it (lack of features, etc)
I'm very happy with using the Cassandra driver directly.

**Comment by cbornet** [comment]
OK.
Just one more thing : I just saw that we will also lose the [exception translator](https://github.com/spring-projects/spring-data-cassandra/blob/69e7f41fef0b5b139d3631a2d450543070379a2e/spring-cql/src/main/java/org/springframework/cassandra/support/CassandraExceptionTranslator.java). Is that a big issue ?

**Comment by jdubois** [comment]
Oh I didn't even know about it! Not a big issue for me, then :-)

**Comment by cbornet** [comment]
I noticed something strange : the remember-me token is not stored when using cassandra : https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/security/_CustomPersistentRememberMeServices.java#L128

Is it normal ?

**Comment by cbornet** [comment]
> * should we drop ZonedDateTime and use Instant (breaking change) ?
* or should we have both ZonedDateTime and Instant in parallel (kinda redundant) ?
* or should we use ZonedDateTime also for Cassandra ? In this case, do we use the datastax codec or do we write our own that maps to a simple timestamp (more compact than tuple) ?

I propose to implement the last option for now with a custom codec to map to timestamp (for timeseries performance reason). Yell if you disagree.

**Comment by jdubois** [comment]
@cbornet or update the Driver -> Cassandra 3.0 is coming to DSE anyway, let's upgrade instead, that's less work

**Comment by cbornet** [comment]
The question is not related to the driver or cassandra version. It's about the way we implement ZonedDateTime with cassandra. I'm preparing a PR, we will be able to discuss on it.

**Comment by atoulme** [comment]
@jdubois "Yes we should go with 3, and remove Spring Data Cassandra totally: it's not supported (by the Spring team and Datastax, this is done by some external people), and each time I looked at it I wasn't happy with it (lack of features, etc)"

**Comment by jdubois** [comment]
@atoulme great news that Pivotal takes over the project! I indeed see they [sell support](http://docs.spring.io/spring-data/cassandra/docs/1.4.1.RELEASE/reference/html/#get-started.help.professional) on it, which is very new! I'd be interested to know who at Pivotal does this. 

Anyway, they will need some time before they release a new version - at the time of this writing [the graphs](https://github.com/spring-projects/spring-data-cassandra/graphs/contributors) show that the project was mostly done by 2 people at the beginning of 2014, outside of Pivotal, and not much work has been done since.

I don't have the time right now, but one the thing that has been lacking for years is documentation - if you look at [the current doc](http://docs.spring.io/spring-data/cassandra/docs/1.4.1.RELEASE/reference/html/) it still has empty sections, and many of the things listed look totally wrong. They don't explain how to use Spring Boot's excellent Cassandra auto-configuration - I'm saying it's excellent because I coded it, of course :-)

I'm clearly not a fan of Spring Data Cassandra anyway:

- I'd rather stick to what Datastax provide, they know their product much better, and there is much better documentation and help on their side. 
- What I like with Spring Data JPA are the auto-generation of queries based on method names, as well as pagination and sorting: all those don't really work for Cassandra, or at a very simple level, that don't justify the need for a tool.
