### ISSUE TITLE
New i18n application: build failing on e2e tests

### ISSUE THREAD

**Issue by hdevichi** [jhipster/generator-jhipster#3679]
##### **Overview of the issue**

I am working on a i18n application configured with 2 languages: french & english. French is the default language. My computer is on french locale.

When I build the generated application (out of the box without changes), e2e tests are failing due to i18n issue as tests are expecting english while pages are displayed in french

exemple of error (when generating an entity, but I had the same at app generation):

3) Route e2e test should load create Route dialog
  Message:
    Expected 'Créer ou éditer un Route' to match /Create or edit a Route/.

##### **Motivation for or Use Case**

In all cases, it would be good to have the build of an "out of the box" app work ok.

In theory it could be worked around by passing the browser options in the protractor js config file, but I couldn't make it work.

##### **JHipster Version(s)**

3.4.0

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

please find attached
[yo-rc.txt](https://github.com/jhipster/generator-jhipster/files/295106/yo-rc.txt)

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

Error message given as sample was for an entity but the pb is not with entity: same error in the homepage of a newly generated app (that I fixed since to allow the build to pass)

##### **Browsers and Operating System**

MacOs 10.11
Chrome 50 or firefox 33

##### **Reproduce the error**

Generate a new app with i18n
fr as native language, en as second language

run mvn + gulp itest

##### **Related issues**

searched issues with i18n keyword, didn't find something related.

##### **Suggest a Fix**

refactor the text to use a non i18n keyword, or to use default language
add a browser hint in protractor to force language?

alternatively, document the issue in the README.md generated file to explain how to get a working build.

**Comment by jdubois** [comment]
Indeed, I have never tried this with a non-English locale, and that seems like a very logical issue.

Maybe we could force the EN locale with Protractor. Of course it wouldn't work with an app that hasn't got an EN option -> that should be easy, but that's not a perfect solution.

Could we remove Angular Translate when doing Protractor tests? That would make all use case work, but then we wouldn't test the "real" text that is displayed, so that's like missing the whole point of using Protractor.

Indeed, last solution is that this only works with EN locale, and document this. Then, if you want to have this working, you need to do the translations in Protractor manually. Not a very "automated" solution, then I guess most people will modify many texts anyway.

**Comment by deepu105** [comment]
One solution could be to set the content from the base language as the default text to check on the test case during generation by reading the base language i18n json. similar to what I did for removing translation and replace with the content of json file for placeholders.

**Comment by jdubois** [comment]
@deepu105 would that be complex to do?
Anyway I'm not sure about this: we generate scaffolding code, that will then be changed by users. Most labels will be changed in the end, anyway, so is it really worth the effort to get the correct internationalized label? I'm really wondering what the good solution would be here.

**Comment by deepu105** [comment]
Its not very complex. But i agree that it might not be worth the effort an
alternate would be to check if the header element is loaded instead of
checking the label

**Comment by jdubois** [comment]
Yes but on the other hand, I guess people using Protractor want to test that the correct text is present... So it looks impossible to solve in non-English languages.

**Comment by deepu105** [comment]
In that case dynamic content replace might be the only way, its not very
difficult. Ill try to do it when i find time from angular2 stuff


Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
- One of the good use cases for Protractor is to check that the text is correct, so from my point of view it's quite impossible to solve (unless @deepu105 you have a good trick)
- Then on the other hand, we can't generate failing tests out-of-the-box, that just makes a bad user experience...

Documenting it is good, but still most people won't read the documentation, so the "bad user experience" will remain.

My current idea is to remove those checks: there aren't a lot of them, and we could keep one commented, so that people see how to use them.

Anyway those are just squeleton classes, most of those code should be changed by users, depending on their business needs, and on the read text that will be used in their application.

**Comment by jdubois** [comment]
OK I got it now, the solution is:

- Keep it that way if i18n isn't supported
- If i18n is selected, check the "translate" attribute

So with i18n, we do something like:

    expect(element.all(by.css('h2')).first().getAttribute("translate")).toMatch(/userManagement.home.title/);

**Comment by hdevichi** [comment]
hello

If not possible: Another solution might be to force the browser language to english?

This could be done by configuring it through runtime parameters (preferred language) in the browser driver config - however I tried and it seems quite complex/ platform dependent.

But, more simply, maybe by navigating to english at the beginning of tests? ("clicking" language icon)

**Comment by jdubois** [comment]
The issue is that some people might not select English at all :-)

**Comment by jdubois** [comment]
But indeed with i18n I'm just checking the translation key is correct, not the final text.
