### ISSUE TITLE
Java Based Cassandra Migration Utility

### ISSUE THREAD

**Issue by jd-carroll** [jhipster/generator-jhipster#3684]
I've created a simple Java based Cassandra migration utility using code from jsevellec/cassandra-unit and smartcat-labs/cassandra-migration-tool-java.  The utility uses the same cql files that are already available, however instead of executing them in a separate Docker container, it executes them as part of the cluster creation.

Happy to PR this, if it would be something people are interested in... ?

**Comment by deepu105** [comment]
I thought this was done already!

**Comment by jd-carroll** [comment]
@deepu105 I'm going to repost (I know.. ) what I have in [stackoverflow](http://stackoverflow.com/questions/37515368/java-based-cassandra-migration-utility):

There has been some previous discussion of using liquibase/liquibase-cassnadra similar to the way liquibase is utilized for the other databases (#2074). To be clear, I am not advocating for using the third party liquibase-cassandra as there has been no recent development and I also agree that it is in general unnecessary.

However....

The issue I have with the current migration tool (:+1:) is that it assumes the Cassandra instance(s) will be managed directly from the docker-compose scripts provided.

Proposal:

Move the migration utility from the shell scripts to a Java based implementation that is included in the CassandraConfiguration.java. This way the migration utility doesn't care about where the Cassandra instance(s) come from, only that a connection was successfully created.

The current docker files could be used to create the Cassandra instance(s) which the app/microservice/uaa/etc.. connect to. Thus the connection could be to a local Cassandra instance or a globally available cluster.

Question:

Or am I missing a reason why this would not be possible / be sub-optimal to the current implementation?

The architecture I am basing this reasoning off of is a "database as a service" architecture, where there would be a managed global Cassandra cluster that spans regions/zones which is shared by many/all microservices. **If there isn't this type of "Cassandra as a service", how are people managing clusters across zones/regions?**

**Comment by deepu105** [comment]
Oh ok so you want to migrate from the shell scripts to java.

Lets see what others think

**Comment by jdubois** [comment]
Could you write a clear title?

**Comment by jdubois** [comment]
I'd be happy to have comments from @raphaelbrugier on this, as he coded the current implementation.

**Comment by raphaelbrugier** [comment]
Hi,

First some history. The docker/scripts implementation of the migration tool was produce iteratively and it was not intended at the beginning to produce the tool only with scripts. :)

So, your idea of using smartcat-labs/cassandra-migration-tool-java as a migration tool is welcome. Disclaimer: I don't know this tool and its limitations.

### A few things to be aware of:

##### The current tool does not requires compose:
> The issue I have with the current migration tool (👍) is that it assumes the Cassandra instance(s) will be managed directly from the docker-compose scripts provided.

The script does not assume the Cassandra cluster is also managed by compose, you could also run in standalone for any cluster.
In "manual mode", you would define the CONTACT_POINT environment variable to your cluster ip:
`export CASSANDRA_CONTACT_POINT=your-cluster-contact-point-ip`

This is not clear in the documentation, so I could update it.

##### Running the tool from a service instance:
> [...] included in the CassandraConfiguration.java [...]

The __main problem__ I see of having the migration tool directly run by the application instances is that  you can not guarantee not more than one instance will try to execute the tool at the same time.
With liquibase this is prevented by using a lock table, but with Cassandra you can not use a similar pattern because of the lack of transactions.
This is why I've always advocated for an external tool, integrated in a deployment process.

Of course, you can workaround this by first only deploying only one instance of a new version, then wait for the migration tool to completed before adding new instances of the same version.
But I think this would make the deployment much more completed and error prone.

If you know a way of "locking" the cluster during the migration process, I'm totally in however :)


##### Sharing a cluster for multiple services:
> managed global Cassandra cluster that spans regions/zones which is shared by many/all microservices.

You should be very careful about sharing a cluster for multiple microservices.
At least you should use a different schema.
see: http://microservices.io/patterns/data/database-per-service.html

**Comment by jd-carroll** [comment]
@raphaelbrugier Thanks for the notes!  I was definitely not aware that `CASSANDRA_CONTACT_POINT` could be set and that does accomplish much of what I wanted.  And you are correct that my plan was to deploy a single instance at a time. 

I did test launching multiple instances concurrently and didn't observe any exceptions (even though multiple instances were creating the same table on different nodes).  But, I wouldn't stand by that completely as my testing was very casual.

Each microservice would absolutely have its own schema/keyspace, but I don't know that I agree with each microservice maintaining whole clusters.  I think that kind of plumbing needs to be at an infrastructure level.

I just recently started playing with [Google Cloud](http://cloud.google.com) and this whole idea came about because I was having difficulty spinning up instances.  Let me clean-up the code a little and I'll either PR it here or somewhere else and then folks can decide where/if the code should go from there.

**Comment by raphaelbrugier** [comment]
Good!
I think Cassandra has a "schema agreement" kind of lock for tables creations, but the other concern is about data migration.
Say, adding a column and then filling it based on some existing data.
A good workaround is to have only idempotent queries, but it's not always feasible and I'm not even sure if this would work concurrently.

I'm still not sure to buy the idea of having the app itself doing the migration.
@pascalgrimaud @jdubois what do you think?  

I agree, one cluster per service would probably be a bit of overweighting. 1 keyspace per service  should be enough for most of the use cases.
But it really depends on your services load and you have to be careful.
You don't want a very loaded service to have performance impact on another because of the C* cluster. 

You can keep working on your PR and let me know if I can help.
If we don't want to have the service instance manage the migration, at least we can use your work to do it externally.

**Comment by pascalgrimaud** [comment]
@raphaelbrugier : I'm not a Cassandra expert, but I agree with you -> "I'm still not sure to buy the idea of having the app itself doing the migration" 
I think the idea behind the initial migration tool with Docker was simply to provide a Cassandra database ready to the developer.

**Comment by raphaelbrugier** [comment]
Yes exactly, the initial idea was to provide an easy way to setup a cluster locally and to keep track of the changesets.
It has evolve to a simple migration tool that could be use to migrate any cluster.

**Comment by jdubois** [comment]
@raphaelbrugier @pascalgrimaud I agree with both of you.

Anyway doing this migration utility should be a project outside of JHipster: here we are just providing something, because we didn't have any other option. But normally we would use an external tool to do that job.

I'm clearly not for doing that kind of job as part of JHipster. Then, if someone writes a Liquibase equivalent for Cassandra, I'd be happy to use it.
