### ISSUE TITLE
Different approach to code generating

### ISSUE THREAD

**Issue by seo000** [jhipster/generator-jhipster#3704]
##### **Overview of the issue**

Hello,
as most of developers I have problem when adding a new field to previously generated code. Also when you change something in entity service. Why not separate base files from ext files? Some frameworks like Zend of Ruby on Rails uses this method for years. For example you generate class Car and the extension point CarExt which extends Car. It could work well for some situations.

**Comment by jdubois** [comment]
Did you see that you can run the sub-generator again, and add/remove fields and relationships? That shouldn't be too hard.
Then, of course, you need to do a merge if you modified stuff, but that's the issue with all scaffolding tools.

**Comment by seo000** [comment]
Yes, I saw those new beta functions add/remove fields and if it will be needed in my project I will use them for sure. I just thought I could share my knowledge about aproche from diffrent scaffolding tools. I know it is a lot of work to develop jhipster.
If you are not interested with convention of extension classes you can close this issue.

**Comment by jdubois** [comment]
Yes sorry, I was just wondering if you knew this feature.
Indeed, I know many code generation tools that use this approach, using inheritance. I've also seen some very smart things, that understand when a file is commited to Git: as soon as the file is commited, the generator then does inheritance.
We originally don't work this way, because I just copied on other Yeoman generators, so there wasn't much thinking behind it. Today that's an approach we should consider: I'm not sure how it would work, with Hibernate/JPA for instance. It could be a new option, for example.
Main trouble is that this would be a huge job: I don't think we could do it now, as we are already working on migrating to AngularJS 2, and we can't do 2 big refactoring at the same time.
But there is clearly a study to be done here: how it would work, what would need to be done, and of course the benefits/problems in the end.

**Comment by deepu105** [comment]
@jdubois I guess after we are done with ng2 we can try to do a POC. may be we can start small so that whenever an entity is created we create two sets of files:
1. for java classess one base class with all the default code and another which extends this base and users can further add their code here. We can start with domain and if its ok we can do the same for service, resource and repository. We need to architect this carefully ofcourse. But we have lots of java experts here so this shouldnt be too difficult.
2. for the angularJS part we can utilize ng2 features to modularize the code similarly and use inheritance with typescript, this might be tricky but seems doable.

This would make upgrades and stuff easier.

If the above is successful then we can see how further we can automate the process

**Comment by jdubois** [comment]
Indeed, another reason to wait for AngularJS 2 is that on the client side we might be able to do inheritance like in Java.

I know it's very early to talk about it, so I'd just like to dump here my idea:

- By default we still generate the same files as today
- When a user wants to "take control" of a file, he commits this file into Git
- JHipster looks for commited files in Git, and when a file is commited, it is treated differently: it is not generated anymore -> it just extends a "Base" Class, which is one now being generated (the only change in the user-controled file is that "extends Base..", and then everything stays as the user modified)

As I don't like to have issues opened for several months, I propose to close this for the moment as "will do later", and then we can start this discussion again after our AngularJS 2 support is stable.
