### ISSUE TITLE
Null values are filtered out in generated test during json conversion

### ISSUE THREAD

**Issue by fraf** [jhipster/generator-jhipster#3736]
The generated test :

 ```
@Test
    @Transactional
    public void checkPreValidationCertificatIsRequired() throws Exception
    {
        int databaseSizeBeforeTest = informationBanqueEbicsRepository.findAll().size();
        // set the field null
        informationBanqueEbics.setPreValidationCertificat(null);

        // Create the InformationBanqueEbics, which fails.

        restInformationBanqueEbicsMockMvc.perform(post("/api/informationBanqueEbicss")
                .contentType(TestUtil.APPLICATION_JSON_UTF8)
                .content(TestUtil.convertObjectToJsonBytes(informationBanqueEbics)))
                .andExpect(status().isBadRequest());

        List<InformationBanqueEbics> informationBanqueEbicss = informationBanqueEbicsRepository.findAll();
        assertThat(informationBanqueEbicss).hasSize(databaseSizeBeforeTest);
    }
```

The entity class :
```

@Entity
@Table(name = "STFHPDTB")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class InformationBanqueEbics extends AbstractAuditingEntity implements Serializable
{

 @NotNull
 @Column(name = "VALCER", nullable = false)
 private Boolean preValidationCertificat;
...

}
```
The rest end point : 

```
/**
     * POST  /informationBanqueEbicss -> Create a new informationBanqueEbics.
     */
    @RequestMapping(value = "/informationBanqueEbicss", method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE)
    @Timed
    public ResponseEntity<InformationBanqueEbics> createInformationBanqueEbics(
            @Valid @RequestBody InformationBanqueEbics informationBanqueEbics) throws URISyntaxException
    {
        log.debug("REST request to save InformationBanqueEbics : {}", informationBanqueEbics);
        if (informationBanqueEbics.getId() != null)
        {
            return ResponseEntity.badRequest().headers(HeaderUtil.createFailureAlert("informationBanqueEbics",
                    "idexists", "A new informationBanqueEbics cannot already have an ID")).body(null);
        }
        InformationBanqueEbics result = informationBanqueEbicsRepository.save(informationBanqueEbics);
        return ResponseEntity.created(new URI("/api/informationBanqueEbicss/" + result.getId()))
                .headers(HeaderUtil.createEntityCreationAlert("informationBanqueEbics", result.getId().toString()))
                .body(result);
    }
```

**The whole code above works fine ! The generated test above works fine ! All is OK !**

But just change the entity class like this :

```
@NotNull
 @Column(name = "VALCER", nullable = false)
 private Boolean preValidationCertificat = false;
```

....I just added a default value.
And it failed.

In fact, this test is useless because JSON transformation DOES ignore null values :
```

/**
     * Convert an object to JSON byte array.
     *
     * @param object
     *            the object to convert
     * @return the JSON byte array
     * @throws IOException
     */
    public static byte[] convertObjectToJsonBytes(Object object)
            throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        mapper.setSerializationInclusion(JsonInclude.Include.NON_NULL);
...
}
```

**Comment by deepu105** [comment]
I dont see anything wrong here. The generated test is for the generated entity, if you alter the entity you have to alter the test as well. Simple as that.
The test checks to see if there is an error thrown when a required field is not set. If yiu set a value always then the error wont be thrown and the test fails and thats a valid failure.

**Comment by fraf** [comment]
I don't agree with you. It is not because I set a default value to the entity that the result of the test change. Moreover, the test forces it to null (supposed to force it, because technically, it is not the case).

**Comment by deepu105** [comment]
I lost you there. Do you mean the test is not setting the value to null?


Thanks & Regards,
Deepu

**Comment by fraf** [comment]
Yes. More exactly during json serialization. Null values are filtered. Look at the converter.

**Comment by deepu105** [comment]
Ok fair enough. Do you want to do a PR?

**Comment by fraf** [comment]
I just revealed the (minor) bug. I prefer let someone else to correct it eventually. I'am a jhispter end user :).
Your title editing is quite better ! :)

**Comment by cbornet** [comment]
@fraf Well, you modified the code generated by jhipster so it's no wonder that you also have to modify the test... The jhipster app behavior is expected since if the client don't send the NULL, it uses the default value and since you modified it to non-null the bean validation passes.

That said, I don't think it's a harmful to serialize all NULLs in our test requests. Do all your tests pass if you modify the mapper ?

Eventually, note that during deserialization, the meaning of "required" may vary between "must be present in the JSON payload" and "must not be set to NULL in the JSON payload". If you take [JSON schema validation](http://json-schema.org/latest/json-schema-validation.html#anchor61), then it must be present in the payload. But in Jhipster, it currently means that it must not be set to NULL in the JSON payload. To force it to be present in the JSON payload, it should be put in a JsonCreator constructor with DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES enabled.
@jhipster/developers what do we intend to mean by "field is required" ?

**Comment by jdubois** [comment]
"required" means `@NotNull` with Beans Validation. Usually we follow what the Java framework we use do, so it's less surprising to users.
So for me this attribute should be present in the JSON data, with some payload.
But to be honest I don't understand this ticket...

**Comment by fraf** [comment]
You mean the test just test the @Valid annotation at final.
I was thinking the user intentionnally passes null value to the required field but he can't, json converter filtered it.

**Comment by cbornet** [comment]
@jdubois our bean validation occurs after creating the bean so the attribute is actually not mandatory in the JSON payload. But as our default value for bean attributes is ```null```, if the attribute is not present in the payload, it is set to null and then the bean validation will reject it. @fraf modified the default value to something else than null so if he doesn't set explicitly the attribute in the payload, this value is used and the bean validation passes.

Say we have entity Foo with attributes bar and preValidationCertificat "required".

In a default jhipster, we have
```java
@NotNull
private Boolean preValidationCertificat;
```

In the modified jhipster, we have
```java
@NotNull
private Boolean preValidationCertificat = false;
```
If we send ```{"bar":"baz"}```
* Default jhipster: foo.preValidationCertificat is null so bean validation rejects
* Modified jhipster: baz preValidationCertificat is false so bean validation accepts

If we send ````{"bar":"baz", "preValidationCertificat": null}```
* Default jhipster: foo.preValidationCertificat is null so bean validation rejects
* Modified jhipster: baz preValidationCertificat is null so bean validation rejects

**Comment by jdubois** [comment]
Thanks for the clarification @cbornet but then, this isn't a JHipster issue - with our default setup, it works correctly! Is there something I still don't understand here?

**Comment by cbornet** [comment]
Yes the default works well.

A question would be wether we generate a JsonCreator constructor with the required arguments and set FAIL_ON_MISSING_CREATOR_PROPERTIES to true to handle the required properties at the Jackson level instead of bean validation.

We can also make the test serialize the null : the default test will pass and @fraf 's one also

@fraf depending on what you want to do if the "required" value is not in the payload:
* if you consider that the default value should be used: change the test to serialize the nulls
* if you consider that it's an error: add a JsonCreator constructor and set FAIL_ON_MISSING_CREATOR_PROPERTIES to true

**Comment by fraf** [comment]
ok thanks for clarification. Setting a default value for my "Json Object" on the required attribute, the meaning of the test implies that what you said in first point : change the test to serialize the nulls.
I retain that required means @NotNull as @jdubois said.

I close this misunderstood/ambiguous ticket.
