### ISSUE TITLE
ErrorGradle,  java.lang.String cannot be cast to org.gradle.api.JavaVersion

### ISSUE THREAD

**Issue by renanrboliveira** [jhipster/generator-jhipster#377]
- What went wrong:
  Execution failed for task ':eclipseJdt'.
  > java.lang.String cannot be cast to org.gradle.api.JavaVersion

I tried:
sourceCompatibility= '1.7'
targetCompatibility= '1.7'
but still the same problem. Now, if I remove the two line, stay ok!

**Comment by francisoud** [comment]
Testing JHipster for the first time also ;) I stumble on the same issue.
I wanted to setup IDE support for it so added those 2 lines
```groovy
apply plugin: 'eclipse'
apply plugin: 'idea'
```
And as explain by @banzera you need to move the 
```
sourceCompatibility=1.8
targetCompatibility=1.8
```
from ```gradle.properties``` to ```build.gradle```

It is clearly a gradle issue (see https://issues.gradle.org/browse/GRADLE-1666 or https://issues.gradle.org/browse/GRADLE-1350)

But (even if I'm not an expert in gradle too), the usage of ```gradle.properties``` in jhipster confuses me.
For me ```gradle.properties``` is use to set "internal props" of gradle such as deamon usage or jvm memory args for exemple . 
see: http://gradle.org/docs/current/userguide/userguide_single.html#sec:gradle_configuration_properties

I though (and tried) to put those properties in the ```build.gradle``` (with def var = '') because it felt more "the gradle way" but putting ```liquibase_hibernate4_version``` property in ```gradle.properties``` is a easy way to set a version number in on single place the ```gradle.properties``` and it will be visible in ```liquidebase.gradle```

So sticked with the easiest solution see pull request

**Comment by tdavis61** [comment]
It would be nice to actually have the solution printed here before you closed it.
The problem is that in the build.gradle the Java{...} item needs one of these version enums.

> Cannot convert string value '1.7' to an enum value of type 'org.gradle.api.JavaVersion' (valid case insensitive values: VERSION_1_1, VERSION_1_2, VERSION_1_3, VERSION_1_4, VERSION_1_5, VERSION_1_6, VERSION_1_7, VERSION_1_8, VERSION_1_9, VERSION_1_10, VERSION_11, VERSION_12, VERSION_13, VERSION_14, VERSION_15, VERSION_16, VERSION_17, VERSION_HIGHER)

The solution is to enter it as
    java {
        sourceCompatibility = JavaVersion.VERSION_1_7
        targetCompatibility = JavaVersion.VERSION_1_7
    }

I'm using Java 14 so mine was updated to 

    java {
        sourceCompatibility = JavaVersion.VERSION_14
        targetCompatibility = JavaVersion.VERSION_14
    }

And then my Gradle 6.6.1 built  **gradle.build** successfully.

**Comment by tdavis61** [comment]
Note:
If your using gradle 5.6.4
Then VERSION_14 isn't declared.
You need to user JavaVersion.VERSION_12                    (last defined version for that gradle)
(the 1.14 JDK works fine with this setting ).
