### ISSUE TITLE
Add option for string PK instead of long for generated entities

### ISSUE THREAD

**Issue by cm325** [jhipster/generator-jhipster#3853]
##### **Overview of the issue**

Currently the PK "id" is added automatically, and there's no option to make it a String instead of a Long. Our dbas only want string pks (they usually look like G00001), and it's a fair number of changes to fix this after generation. I don't mind having to customize the sequence generation (I can see how that's clearly beyond jhipsters scope), but because of all the fks, afaik, there's no easy way to change the column type afterwards. The liquibase file would have to first remove all the fks, make the changes, and then re-add them.

**Comment by deepu105** [comment]
We are sorry, This is a specific requirement for you and not something that we would like to change for everyone. the current long running ids are perfect for most people. what you can do is you can have a field called `identifier` with type string in your generated entities if you want and can ignore the ID generated as its internal anyways.

**Comment by deepu105** [comment]
I'll keep the issue open to see if anyone from @jhipster/developers have a different opinion

**Comment by sendilkumarn** [comment]
I too feel the same, have an unique column for `identifier` will solve the problem.

**Comment by jdubois** [comment]
Just some explanations on why we use a Long (for SQL databases only), as I'm the one who made that decision at the very beginning of the project:

- It's faster for joins on "most" databases. For instance, with MySQL. Of course it depends on the underlying implementation, but it's quite logical joins will work better with a Long than with a String. They are also shorter, so that's obviously better.
- On Ruby on Rails, by default, the `id` is called `id` (like us), and is an Integer. For a PK, however, I felt that using a Long is much better than an Integer, as the idea is that you'll probably store quite a lot of data in some tables, and don't want to have the max integer limit

So I'm against modifying this for everyone. Then it could be an option, but we can't have options for everything, and this looks like a very specific use case.

It shouldn't be too hard to modify your JHipster code if you do a refactoring with your IDE. Of course you'll also need to refactor the Liquibase code, but all those `id` columns are the same, so a search/replace should do the trick.

If this is really a need for you, you could also do your own module, that modifies the generated code - that's a good use case for a module, in fact.

**Comment by cm325** [comment]
Hi, yes, I expected this would be an optional change, as I think you're spot on with you're justification for using longs (alas, I am not in charge of the db). At least in Eclipse, there's no easy way to refactor a field's type, so I have to change it, and then run through the quick fixes (which is straightforward, if not tedious). I don't even get a quick fix for changing the types automatically in the interfaces either :(

Making all of these changes for a few entities might not be too bad, but since every table in my db is like this, I've got 8 tables and counting that I need to make the changes for, and it took a while. And of course, all these changes means I lose out on the ability to add/remove fields in the future without a lot of cherry picking.  I'll investigate the module route-

**Comment by cbornet** [comment]
Does hibernate sequence work with non integer pk ?

**Comment by ActionAdi83** [comment]
What if we need an entity with UUID id? Should we not use JHipster?

**Comment by pascalgrimaud** [comment]
@ActionAdi83 :
- you can update the generated code, and replace long by UUID, as the generated code is yours
- you can try to use this module: https://github.com/amitjindal/generator-jhipster-postgresuuid-converter
    - but as it isn't updated since 2017, not sure it will work
    - then, you can try to update this module, help the maintainer and update it for JHipster 6 ?
- last solution, you can code a specific module to provide this option to other users, so the module will belong to you and you'll need to maintain it
