### ISSUE TITLE
Field names for enumerated values for I18N not generated

### ISSUE THREAD

**Issue by russTbaker** [jhipster/generator-jhipster#3883]
##### **Overview of the issue**

After generating an entity in an internationalized microservice with an enum and then generating the entity in the gateway, field names are not generated resulting in <appname>.<enumclass>.<enumFieldName> in rendered AngularJs page.

##### **Motivation for or Use Case**

I would like to leverage the internationalization capabilities.

##### **Reproduce the error**

1) Generate an internationalized microservice.
2) Create an entity with an enum
3) generate the entity in the gateway (Also internationalized)
4) Select the newly generated entity from the "Entities" dropdown
5) Click on the "Create a new <entity>" button.
6) Select the enum values from the select options

##### **Related issues**

Might be related to #3879 

##### **Suggest a Fix**

?

##### **JHipster Version(s)**

3.5.0

**Comment by ruddell** [comment]
@russTbaker This was also fixed in #3879.  Until the next release you will need to manually fix it if you want to use translation with enums (or use the master version but it's constantly changing).

For a `Foo` entity with a `Name` enum (values Jon, Russ), create a file called `src/main/webapp/i18n/en/name.json` - replace gatewayApp with your application's `basenameApp`
```
{
    "gatewayApp": {
        "Name" : {
            "null": "",
            "Jon": "Jon",
            "Russ": "Russ"
        }
    }
}
```
