### ISSUE TITLE
Change the place of scss vendor file

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster#3943]
##### **Overview of the issue**

When using scss and importing some modules changing bootstrap styles it won't work as expected (e.g. https://github.com/moifort/generator-jhipster-bootstrap-material-design/issues/9), because bootstrap styles of a theme (coming from bower) are always overwritten by vendor.css with default styles.

##### **Motivation for or Use Case**

See here: https://github.com/moifort/generator-jhipster-bootstrap-material-design/issues/9

##### **Suggest a Fix**

Just change the place of the injected compile sass:

```html
<!-- build:css content/css/vendor.css -->
<!-- bower:css -->
<!-- endinject -->
<%_ if(useSass) { _%>
<link rel="stylesheet" href="content/css/vendor.css">
<%_ } _%>
```

Will become:

```html
<%_ if(useSass) { _%>
<link rel="stylesheet" href="content/css/vendor.css">
<%_ } _%>
<!-- build:css content/css/vendor.css -->
<!-- bower:css -->
<!-- endinject -->
```

##### **JHipster Version(s)**

>= 2.27

@jhipster/developers Did I forget some consequences of this change? It seems it won't have an effect to something else.

**Comment by deepu105** [comment]
@atomfrede  `content/css/vendor.css` is actually created during `gulp sass` from `scss/vendor.scss` and the line `<!-- build:css content/css/vendor.css -->` makes sure the concatenated minified file during `gulp build` is placed as `content/css/vendor.css`  as well, so both uses the same file name. In dev mode the file would have compiled css from`vendor.scss` and in `prod` it will have all the bower css and `content/css/vendor.css` stitched together. I understand the issue here but the solution you suggest will exclude the result of `scss/vendor.scss` from concat and minification as well. I assume what you wanted is 
```
<!-- build:css content/css/vendor.css -->
<%_ if(useSass) { _%>
<link rel="stylesheet" href="content/css/vendor.css">
<%_ } _%>
<!-- bower:css -->
<!-- endinject -->
```

but even with this there are chances that our customization in `vendor.scss` if any will be overwritten by any bower lib css, the file is actually placed after the bower files files so that any custom changes we do take precedence.

The issue here is unique for this use case so a better solution would be to use the sass files from the theme by adding some overrides for main and dependency of the lib to our `bower.json` file when installing the module. This will ensure that the sass files are injected into the `scss/vendor.scss`

**Comment by atomfrede** [comment]
Thanks @deepu105 for the detailed answer. Let's close this here and try to fix it in the module.

**Comment by nicoguevara** [comment]
Good afternoon, I have the same inconvenience for some time and I still can not solve it, every time I run the project with profile Prod, the styles are overwritten.
If a solution has already been found, I appreciate your help.

**Comment by gmarziou** [comment]
Please don't post on an old issue, open a new one and provide all the details required.
