### ISSUE TITLE
MySQL integration broken when using utf8mb4 encoding

### ISSUE THREAD

**Issue by axelfontaine** [jhipster/generator-jhipster#3996]
##### **Overview of the issue**

When using JHipster with a MySQL database configured to use UTF-8 (utf8mb4), the schema creation fails with `com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes` due to the reasons outlined here: http://stackoverflow.com/a/22515986/350428

##### **Motivation for or Use Case**

The utf8mb4 encoding is the only *true* UTF-8 encoding for MySQL

##### **Reproduce the error**

1. Generate a new JHipster application and select MySQL. 
2. Configure the MySQL instance to use utf8mb4
3. Configure the JHipster application to use that MySQL instance
4. Start the JHipster application
5. Liquibase fails due to the MySQL exception above!

##### **Related issues**

None

##### **Suggest a Fix**

Change the varchar(255) references in the schema to varchar(191) or stop using varchar columns as primary keys

##### **JHipster Version(s)**

Latest from npm

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

```
{
  "generator-jhipster": {
    "jhipsterVersion": "3.5.1",
    "baseName": "jhipapp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "session",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": "no",
    "websocket": "no",
    "databaseType": "sql",
    "devDatabaseType": "h2Memory",
    "prodDatabaseType": "mysql",
    "searchEngine": "no",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "rememberMeKey": "20ca46979c8e88947934d6947fa4e2788fc16bff",
    "useSass": false,
    "applicationType": "monolith",
    "testFrameworks": [
      "gatling"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A (fails on startup, regardless of the OS)

**Comment by jdubois** [comment]
Thanks for the report @axelfontaine (and btw we should work on Flyway with JHipster!)

We've already got similar issues like #307 so I'm not too surprised.

We do use varchar on some very specific tables (on "normal" tables we don't), for example in your application, that's how we store the persistent token we use for securing your application with our own Spring Security remember-me implementation (see the `jhi_persistent_token` table). I'm pretty sure this should be OK.

**Comment by jdubois** [comment]
For the record: this can be tested with our Docker image by adding ` --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci` to the command line

**Comment by jdubois** [comment]
This works on the version we release in our Docker Compose and Kubernetes configurations (latest 5.7 version), but not if we downgrade to MySQL 5.6.
So I guess this was corrected in the latest MySQL release, and you are using an older release.

I'm checking to see if we can reduce those index length anyway, as it's useless to have them so big.

**Comment by axelfontaine** [comment]
@jdubois Yes, let's do this! I would be happy to assist!

P.S.: We at Boxfuse have just launched first-class support for JHipster with one command zero downtime deploys to AWS. See https://boxfuse.com/getstarted/jhipster Would it be OK if I sent your a PR for https://jhipster.github.io/aws/ or a new page to let JHipster users know about this option?

**Comment by jdubois** [comment]
@axelfontaine 

- For Flyway integration: this is a big subject, I'm going to create a specific ticket for this (I was going to do one anyway). This will lead to some big discussion, and will take time.
- For BoxFuse: I didn't know about this, this is insanely great!!!!!!! Why didn't you tell us before??? Yes you should have a specific "production" page, like Heroku/CloudFoundry/Kubernetes/AWS - I can create a template if you need to (otherwise that's pretty simple, have a look at https://github.com/jhipster/jhipster.github.io ). And we should tweet, and let people know about it!!! I'm tweeting this right away, but we should do more!

**Comment by jdubois** [comment]
So I'm able to solve the length issue everywhere, excepted for our OAuth2 support (which isn't very widely used, less than 1% of people last month!!! So let's not worry too much).
I'm not doing this for OAuth2 because of http://stackoverflow.com/questions/8098515/can-access-token-be-longer-than-255-characters -> I'm expecting some people might have 255-length tokens, even if I have no idea if people use those or not.
And as mentioned in the StackOverflow question, we shouldn't limit those to 255 anyway.

**Comment by axelfontaine** [comment]
@jdubois Thank you very much for the kind words about Boxfuse and the tweets!! We do indeed share a lot of the same design goals as JHipster: combining existing best-of-breed technologies, a great out-of-the-box experience (it just works), eliminating complexity and infrastructure headaches and freeing more time to actually work on the app.

I have submitted a PR for the docs: https://github.com/jhipster/jhipster.github.io/pull/300 

Please let me know if you want anything added or changed.
