### ISSUE TITLE
no cloud config in boostrap phase

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#4132]
I was about building our first 3.7 service at office and lost a couple of time by looking, why several settings not work....

if you start a JHipster application from war directly, or using docker....at the very first moment no bootstrap configuration is loaded. So setting SPRING_CLOUD_CONFIG_URI doesn't override anything, and finally a lot of things fail. In my case I don't get any connection to SQL db, because the config never arrives the app.

to reproduce that issue, just start a microservice using `java -jar` or docker, and watch the first line commiting a successful handshake with config server (like `s.n.www.protocol.http.HttpURLConnection  : sun.net.www.MessageHeader@7d3e86556 pairs: {GET /config/UAA/dev/master HTTP/1.1: null}`) is missing...

I guess this may have something to do with work on DefaultProfileUtil, which recently was done...

**edit:** copying bootstrap-prod.yml to bootstrap.yml is a dirty fix to that issue

**Comment by PierreBesson** [comment]
Well, initially, the app can be either in dev profile or in prod, that's why we have a bootstrap-dev and bootstrap-prod. Is there a bug that cause the app not to pick up it's profile correctly.

**Comment by xetys** [comment]
i am currently on it...I report as soon I got some results

**Comment by xetys** [comment]
it seems to work sometimes....it's harder to reproduce than it looked like....however in production something goes heavily wrong because of not contacting cloud config server

**Comment by xetys** [comment]
well, I still can't say what is exactly wrong....
I am missing the config fetch during startup in my production and also when starting a UAA using docker....when I point to spring.cloud.config.uri via ENV and maintain database url inside...this doesn't work....

I will have to spend some more time on it....but it seems for config to be broken somehow...and I hate I have no more accurate description of that issue....maybe this have something to do with the 32 degrees in my office now..

**Comment by PierreBesson** [comment]
@xetys Thanks for investigating the issue. Does your uaa-setup repo allows to reproduce the bug ?

**Comment by xetys** [comment]
The docker setup specifies all important config variables over environment, so they are able to run there. For some reason it happens to me, that since 3.7 the services just do not connect to cloud config, and still don't fail. I share database config over the config server, so I recognized this behaviour. Note, I am not using docker compose in production, and so not provide SPRING_DATASOURCE_URL

**Comment by PierreBesson** [comment]
@xetys I wonder if your problem comes from the my recent refactor of src/main/docker/central-server-config to have it work in dev when using src/main/docker/JHipster - registry.yml.
I'm really sorry if this is the case.

**Comment by dasbh** [comment]
More Info:

Reverting DefaultProfileUtil to previous version picks up the bootstrap-{profile}.xml file.

Previous version read the application.yml file from classpath and extracted the active profile and added it as ```spring.profiles.active``` as a property before spring booted.

Previous implementation of ```DefaultProfileUtil.addDefaultProfile``` was a misnomer it never set ```spring.profiles.default``` instead it was assigning active profile which it read from the yml file early in boot sequence.

After this commit [https://github.com/jhipster/generator-jhipster/commit/4ff09c2c30395709ff55e37edf17ebef10eb83ad] method is changed to ```spring.profiles.default```  without any gaurd condition to devleopment profile may be spring will never look into default profile unless there is no active profile.   But the regression there is no code which sets up the active profile prior to boot sequence.  

Passing --spring.profiles.active from cmdline or setting SPRING_PROFILES_ACTIVE ENV variable does resolve this as the property is set early.

Other way to solve this issue is to have
```
bootRun {
        args = ["--spring.profiles.active=dev"]
    }
```
In gradle file ( This use to be the case prior to 3.x). However this will not help folks wh wants to run the app from IDE ( Intellij run main)

**Comment by xetys** [comment]
@dasbh this seems to be related to my issue, i will check this right tomorow in the morning

**Comment by deepu105** [comment]
I really hate the spring boots property and profile loading sequence. Its
very chaotic and confusing. Its definitely not as clean as they claim in
the documentation. The earlier code in the DefaultProfileUtil was a hack to
handle a spring boot bug, thats why I removed it when the bug was partially
fixed. But if its causing too much issue then lets revert back to the hack
itself.

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
Btw FYI, the default profile is used only when you run app from an IDE
otherwise the active profile is set in the application.yml file and is
loaded from there.

Thanks & regards,
Deepu

**Comment by xetys** [comment]
ok, I just restored `DefaultProfileUtil` and `ProfileInfoResource` to the previous state and my applications are no longer failing anymore.....

So I suggest now 2 ways to go: revert to the hack or build some shared consensus where the new and the old needs are fit. But in the current state we cut of spring cloud config support for microservice, which is unacceptable for production running

If you ok to revert it for now, I can do it...my current sprint is done since yesterday and I got time for that

**Comment by deepu105** [comment]
@jdubois do you have any issue in reverting this?

**Comment by jdubois** [comment]
@deepu105 I did not follow this close enough to have a good opinion.
But clearly the current situation isn't good, so we can't stay like that.

**Comment by deepu105** [comment]
@xetys @dasbh before we revert this I want to check with you one thing, since you seem to have a setup to reproduce this, we do set active profile using the `application.yml` and spring is indeed loading the appropriate profile from `application-{profile}.yml` file. hence I wonder why the same doesn't work for the bootstrap files?

**Comment by dasbh** [comment]
I have added below config to application-dev.yml as per  #4146
```
    profiles:
        active: dev,swagger
```

Still running ./gradlew shows as its trying connect to default config server.

```
----------------------------------------------------------
        Config Server:  Not found or not setup for this application
----------------------------------------------------------
```

**Comment by brunnels** [comment]
I am experiencing this issue and can reproduce as well if you need any additional testing resources.

**Comment by jdubois** [comment]
I'm sorry, I still didn't have enough time to work on this -> @deepu105 it looks like reverting the DefaultProfileUtil solves the issue (and I didn't have any issue at that time), are you OK to revert it?
I could do a minor version quickly to solve this for everyone.

**Comment by deepu105** [comment]
Yes if its affecting others then lets revert back to the hack. In that case
we can remove the active profile hack introduced in the dev profile as
well, as this hack will cover that. Lets take time to investigate and find
a proper fix later.

Thanks & regards,
Deepu

**Comment by xetys** [comment]
I already prepared that in #4155, if it is ok....I am ok if in future will be a more elegant solution, but for now I think it's better to revert

**Comment by PierreBesson** [comment]
Guys ! I just found a way to make it work !
The trick is to add a bootstrap.yml with spring.profiles.active=#maven profile#

**Comment by agoncal** [comment]
Looks like the configuration of the active profile arrives too late. With @PierreBesson we gave a try at changing the ordre. For that we created a file `bootstrap.yml` with the following code which we got rid from `application.yml`:

```
spring:
    profiles:
        active: #spring.profiles.active#

```

**Comment by deepu105** [comment]
guys also please not that spring-boot 1.4.1 has arrived which has the fix for the issue I raised so now `spring.profiles.include` should work as well

**Comment by deepu105** [comment]
im gonna PR upgrade to SB 1.4.1

**Comment by PierreBesson** [comment]
@xetys, please tell my PR fixes your issue.

**Comment by xetys** [comment]
I will need to test that

**Comment by PierreBesson** [comment]
To explain my fix it's actually not that complicated. @jdubois, @xetys, @deepu105

Maven/Gradle is substituting the spring.profile active property in application.yml. However for microservices the startup sequence is the following : load properties first from bootstrap.yml, then fetch them from config server and then finally from application.yml. Since the profile is set in application.yml. So this is actually too late to be fetching the correct profile from the config server. QED. 
So the fix is to do the profile property substitution in bootstrap.yml for non monolith.

The reason it was working before was because of the DefaultProfileUtil hackery. Which is not needed now please don't put it back !

**Comment by deepu105** [comment]
Pierre I understand and agree that this should be the right way. I too dont
want to put the hack back.

Thanks & regards,
Deepu

**Comment by xetys** [comment]
I will have time to check this in a few hours, if this works, I am OK with that, of course
