### ISSUE TITLE
permission error when installing bower in production

### ISSUE THREAD

**Issue by israeleriston** [jhipster/generator-jhipster#4137]
Gentlemen, good evening, was a problem running application to production mvn -Pprod to install bower maven demanded permission, I do not know if anyone of you this through or have gone through the same problem, then the line 792 maven added arguments allowing User root run setup bower <arguments> install --no-color --allow-root </ arguments> I do not know if I'm following the rules repository to ticket opening, but if any of the core committers team, be able to add in the next versions this line will greatly help those who work with linux servers in their applications

**Comment by jdubois** [comment]
It looks like you are running your application as `root`, and indeed Bower doesn't like that (downloading stuff from GitHub and running them as root isn't a good idea).
It's true we don't have any documentation for that, but I would advise against running the app as root. Then, of course, this setting will make your app work.
Oh, and don't take my comment as a critic: I know this issue because I was doing exactly the same thing during the first months of JHipster!

**Comment by israeleriston** [comment]
okay ... no problem, any complaint is welcome!

**Comment by pascalgrimaud** [comment]
As Julien said, it's not recommanded to run bower as root.
Anyway, if you are logged as root, you can try to put this, inside /root/.bowerrc :
{ "allow_root": true }

**Comment by jdubois** [comment]
Closing as we have a solution - not sure if we should document that, because of [Policy 1](https://jhipster.github.io/policies/)

**Comment by accferronato** [comment]
I'm having the same problem, but when I run the application without the root one yarn error appears. 

Running the application as root I have the same bower problem presented above.
Any help?? I don't know what else to do.

**Comment by gmarziou** [comment]
@accferronato please don't comment on an old closed issue as we don't have any idea of your environment, please open a new issue with all required details if you think it's an issue in JHipster otherwise use stackoverflow or gitter.
