### ISSUE TITLE
Some jackson-datatype-* are unused and/or uninitialized

### ISSUE THREAD

**Issue by unknownboy** [jhipster/generator-jhipster#415]
Hello,

First thank you for your fantastic work !

Where are initialized and used the following maven dependency :

``` xml
<groupId>com.fasterxml.jackson.datatype</groupId>
<artifactId>jackson-datatype-json-org</artifactId>
```

``` xml
<groupId>com.fasterxml.jackson.datatype</groupId>
<artifactId>jackson-datatype-hppc</artifactId>
```

As far as i know, there is no custom object mapper to initialize the datatype modules (joda, hibernate and theses two). Something like this need to be used as a property to org.springframework.http.converter.json.MappingJackson2HttpMessageConverter : 

``` java
ObjectMapper mapper = new ObjectMapper();
mapper.registerModule(new JodaModule());
mapper.registerModule(new Hibernate4Module());
```

Please let me know if I am wrong. I can submit a pull request to remove the two unused datatype modules and to provide an initialization of the two used datatype modules.

**Comment by cm325** [comment]
It appears that the Jackson2ObjectMapperBuilder with "findModulesViaServiceLoader" in the JacksonConfiguration is now actually picking up Hibernate4Module automatically as well, just by being in the classpath. This is problematic, because even if you configure the module manually (i want SERIALIZE_IDENTIFIER_FOR_LAZY_NOT_LOADED_OBJECTS to be true for instance), a default version of the module is picked up and overrides the configured one. It would seem that manual configuration of these modules might be a better way to go-

**Comment by cbornet** [comment]
What version of JHipster are you using ? From v3.5.0, we don't use findModulesViaServiceLoader() anymore. We use the standard SB autoconfig and just do some post config of the ser/deserializers

**Comment by gmarziou** [comment]
@cm325 please don't camp on an old issue (2years old), open a new one.

**Comment by cm325** [comment]
Ok,
Great, looks like I was using 3.4.1, so I'll go upgrade. I didn't want to make a new issue until I was sure there was an issue, but if you don't like this approach for your project, I can open new issues, no problem-
