### ISSUE TITLE
CachingHttpHeadersFilter shouldn't add cache headers to 404 responses

### ISSUE THREAD

**Issue by kutzi** [jhipster/generator-jhipster#4172]
CachingHttpHeadersFilter adds cache headers to *all* asset requests, which can be actually harmful as it might lead to 404s being cached for a really long time.

You should IMHo get rid of the filter and just rely on Spring's ResourceChainRegistry!

**Comment by jdubois** [comment]
- I did not know we where adding a cache header to a 404 response - I didn't know this was even possible! That's really something strange, I will check this out.
- As we always use a checksum in front of our production assets, I don't think this should cause any issue. It's the same thing as any other asset.
- I haven't checked Spring's ResourceChainRegistry - last time I had a look at this part of Spring MVC, it wasn't doing exactly what I wanted - not sure I will have time to check this again

**Comment by jdubois** [comment]
I confirm the 404 responses are cached -> it won't do any harm (as we have the checksum), but indeed that looks like a bad idea, so we should cache exceptions and remove cache headers when they occur.

**Comment by kutzi** [comment]
This can become an issue, if you do a rolling update to multiple prod instances who are all behind a caching, load balancing proxy.
Then new instances may already request assets under the new name and old instances answer with 404s - which are then cached for longer.

In fact that happened to us.

Am 20. September 2016 19:34:22 MESZ, schrieb Julien Dubois <notifications@github.com>:
>- I did not know we where adding a cache header to a 404 response - I
>didn't know this was even possible! That's really something strange, I
>will check this out.
>- As we always use a checksum in front of our production assets, I
>don't think this should cause any issue. It's the same thing as any
>other asset.
>- I haven't checked Spring's ResourceChainRegistry - last time I had a
>look at this part of Spring MVC, it wasn't doing exactly what I wanted
>- not sure I will have time to check this again
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jhipster/generator-jhipster/issues/4172#issuecomment-248373692

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by kutzi** [comment]
I'd really suggest to take the 'standard' Spring approach instead of rolling out a not so well tested handmade filter

**Comment by kutzi** [comment]
Exceptions are probably not the only source of 404s, so just checking for them won't help.
Btw: I tried to adapt thd filter to set the cache headers after thd filter chain, but that didn't work!
Probably because the response was already flushef

**Comment by jdubois** [comment]
Yes you are totally right.
I need to check again the "standard" Spring filter, I haven't looked at that since a couple of years. If it's good, let's use it, otherwise we can still have our filter, but we need to solve this issue.

**Comment by jdubois** [comment]
@kutzi which "standard" filter are you referring to? Is it `ShallowEtagHeaderFilter`? If you have a look at it, you'll see it's pretty bad for our use-case. You only gain bandwidth, but it uses a lot of resources for nothing. So I'm quite strongly against it.

**Comment by kutzi** [comment]
I never said it's a filter ;-)
It's somewhere in the ResourceChain of Spring. Some handler class there AFAI remember.
You're even re-configuring it in jHipster AFAIK. See ResourcesConfiguration where the build-in support for Cache headers is basically disabled.

**Comment by kutzi** [comment]
or maybe not in jHipster, because I cannot find it in this repository ...
But anyway if you put this method in a .@Configuration class, you can configure it:

`@Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
CacheControl cacheControl = CacheControl.maxAge(31, TimeUnit.DAYS).cachePublic();
    ResourceChainRegistration resourceChain = registry
      .addResourceHandler("/**")
      .addResourceLocations(paths)
      .setCacheControl(cacheControl)
      .resourceChain(useResourceCache);`
}

**Comment by kutzi** [comment]
And the handler is ResourceHttpRequestHandler. See handleRequest() and prepareResponse()

**Comment by jdubois** [comment]
OK, this is really tricky.

- I've had a look at how Varnish does it, but indeed with a Java Servlet filter the response might have been flushed before, so we can't really change the cache header afterwards.
- I'm not sure of how Spring handles this internally, but this doesn't really change the problem -> if you hit the "wrong" server, you'll still get 404 errors, and with your configuration they will also be cached. So I'm not sure you could solve this with the Spring configuration, it's probably going to be the same problem in the end.

Now, I've read again your use-case, and there is something strange: if you have a front-end proxy, then you shouldn't use the caching headers from JHipster. You should disable them in JHipster, or ignore them in your proxy.
You also use some kind of sticky sessions, so this use-case doesn't really happen anyway: if don't use sticky-sessions, your REST requests will be all mixed up between both app versions, so that's an even worse problem.

So in the end:

- I totally agree 404 errors should not be cached
- I can't find a good solution
- With a normal app this shouldn't happen, and with your proxy cache it also shouldn't happen

**Comment by deepu105** [comment]
I had few jhipster apps in production with a similar setup, hw load
balancer with sticky session -> apache ws soft load balancer -> jboss eap
6, and I never faced this issue.

Thanks & regards,
Deepu

On 27 Sep 2016 03:51, "Julien Dubois" <notifications@github.com> wrote:

OK, this is really tricky.

   - I've had a look at how Varnish does it, but indeed with a Java Servlet
   filter the response might have been flushed before, so we can't really
   change the cache header afterwards.
   - I'm not sure of how Spring handles this internally, but this doesn't
   really change the problem -> if you hit the "wrong" server, you'll still
   get 404 errors, and with your configuration they will also be cached. So
   I'm not sure you could solve this with the Spring configuration, it's
   probably going to be the same problem in the end.

Now, I've read again your use-case, and there is something strange: if you
have a front-end proxy, then you shouldn't use the caching headers from
JHipster. You should disable them in JHipster, or ignore them in your proxy.
You also use some kind of sticky sessions, so this use-case doesn't really
happen anyway: if don't use sticky-sessions, your REST requests will be all
mixed up between both app versions, so that's an even worse problem.

So in the end:

   - I totally agree 404 errors should not be cached
   - I can't find a good solution
   - With a normal app this shouldn't happen, and with your proxy cache it
   also shouldn't happen

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/4172#issuecomment-249714912>,
or mute the thread

**Comment by jdubois** [comment]
Yes @deepu105 with a "normal" configuration that shouldn't happen. Then I'm not saying this is easy to set up, and the original issue comes from us.

I'm closing this as I don't think we could solve this, so this is a matter of correctly configuring the front-end cache if you have one.

BTW, in a "normal" JHipster setup, the front end is handled by the gateway, and this issue shouldn't occur.

**Comment by kutzi** [comment]
I don't expect jHipster to fix the issue with the frontend LB/caching (we fixed it with sticky sessions too, btw)
It was just that the cache headers on the 404s incredibly increased the scope of the error.
So when the cache headers are now gone in jHipster that's fine for me.

**Comment by kutzi** [comment]
Wait - you have done nothing for this and CachingHttpHeadersFilter is still there?
Then please reopen it!

**Comment by jdubois** [comment]
Yes, maybe another solution would be to allow to remove the caching headers by configuration - that would solve your issue, as caching is done by your proxy.
Then you could as well just remove the line...

**Comment by jdubois** [comment]
No I couldn't find a solution for this.
I don't see what's wrong with CachingHttpHeadersFilter - it's working fine and has been used for a long time.
I haven't worked on what Spring Boot provides, that's quite new to me, and I don't have the time currently to code & test this.

**Comment by kutzi** [comment]
Okay: to state it clearly, again, I think the behaviour of jHipster to add cache headers to 404s is absolutely dangerous and shouldn't be in the default configuration

**Comment by jdubois** [comment]
Yes I understand, but if you add a caching proxy on top of JHipster, we can't really do much about it.
Most people don't use this, and for them having caching headers is very important.
Another solution would be to use your proxy not to cache 404 responses: I know that this is what Varnish does, but I don't know how it does it internally (I guess it stores the whole response and does not stream it, like a Java server does)

**Comment by kutzi** [comment]
The thing is that we/jHipster tell the caching proxy via the caching headers to cache the 404s for 1461 days. Of course I can then reconfigure the cache to ignore this headers, but it's just wrong from the beginning IMO

**Comment by kutzi** [comment]
Even browsers are advised to cache this 404 for so long, so it's not just a caching proxy thing

**Comment by jdubois** [comment]
Yes I know it's wrong from the JHipster side, but it's very difficult to solve.
BTW I thought we were caching resources for 31 days, I don't know why this has been updated to 1461 days (but I'm sure there's a good reason and that this isn't a random number).

**Comment by kutzi** [comment]
I'm not getting the part about difficult to solve. Just use Spring's ResourceHttpRequestHandler and configure it to the Cache timeouts you want!

**Comment by jdubois** [comment]
- it's difficult to solve with the servlet filter, as the response may be flushed
- I have no idea how the ResourceHttpRequestHandler works in detail, and I'm not changing this without a good study first. I'm sorry, I just don't have the time at the moment.

**Comment by deepu105** [comment]
@kutzi if you know how the spring filter works could you do a PR so that we can take a look and test it out as we lack the time due to our current ng2 migration
