### ISSUE TITLE
Kubernetes support: cassandra, elk, consul

### ISSUE THREAD

**Issue by pascalgrimaud** [jhipster/generator-jhipster#4205]
As suggested on Twitter (@deepu105, @PierreBesson, @saturnism), Kubernetes support need to be improved:
- [X] npm test
- [X] elasticsearch -> I already coded this [_elasticsearch.yml file](https://github.com/jhipster/generator-jhipster/blob/master/generators/kubernetes/templates/db/_elasticsearch.yml) but currently it isn't included to the kubernetes sub generator
- [ ] cassandra -> on local, it's easy by mounting volume to our cql files to create all tables, but I have no idea how it should work with Kubernetes. Maybe manually? Or using **Pet Set** as suggested by @saturnism 
- [ ] ELK with JHipster console
- [X] kafka -> very new, from the latest release 3.8.0
- [ ] consul -> the PR from @PierreBesson need to be merged first

Feel free to code one part of this, if someone is motivated :star:

**Comment by pascalgrimaud** [comment]
I'm working first on npm test for kubernetes

**Comment by PierreBesson** [comment]
I think we should use Helm and officially supported charts, this will make our job easier: https://github.com/kubernetes/charts
They already have config for mysql, mariadb, mongodb, elasticsearch, consul.

**Comment by pascalgrimaud** [comment]
I'm working on elasticsearch
@PierreBesson : https://github.com/kubernetes/charts seems interesting but I don't see how it can be used with our subgenerator.

**Comment by raphaelbrugier** [comment]
I'm interested in helping with Cassandra and Kafka. Can you please tell me where to start or describe more the problems?

**Comment by PierreBesson** [comment]
Hi @raphaelbrugier, similar to a what's already in place in the docker-compose subgen we want to have a multi-node Cassandra that works out of the box with a JHipster app and that can scale at will. One resource that might help you is the 1000 cassandra node demo using JHipster :

https://github.com/k8s-for-greeks/gpmr

Good luck !

**Comment by PierreBesson** [comment]
And the related k8s blog post : http://blog.kubernetes.io/2016/07/thousand-instances-of-cassandra-using-kubernetes-pet-set.html?m=1

**Comment by raphaelbrugier** [comment]
Awesome! Thanks, I'll read that and play a bit with k8s as a start.

**Comment by pascalgrimaud** [comment]
@raphaelbrugier thanks !!
- you can begin with kafka, it should be easier
- then, about cassandra, it should be more complex because you can't mount volume as we do locally. Maybe start 1st the cassandra cluster, launch cql manually, then launch all other apps? I don't have idea about this, at the moment

- you can use minikube locally (that's what I do because I don't have k8s) to test your configuration
- the sub generator kubernetes uses same functions from sub generator docker-compose

Don't hesitate to ping me if you need help

**Comment by raphaelbrugier** [comment]
Thanks @pascalgrimaud, I'll start with Kafka then.
I have just installed minikube and started playing with k8s, so I need to get familiar with it first.

Does the hacktoberfest tag mean you'll owe me a beer for my contribution? ;)

**Comment by pascalgrimaud** [comment]
@raphaelbrugier sure, with pleasure !!:beers:

**Comment by raphaelbrugier** [comment]
So, after playing with the JHipster k8s generator and researching on how to integrate Kafka I have a couple of questions.

**1) What are the features that the configuration generated by JHipster should cover?**
Production ready? high availability? fault tolerant?
Or is it just for local testings with minikube and to give examples of a kubernetes configuration?

I am asking, because when I tested with a single JHipster app and a mysql database, the webapp was correctly fault tolerant (I killed the container and k8s restarted a new one as expected) but the mysql container was not.
All the tables and data were gone.
I may be wrong somewhere in my tests because the k8s mysql service declares a volume data which is supposed to survive a container failure (if restarted in the same pod).


**2) Kafka is not currently "supported" by kubernetes**
By supported, I mean there is [no official example](https://github.com/kubernetes/kubernetes/issues/5017) or charts unlike for [Cassandra](https://github.com/kubernetes/kubernetes/tree/master/examples/storage/cassandra).

An example for Zookeeper using petset has just landed in the [official repository](https://github.com/kubernetes/contrib/tree/master/pets/zookeeper).
I have found [this work in progress](https://github.com/Yolean/kubernetes-kafka) but I have not tested it yet.

Here are my options, also depending on 1)
- do not try to cover HA and write something very simple (one ZK node, one Kafka node) but that works out of the box locally
- dig more and write our own Kakfa config using petset
- wait for an example on the official repository

What is your point of view on this?

**Comment by pascalgrimaud** [comment]
@raphaelbrugier :

Note: everything here is my point of view

Docker-compose subgen generates docker-compose yaml files.
k8s subgen should do the same, with the appropriate syntax.

- IMO, both (k8s and dockercompose subgenerator) should provide some basic configuration, then the user can custom it, accordingly to what he needs. It's like the java code => JHipster helps people to start quickly, then the user has to custom!
- about volume with mysql (or something else), I didn't have a look on how volumes work with k8s, so I have no idea
- about kafka: something very basic and simple, like you said, 1 ZK node, 1 Kafka node => it should be to transform kafka.yml (for docker-compose) into kafka.yml (for k8s)

Last word about volume:
- The current configuration for kafka doesn't need volume so that's why it should not be very difficult.
- About ELK, Cassandra, Consul, if you look on the compose files, all of them use volume. So it's a little bit more complex.

**Comment by PierreBesson** [comment]
@rafaelbrugier You make really good points. Configuring "prod" deployments of things like Cassandra or Zookeeper is very hard. This is what the DataMC team is doing at Ippon for their Cassandra and Kafka managed services offering and it's a full time job.
Anyway it would be lying to imply that we provide a complete prod setup here. A simple deployment or petset should be enough to help users get started.

**Comment by raphaelbrugier** [comment]
Hi,

Thank you both for your answers.

Ok, let's keep it simple and just add a warning in the documentation page to explain it's up to the users to tweak for their needs (more fault tolerant == more complicated).

I'll just port the Kafka docker-compose file to k8s.

@pascalgrimaud 
About volumes:
- I don't know about ELK and Consul but for Cassandra the volume section in the docker-compose file generated by JHipster is commented.
Were you referring to something else?

@PierreBesson 
Julien demoed us DataMC last week and that was pretty impressive! Good job guys!

**Comment by pascalgrimaud** [comment]
@raphaelbrugier :
I was refering to this https://github.com/jhipster/generator-jhipster/blob/master/test/templates/compose/05-cassandra/src/main/docker/cassandra-migration.yml#L12-L13

With Kubernetes, we have probably to find another way to play CQL scripts

**Comment by raphaelbrugier** [comment]
Oh thanks Pascal, I forgot about this one :).
Yes, we'll have to rethink how to apply the CQL scripts when deploying in k8s.
I have always preferred the idea to have the deployment pipeline responsible for applying the scripts, so it really depends on what we want to achieve with the k8s default setup.

I have not make any progress on Kafka because I'm running into a problem with the existing k8s configuration for a monolithic/mysql JHipster app.
The fist time I used the generated configuration and deployed it in minikube, it worked fine.
Now, when I try to use it again, the JHipster app complains it can not reach the mysql address:

`Caused by: java.net.UnknownHostException: jhipsterapp-mysql.default.svc.cluster.local: unknown error`

If I change the webapp container configuration (SPRING_DATASOURCE_URL) to point directly to the IP of the MySQL container, it works.

I have tried to recreate everything from scratch, deleting the .minikube folder and recreating the JHipster application, but the same problem occurred.

I'm not sure of the reason, probably a DNS problem?
Any idea?

**Comment by pascalgrimaud** [comment]
Can you look at :
- issue: https://github.com/jhipster/generator-jhipster/pull/4364
- PR: https://github.com/jhipster/generator-jhipster/pull/4364

Maybe it's related to this issue

**Comment by pascalgrimaud** [comment]
@raphaelbrugier : I retry to deploy a simple monolith application. Everything works fine on my minikube

**Comment by raphaelbrugier** [comment]
Thanks @pascalgrimaud,
Yes, my problem is with a very simple JHipster monolith application from scratch with just a MySQL database.
It was working fine the first time I used the k8s generator, but I doest not work anymore.

I'll give it another try tomorrow with a fresh install of minikube and the latest JHipster master.

**Comment by pascalgrimaud** [comment]
I begin to work on consul

**Comment by pascalgrimaud** [comment]
Edit: I only begin to write tests for consul, but I don't have time to finish it. I will do it later -> as I will help for testing angular2

**Comment by pascalgrimaud** [comment]
@PierreBesson : we need to test https://github.com/kubernetes-incubator/kompose :-)

**Comment by PierreBesson** [comment]
Yes I have heard that it has improved a lot recently and now supports docker-compose v2.

**Comment by jdubois** [comment]
@pascalgrimaud @PierreBesson is there still work to do here? Nothing on this ticket since October, and Cassandra support isn't very important (only very few people use it, less than 2%)

**Comment by pascalgrimaud** [comment]
I think we can close it, as there are few feedback on Kubernetes.
And it can be done later! Nothing here is urgent.
