### ISSUE TITLE
login code question

### ISSUE THREAD

**Issue by liseri** [jhipster/generator-jhipster#4221]
HI,
In Monolithic application.
Why use plaintext password logining, and hash in backend ?

Thank you!

**Comment by jdubois** [comment]
We hash it for security. It's even illegal in some countries (like mine!) to store un-hashed password information.

**Comment by jdubois** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**Comment by liseri** [comment]
Sorry,  
 It was not clearly what I said yesterday;  
1. Of course hash is need; 
2. My question is that why not hash in front-end  but in back-end; 
3. I think it is inappropriate for security of  Plaintext-Password Transmit Mode

Thank you !

**Comment by xetys** [comment]
1. It is not the best idea to have the hash algorithm (with your salt logic) in frontend...this is observable
2. there is no need, if you are using TLS...

the security for hasing is not about securing the password transmission, but preventing evil system administrators to review your password, you probably use for other sites with the same mail...

and as @jdubois said, the right place for this question would be our gitter or on stack overflow, as it is a misunderstanding of common principles, rather than an issue with JHipster

**Comment by jdubois** [comment]
Yes, please, this is for StackOverflow -> I'm locking the conversation
