### ISSUE TITLE
Get the license badge correctly on Github

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4231]
I want the project to have the license correctly displayed, like on https://wptavern.com/github-updates-repository-overview-to-prominently-display-open-source-license-information

I already tried once and failed miserably at https://github.com/jhipster/generator-jhipster/commit/6fe43f63bf810c6bb183fa270b4981257916e068

Maybe I need to change something in the text itself.... Anyway, this is just to warn everybody:

- there might be several commits in the license file, that's me trying, don't worry the goal is not to change the license, just to display it well!
- I will then probably do the same on all our projects, so everything is the same everywhere

**Comment by deepu105** [comment]
It seems to work only for MIT, GPL etc. I checked few Apache licence
projects it was not shown


Thanks & Regards,
Deepu

**Comment by deepu105** [comment]
see this its working automatically as it was MIT https://github.com/jhipster/jdl-studio
for apache to be detected it should match this it seems https://github.com/benbalter/licensee/blob/master/vendor/choosealicense.com/_licenses/apache-2.0.txt
Btw for jdl-studio I started with MIT licence, do you want to dual licence it under Apache as well? if so please feel free to change it

**Comment by PierreBesson** [comment]
I also think it cannot be done for the apache license. However you could put a badge on the README like this: `![Apache License](https://img.shields.io/badge/license-Apache-blue.svg)`
![Apache License](https://img.shields.io/badge/license-Apache-blue.svg).

**Comment by jdubois** [comment]
OK thanks, so I'm closing this....

@MathieuAA for the JDL Studio, yes we need to discuss a license change: I'm sending an email on the dev mailing list for this, so we can discuss it all together.

**Comment by pascalgrimaud** [comment]
Look: https://github.com/apple/swift
Do we want the same display as this project ?

**Comment by jdubois** [comment]
Oh, so this is possible, so I'm reopening this.
I need to check, I want the "real" license, so I'm not copy/pasting it from anywhere outside of the official Apache website.

**Comment by pascalgrimaud** [comment]
I think you have to put the full text from http://www.apache.org/licenses/LICENSE-2.0.txt, then replace the part `Copyright [yyyy] [name of copyright owner]` and it works

**Comment by jdubois** [comment]
OK, I'm going to try that.

For the copyright owner, I'm going to copy on https://github.com/robbyrussell/oh-my-zsh/blob/master/LICENSE.txt which does:

    Copyright (c) 2009-2016 Robby Russell and contributors
    See the full list at https://github.com/robbyrussell/oh-my-zsh/contributors

It is in fact not totally correct, because the list is limited to the top 100 contributors, so I'm going to modify this, but you get the idea.

Once it's done:

- If you have any comment or problem with the license, please tell me. I don't want any issue here, it's very important to me that the license is fine for everyone.
- We can then use the same license on all sub-projects - of course the license "owner" will be the person who started each project. If there is an issue with that, we can just put "the contributors": under French law I think it is correct, but still having a real, physical person looks better to me in case of copyright dispute. At least you have one person responsible, for sure.

**Comment by jdubois** [comment]
It's working, yes :-)
Closing this as it's OK, but don't hesitate to comment!!!!!

**Comment by deepu105** [comment]
It sounds good. Im perfectly fine with copyright 'owner and contributors'
as you suggest. And yes atleast having one physical person per project is
good

Thanks & regards,
Deepu

On 30 Sep 2016 13:59, "Julien Dubois" <notifications@github.com> wrote:

OK, I'm going to try that.

For the copyright owner, I'm going to copy on https://github.com/
robbyrussell/oh-my-zsh/blob/master/LICENSE.txt which does:

Copyright (c) 2009-2016 Robby Russell and contributors
See the full list at https://github.com/robbyrussell/oh-my-zsh/contributors

It is in fact not totally correct, because the list is limited to the top
100 contributors, so I'm going to modify this, but you get the idea.

Once it's done:

   - If you have any comment or problem with the license, please tell me. I
   don't want any issue here, it's very important to me that the license is
   fine for everyone.
   - We can then use the same license on all sub-projects - of course the
   license "owner" will be the person who started each project. If there is an
   issue with that, we can just put "the contributors": under French law I
   think it is correct, but still having a real, physical person looks better
   to me in case of copyright dispute. At least you have one person
   responsible, for sure.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/4231#issuecomment-250689126>,
or mute the thread
