### ISSUE TITLE
securing consul communication using ACLs

### ISSUE THREAD

**Issue by xetys** [jhipster/generator-jhipster#4252]
Similar to JHipster Registry we need some securing solution for config and service discovery for consul...

I spent some time on this topic, and figured out some solution which is almost equivalent to the way we do it for jhipster-registry. 

to sum up, there is a clean way or the fast way (as usual). For the fast way we initialize consul with a master acl token (which has maxmimum permissions), and use it for accessing services and KV. The clean way is to use the master token only to generate some "JHipster ACL client token", which gets a ***default*** read/write permission to services and read on KV. The details of that clients policies is open for later modification / specification. This flow may be provided in our docker setup, if there is any consideration to use it in production. 

For the spring side, its just easy as setting "consul.token" via configuration. For further work I need to know,
if we prefer the more secure solution, by:

* setting a acl_config.json in consul docker files with a predefined master token (similar to JWT secret, can be generated per project)
* changing the consul-config-loader, so it creates the JHipster client ACL using master token
* setting client token to docker files

or a little more straight foreward and less secure solution, by:

* setting a acl_config.json in consul docker files with a predefined master token (similar to JWT secret, can be generated per project)
* setting master token to docker files

I'll PR as soon I've heard some opinions on that :smile:

**Comment by PierreBesson** [comment]
Great ! Thank you for doing this research. I will need to think more about
it but the most important thing is that it should work out of the box in
dev and in prod. So a master token could be generated by the docker-compose
subgen but for dev maybe we could put a predefined non-secure master token
so that it is already shared by all microservices when run in dev.

Also I like the idea of extending consul-config-loader to setup ACLs.

Anyway I'm not sure I understood everything about ACL tokens so you can go
ahead.

Regards,
Pierre

Le 3 oct. 2016 4:23 PM, "David Steiman" <notifications@github.com> a écrit :

Similar to JHipster Registry we need some securing solution for config and
service discovery for consul...

I spent some time on this topic, and figured out some solution which is
almost equivalent to the way we do it for jhipster-registry.

to sum up, there is a clean way or the fast way (as usual). For the fast
way we initialize consul with a master acl token (which has maxmimum
permissions), and use it for accessing services and KV. The clean way is to
use the master token only to generate some "JHipster ACL client token",
which gets a *default* read/write permission to services and read on KV.
The details of that clients policies is open for later modification /
specification. This flow may be provided in our docker setup, if there is
any consideration to use it in production.

For the spring side, its just easy as setting "consul.token" via
configuration. For further work I need to know,
if we prefer the more secure solution, by:

   - setting a acl_config.json in consul docker files with a predefined
   master token (similar to JWT secret, can be generated per project)
   - changing the consul-config-loader, so it creates the JHipster client
   ACL using master token
   - setting client token to docker files

or a little more straight foreward and less secure solution, by:

   - setting a acl_config.json in consul docker files with a predefined
   master token (similar to JWT secret, can be generated per project)
   - setting master token to docker files

I'll PR as soon I've heard some opinions on that 😄

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/4252>, or mute the
thread

**Comment by xetys** [comment]
ok, as you can see I choosed the 2 token solution, as it is safer. To simplify, I use the master token to create the client token (which is far more restricted) and to update the config.

A think *may* be added, is some kind of token generation for production, but we don't do this with the registries basic auth credentials...should we then do this to both projects? Or just merge this after testing?

I need to get my consul config loader up to docker hub to make this merge work. If you want to test it earler, checkout my branch of the consul-loader and refer to it as a local image


As usual, the whole thing can be tested working here: https://github.com/xetys/jhipster-uaa-consul

**Comment by PierreBesson** [comment]
Sorry I won't have much time to test it during the week. I will definitely check it out this weekend.

If you have ideas to improve security for prod eureka as well please propose them. This stuff hasn't changed since the initial implementation of the basic auth in march. As long at it stays simple and well explained in the docs.

**Comment by deepu105** [comment]
closed via #4259
