### ISSUE TITLE
"dev" profile not active anymore when starting from an IDE

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#4256]
I think this comes from the recent changes from @deepu105 in the `spring.profiles.active` configuration in the `application.yml` file, but I didn't follow this close enough.

On the current master branch:

- Generate a new project
- Open it in IDEA
- Run the main class
- It will only have the "swagger" profile, and not "dev,swagger"

It still starts up, so it's not obvious, but it doesn't have our "dev" configuration: for example Liquibase is starting synchronously.

**Comment by deepu105** [comment]
Thats weird. It worked when I tested for that change and  tested from IntelliJ as well

**Comment by deepu105** [comment]
ok wait how are you getting the swagger profile loaded if dev profile is not loading? coz swagger is included only in the dev profile yml

**Comment by jdubois** [comment]
Yes, that's the weird think: I just have "swagger", and not "dev".
But "dev" is needed in several parts, at least for Liquibase: as it starts synchronously, it's clear there is an issue here.

**Comment by cbornet** [comment]
Same for me.

**Comment by deepu105** [comment]
Ok let me check

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
I think I know the issue. Ill work on this tomorrow

**Comment by jdubois** [comment]
Thanks @deepu105 - I think I understand it, but I can't find a good solution right now... And that's a very annoying issue.

**Comment by jdubois** [comment]
Looks it works by adding in the `application-dev.yml`:

    spring:
        profiles:
            active: dev

I'm testing this, if it works I will push it and linked the commit to this ticket

**Comment by jdubois** [comment]
The solution above looks OK to me, but as this is a recurring issue, and that's a really annoying one, @deepu105 could you have a look?

**Comment by deepu105** [comment]
The issue is from using env.getActiveProfiles method which doesnt return
default profiles. I already have a fix for this I'll PR that and close the
issue today, currently away from laptop but tonight I can do it.

Thanks & regards,
Deepu

**Comment by jdubois** [comment]
Oh sorry @deepu105 -> I closed it with my commit, I'm reopening it, so you can validate or do your PR instead

**Comment by deepu105** [comment]
No probs. Ill take care of it

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
@jdubois The problem is with the way spring loads default and included profiles I guess. Even with dev profile added to active profile in dev.yml it wasnt working and my solution to check for profiles using a custom method was too hacky for my taste. So I reverted back to the solution you suggested earlier. Let me know if its ok for you

**Comment by jdubois** [comment]
Sorry but we tried so many solutions: what did you do in the end?

**Comment by jdubois** [comment]
Sorry I just got your commit!
(I'm in the metro!)

**Comment by cbornet** [comment]
It doesn't work anymore if starting from Maven : the profile is always only dev
```shell
./mvnw -Pdev,swagger
...
2016-10-07 14:15:22.015  INFO 12174 --- [  restartedMain] com.mycompany.myapp.StandardApp          : Running with Spring profile(s) : [dev]
```

**Comment by cbornet** [comment]
The conf used is the default one in pom.xml under "dev" profile <spring.profiles.active>i

**Comment by jdubois** [comment]
You are correct... This is so annoying....
Why don't we do it like I did here: https://github.com/jhipster/generator-jhipster/commit/dc1b582a1a06bb9296d658ef050543d430cf9562

**Comment by jdubois** [comment]
I'm going back to my solution so it works again, and I'll close the ticket with it.

I hope that's fine with everybody, as I wanted to do a release this afternoon.

**Comment by deepu105** [comment]
I know its annoying to continue the discussion, but I need to update my findings here

So the issue you guys faced is due to https://github.com/jhipster/generator-jhipster/commit/96dafc77171f073a4f2869218f9b935199fbc46b which is ironically from me. So when I reverted the change yesterday I forgot to add the profile to `pom` and `gradle` files. thats why it was working for me locally in all cases.

Now having swagger in `includes` doesnt work when launched from IDE for me, but seems like others are not facing that issue which is very weird. Can somebody verify this? I'm using IntelliJ on windows (which really shouldn't matter theoretically) 

@jdubois Hence reverting https://github.com/jhipster/generator-jhipster/commit/96dafc77171f073a4f2869218f9b935199fbc46b should solve the issues for everyone and if you are OK ill do a PR of course this time I need someone apart from me also to double test the below cases to be extra sure, since not much people are affected this is not of high priority

- [ ] `mvnw` from console
- [ ] `mvnw -Pprod` from console
- [ ] `mvnw -Pprod,swagger` from console
- [ ] Run main class from IDE (maven)
- [ ] Run main class from IDE with prod profile (maven)
- [ ] Execute (java -jar) packaged war (maven)
- [ ] Execute (java -jar) packaged war with prod profile (maven)
- [ ] `gradlew` from console
- [ ] `gradlew-Pprod` from console
- [ ] `gradlew-Pprod -Pswagger` from console
- [ ] Run main class from IDE (gradle)
- [ ] Run main class from IDE with prod profile (gradle)
- [ ] Execute (java -jar) packaged war (gradle)
- [ ] Execute (java -jar) packaged war with prod profile (gradle)

**Comment by deepu105** [comment]
Im re opening this as its still an issue atleast on windows + IntelliJ (I would be very surprised if someone can reproduce this on windows)

**Comment by jdubois** [comment]
Yes it's very important we understand this. And this feature is important to me.
With the current v3.9.0 release I have no issue, but it seems we have some different experiences here.

**Comment by deepu105** [comment]
anyway i'll wait for someone to reproduce this. Until then its just affecting me and thats OK coz I rarely use it from IDE and even if I do I know how to set profile there
![image](https://cloud.githubusercontent.com/assets/1107223/19210473/beb0d4be-8d41-11e6-86be-0a4fb89a074e.png)

**Comment by jdubois** [comment]
Oh, the idea is that you don't need to set anything there by default -> you will be in dev profile.
So it also works with Intellij Community, which doesn't understand Spring Boot, it just runs an executable Jar.
Of course you can tweak stuff in that box, but the goal is that everything works out of the box without any tweaks.

**Comment by jdubois** [comment]
@deepu105 I'm going to go through all the cases and tick the boxes...

**Comment by jdubois** [comment]
OK, I tested all of them, everything works!!!

**Comment by deepu105** [comment]
Ok then :)

Thanks & regards,
Deepu

**Comment by cirovladimir** [comment]
Hi, I had the same issue when I ran `mvn -Pprod` from CLI and later tried to run the app from IntelliJ. It appears, Maven or IntelliJ remembers the last profile used and if not specified it will run with that profile.
Afterwards I ran `mvn -DskipTests' from CLI and tried to run again from IntelliJ and it, of course, ran with dev profile.
