### ISSUE TITLE
Saving Tokens in local storage is vulnerable to XSS

### ISSUE THREAD

**Issue by ThomasWilhelmUR** [jhipster/generator-jhipster#4278]
##### **Overview of the issue**

I've discussed this issue briefly with @xetys via E-Mail, so I think this might add value to this awesome(!) project.

Saving Auth-Tokens in local storage can expose them via an XSS-attack, for example on third party JS libs.

See this stormpath blog post for further details:
[https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage](https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage )

##### **Motivation for or Use Case**

Stealing the Token can expose private data. Manual token invalidation will be too late at that point.

##### **Suggest a Fix**

Possible solutions as I understand them per @xetys 
- Make the web app gateway store the tokens in a cookie (@EnableOAuth2Sso [?])
- Zuul filter 

##### **JHipster Version(s)**

current

##### Comments

I think discussing this is worthwile. Sadly, I can't provide a solution myself - should there be agreement on a move. Keep up the good work, it's very much appreciated and thanks for your time!

**Comment by ruddell** [comment]
Related discussion (same link and topic): https://github.com/jhipster/generator-jhipster/issues/3405

**Comment by deepu105** [comment]
@jdubois should we close this or do you have any comment?

**Comment by jdubois** [comment]
I haven't changed my mind since last time... Cookies also cause issues, etc...

**Comment by xetys** [comment]
I just forgot we had this topic earlier this year...

however, there seems to be a way to store JWT inside a session, while NOT providing a real state at the server side.... like some ZuulFilter which reads the JWT from cookie and restores a session from it, similar to if it were in header / uri....

the question is, how hard that issue is, and if we should do something on this...

I just can take a look about the Cookie Solution which is scalable...

**Comment by deepu105** [comment]
Im wouldn't want all that zuul related dependencies for a monolith. However
for a microservice or gateway it could be ok if its not very complicated.
Having stuff in local storage is not that vulnerable, if you cant trust
your own domain root, only which can access the local store, then you have
a bigger issue than this anyway.

Thanks & regards,
Deepu

**Comment by xetys** [comment]
As communicating with cookies on the protocol layer is just another HTTP
header, we could consider to build a generic request filter, which just
transforms the cookie header to a JWT authorization bearer header for lower
use, would be a server cookie solution without any actual state... If I am
not missing something..

вс, 9 Окт 2016 г., 4:44 Deepu K Sasidharan <notifications@github.com>:

> Im wouldn't want all that zuul related dependencies for a monolith. However
> for a microservice or gateway it could be ok if its not very complicated.
> Having stuff in local storage is not that vulnerable, if you cant trust
> your own domain root, only which can access the local store, then you have
> a bigger issue than this anyway.
>
> Thanks & regards,
> Deepu
>

**Comment by jdubois** [comment]
Definitely not a Zuul filter for monoliths, and we need a similar solution for monoliths and microservices, otherwise it will be impossible to manage.

Let me also thank @ThomasWilhelmUR : we need more security reviews. They are very important. We must look at those reports very closely.

Then, I've read again the blog post and I'm still not convinced. I'm seeing @mraible from Stormpath tomorrow, we can have a chat about it, but from my opinion:

- The local storage can only be used from the same domain, so it's the "usual" protection from me. No specific issue here.
- Of course you have XSS attacks, but like everywhere else. Please note that if you use "normal" JHipster you shouldn't have that kind of attacks, as the Strings are escaped. So a "normal" JHipster application shouldn't be affected -> the only issue is if a developer messes around and un-escapes the Strings, so that's definitely his fault

Cookies come with their own issues too: they are easier to eavesdrop (as they are send with every request), and they take a lot more resources (again, as they are sent with every request).

So for me the current situation is OK, that's why I'm closing this.

Then, if someone has a working solution, with cookies, I will happily review it. And I will chat about it with Matt tomorrow, just to be sure.
