### ISSUE TITLE
Refresh of OAuth2 Token

### ISSUE THREAD

**Issue by imduffy15** [jhipster/generator-jhipster#441]
Refreshing of the OAuth2 token from the AngularJS application doesn't seem to exist. 

When a token is expired all views start returning 401 responses, breaking the application.

If I understand the OAuth2 flow correctly, the client should attempt to refresh their token on receiving a 401.

**Comment by mikhail-angelov** [comment]
I can see the  refresh_token is not used on Jhipster2.0, it's better reopen this issue. But thank you  francoisledroff, your solution kind of woking.

**Comment by artjomg** [comment]
+ 1 for reopen this and having the ability to configure the refresh_token feature. I think from user experience it is valid, that the session is prolonged as long as you interact with the app. I have one part of the app where users edit some source code online via an entity, let say they start to edit it at second 1500 and after 300 seconds the session just dies and unsaved changes are lost. This is a frustrating experience and I would expect that a generator has the same basic behavior over all provided authentication methods which can be deconfigured if required. But refresh capability is such a basic and expected behavior from end users point of view, that I would like to suggest to enable it by default.
