### ISSUE TITLE
Set default 'produces' to JSON in REST mappings

### ISSUE THREAD

**Issue by delverdev** [jhipster/generator-jhipster#4448]
##### **Overview of the issue**

Since most of the REST mappings produce JSON, I would like to suggest to set default 'produces' to `MediaType.APPLICATION_JSON_VALUE`.

##### **Motivation for or Use Case**

Less code.

##### **Suggest a Fix**

Make `WebConfigurer` extend `WebMvcConfigurerAdapter` and add the following bean:

```
@Override
public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
    configurer.defaultContentType(MediaType.APPLICATION_JSON);
}
```
Then remove all `produces = MediaType.APPLICATION_JSON_VALUE` from rest controllers.

**Comment by xetys** [comment]
Since we migrated to spring boot 1.4, we are already using the short cut
annotations like GetMapping. We also figured out, that json is already
there default value for content negotiation, so we are not mentioning it
anymore.

So for new JHipster applications, this would be ambiguous

вт, 8 Ноя 2016 г., 13:09 Delver Developer <notifications@github.com>:

**Comment by PierreBesson** [comment]
I hadn't noticed as well but as @xetys pointed out, the media type is not present anymore in generated REST resources:
https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/templates/src/main/java/package/web/rest/_EntityResource.java

Anyway thanks for your input.
