### ISSUE TITLE
[FEATURE] Improve infinite-scroll for Entity with Slice

### ISSUE THREAD

**Issue by nkolosnjaji** [jhipster/generator-jhipster#4450]
* **Overview of the request**

Use Spring Slice instead of Page when infinite-scroll is turned on for Entity. 

Edit: this techinque can be used with Simple Pager also, but it can't show total count for jhi-item-count component

* **Motivation for or Use Case** 

Slice is more suited for infinite-scroll because count all query can be avoided which will improve performance. Requesting page with size 20 will produce query with limit 21, so you can [check ](http://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/domain/Slice.html#hasNext--) if there is a next page.

Details:
[Spring Data Commons Slice](http://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.special-parameters)

* **Suggest a Fix** 

Implementation can be done to return custom http header X-HAS-NEXT from server and use value with infinite-scroll plugin
I can submit a PR

**Comment by jdubois** [comment]
I'm not familiar with it, but indeed this looks much better!
So +1 from me!

If you do a PR be careful:

- On the backend this should be implemented for JPA (easy), MongoDB (no idea how it's done), and Cassandra (I coded this myself, should be similar, but that was some time ago so I'm not 100% sure).
- On the frontend we have 2 branches, one for AngularJS 1 and one for Angular 2. So the best solution would be to have very, very small impact on the front end

If this looks too big, we can also close this and reopen it in a couple of months, when Angular 2 is stable, so that would remove the second point.

And please comment while you do the PR, so we know this is moving forward.

**Comment by nkolosnjaji** [comment]
Yes, there will be a small impact on frontend, so we don't need to wait for Jhipster 4 release.
I have working sample for JPA and today I will start PoC for other DB options before doing PR.
I will let you know of progress later.

**Comment by jdubois** [comment]
Great, thank you @nkolosnjaji 
I think it shouldn't be too hard on MongoDB and Cassandra, and at least I'm available to help on Cassandra

**Comment by nkolosnjaji** [comment]
@jdubois I finished PoC for MongoDB. It's easy to implement, same as JPA, because it's using spring data abstraction. With Cassandra I will need help, because I don't have knowledge.
Is there any reason why not using spring-data-cassandra ? It will be easier for developers to use uniform spring data project. Are there any open issues ? If yes, I can make same test.

**Comment by jdubois** [comment]
@nkolosnjaji basically spring-data-cassandra is not as up to date and as well documented as the rest of Spring Data, because that's a contribution from a third-party company.
Then, I don't find the Spring Data philosophy fits well with Cassandra, and I know a lot of Cassandra developers and nobody uses it. So I'd rather use the "normal" API, which is the recommended one by DataStax, which is (obviously) up to date, and which everybody uses.

**Comment by nkolosnjaji** [comment]
@jdubois currently pagination is [disabled ](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/prompts.js#L347-L349) for entity generator and [user-management](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/web/rest/_UserResource.java#L157) in admin section when cassandra is selected. Do we have to implement this  feature for cassandra db type?

**Comment by jdubois** [comment]
Oh I didn't think it was disabled! I coded this to have it working, and probably didn't finish... As nobody asked about it, it probably isn't that useful anyway.
For this PR, anyway: let's do one thing at a time, so let's improve the current code with the "slice", and then we could do a 2nd PR do add this feature for Cassandra, but that's a different thing.
So for me if you have JPA+MongoDB working that's perfect, don't worry about Cassandra.

**Comment by nkolosnjaji** [comment]
@jdubois unfortunately this feature can not be implement for elastic search as spring-data-elastic doesn't support Slice for search method (only for find). Do you still want to go with this feature when elastic search is turned off and db is not Cassandra ?

**Comment by deepu105** [comment]
I dont like to maintain 2 implementations for the same thing unless there
is a huge benefit from doing so

Thanks & regards,
Deepu

On 12 Nov 2016 9:18 a.m., "Nikola Kološnjaji" <notifications@github.com>
wrote:

@jdubois <https://github.com/jdubois> unfortunately this feature can not be
implement for elastic search as spring-data-elastic doesn't support Slice
for search method (only for find). Do you still want to go with this
feature when elastic search is turned off and db is not Cassandra ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/4450#issuecomment-260109063>,
or mute the thread

**Comment by nkolosnjaji** [comment]
@deepu105  yes, it will add confusions with different combos. This feature is really easy to implement so it will not add too much value.

**Comment by jdubois** [comment]
Oh I'm so sad about this!!
Indeed, it's going to be confusing to have 2 implementations, and a lot of people are using ElasticSearch, so this wouldn't be a minor change.

So I'm closing this as we can't do it, but I'm really sorry about this @nkolosnjaji you had a good idea and spent time to implement it!!!!!

**Comment by deepu105** [comment]
You could submit this as a tip on the website if you like

Thanks & regards,
Deepu

**Comment by nkolosnjaji** [comment]
@deepu105 will do

**Comment by sergio-otero** [comment]
I've made tests with a 5M row table in MySQL and it takes 1.2s to perform the select count 
When executing Gatlin tests, i receive timeouts because the pool gets full.
Changing to Slice solves the problem and the performance is very good: 5-20ms
