### ISSUE TITLE
[FEATURE] Generate front-end code more smart and friendly

### ISSUE THREAD

**Issue by magixsource** [jhipster/generator-jhipster#4587]
Hi admin.
i found front-end code from generator-jhipster do not readable and friendly. for example, in my project,it's generate a page list.html, in list.html , some link like this:
`<td><a ui-sref="dict-detail({id:dict.id})">{{dict.id}}</a></td>`
you see, text of  link element is {{dict.id}}, I think this should be more smart, Generate program should know all field of dict, and test is name field exist ? and title field ? label field ? if all of them no exist, ok, using id field.
I think {{dict.name}} should good than {{dict.id}}

I check generate-jhipster source code, list.html generate from template '_entity-management.html'.

en, What do you think of .

**Comment by jdubois** [comment]
The ID is the only way to have a unique field identifying the row, then of course you could do something smarter, but that depends on your business needs, and JHispter is mostly generating technical (and not business) code.
One of the solutions would be to ask a specific question, but then that question wouldn't have a lot of value, as editing the code is very simple, so that would be against our policies.
So I'm really sure what we can do for you here.

**Comment by deepu105** [comment]
Agree it would be nicer. If you have a smart simple way of doing this you can PR it and we will be happy to accept it. we are way too busy with ng2 now hence we wont be doing this ourself

**Comment by cbornet** [comment]
Having the possibility to specify a business key could probably help here and also for the hash code calculation.

**Comment by magixsource** [comment]
Ok, thanks.

today i try to debug generator program, and i found `relationships` do not store fields of reference,  only relationshipType\relationshipName\otherEntityName\otherEntityField\ownerSide\otherEntityRelationshipName in pojo.json, sadness. 

: )
