### ISSUE TITLE
Sleep vs Checking for connectivity

### ISSUE THREAD

**Issue by imduffy15** [jhipster/generator-jhipster#4776]
The default DockerFile sleeps for 10 seconds waiting for the database to be available:

```
CMD echo "The application will start in ${JHIPSTER_SLEEP}s..." && \
    sleep ${JHIPSTER_SLEEP} && \
    java -Djava.security.egd=file:/dev/./urandom -jar /app.war
```

Would it not be better to parse the `SPRING_DATASOURCE_URL` environment variable to extract the hostname/port and check them until successful connection rather than sleeping for magic number?

**Comment by jdubois** [comment]
Yes but that's way more difficult to achieve... In fact there are many ways to configure Spring: the main YAML file, a specific YAML file with a profile, an env variable, a config server... And people might use any of those methods, or a combination of them. So that's very hard to do something similar in a Shell script.
And then you need to check the connection, etc.

A better solution might be to check that in Spring: have the connection pool try until it establishes the connection. I've never seen this kind of feature anymore, and it kind of goes against the Spring philosophy of starting everything at boot time (I'm not saying that's a good philosophy! Just that's the way it is).

So if anybody wants to try a PR, that's very welcome, otherwise we'll stick to the basic "sleeps for 10 seconds", which isn't very good, but is easy to do.

**Comment by jdubois** [comment]
I'm closing this because I don't think anybody is going ever to code this. Lots of time, lots of tests, for not a big gain in the end.

**Comment by pascalgrimaud** [comment]
@imduffy15 : I'm the one who coded this, and as @jdubois said, I did this because it was very easy and fast. Going further would be complex and no real gain.

You can look the migration script which waits the Cassandra cluster:
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/docker/cassandra/scripts/_autoMigrate.sh#L16-L34

**Comment by PierreBesson** [comment]
@imduffy15 I like jour idea but it would add extra complexity, add an entrypoint script and depends on the database chosen. Also it would not work in a microservice setup where the database credendials are provided by a config server. So I don't think we can integrate this in JHipster. Anyway thanks for the feedback.

**Comment by imduffy15** [comment]
Cool! Thanks for the input all 😊.
