### ISSUE TITLE
Is there a reason to not have social login on gateway?

### ISSUE THREAD

**Issue by marcelinobadin** [jhipster/generator-jhipster#4850]
I can see that there is a social login for JWT when I choose monolithic application and because of that I was wondering why we don't have social login when we are using microservices architecture?

**Comment by jdubois** [comment]
This is because we use JWT for securing the micro-services. We would need to generate a JWT token on the gateway, which is basically what we do with UAA: shouldn't be very hard to do, it's just we haven't done it yet. This is mostly because there isn't a lot of interest in Social login.

PR is welcome if anyone wants to do it.

**Comment by marcelinobadin** [comment]
Ok, probably when a move my app from the monolithic to microservices I can work on this. Thanks.

**Comment by SidMorad** [comment]
We are using Microservices architecture, and we also want to add social login functionality. I did some test with latest version(`4.7.0`) and with minor manual modifications I progress forward into [this issue](https://github.com/spring-projects/spring-social/issues/216).

Since this feature discussed here, I was wondering if any work is in progress on this right now?

Thanks!
p.s. You can count on me for further tests and research on this.

**Comment by jdubois** [comment]
No progress that I know of.... For me the priority would be #6139 as this would help for so many complex use cases like this one, but this isn't going forward at the moment.
