### ISSUE TITLE
Error: State 'settings' is already defined

### ISSUE THREAD

**Issue by MitchDresdner** [jhipster/generator-jhipster#4859]
##### **Overview of the issue**

JHipster Generator v3.12.2

Following the Matt Raible - JHipster mini-book I created the sample entities, after which the UI stopped displaying and I found the following stack trace:

Uncaught Error: [$injector:modulerr] Failed to instantiate module minibookApp due to:
Error: State 'settings' is already defined
    at registerState (http://localhost:8080/bower_components/angular-ui-router/release/angular-ui-router.js:2362:44)
    at $StateProvider.state (http://localhost:8080/bower_components/angular-ui-router/release/angular-ui-router.js:2872:5)
    at stateConfig (http://localhost:8080/app/account/settings/settings.state.js:11:24)

settings appears to be defined in both: 

app/entities/settings/settings.state.js

and

app/account/settings/settings.state.js

The duplicate use of settings seems to be the cause of the error above.

Renaming .state('settings' to .state('settingz' in app/entities/settings/settings.state.js [line 12] allows the browser to render html again:

    function stateConfig($stateProvider) {
        $stateProvider
        .state('settingz', {

Uncaught Error: [$injector:modulerr] Failed to instantiate module minibookApp due to:
Error: State 'settings' is already defined
    at registerState (http://localhost:8080/bower_components/angular-ui-router/release/angular-ui-router.js:2362:44)
    at $StateProvider.state (http://localhost:8080/bower_components/angular-ui-router/release/angular-ui-router.js:2872:5)
    at stateConfig (http://localhost:8080/app/account/settings/settings.state.js:11:24)

##### **Motivation for or Use Case**

display won't render

##### **Suggest a Fix**

Error: State 'settings' is already defined

##### **JHipster Version(s)**

JHipster Generator v3.12.2

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

created entities (described in raible book) using command line.

##### **Browsers and Operating System**

Chrome, latest

Windows 10 Surface

**Comment by MitchDresdner** [comment]
Seems using the table name 'settings' caused a collision in the namespace  :)

**Comment by jdubois** [comment]
@deepu105 should we add all our default "states" to our "reserved keywords"? Like "password", "register", "sessions", "audit", "configuration".... Why don't we use a prefix for those?

**Comment by deepu105** [comment]
I think we could. it wasnt added since no body complained I guess


Thanks & Regards,
Deepu

**Comment by gmarziou** [comment]
As reported the problem exists in angular 1 but I amde some test and it exists also in ng2 and modules don't help because ui-router has only one namespace for state names.
My test was to change name of healthState from "jhi-health" to "settings" and it fails even though conflicting states are in 2 modules: AdminModule and AccountModule.

This cannot happen with ng2 router because there are no states only routes, so there still can be URL conflicts but same problem exists with ui-router.

**Comment by jdubois** [comment]
Of course, that's stupid of me: the URL should be unique, as the REST endpoints, so what I said makes no sense at all :-)
Then there is always the trick of using a prefix, but many people dislike to have "jhi" everywhere, and we decided to keep those to a minimum.

So, as this has been working for ages without any issues, let's keep the current names/features, but limit the names in our reserved keywords. That's simple, and doesn't break anything.

I'll do a quick list: I might miss some of them, but I guess everyone gets the idea, and that will be simple to improve.

**Comment by jdubois** [comment]
More information on the URL conflict (not just the state conflict, like @gmarziou ): with Angular 2, you can indeed create 2 components with the same URL, in 2 different modules. I just created one entity called "Configuration", and it works. Of course, that's pretty stupid, because you have twice the same URL, and they both work when you click on them from the navbar!! And in case you wonder, when you reload, you get the "/configuration" from the admin, and not from the entity. So it works, but it's stupid, so it's like AngularJS 1: we shouldn't allow this anyway.
