### ISSUE TITLE
[Feature] Choosing The scope of the DTO type to return in REST resources dynamically

### ISSUE THREAD

**Issue by unikzforce** [jhipster/generator-jhipster#4926]
##### **Overview of the issue**

Suppose you have to DTOs for your User entity: the heavyweight one, UserFullDTO, and the light
one, UserLightDTO. and suppose the Generated resources could get the type of DTO you need as a query parameter ---> localhost:8080/api/users?scope=full

a map could be generated for user --- Map<String, Class> --- which contains pair("full", UserFullDTO.class) and pair("tiny", UserTinyDTO.class)
so the 1 REST resource could produce response with respect to the scope you provided, and if you don't provide one, by default it could return the scopeless DTO --> UserDTO or anything that suits better (maybe UserDTO doesn't fit anymore in this case, all DTOs should have a scope from now on ---> UserFullDTO , UserLightDTO, UserUidDTO, UserLightDTO .....

##### **Motivation for or Use Case**

so you don't have to write many resource methods for just changing a DTO scope

**Comment by gmarziou** [comment]
Could you élaborate further? What would the method signature in the resource controller ?

**Comment by unikzforce** [comment]
My DTOs could change like this:
class PipelineFullDTO extents AbstractPipelineDTO {
}
class PipelineLightDTO extents AbstractPipelineDTO {
}
in which the AbstractPipelineDTO is the parent for both. it could be reduced to an interface of course. i haven't thought about it precisely yet.

then I would then generate a Converter,,which would call the suitable function with respect to the scope
class PipelineConverter {
        AbstarctPipelineDTO convert(Pipeline p, String scope) {
               switch(scope)  {
                      case "full":
                              return pipelineMapper.pipelineToPipelineFullDTO(p);
                      case "light":
                              return pipelineMapper.pipelineToPipelineLightDTO(p);
               }
        }
}

in the service layer i would change the generated code to this (in this example findAll() method) : 
    .....
    @Transactional(readOnly = true) 
    public AbstractPipelineDTO findOne(Long id, String dtoScope) {
        log.debug("Request to get Pipeline : {}", id);
        Pipeline pipeline = pipelineRepository.findOne(id);
        AbstractPipelineDTO pipelineDTO = pipelineConverter.convert(pipeline, dtoScope);
        return pipelineDTO;
    }
    ....


and in the REST layer i would generate this:
    @GetMapping("/pipelines/{id}")
    @Timed
    public ResponseEntity<AbstractPipelineDTO> getPipeline(@PathVariable Long id, @RequestParam("scope") String scope) {
        log.debug("REST request to get Pipeline : {}", id);
        AbstractPipelineDTO pipelineDTO = pipelineService.findOne(id, scope);
        return Optional.ofNullable(pipelineDTO)
            .map(result -> new ResponseEntity<>(
                result,
                HttpStatus.OK))
            .orElse(new ResponseEntity<>(HttpStatus.NOT_FOUND));
    }

**Comment by unikzforce** [comment]
sorry i will edit my codes to make it readable, as soon as i learn how to do it

**Comment by unikzforce** [comment]
and all of these is possible only if we could get some little extra information from the user before generating ,, some pairs --->
"full"    ----for---> PipelineFullDTO and 
"light"  ----for---> PipelineLightDTO

**Comment by unikzforce** [comment]
and about the swagger and springfox ... i don't know yet, i'm only familiar with swagger but only a little. i've to take a look at them first for any comments about them

**Comment by gmarziou** [comment]
Ok so it looks like a lightweight graphql for which we had a request : #4251
I think the same answer could apply here but I let others comment.

**Comment by unikzforce** [comment]
tnx, i'll see that soon

**Comment by unikzforce** [comment]
One thing that you may Mention is that the "AbstractPipelineDTO"  may lack value for the people who want to get DTO's properties... the fact is maybe we should separate Generated Resource classes and provide  Some Custom Resource classes... like spring data
in spring data we've seen sweet repository interfaces, and if someone needed a custom repository method she could create her custom repository class....
For example we could Generate PipelineCustomResource alongeside PipelineResource... if someone needed   a specific custom api write it in PipelineCustomResource and leave the generic PipelineResource alone.
and in that PipelineCustomResource she could play with Concrete DTOs

**Comment by unikzforce** [comment]
it seems that GraphQL has some personality ... attractive

**Comment by jdubois** [comment]
Yes I know people will want to do "light" and "heavy" DTOs, and that's what I don't like too much about this pattern, because you end up with lots of classes.

- We can't do it now, the DTO as been in BETA for years (literally), so first it needs to be out of beta before we do something more complex
- Indeed, GraphQL could be a better solution - then it's not ready yet, as its implementation is not finished yet (it's a working draft at the moment)
- We also have the concept of VM (View Model) that we should work on, and which would complement this sometimes. Here also, we have work to do, at least for documenting this correctly, and generating VMs as well as DTOs

For me it's too early to do this kind of stuff. Our added-value wouldn't also be very high: just copy/paste the current DTO, or do another mapping.... There's not a lot of added-value with JHipster here.

I'm closing this as for me it's really too early to go into that kind of thing.

**Comment by unikzforce** [comment]
okay, i understand, would you please tell me what is graphql draft repository ? can we see that draft?

**Comment by jdubois** [comment]
I'm talking about https://github.com/graphql-java/graphql-java

**Comment by lobosan** [comment]
Hi is jhipster offering support for graphql?

**Comment by jdubois** [comment]
No. There isn't a good GraphQL solution in Java, and also the way GraphQL works will probably be very inefficient with Hibernate, and quite troublesome with Spring Security.

I'm also waiting to see if the technology takes off. At the moment, after a lot of hype, the main GraphQL project has as many stars as JHipster. And the issue with something this complex, is that we need a **lot** of users in order to have something working. That's how OSS works: we have typically 1 contributor for every 1,000 users. So if a complex technology is asked by too few people, we won't be able to maintain it correctly.

So while I'd like to use GraphQL (I'm using it for a client, and like many parts of it), we're not supporting it now, and probably not in the near future. Unless a great team of people decide to join the project and implement it & maintain it, of course.

**Comment by lobosan** [comment]
@jdubois Thanks for your quick and detailed response. I understand the complexity to integrate GraphQL with Jhipster and I hope next year this technology gain more adepts

**Comment by cbornet** [comment]
If you're interested in GraphQL, don't hesitate to do a module or blueprint !
