### ISSUE TITLE
Upgrade to latest ng2-translate

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#4968]
The last time i tried to upgrade to latest ng2-translate version for the library I had so many issues. There wasnt any breaking change reported on the changelogs but somehow things were messed up. So I didnt upgrade.
Need to see if we can upgrade and fix issues after our Beta release

**Comment by jdubois** [comment]
I didn't study it, but I saw there was now an official i18n support in
Angular 2, so this is like NG Router and probably we should migrate to it.

Le 25 janv. 2017 6:22 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

The last time i tried to upgrade to latest ng2-translate version for the
library I had so many issues. There wasnt any breaking change reported on
the changelogs but somehow things were messed up. So I didnt upgrade.
Need to see if we can upgrade and fix issues after our Beta release

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/4968>, or mute the
thread

**Comment by deepu105** [comment]
I would pass their option :smiling_imp: 

> The i18n template translation process has four phases:
> 
> Mark static text messages in your component templates for translation.
> 
> An angular i18n tool extracts the marked messages into an industry standard translation source file.
> 
> A translator edits that file, translating the extracted text messages into the target language, and returns the file to you.
> 
> The Angular compiler imports the completed translation files, replaces the original messages with translated text, and generates a new version of the application in the target language.
> 
> You need to build and deploy a separate version of the application for each supported language.

really I have to compile and deploy a separate app for each language?
This is why I'm starting to like React more and more as they dont force their stuff on to users and you are free to mix and match and still works. I really hate the direction Ng2 is going trying to do everything

**Comment by gzsombor** [comment]
So you can't switch between the languages on the fly? The whole app needs to be re-loaded? Strange feature ...

**Comment by deepu105** [comment]
like most other strange design decisions of NG2

**Comment by jdubois** [comment]
I'm definitely not a big fan of how the Angular team behaves and works....

I'm putting this on "hold", let's have a look after the JHipster 4 release.

**Comment by jdubois** [comment]
Let's do this after v4: there is a lot of discussion to do here before deciding. So I'm removing the label.

**Comment by deepu105** [comment]
The library has been renamed to [ngx-translate](https://github.com/ngx-translate/core)

**Comment by wmarques** [comment]
The Angular team strongly advised to remove any "ng2" things in project names, as Angular 4 is coming, that's why some libs are renamed.

**Comment by dancancro** [comment]
Judging from the [demo](https://embed.plnkr.co/pYo6bFPRRxVPgRR8toDt/), it doesn't seem like this requires you to have a separate app for each language. Maybe this has changed since January?

**Comment by deepu105** [comment]
closed https://github.com/jhipster/generator-jhipster/commit/1e0720f3d6d36c79149d363e88b920614736b181
