### ISSUE TITLE
A new (post-3.12.2) AngularJS (i.e. 1.x) based release?

### ISSUE THREAD

**Issue by piprog** [jhipster/generator-jhipster#5027]
##### **Overview of the issue**

First of all a big thanks from all of us for the work you are putting into the 4.0 (primarily Angular 2) release! In the process a number of issues have been addressed / enhancements added that are not strictly Angular 2 related and would greatly benefit production applications working with AngularJS. Are there any plans to have an interim release (e.g. 3.12.3?) that would make these important changes available for us soon in order to incorporate into live apps? I know that we could pick these by hand and merge into our code bases, but it is non-trivial and would fragment the JHipster landscape. 

Another (related) issue is that even if 4.0 is imminent we may not switch to Angular 2 for a couple+ of months with live apps (may require considerable work, although far less than without JHipster) so some kind of well-defined maintenance route for AngularJS would be nice for the next year or so (please point me to the right docs if this is already addressed).

Thanks!

**Comment by jdubois** [comment]
There is a misunderstanding with JHipster 4:

- we still support AngularJS 1.x, in fact it is the default option
- Angular 2 is only available as BETA

So that should be OK for you, if you can easily upgrade from JHipster 3.x to JHipster 4: I have not tried it myself, but I don't think it's going to be very complex.

Of course, if the upgrade is complex, we can have a look at doing a new JHipster 3.x release.

Then, remember this is a community project, and maintenance releases are never fun, so that would probably won't have much support...
