### ISSUE TITLE
Convert has-authority directives to structural directives

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#5063]
JHipster 4.0.0

The "Administration" menu doesn't disappear for non-admin users. It just doesn't render - so there's a large gap in the menu.

![screen shot 2017-02-02 at 7 44 40 am](https://cloud.githubusercontent.com/assets/17892/22553966/c0a202a8-e91b-11e6-853f-54b1bcbbff2e.png)

**Comment by mraible** [comment]
Changing `has-authority.directive.ts` to have the following seems like one way to fix this issue.

```
    private setVisible () {
        this.renderer.setElementStyle(this.el.nativeElement, 'display', '');
    }

    private setHidden () {
        this.renderer.setElementStyle(this.el.nativeElement, 'display', 'none');
    }
```

I tried the following too, but it does not work.

```
    private setVisible () {
        this.renderer.setElementAttribute(this.el.nativeElement, 'hidden', '');
    }

    private setHidden () {
        this.renderer.setElementAttribute(this.el.nativeElement, 'hidden', 'true');
    }
```

**Comment by deepu105** [comment]
setting the display style property would be the correct approach. but instead of making it empty on visible its better to add 'block' or 'inline-block' depending on whats currently applied when visible

**Comment by gmarziou** [comment]
Sorry I did not notice this gap. Have you tred just to revert  PR #5054 by using `hidden-xs-up` rather than invisble ?

**Comment by mraible** [comment]
@gmarziou Using `hidden-xs-up` instead of `invisible` seems to work. I believe this needs to change in `has-authority.directive.ts` as well as `has-any-authority.directive.ts`. Another option would be to make these directives behave like `*ngIf`.

https://angular.io/docs/ts/latest/guide/template-syntax.html#!#star-template

**Comment by gmarziou** [comment]
Using something similar to *ngIf would make sense but as I don't know how to do it, let's revert my PR.

**Comment by deepu105** [comment]
we can convert them to structural directives https://angular.io/docs/ts/latest/guide/structural-directives.html

**Comment by deepu105** [comment]
@gmarziou do you wanna do it else I can do it this weekend

**Comment by gmarziou** [comment]
I can do it but maybe next week, I guess there's no emergency.

**Comment by jdubois** [comment]
Please note I'm documenting this in the (not released yet) "using Angular" documentation page. It should still be OK if you transform this to a structural directive, but that's always good to check if you modify this.

**Comment by jdubois** [comment]
And the "using Angular" documentation is ready at: https://jhipster.github.io/using-angular/

**Comment by gmarziou** [comment]
My first attempt is not successful so far. It seems that you can have only one structural directive per element. In navbar, I tried:

~~~html
   <li *ngSwitchCase="true"  *jhiHasAuthority="ROLE_ADMIN">`
~~~

and got this error:

> Can't have multiple template bindings on one element. Use only one attribute named 'template' or prefixed with *.

So a workaorund could be to split the 2 directives on 2 elements.

~~~html
   <li *ngSwitchCase="true"><span *jhiHasAuthority="ROLE_ADMIN">`
~~~

**Comment by jdubois** [comment]
Yes you could split it in 2. It's not perfect, but still better than hiding the elements.

**Comment by gmarziou** [comment]
I got `jhiHasAuthority` directive working.
An important thing to notice is that the argument of a structural directive must be an expression, it implies that to pass a string you must quote it as below:

~~~html
<some-element *jhiHasAuthority="'ROLE_ADMIN'">...</some-element>
~~~

This may seem cumbersome but in fact it is more powerful because you can also pass an array of strings:

~~~html
<some-element *jhiHasAuthority="['ROLE_ADMIN', 'ROLE_USER']">...</some-element>
~~~

So I see no point in having 2 directives `jhiHasAuthority` and `jhiHasAnyAuthority`, I propose to keep only `jhiHasAnyAuthority` and to pass either a single string or an array of strings.

**Comment by deepu105** [comment]
Ok for only one directive

Thanks & regards,
Deepu

On 15 Feb 2017 1:26 a.m., "Gaël Marziou" <notifications@github.com> wrote:

I got jhiHasAuthority directive working.
An important thing to notice is that the argument of a structural directive
must be an expression, it implies that to pass a string you must quote it
as below:

<some-element *jhiHasAuthority="'ROLE_ADMIN'">...</some-element>

This may seem cumbersome but in fact it is more powerful because you can
also pass an array of strings:

<some-element *jhiHasAuthority="['ROLE_ADMIN', 'ROLE_USER']">...</some-element>

So I see no point in having 2 directives jhiHasAuthority and
jhiHasAnyAuthority, I propose to keep only jhiHasAnyAuthority and to pass
either a single string or an array of strings.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5063#issuecomment-279880392>,
or mute the thread

**Comment by jdubois** [comment]
Yes it's easier ! But don't forget to update the website in the "using
Angular 2" section

Le 15 févr. 2017 8:39 AM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

> Ok for only one directive
>
> Thanks & regards,
> Deepu
>

**Comment by gmarziou** [comment]
OK

**Comment by gmarziou** [comment]
PR for doc:jhipster/jhipster.github.io#391
