### ISSUE TITLE
i18n JSON files could be bundled by Webpack

### ISSUE THREAD

**Issue by gmarziou** [jhipster/generator-jhipster#5072]
##### **Overview of the issue**

Today translation files are loaded by XHR from server which results in many roundtrips to server.

Webpack has a json-loader and ng2-translate has a TranslateLoader interface that we already implement in [TranslatePartialLoader](https://github.com/jhipster/ng-jhipster/blob/master/src/language/translate-partial-loader.ts).

So maybe we could combine both and have ng2-translate load translations from bundles.

##### **Motivation for or Use Case**

Reduce network latency.

**Comment by flaviencathala** [comment]
I made something to load directly the translations without any http request (see https://github.com/jhipster/ng-jhipster/pull/28 and https://github.com/jhipster/generator-jhipster/pull/5131).

**Comment by gmarziou** [comment]
Great, I'll have a look tonight.

**Comment by deepu105** [comment]
There was a reason to do it with http request instead of bundling it with the source. In a real world app the translation files will keep growing and if you have multiple languages you will have a lot of json files. So if we bundle it we are making the initial file huge and takes time to download hence loading them as partials will not hit the initial loading and also not everyone might need all translation files like admin part for example. What I would rather do is to improve the partial loader to have some sort of in memory caching so that same file for a language is not requested again. Im not ok to bundle everything in a huge file which takes long time to load as its bad user experience and already our bundles are quite big

**Comment by gmarziou** [comment]
Let's take a small app: 5 languages, 11 entities.

The i18n folder takes 162 KB, once gzipped it takes only 23 KB. I could be wrong but I don't think it makes a big difference over our current bundle size, what should make a big difference is AOT

On the other hand, when you access i18n partial over http, you pay latency on each page first time you hit it and this is quite noticeable on a phone.

**Comment by gmarziou** [comment]
if we don't implement this, I will turn it into a module for those who are more concerned about application reactivity than bundle size.

**Comment by jdubois** [comment]
Thanks @gmarziou -> I am convinced this is a better solution, than actually downloading JSON files all the times (which is what we currently do with AngularJS 1)

**Comment by deepu105** [comment]
I understand your point but i'm still concerned as we already have quite a lot of js code. Let me do some tests for this

**Comment by allahbaksh** [comment]
@deepu105 We are facing few issues because of this. Is the solution to this is coming soon in the branch

**Comment by deepu105** [comment]
I dont think anybody is working on this

**Comment by allahbaksh** [comment]
Ok. Just wanted to check.

**Comment by gzsombor** [comment]
Actually, I've run into this same issue, and I've implemented a fix : #5689

**Comment by gzsombor** [comment]
My main problem was, that [TranslatePartialLoader](https://github.com/jhipster/ng-jhipster/blob/master/src/language/translate-partial-loader.ts) reloads all the jsons, in every page change - because the setLocation call clears the caches, and tries to fetch all the specified jsons.

**Comment by deepu105** [comment]
Closed via #5689
