### ISSUE TITLE
Jhipster upgrade does not work

### ISSUE THREAD

**Issue by caneraydinbey** [jhipster/generator-jhipster#5137]
##### **Overview of the issue**

When i try to upgrade jhipster, it stays in current version.

> vegan@vegan:~$ yo
? 'Allo vegan! What would you like to do? Jhipster

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo jhipster

 
        ██  ██    ██  ████████  ███████    ██████  ████████  ████████  ███████
        ██  ██    ██     ██     ██    ██  ██          ██     ██        ██    ██
        ██  ████████     ██     ███████    █████      ██     ██████    ███████
  ██    ██  ██    ██     ██     ██             ██     ██     ██        ██   ██
   ██████   ██    ██  ████████  ██        ██████      ██     ████████  ██    ██

                            http://jhipster.github.io

Welcome to the JHipster Generator v3.12.2
Documentation for creating an application: https://jhipster.github.io/creating-an-app/
Application files will be generated in folder: /home/vegan
 ______________________________________________________________________________

  JHipster update available: 4.0.2 (current: 3.12.2)
  Run npm install -g generator-jhipster to update.

I do this but still same

> vegan@vegan:~$ sudo  npm install -g generator-jhipster
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/usr/lib
└── generator-jhipster@4.0.2 

those are information

> vegan@vegan:~$ npm -v
4.1.2
vegan@vegan:~$ nodejs -v
v5.12.0
vegan@vegan:~$

**Comment by jdubois** [comment]
This lacks some information on what you are doing, so what I guess is your issue:

- with "npm -g" you update JHipster globally. You can try creating a new project, and you will have the new version
- if you run JHipster on a project that was already generated, JHipster will keep the same version (this is for people doing multiple projects, we can't upgrade every thing) -> this would cause your issue

That's why we say in the release notes at https://jhipster.github.io/2017/02/06/jhipster-release-4.0.2.html that you should first delete your node_modules directory.
