### ISSUE TITLE
Suggest git ignoring bower_components by default

### ISSUE THREAD

**Issue by hookszhang** [jhipster/generator-jhipster#5154]
##### **Overview of the issue**

Suggest git ignoring bower_components by default, this is a hidden trouble.
##### **Motivation for or Use Case**

Submit bower_components is incomplete
##### **Reproduce the error**

The `.gitignore` file ignored bin, build, etc folder can cause bower_components incomplete, and `bower install` also can't fix that.

Need to delete the incomplete components then run `bower install` can fixed that.
##### **Related issues**

When another developer clone my jhipster project and run `gulp build` index.html changed.
After diff found some bower components not inject.
I check my bower components, the following files are ignored:

```
src/main/webapp/bower_components/angular-loading-bar/build/loading-bar.css
src/main/webapp/bower_components/angular-loading-bar/build/loading-bar.js
src/main/webapp/bower_components/angular-loading-bar/build/loading-bar.min.css
src/main/webapp/bower_components/angular-loading-bar/build/loading-bar.min.js
src/main/webapp/bower_components/messageformat/bin/messageformat.js
src/main/webapp/bower_components/modernizr/bin/modernizr
src/main/webapp/bower_components/modernizr/test/node/lib/build.js
src/main/webapp/bower_components/modernizr/test/node/lib/cli.js
src/main/webapp/bower_components/modernizr/test/node/lib/metadata.js
src/main/webapp/bower_components/modernizr/test/node/lib/options.js
src/main/webapp/bower_components/ngInfiniteScroll/build/ng-infinite-scroll.js
src/main/webapp/bower_components/ngInfiniteScroll/build/ng-infinite-scroll.min.js
```
##### **Suggest a Fix**

```
echo 'bower_components/' >> generator-jhipster/generators/server/templates/gitignore
```
##### **JHipster Version(s)**

3.10.0

**Comment by ruddell** [comment]
This issue is really bad because you won't notice it anything wrong until someone else checks out the project or until CI tries to build it.  The angular-loading-bar and ngInfiniteScroll issue was fixed in #5143, I fixed modernizr in a new PR.

If you want to stay on v3 or use AngularJS with v4, make sure `.gitignore` contains
 - `/build/` instead of `build/`
 - `/bin/` instead of `bin/`
 - `/node/` instead of `node/`

The bower_components ignore issue was discussed #1816, if you prefer to ignore them just add it to your .gitignore

**Comment by jdubois** [comment]
Yes please look at the old issues, this has been discussed many times already.

**Comment by hookszhang** [comment]
Ok, obviously using ignore base level is better. Thanks @ruddell.
