### ISSUE TITLE
does Jhipster support Mybatis?

### ISSUE THREAD

**Issue by andywang2014** [jhipster/generator-jhipster#5195]
does Jhipster support Mybatis?On the main page,I got it just support Hibernate.

**Comment by atomfrede** [comment]
We only support hibernate.

**Comment by pascalgrimaud** [comment]
You can read the old discussion between our 2 techleads: https://github.com/jhipster/generator-jhipster/issues/1252

You can try to do it as a module: https://jhipster.github.io/modules/creating-a-module/

**Comment by andywang2014** [comment]
if i want to use jhipster with mybatis,how should i do?

**Comment by jdubois** [comment]
You remove the DAO layer, remove the Hibernate configuration, and code everything by hand.
You might better not use JHipster at all in your case, you'll have tons of issues (we also rely on lazy loading, etc...).

**Comment by andywang2014** [comment]
@jdubois so sad to hear that

**Comment by deepu105** [comment]
Wow I asked that 2 years ago :) a lot have changed since. For the said
project in the old ticket I took the plunge and went with JPA + hibernate
and thanks to simplicity of spring data it was easier for my team and I
successfully implemented the project for advanced queries I used queryDSL
and I never missed myBatis. So my suggestion would be below:

If you are starting a new project its safer to go with JPA as you
wouldn'thave much benefit from myBatis over JPA

If you have an existing DB model and want to build a project on top go with
myBatis with or without Jhipster

Thanks & regards,
Deepu

**Comment by andywang2014** [comment]
thank you very much.@deepu105
