### ISSUE TITLE
[discuss]why databases is not for containers

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#5197]
[Mountain West Ruby 2016 - Surviving the Framework Hype Cycle by Brandon Hays test](https://www.youtube.com/watch?v=9zc4DSTRGeM#7m40s)

[why databases is not for containers](https://myopsblog.wordpress.com/2017/02/06/why-databases-is-not-for-containers/)

**Comment by pascalgrimaud** [comment]
Sorry but I dont understand this issue.

Do you mean it is bad to use database with Docker? I dont care about all these points described in your article when I start development.
JHipster provided all Docker Compose files to start very very quickly a database. Feel free to use it or not.

Closing this ticket because I dont think there is a need to discuss about that.

**Comment by jdubois** [comment]
I also don't understand the point?

If the idea is to say that we shouldn't use a database in a container:

- Our main use case is for development and testing, and here containers are a HUGE gain
- For prod you are free to point to any database you want

On a personal point of you, and with JHipster we don't force you at all, I would still recommend using a container for running your database in production, there are tons of companies doing this (including mine), and I'm not going to change my mind because someone writes some blog post on a technology he doesn't understand.
