### ISSUE TITLE
Entity Audit issue with Jhipster 4.0.6

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#5340]
Installed Jhipster 4.0.6 and Jhipster Entity Audit 2.2.2

![image](https://cloud.githubusercontent.com/assets/11784253/23493454/ecc7e9fc-ff31-11e6-8f9b-30f3a256bc64.png)

Error jhipster-entity-audit 

ERROR! I support only JHipster versions greater than ^3.6.0...
          If you want to use Entity Audit with an older JHipster version, download a previous version that supports the required JHipster version.

**Comment by ruddell** [comment]
That module is in a separate repository.  There's an issue [tracking Angular 2 support](https://github.com/hipster-labs/generator-jhipster-entity-audit/issues/48).  If you use AngularJS or microservices, there is also a workaround in that issue.

**Comment by jdubois** [comment]
I don't understand what you mean -> the message is clear, that's not supported, so there's no bug at all here.

**Comment by JinnaBalu** [comment]
ERROR says that I support only JHipster versions greater than ^3.6.0..., i have latest version installed. which is 4.0.6

**Comment by jdubois** [comment]
Oh sorry you are correct.
Then 4.x is another major release, don't expect it to work :-)

Le 2 mars 2017 8:51 AM, "jbalu" <notifications@github.com> a écrit :

ERROR says that I support only JHipster versions greater than ^3.6.0..., i
have latest version installed. which is 4.0.6

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5340#issuecomment-283581487>,
or mute the thread

**Comment by JinnaBalu** [comment]
can we reopen this.

**Comment by deepu105** [comment]
Not here as its a module and has its own issue tracker. Some major work is
required to make it work with angular2 and I don't have enough time at the
moment

Thanks & regards,
Deepu
