### ISSUE TITLE
JWT token - user is still logged in on other browser tabs after log out

### ISSUE THREAD

**Issue by MarcGiffing** [jhipster/generator-jhipster#5410]
##### **Overview of the issue**

I'm using JHipster with JWT tokens which are stored in the local storage when user checks the checkbox on login (don't know the naming now). When logging out on one tab I'm still logged in in the other tab. 
I need to refresh the page to be logged out. 

##### **Motivation for or Use Case**

If the user logs out you expected to be logged out! It's a security problem if you still have full access to the application on another tab.

##### **Reproduce the error**

https://github.com/PillowPillow/ng2-webstorage/issues/38

http://plnkr.co/edit/S9nWN60fpS6TLUEbWf5L?p=preview&open=app%2Fapp.component.ts
(Change the version back to 1.5.0)

##### **JHipster Version(s)**

4.0.8

**Comment by jdubois** [comment]
As the JWT is basically stored in memory in your tab, I understand your issue, and I'm quite surprised you could solve it this way.
Of course that's great, you provide the bug report and the fix, and it's all easy for us -> I'll wait a little bit to have more feedback (and don't worry, the build will fail, we currently have an issue there, this isn't your fault), and otherwise I'll merge this.

**Comment by MarcGiffing** [comment]
The browsers 'session storage' is used if you don't click the remember me checkbox on log in. So you are only logged in in the current tab. If you click the remember me checkbox the token is stored in the 'local storage' which is for all tabs and also available after restarting the browser. The problem is that the log out removes the token in the local storage but is still available the the cache of the ng2-webstorage module. Many thanks to @PillowPillow for the module and for providing a quick fix with a new release. 👍

**Comment by jdubois** [comment]
OK, thanks, let's do it!
