### ISSUE TITLE
Jhipster MicroService application - Error "Your request cannot be processed"

### ISSUE THREAD

**Issue by shivangmodi21** [jhipster/generator-jhipster#5457]
Hello,
I generated with "yo jhipster" applications, Microservice application 'JHipsterPOC' then download Jhipster Registry "https://github.com/jhipster/jhipster-registry.git"

I started jhipster registry and it urns on http://127.0.0.1:8761/
But after that, I started 'JHipsterPOC' microservice application, it shows up in registry project.
When I directly hit the application, http://127.0.0.1:8081/
![microservice-application](ht
![microservice-application](https://cloud.githubusercontent.com/assets/20971111/24162879/e11b8c0a-0e8e-11e7-8c12-ea0828073c0f.png)
tps://cloud.githubusercontent.com/assets/20971111/24162820/ae805032-0e8e-11e7-81ea-b34fedefe9e2.png)
, it throws error like  "Your request cannot be processed"

Thanks
![jhipster-registry](https://cloud.githubusercontent.com/assets/20971111/24162743/7f56fb58-0e8e-11e7-90a1-02a355febceb.png)

**Comment by jdubois** [comment]
Please follow our guidelines....
That's normal you have a 404 error, you selected a microservice, so it
doesn't have a front-end. That's what the 404 is all about.

Le 21 mars 2017 7:04 PM, "shivangmodi21" <notifications@github.com> a
écrit :

Hello,
I generated with "yo jhipster" applications, Microservice application
'JHipsterPOC' then download Jhipster Registry "https://github.com/jhipster/
jhipster-registry.git"

I started jhipster registry and it urns on http://127.0.0.1:8761/
But after that, I started 'JHipsterPOC' microservice application, it shows
up in registry project.
When I directly hit the application, http://127.0.0.1:8081/
![microservice-application](ht
[image: microservice-application]
<https://cloud.githubusercontent.com/assets/20971111/24162879/e11b8c0a-0e8e-11e7-8c12-ea0828073c0f.png>
tps://cloud.githubusercontent.com/assets/20971111/24162820/
ae805032-0e8e-11e7-81ea-b34fedefe9e2.png)
, it throws error like "Your request cannot be processed"

Thanks
[image: jhipster-registry]
<https://cloud.githubusercontent.com/assets/20971111/24162743/7f56fb58-0e8e-11e7-90a1-02a355febceb.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5457>, or mute the
thread

**Comment by deepu105** [comment]
This ticket has been closed as the guidelines are not followed.

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#submitting-an-issue), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md), 
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.
