### ISSUE TITLE
Authenticationservice not upgrading to client credentials in database

### ISSUE THREAD

**Issue by NilsWild** [jhipster/generator-jhipster#5459]
##### **Overview of the issue**

I got an old authentication microservice i like to update to 4.1.0. I upgraded the application but it keeps the old hardcoded clientcredentials instead of generating the new database based client authentication. I dont know how as the template (according to the git repo here) doesn't contain that code for sql based apps. I expect its due to my database configuration (h2Disk dev, mysql prod) no sure though. csv file for client credentials isnt copied either.

Happens with newly generated application as well. Seems like my v4.1.0 uses different template files than those that are contained in this repo.

##### **Motivation for or Use Case**

See above

##### **JHipster Version(s)**

4.1.0

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.0",
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableTranslation": true,
    "applicationType": "uaa",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn"
  }
}

##### **Browsers and Operating System**
Ubuntu 16.04
upgraded jhipster with yarn global upgrade generator-jhipster

**Comment by jdubois** [comment]
I don't understand your issue very well, but it looks like an upgrade issue, with you still having the old templates.
This is normal, and on purpose: otherwise you couldn't have several applications, with several JHipster versions. When you upgrade you need to follow the procedure which is written with each release notes, see https://jhipster.github.io/2017/03/20/jhipster-release-4.1.0.html
-> so basically, delete your `node_modules`, where you have a copy of the JHipster release you used to generate the project

**Comment by NilsWild** [comment]
I did exactly that. I deleted the node_modules folder right now and regenerated the app -> same problem. So i created a new vm right now installed nvm node npm and yarn. Installed jhipster globally and created a new uaa service. Same problem. So i took a look into the node_module files and there i got that template 

```package <%=packageName%>.config;

import <%=packageName%>.security.AuthoritiesConstants;

import io.github.jhipster.config.JHipsterProperties;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.oauth2.config.annotation.configurers.ClientDetailsServiceConfigurer;
import org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableAuthorizationServer;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableResourceServer;
import org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer;
import org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerSecurityConfigurer;
import org.springframework.security.oauth2.config.annotation.web.configurers.ResourceServerSecurityConfigurer;
import org.springframework.security.oauth2.provider.token.TokenStore;
import org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter;
import org.springframework.security.oauth2.provider.token.store.JwtTokenStore;
import org.springframework.security.oauth2.provider.token.store.KeyStoreKeyFactory;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
import org.springframework.web.filter.CorsFilter;

import javax.servlet.http.HttpServletResponse;
import java.security.KeyPair;

@Configuration
@EnableAuthorizationServer
public class UaaConfiguration extends AuthorizationServerConfigurerAdapter {

    @EnableResourceServer
    public static class ResourceServerConfiguration extends ResourceServerConfigurerAdapter {

        private final TokenStore tokenStore;

        private final JHipsterProperties jHipsterProperties;

        private final CorsFilter corsFilter;

        public ResourceServerConfiguration(TokenStore tokenStore, JHipsterProperties jHipsterProperties, CorsFilter corsFilter) {
            this.tokenStore = tokenStore;
            this.jHipsterProperties = jHipsterProperties;
            this.corsFilter = corsFilter;
        }

        @Override
        public void configure(HttpSecurity http) throws Exception {
            http
                .exceptionHandling()
                .authenticationEntryPoint((request, response, authException) -> response.sendError(HttpServletResponse.SC_UNAUTHORIZED))
            .and()
                .csrf()
                .disable()
                .addFilterBefore(corsFilter, UsernamePasswordAuthenticationFilter.class)
                .headers()
                .frameOptions()
                .disable()
            .and()
                .sessionManagement()
                .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
            .and()
                .authorizeRequests()
                .antMatchers("/api/register").permitAll()
                .antMatchers("/api/activate").permitAll()
                .antMatchers("/api/authenticate").permitAll()
                .antMatchers("/api/account/reset_password/init").permitAll()
                .antMatchers("/api/account/reset_password/finish").permitAll()
                .antMatchers("/api/profile-info").permitAll()
                .antMatchers("/api/**").authenticated()<% if (websocket == 'spring-websocket') { %>
                .antMatchers("/websocket/tracker").hasAuthority(AuthoritiesConstants.ADMIN)
                .antMatchers("/websocket/**").permitAll()<% } %>
                .antMatchers("/management/health").permitAll()
                .antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN)
                .antMatchers("/v2/api-docs/**").permitAll()
                .antMatchers("/swagger-resources/configuration/ui").permitAll()
                .antMatchers("/swagger-ui/index.html").hasAuthority(AuthoritiesConstants.ADMIN);
        }

        @Override
        public void configure(ResourceServerSecurityConfigurer resources) throws Exception {
            resources.resourceId("jhipster-uaa").tokenStore(tokenStore);
        }
    }

    private final JHipsterProperties jHipsterProperties;

    public UaaConfiguration(JHipsterProperties jHipsterProperties) {
        this.jHipsterProperties = jHipsterProperties;
    }

    @Override
    public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
        /*
        For a better client design, this should be done by a ClientDetailsService (similar to UserDetailsService).
         */
        clients.inMemory()
            .withClient("web_app")
            .scopes("openid")
            .autoApprove(true)
            .authorizedGrantTypes("implicit","refresh_token", "password", "authorization_code")
            .and()
            .withClient(jHipsterProperties.getSecurity().getClientAuthorization().getClientId())
            .secret(jHipsterProperties.getSecurity().getClientAuthorization().getClientSecret())
            .scopes("web-app")
            .autoApprove(true)
            .authorizedGrantTypes("client_credentials");
    }

    @Override
    public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
        endpoints.authenticationManager(authenticationManager).accessTokenConverter(
                jwtAccessTokenConverter());
    }

    @Autowired
    @Qualifier("authenticationManagerBean")
    private AuthenticationManager authenticationManager;

    /**
     * Apply the token converter (and enhander) for token store.
     */
    @Bean
    public JwtTokenStore tokenStore() {
        return new JwtTokenStore(jwtAccessTokenConverter());
    }

    /**
     * This bean generates an token enhancer, which manages the exchange between JWT acces tokens and Authentication
     * in both directions.
     *
     * @return an access token converter configured with the authorization server's public/private keys
     */
    @Bean
    public JwtAccessTokenConverter jwtAccessTokenConverter() {
        JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
        KeyPair keyPair = new KeyStoreKeyFactory(
             new ClassPathResource("keystore.jks"), "password".toCharArray())
             .getKeyPair("selfsigned");
        converter.setKeyPair(keyPair);
        return converter;
    }

    @Override
    public void configure(AuthorizationServerSecurityConfigurer oauthServer) throws Exception {
        oauthServer.tokenKeyAccess("permitAll()").checkTokenAccess(
                "isAuthenticated()");
    }
}
```

which isn't correct. But the package.json seems to be correct: 
```
{
  "name": "generator-jhipster",
  "version": "4.1.0",
  "description": "Spring Boot + Angular in one handy generator",
  "files": [
    "generators"
  ],
  "keywords": [
    "yeoman-generator",
    "Java",
    "Spring",
    "Spring Boot",
    "Spring Security",
    "JPA",
    "Hibernate",
    "AngularJS",
    "Angular",
    "Twitter Bootstrap"
  ],
  "homepage": "http://jhipster.github.io/",
  "bugs": "https://github.com/jhipster/generator-jhipster/issues",
  "author": {
    "name": "Julien Dubois",
    "email": "",
    "url": "https://github.com/jdubois"
  },
  "main": "app/index.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/jhipster/generator-jhipster.git"
  },
  "scripts": {
    "pretest": "eslint .",
    "lint": "eslint .",
    "lint-fix": "eslint . --fix",
    "test": "mocha --timeout 20000 --slow 0 --reporter spec"
  },
  "dependencies": {
    "chalk": "1.1.3",
    "cheerio": "0.22.0",
    "ejs": "2.5.6",
    "glob": "7.1.1",
    "html-wiring": "1.2.0",
    "insight": "0.8.4",
    "jhipster-core": "1.2.8",
    "js-yaml": "3.8.2",
    "lodash": "4.17.4",
    "mkdirp": "0.5.1",
    "pluralize": "4.0.0",
    "randexp": "0.4.5",
    "semver": "5.3.0",
    "shelljs": "0.7.7",
    "yeoman-generator": "1.1.1",
    "yo": "1.8.5"
  },
  "devDependencies": {
    "eslint": "3.17.1",
    "eslint-config-airbnb-base": "11.1.1",
    "eslint-plugin-import": "2.2.0",
    "fs-extra": "2.1.0",
    "mocha": "3.2.0",
    "yeoman-assert": "3.0.0",
    "yeoman-test": "1.6.0"
  },
  "engines": {
    "node": ">=6.9.0",
    "npm": ">=2.14.2"
  },
  "license": "Apache-2.0"
}
```

Somehow the sources arent correct

**Comment by jdubois** [comment]
When you say "install globally", did you use Yarn or NPM ? Those two can be
mixed up

Le 22 mars 2017 8:42 AM, "Nils Wild" <notifications@github.com> a écrit :

I did exactly that. I deleted the node_modules folder right now and
regenerated the app -> same problem. So i created a new vm right now
installed nvm node npm and yarn. Installed jhipster globally and created a
new uaa service. Same problem. So i took a look into the node_module files
and there i got that template


import <%=packageName%>.security.AuthoritiesConstants;

import io.github.jhipster.config.JHipsterProperties;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.oauth2.config.annotation.configurers.ClientDetailsServiceConfigurer;
import org.springframework.security.oauth2.config.annotation.web.configuration.AuthorizationServerConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableAuthorizationServer;
import org.springframework.security.oauth2.config.annotation.web.configuration.EnableResourceServer;
import org.springframework.security.oauth2.config.annotation.web.configuration.ResourceServerConfigurerAdapter;
import org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer;
import org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerSecurityConfigurer;
import org.springframework.security.oauth2.config.annotation.web.configurers.ResourceServerSecurityConfigurer;
import org.springframework.security.oauth2.provider.token.TokenStore;
import org.springframework.security.oauth2.provider.token.store.JwtAccessTokenConverter;
import org.springframework.security.oauth2.provider.token.store.JwtTokenStore;
import org.springframework.security.oauth2.provider.token.store.KeyStoreKeyFactory;
import org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter;
import org.springframework.web.filter.CorsFilter;

import javax.servlet.http.HttpServletResponse;
import java.security.KeyPair;

@Configuration
@EnableAuthorizationServer
public class UaaConfiguration extends AuthorizationServerConfigurerAdapter {

    @EnableResourceServer
    public static class ResourceServerConfiguration extends
ResourceServerConfigurerAdapter {

        private final TokenStore tokenStore;

        private final JHipsterProperties jHipsterProperties;

        private final CorsFilter corsFilter;

        public ResourceServerConfiguration(TokenStore tokenStore,
JHipsterProperties jHipsterProperties, CorsFilter corsFilter) {
            this.tokenStore = tokenStore;
            this.jHipsterProperties = jHipsterProperties;
            this.corsFilter = corsFilter;
        }

        @Override
        public void configure(HttpSecurity http) throws Exception {
            http
                .exceptionHandling()
                .authenticationEntryPoint((request, response,
authException) ->
response.sendError(HttpServletResponse.SC_UNAUTHORIZED))
            .and()
                .csrf()
                .disable()
                .addFilterBefore(corsFilter,
UsernamePasswordAuthenticationFilter.class)
                .headers()
                .frameOptions()
                .disable()
            .and()
                .sessionManagement()
                .sessionCreationPolicy(SessionCreationPolicy.STATELESS)
            .and()
                .authorizeRequests()
                .antMatchers("/api/register").permitAll()
                .antMatchers("/api/activate").permitAll()
                .antMatchers("/api/authenticate").permitAll()
                .antMatchers("/api/account/reset_password/init").permitAll()
                .antMatchers("/api/account/reset_password/finish").permitAll()
                .antMatchers("/api/profile-info").permitAll()
                .antMatchers("/api/**").authenticated()<% if
(websocket == 'spring-websocket') { %>

.antMatchers("/websocket/tracker").hasAuthority(AuthoritiesConstants.ADMIN)
                .antMatchers("/websocket/**").permitAll()<% } %>
                .antMatchers("/management/health").permitAll()

.antMatchers("/management/**").hasAuthority(AuthoritiesConstants.ADMIN)
                .antMatchers("/v2/api-docs/**").permitAll()
                .antMatchers("/swagger-resources/configuration/ui").permitAll()

.antMatchers("/swagger-ui/index.html").hasAuthority(AuthoritiesConstants.ADMIN);
        }

        @Override
        public void configure(ResourceServerSecurityConfigurer
resources) throws Exception {
            resources.resourceId("jhipster-uaa").tokenStore(tokenStore);
        }
    }

    private final JHipsterProperties jHipsterProperties;

    public UaaConfiguration(JHipsterProperties jHipsterProperties) {
        this.jHipsterProperties = jHipsterProperties;
    }

    @Override
    public void configure(ClientDetailsServiceConfigurer clients)
throws Exception {
        /*
        For a better client design, this should be done by a
ClientDetailsService (similar to UserDetailsService).
         */
        clients.inMemory()
            .withClient("web_app")
            .scopes("openid")
            .autoApprove(true)
            .authorizedGrantTypes("implicit","refresh_token",
"password", "authorization_code")
            .and()
            .withClient(jHipsterProperties.getSecurity().getClientAuthorization().getClientId())
            .secret(jHipsterProperties.getSecurity().getClientAuthorization().getClientSecret())
            .scopes("web-app")
            .autoApprove(true)
            .authorizedGrantTypes("client_credentials");
    }

    @Override
    public void configure(AuthorizationServerEndpointsConfigurer
endpoints) throws Exception {
        endpoints.authenticationManager(authenticationManager).accessTokenConverter(
                jwtAccessTokenConverter());
    }

    @Autowired
    @Qualifier("authenticationManagerBean")
    private AuthenticationManager authenticationManager;

    /**
     * Apply the token converter (and enhander) for token store.
     */
    @Bean
    public JwtTokenStore tokenStore() {
        return new JwtTokenStore(jwtAccessTokenConverter());
    }

    /**
     * This bean generates an token enhancer, which manages the
exchange between JWT acces tokens and Authentication
     * in both directions.
     *
     * @return an access token converter configured with the
authorization server's public/private keys
     */
    @Bean
    public JwtAccessTokenConverter jwtAccessTokenConverter() {
        JwtAccessTokenConverter converter = new JwtAccessTokenConverter();
        KeyPair keyPair = new KeyStoreKeyFactory(
             new ClassPathResource("keystore.jks"), "password".toCharArray())
             .getKeyPair("selfsigned");
        converter.setKeyPair(keyPair);
        return converter;
    }

    @Override
    public void configure(AuthorizationServerSecurityConfigurer
oauthServer) throws Exception {
        oauthServer.tokenKeyAccess("permitAll()").checkTokenAccess(
                "isAuthenticated()");
    }
}

which isn't correct. But the package.json seems to be correct:

{
  "name": "generator-jhipster",
  "version": "4.1.0",
  "description": "Spring Boot + Angular in one handy generator",
  "files": [
    "generators"
  ],
  "keywords": [
    "yeoman-generator",
    "Java",
    "Spring",
    "Spring Boot",
    "Spring Security",
    "JPA",
    "Hibernate",
    "AngularJS",
    "Angular",
    "Twitter Bootstrap"
  ],
  "homepage": "http://jhipster.github.io/",
  "bugs": "https://github.com/jhipster/generator-jhipster/issues",
  "author": {
    "name": "Julien Dubois",
    "email": "",
    "url": "https://github.com/jdubois"
  },
  "main": "app/index.js",
  "repository": {
    "type": "git",
    "url": "git://github.com/jhipster/generator-jhipster.git"
  },
  "scripts": {
    "pretest": "eslint .",
    "lint": "eslint .",
    "lint-fix": "eslint . --fix",
    "test": "mocha --timeout 20000 --slow 0 --reporter spec"
  },
  "dependencies": {
    "chalk": "1.1.3",
    "cheerio": "0.22.0",
    "ejs": "2.5.6",
    "glob": "7.1.1",
    "html-wiring": "1.2.0",
    "insight": "0.8.4",
    "jhipster-core": "1.2.8",
    "js-yaml": "3.8.2",
    "lodash": "4.17.4",
    "mkdirp": "0.5.1",
    "pluralize": "4.0.0",
    "randexp": "0.4.5",
    "semver": "5.3.0",
    "shelljs": "0.7.7",
    "yeoman-generator": "1.1.1",
    "yo": "1.8.5"
  },
  "devDependencies": {
    "eslint": "3.17.1",
    "eslint-config-airbnb-base": "11.1.1",
    "eslint-plugin-import": "2.2.0",
    "fs-extra": "2.1.0",
    "mocha": "3.2.0",
    "yeoman-assert": "3.0.0",
    "yeoman-test": "1.6.0"
  },
  "engines": {
    "node": ">=6.9.0",
    "npm": ">=2.14.2"
  },
  "license": "Apache-2.0"
}

Somehow the sources arent correct

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5459#issuecomment-288321485>,
or mute the thread

**Comment by deepu105** [comment]
Try to generate a fresh app in a new folder using the .yo_rc.json from your
old app and compare both apps to see whats different

Thanks & regards,
Deepu

**Comment by deepu105** [comment]
And your yo-rc comfig looks weird. Whats with the promtValues section?

**Comment by NilsWild** [comment]
Those prompt values are there when i generate a new yo-rc.json. In my old config they are missing but thats not a problem. The Problem is that the template files arent correct when i install generator-jhipster via yarn. 

i used yarn as stated above. on both my system and vm. i also cleared generator-jhipster in .cache and .config dir of yarn and readded generator-jhipster and even did a new installation on a clear vm on all systems i get those old template files for UaaConfiguration but the correct package.json.

At the VM i followed exactly the steps stated in the install Jhipster manual:
Local installation with Yarn (recommended for normal users)

**Comment by pascalgrimaud** [comment]
it's hard to help if we dont have all exact steps to **reproduce**, with commands you used etc...

**Comment by deepu105** [comment]
Ok Im really confused and dont get exactly what you are doing. Could you
explain what you are doing and the issue in more detail please

Thanks & regards,
Deepu

**Comment by NilsWild** [comment]
I am sorry just saw that the new OAuthConfig is in a different file. Don't know how i missed it.
Anyway why is the _UaaConfiguration file used instead of the _OAuth2ServerConfiguration file. yo-rc.json looks exactly like the one in my opening report when generating a new app.

**Comment by NilsWild** [comment]
Just to be clear: 

i generate a Uaa service with all default values. This results in a yo-rcjson looking like that:
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.1.0",
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableTranslation": true,
    "applicationType": "uaa",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "skipClient": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "clientPackageManager": "yarn"
  }
}
```
Now the UaaConfiguration is generated. The Oauth2Configuration isnt. 

You can copy the above yo-rc.json and run yo jhipster to reproduce.

**Comment by NilsWild** [comment]
Ok got it. Sorry. Just saw in the pullrequest discussion that the database backed client authorization wasnt updated for microservices https://github.com/jhipster/generator-jhipster/pull/3772 i will generate a monolith an edit my config accordingly.
