### ISSUE TITLE
CSV to use , instead of ;

### ISSUE THREAD

**Issue by tezcane** [jhipster/generator-jhipster#5492]
##### **Overview of the issue**

CSV stands for Comma Separated Values, but the CSV files used by JHipster and Liquibase are separated by semicolons.

##### **Motivation for or Use Case**

This is annoying as Excel and other spreadsheet programs by default do not work when you use a semicolon, but they would if you used a comma. 

##### **Reproduce the error**

N/A

##### **Related issues**

N/A

##### **Suggest a Fix**

00000000000_initial_schema.xml:
```
<loadData encoding="UTF-8"
                  file="config/liquibase/users.csv"
                  separator=";"
```
to
```
<loadData encoding="UTF-8"
                  file="config/liquibase/users.csv"
                  separator=","
```

Replace all ";" with "," for authorities.csv, users.csv and users_authorities.csv

I confirmed all this works as expected.

##### **JHipster Version(s)**

All

##### **JHipster configuration**

N/A 

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A

- [ X ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm not totally sure about his:

- The ";" is correct CSV code
- It's less widely used than "," (in sentences, in numbers, etc), so there are less things to escape, which I find easier to use
- You can still import it in Excel and/or Open Office, there's a wizard which asks you the separator, this shouldn't cause a big issue

Then I understand it's easier to double-click on the file, rather than importing it... Anybody else as an opinion here?

**Comment by gmarziou** [comment]
';' is the default CSV separator for french Excel.

**Comment by PierreBesson** [comment]
I found a related stackoverflow discussion : http://stackoverflow.com/a/10141147/6896299 that might help us to decide what to do...

**Comment by tezcane** [comment]
I'm OK either way, thought it may be more of a pain point for others.

**Comment by PierreBesson** [comment]
@tezcane So the reason we have semicolon separators is that in some countries (e.g France where most of the JHipster team is from) the decimal separator is the comma rather than the dot.

To access the CSV import wizard in Excel, go to the "Data tab" and select "From text".

![screen shot 2017-03-29 at 13 53 12](https://cloud.githubusercontent.com/assets/513471/24453240/56f1840e-1487-11e7-9185-6d6f4dfb1ef9.png)
