### ISSUE TITLE
Some subgenerators not working since Angular2 had been added

### ISSUE THREAD

**Issue by manfredpaul** [jhipster/generator-jhipster#5713]
Hy, 

Since all function in `generator-base` have an additional parameter `clientFramework ` some subgenerators like `generator-jhipster-leaflet` are not working anymore. 

Shouldn't we consider adding a default parameter `clientFramework = angular1` ?
Otherwise you should make sure that the subgenerators will work with the given application configuration (ex. chose Angluar2 when subgenerator will generate Angular1 code)

Here are the steps for reproduction : 
I created an jhipster application (4.3.0) with Angular1. 
I added the subgenerator  `generator-jhipster-leaflet` (1.0.0)

I have an error message : Unable to find `src/main/webapp/app/layouts/navbar/navbar.component.html or missing required jhipster-needle. Reference to leaflet-maps not added to menu.`

Ok, the developers of the subgenerator should update their code, but I thinks for subgenerators to be successful you should consider a non breaking API. 

I can write the code if you want.

Manfred PAUL

**Comment by pascalgrimaud** [comment]
The system of module allows to create third-party generators that have access to the JHipster variables and functions, and act like standard JHipster sub-generators.

We know that some of these modules are not compatible with Angular4 but you should ask directly to the respective owners to update them.

Some of these generators don't know the parameter `clientFramework`, when they were coded, so I don't understand what you proposed. How can we control a 'non breaking API' as these subgenerators can do what they want?

I'm closing this, as I don't think we can do something here.
But you can still propose here, if you have an idea.

**Comment by jdubois** [comment]
- Those are not sub-generators, but modules: modules are done by people outside of the project, and indeed they should update their code, that's their responsibility
- This change was done with the last major update, so we did break the API, but that's normal (that's why it was a major update in the first place)

Indeed, we should have some check to prevent this: we already have a check for the minimum required version of JHipster used by a module, we should have the same check for the maximum version. And by default, we should not use a new major release automatically - in your case, that would mean the module would produce an error.

**Comment by deepu105** [comment]
But the suggestion of having a default value is actually good. Let me see
if i can add it in

**Comment by manfredpaul** [comment]
Hi, 

It was actually for a module using Angular1 so the breaking change was adding the parameter `clientFramework`. So no direct problem with Angular1 vs Angular2/3/4... 

Thanks for thinking about it
