### ISSUE TITLE
email domain extensions are missing in many places

### ISSUE THREAD

**Issue by tezcane** [jhipster/generator-jhipster#5810]
##### **Overview of the issue**

Emails in many unit tests and default DB (users.csv file) look like:
john.doe@localhost
instead of:
john.doe@localhost.com

##### **Motivation for or Use Case**

This is scary since many things WILL go wrong if we are not properly testing for real emails in our unit tests and other areas of the code.  Imagine you write lots of logic around handling emails (which is typical), now how can you be sure your code actually works since maybe things may break with .com, .net, etc. are there or not (you should really reject any email without domain extension).

##### **Reproduce the error**

N/A

##### **Related issues**

I have seen domain extensions come up in regards to supporting it in API calls (where username/login was changed to email), but not related to fixing/adding them to the unit tests or ensuring they are there when a user specifies emails.

##### **Suggest a Fix**

Stage 1: Add .com extension to all places it is missing in the generator (all unit tests and users.csv file).
Stage 2: Make sure all logic rejects emails without domain extension (john.doe@localhost should never be legal in my opinion since no one actually has an email that looks like that)

##### **JHipster Version(s)**

N/A

##### **JHipster configuration**

N/A 

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A 

##### **Browsers and Operating System**

N/A 

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
While it may seem weird, I'm pretty sure `admin@localhost` is a valid email address according to the spec ([RFC 5322](https://tools.ietf.org/html/rfc5322), see sections 3.4.1). HTML5 email validation follows that spec and also allows `admin@localhost`.

I'm not sure what the best move here is.

**Comment by jdubois** [comment]
Yes, I often use "root@localhost", it's quite typical on Linux, at least for me...

**Comment by jdubois** [comment]
After checking, I'm sorry but I don't agree with you:

- "root@localhost" is valid, and used quite often (MySQL users use it, as well as many other libraries)
- It's a nice way of testing on a local machine, as you get the mails directly
- Pointing to a domain we don't own, like "localhost.com", is really not nice to the person owning the domain. Trust me, I have a very common name in France, and I keep getting test emails from various people, and I just hate this.
- Of course, we could point to a throwable email account ( http://www.yopmail.com/ is very popular in France), but then everyone can see your credentials, so that's not a good solution either

**Comment by tezcane** [comment]
I am aware the spec allows no domains, but that is not my concern.  My main concern is not testing proper/common email addresses we will actually see by users**.  So, I think what a solution here (so we are all happy) is to ensure the unit tests test exist for both @localhost and @localhost.com formats** (duplicate certain tests or make them functional to take email as a param).  There is no telling what will change or be configured in Spring to chop the .com on or off....

I guess I will also start assuming a user can have @localhost (maybe I will start a company that makes such emails, it is way cleaner and hipper... the only problem is all web developers will hate me)

By the way, I have setup all my unit tests to not send out emails... I mock the MailService.sendEmail() to return null.  Otherwise the test still passes (since it is done asynchronously) but your trace log has long exceptions in it.

**Comment by jdubois** [comment]
I don't understand your issue with **@localhost** - and no you can't sell them, they are sent on your localhost...
Anyway, as the issue is the one of validation: I just checked, and we do use Bean Validation's `@Email` validation. So here again, we're not the ones doing the validation code, it just happens to be the standard Java validation mechanism, and this follows our [policy](https://jhipster.github.io/policies/) of using standard API without modifying them (unless we have a very good reason to do so).

**Comment by tezcane** [comment]
I am fine with @localhost, it should remain there as is.  My concern is when a user begins adding email logic (new API's, modifies email code, acceptable email patterns, makes new unit tests, case sensitivity, email as login, etc.) then you will have many instances where adding the email domain extension to the unit tests will be necessary to test.

Can I do PR where, in addition to @localhost style unit tests, I add a domain extension unit test to the same tests (few lines of code per existing unit test).  I can use a temporary/public email like jhipster@grr.la to not spam anyone and you can actually view the test emails here: https://www.guerrillamail.com/inbox if desired.

**Comment by deepu105** [comment]
I dont think we should add any actual email services in generated tests as we dont want spam any service as well. If you can write a test to mock that its fine as long you use a mock email id as well. If people want to test tis with actual services they need to change the tests

**Comment by tezcane** [comment]
The unit tests are mocked already, so would not be an issue... what would be the safest domain to use for unit tests (haha besides @localhost)

**Comment by tezcane** [comment]
On my machine this actually links back to my pc: http://www.localhost.com/

so @localhost.com is probably safe to use...

**Comment by gmarziou** [comment]
example.org and example.com are reserved for documentations like RFC, so they could be good candidates.
https://www.iana.org/domains/reserved
