### ISSUE TITLE
Can't Edit User via User Management

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster#5870]
##### **Overview of the issue**

Trying to edit a user results in a 400 error, caused by #5857 which changed the ManagedUserVM password field to `@NotBlank`

##### **Reproduce the error**

Generate an application and try to edit a user via User Management.  To make the tests fail, change [this line in UserResourceIntTest.java](https://github.com/jhipster/generator-jhipster/blob/d9cbe8e2ccd9a08a965b0868e35dfb6e368ed87a/generators/server/templates/src/test/java/package/web/rest/_UserResourceIntTest.java#L466) to `null` (or change `UPDATED_PASSWORD` to `null`.  This would be a good change because UserResource doesn't send passwords when editing users, all things related to passwords are handled by AccountResource

##### **Related issues**

#5857
#5848

##### **Suggest a Fix**

Remove the annotation? Use a different VM?

##### **JHipster Version(s)**

Master

##### **JHipster configuration**
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.5.2",
    "baseName": "newtest",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "hibernateCache": "ehcache",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "jwtSecretKey": "ca5c243cd041b2f30b922262a1ee95b0d761432c",
    "clientFramework": "angular2",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Ping @greenstevester : maybe you have a suggestion for the fix too?

**Comment by tezcane** [comment]
I suggest we use the User mapper to not update any field unless it's value is non-null.  This will prevent all kinds of unneeded updates to the db and code execution too.

**Comment by greenstevester** [comment]
Firstly, apologies for breaking existing functionality. 

+1 for @ruddell's suggestion of using a different VM and making AccountResource solely responsible for all things related to password handling.  

I suggest adding a new:  "AccountVM" - which would solely be used in AccountResource and do the handling of the password, instead of ManagedUserVM as is currently the case.  
It would essentially be a copy of ManagedUserVM, but used in the context of Account management (i.e. password handling). Please note I am a firm supporter of the DRY principle, but this case it looks to me like two different contexts here, that are differentiated by a security concern - that being the password (since as @ruddell pointed out, UserResource doesn't send passwords when editing user).

This means reverting my [#5857](https://github.com/jhipster/generator-jhipster/pull/5857) addition of the @NotBlank annotation in ManagedUserVM and instead adding it to the new "AccountVM". 

We would then have the following:
1. KeyAndPasswordVM - used only for finish password reset (in AccountResource)
2. LoginVM - used only for the login
3. AccountVM - used only in AccountResource
4. ManagedUserVM - used only in UserResource

Is that too many VM's?

Additionally,  some comments to the top of each of these VM's would be nice to clearly state their intention and responsibility. One more thing is that AccountResourceIntTest currently has lots of ManagedUserVM references and these would also need to be replaced with AccountVM references.  

@tezcane - I also like this idea, but if someone for example added a lastname and then at a later point wanted to intentionally set it to null again, how would the User mapper handle this?

**Comment by tezcane** [comment]
Once lastname is set, the use user should not be able to clear the field, he has to input something else to replace it (e.g. this time his real/new last name).  The UI would control that, e.g. can't hit save until a valid field is entered again.  For cases where you MUST set to null again you can make it so if the field equals ""/-1 etc. then it can be set to null, but ideally this logic should be though of and designed into the UI again.

**Comment by greenstevester** [comment]
@tezcane - imposing that a user may not clear the field might be too restrictive, since it is a valid use case (see example at the end).  If a field is an empty string literal "", then interpreting that as a null value (and not updating the domain entity) , could indeed be done by the UserMapper.

But since validation logic at the minute, is primarily driven via DTO/VM validation annotations on the REST controllers, moving some of that into the Mappers would spread validation logic between mappers and annotations and this would be bad.  Mind you, there is some "light" validation in the UserMapper currently, but it's really minimal.

DTO/VM validation annotations while very convenient, also create issues... like this one where functionality can be hosed, even with reasonable test coverage and the best intentions.

This begs the next question: why not put all DTO/VM validation in one place -i .e. in the mapper itself? At least you would know that all DTO/VM validation resides in the mapper, which is easier to test and less prone to side effects.

**Suggestion No. 2:** Remove ONLY the validation annotations from the DTO and VM classes that exist currently and transfer validation responsibility over to the mapping layer. 
This also means removing javax.validation.Valid annotation on the REST controllers where DTO's or VM's currently exist in the method signatures.

@ruddell  @pascalgrimaud - what's your thoughts on this?

To be clear, I am not saying no annotations on DTO's, since it makes sense that for Swagger for example, @ApiModel and @ApiModelProperty annotations on DTO's are much better placed, than say cluttering them into the internal domain entities.  Also if people want to expose their internal domain entities without creating DTO's/VM then of course they are completely free to do so and if they use annotation validation, then they will end up with a mix of validation mechanisms in their codebase.

_UseCase example:  From personal experience, some forums I have joined, I realised all details on my profile were in fact public and later decided to set some fields back to null, because I thought they were not required._

**Comment by jdubois** [comment]
This is so complex, for just a simple non-null field!

- We can do validation groups with Bean Validation: that would be the correct way to solve this, but I find the API quite complicated
- We could just leave the field "nullable", as we don't send a password all the time. And only in the business case where we need a non-null password (when we create or change it, for all other use cases the password shouldn't be used for anything), then we test that it is not null.

**Comment by greenstevester** [comment]
Agree, I've written way too much already about a simple non-null field :-)  

How about I revert my #5857 fix (remove the NotBlank annotation) and replace it with the same test for null, which the  AccountResource.changePassword method already uses, i.e:

```
if (!checkPasswordLength(password)) {
       return new ResponseEntity<>("Incorrect password", HttpStatus.BAD_REQUEST);
}
```

**Comment by delverdev** [comment]
@greenstevester, I think `"Incorrect password"` should be replaced to a translation key.

**Comment by jdubois** [comment]
Yes @greenstevester @delverdev that's good solution for me.
As I'd like to do a patch release soon, let me have a look at this

**Comment by jdubois** [comment]
@delverdev I know it's bad, but the rest of that class doesn't use translation keys, so for the moment I'm just solving the issue (one thing at a time), following what @greenstevester proposed
