### ISSUE TITLE
Feature Request: PrimeFaces UI support

### ISSUE THREAD

**Issue by coderhelps** [jhipster/generator-jhipster#5912]
What are the thoughts about adding PrimeFaces as an alternate UI to the current Angular UI?
https://www.primefaces.org/
PrimeFaces has nice simple java ui support and since this is a java framework generator it seems like it would be a nice choice java app developers.
If I were to implement this or put out bounties for the implementation of this what are the recommendations to integrate it into the generator?

**Comment by jdubois** [comment]
Sorry, but we have selected Bootstrap as our UI components.
Adding PrimeNG support is trivial, just follow the PrimeNG documentation: I did it a couple of weeks ago, it took me 10 minutes. So that would also be against [Policy 2](https://jhipster.github.io/policies/), as we don't want to generate something too bloated, when it's trivial to add the feature.
If you want to do this, this could be a module, that would make it even easier to use.
