### ISSUE TITLE
Feature Request: CAS integration

### ISSUE THREAD

**Issue by coderhelps** [jhipster/generator-jhipster#5913]
Thoughts on the integration of a central authentication service, something like: https://github.com/apereo/cas into the generator?
I believe this would allow many more authentication options than what are currently offered, such as x509, 2 factor auth, etc across multiple apps / services.
Any recommendations or suggestions?

**Comment by jdubois** [comment]
I already do this quite often, with our JWT support. The current work is to integrate Keycloak, and I guess this would help this also.
We just can't support everything: this would be a good fit for a module, if anybody is interested.

**Comment by piprog** [comment]
Have you gotten anywhere with cas or keycloak? I'd need 2-factor auth in a new app.

**Comment by piprog** [comment]
hi Matt - thx for the hyperspeed reply! I was wondering how 2FA (two factor authentication; in my case (user name+password) + SMS token) could be integrated into JHipster - I'm not sure OAuth 2.0 helps here, since AFAIK it does not do 2FA by default. cas mentioned in the original comment does do 2FA, though.

**Comment by mraible** [comment]
Okta supports 2FA, not sure about Keycloak.

https://developer.okta.com/signup/
