### ISSUE TITLE
The requestIntercept() in AuthInterceptor.ts will be executed twice for every http request.

### ISSUE THREAD

**Issue by zhaojunjie163** [jhipster/generator-jhipster#5918]
I think it's a bug, version from 0.1.16 to 0.2.2
requestIntercept() method in AuthInterceptor.ts will be executed twice for every http request.

**Comment by deepu105** [comment]
could you be more specific?

**Comment by zhaojunjie163** [comment]
@deepu105
Thanks for your swift reply.
For example:
Whenever I call any **this.http.get()** method once.
The requestIntercept() method in AuthInterceptor.ts was supposed to be executed once, but it was executed twice.

I found this problem by printing logs as shown below:
 requestIntercept(options?: RequestOptionsArgs): RequestOptionsArgs {
        const token = this.localStorage.retrieve('authenticationToken') || this.sessionStorage.retrieve('authenticationToken');
        if (!!token) {
            options.headers.append('Authorization', 'Bearer ' + token);
        }
        **console.log('AuthInterceptor requestIntercept');**
        return options;
    }

I think all the interceptors(error, auth-expired, notification) have this issue, kindly take a look as it's critical.

Thanks 
Best Regards
Junjie

**Comment by deepu105** [comment]
Ok thanks

On 14 Jun 2017 3:47 am, "zhaojunjie163" <notifications@github.com> wrote:

@deepu105 <https://github.com/deepu105>
Thanks for your swift reply.
For example:
Whenever I call any *this.http.get()* method once.
The requestIntercept() method in AuthInterceptor.ts was supposed to be
executed once, but it was executed twice.

I found this problem by printing logs as shown below:
requestIntercept(options?: RequestOptionsArgs): RequestOptionsArgs {
const token = this.localStorage.retrieve('authenticationToken') ||
this.sessionStorage.retrieve('authenticationToken');
if (!!token) {
options.headers.append('Authorization', 'Bearer ' + token);
}
*console.log('AuthInterceptor requestIntercept');*
return options;
}

I think all the interceptors(error, auth-expired, notification) have this
issue, kindly take a look as it's critical.

Thanks
Best Regards
Junjie

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/5918#issuecomment-308296210>,
or mute the thread
