### ISSUE TITLE
add high level control and view to current hard coded REST API paths

### ISSUE THREAD

**Issue by tezcane** [jhipster/generator-jhipster#5943]
##### **Overview of the issue**

Feature Request: It currently requires lots of code edits to update the generated REST API paths (e.g. api/users) since they are hard coded.  This is because the API paths are hard coded in the REST layer, Security Configurations, Unit Tests, and Angular Front End router code.

##### **Motivation for or Use Case**

The API Paths being hard coded makes it quite tedious and error prone to customize and change the REST API path to do things like add an API version number (e.g. api/v1/users) to phase it in/out software releases (canary testing), do A/B testing, zero downtime upgrades, etc.  Also, if you modify the REST path at all now, it will break the unit tests, security configs, and front end router code so it is better to have this data configurable and visible in one or two high level files.  In doing so too, you will provide a high level overview of the entire API and allow the user to understand and customize the system to their liking more too.  On top of that, they can see what they need/don't need and more easily search/refactor through the code to lock down/remove/patch security holes.

##### **Reproduce the error**

N/A

##### **Related issues**

Searched 'REST API Path' and did not find any similar discussions.

##### **Suggest a Fix**

Add a global interface file that holds all the ApiPaths for the Spring side of things, e.g.:
```
package hapi.gtw.web.rest.util;

public interface ApiPath {
    String ROOT                      = "/api/v0";  //NOTE: how by adding "/v0" how I now support versioning throughout my API.

    String ACCOUNT                   = "/account"                 ;
    String ACCOUNT_CHANGE_PW         = ACCOUNT+"/change_password"        ; 
   ...
}
```
Note: The Angular code would need the equivalent .ts file (for example).

Then use like so in REST layer like so:
```
/** REST controller for managing the current user's account. */
@RestController
@RequestMapping(ApiPath.ROOT)
public class AccountResource {
...
@PostMapping(path= ApiPath.ACCOUNT_CHANGE_PW,
                    produces={MediaType.APPLICATION_JSON_VALUE, MediaType.TEXT_PLAIN_VALUE})
    @Timed
    public ResponseEntity<AccountVM> changePassword(...
```
Or since it is an interface can use it like so too:
```
public class SecurityConfiguration extends WebSecurityConfigurerAdapter implements ApiPath {
...
```

I'm not sure if the entities could work using the same ApiPath base file (ideally it should), but it would look similar to this too.

##### **JHipster configuration**

N/A

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

N/A

##### **Browsers and Operating System**

N/A

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
You can't have this at the same place for Angular and Spring Boot, so there isn't a lot of added value: for Spring Boot, for example, that would only be used in the controller and in the test (and for the test, I'm not even sure it's a good idea, as you are supposed to test URLs). So that would be against [Policy 2](https://jhipster.github.io/policies/).

I also never saw people doing this, so that would be against [Policy 1](https://jhipster.github.io/policies/).

Besides:
- I like a lot to have the path next to the method as it's quicker and easier to use (only one file to open)
- having a "centralized file" is what we had with Struts, and that was really annoying when working in a team (as everybody is modifying the same file, you're going to have merge conflicts all the time)

Anyway we can't do such a huge change now: we are struggling to release Angular 4 out of beta, it's not the time to refactor.

**Comment by tezcane** [comment]
Please read my response carefully as I feel many of your statements are not justified.

Policy #2 Quote:
> Policy 2: only add options when there is sufficient added-value in the generated code
> JHipster has many options when generating a project. We only add those options when they are complex and imply configuring or coding several components.
> 
> Adding an option only because it saves a couple of lines to code isn’t a good usage of JHipster:
> 
> It’s easier to code those lines manually than to learn a new JHipster option
> It will only make our generator more complex without adding any value

This feature request is more in favor of Policy # 2, not against it.  For Policy # 2, it does not complicate things but simplify for JHipster users, there is no configuration that is changing or option that is being added here.  If this feature is implemented it will prevent a user from having to make ~200 lines of code changes, not a couple as Policy # 2 states and you have implied.   Not only that, but he can prevent these ~200 line code changes by adding just ~4 characters to one file!  This update would also be used in the SpringConfigurations.java file, entities, front end, front end test code too (more than one or two places so again in Agreement with Policy # 2).  If it is tedious to have two copies of the REST paths for the backend and front end (which again is actually in support of Policy # 2), we can build a single file that both back and front ends can share (this may be best and easiest so entities can easily append to this file too).  Also, by making this change it makes testing URL's much easier and less error prone, so I don't understand how this change would prevent URL paths from being tested, you can more easily test actually and more easily see what needs to be tested.  In general, anytime you hard code a string in code you are asking for trouble, so I believe the current coding conventions of the app are against policy #1 (this is a big no-no for any programming language, just because you haven't seen it done for REST paths, doesn't mean we shouldn't because it is the right thing to do regardless).  I can argue this for things like the project names too, it should be a global static name in the project, so if user wants to rename their gateway for example, they do that in one place, not 500 as they currently have to.

Quote of Policy #1

> Policy 1: technologies used by JHipster have their default configuration used as much as possible
> For example, we use JPA, Spring or AngularJS the “usual way”, without some heavy configuration options and with their usual naming and coding conventions. We do this as:
> 
> Each technology usually has a very good reason to have those defaults
> It’s much easier to understand how JHipster works if we don’t re-configure everything
> We might only change a default configuration if it produces some issue with the other technologies used by JHipster. For example, to have Spring Security and AngularJS working together, we had to change Spring Security’s default configuration.

I don't feel this feature request is against Policy # 1 either.  We are not changing any Spring/Angular configurations, we are simply replacing Strings with variables to make the code easier to understand, test, modify, and refactor.  The last sentence here actually gives a good example of how, by making this change, it will allow Spring and Angular to integrate more easily which is a major concern and pain.

Lastly, I think these policies are good but if they are not followed accurately or misinterpreted they will prevent the project from excelling.  Regardless of any policy, since we are generated code that EVERYONE is going to have trouble understanding and eventually highly modify anyway, shouldn't we make that learning and modification process as painless as possible?  By rejecting feature requests that improve the code architecture and make the project easier to use, modify, understand, build upon, etc. we are really hurting our end users who will go through lots of pain and keep saying "If only JHipster did it this way".

**Comment by jdubois** [comment]
- I don't think that "EVERYONE is going to have trouble understanding and eventually highly modify anyway". We follow the usual Spring Boot configuration you see everywhere, including in all Spring tutorials, and I've never seen someone refactor this code to use constants -> that's my point about policy 1. It's obvious to understand the current configuration, as it's just the String that is written, there's no way people can have a hard time understanding what we generate.
- I don't think that putting everything in one big config file is a good idea: that's one of the original strengths of Spring MVC, compared to Struts, as it's much easier to understand and use (just one String at the right place, you don't need to have a look elsewhere), and it's easier to work in team (no merge conflict in the big constants file).
- Those Strings are not going to get refactored in "200 lines". First of all, they are only used once (outside of the tests): we have Sonar checks and that would violate those. We do use constants when Strings are re-used, for example for the security roles. But if you use a constant for a String that isn't re-used elsewhere, then that's misleading, as you would expect it's being re-used, so for me that wouldn't be good idea.
- For tests it's different: I want to test URLs, which I have in a specification elsewhere. If I use a constant made by the person who coded the controller, then I'm not testing anything: I'm testing a path coming from a constant, using that same constant.
- For Angular you can't have something in common with Spring MVC. First of all, they are very different technologies so that would be hard to do. But the biggest issue is that in a real project you often have something very different from a CRUD, so you're going to have your backend and frontend evolve in different ways, so you can't tie them up or you will get stuck when you code your business logic.

**Comment by deepu105** [comment]
@tezcane @jdubois here are my thoughts on this.
@tezcane I think just changing `@RequestMapping("/api")` annotation at class level to `@RequestMapping(ApiPath.ROOT)` to use the `/api` string from a constant file rather than hard code it in every class would remove all the duplication of that string and will allow you to change the base path without modifying it everywhere. hence personally I would be ok to do this. 
For the remaining I agree with @jdubois I dont see a benefit in having every url in a constant file. I would rather have them as it is today as its easier to read and maintain. I hated the struts way actually.

**Comment by jdubois** [comment]
Oh sorry @tezcane I totally misunderstood one point:

-> For Angular, you're speaking of the URL in the services, not the Angular routes?

If that's the case, I agree with you this is annoying to have the same URL in both Spring MVC REST controllers and Angular services, and needing to modify both.

However, I don't really see how we could implement a solution - typically, the solution to this use-case is JHipster itself! There's a common config file that is used to generate both front and back technologies the same way.

But yes, I agree on the pain point, sorry to missed that.

**Comment by xetys** [comment]
I am likely to say, this feature would be great for a JHipster crack, who knows his stack like his pocket, and confusing for someone, who is new to it. The best example here is the usage of our role constants. They must be consistent to really work with each other in spring and angular. If you are in topic, you know for sure where to change things. But if you check the issue tracker and StackOverflow, you find a lot of people confused about how to handle new roles in JHipster.

Changing a URL mapping now will let several tests fail, what lead a new user to check the correct things. For a pro this can be annoying, perhaps. Otherwise think of finding that "one constants to rule them all" solution, which enforces consistency in both sides in a hard code way. This will obfuscate the actual thing we're doing. While the pro might like that, because he knows the edges.

**Comment by tezcane** [comment]
Maybe the core team can do a vote?

At the least do it on the "/api"+ApiPath.VERSION (default will be "") as @deepu105 suggested.

**Comment by deepu105** [comment]
@tezcane technically we don't vote on everything. Since its impossible for us to support everything, we as project maintainers make a decision based on what will be overall more beneficial to the project, maintainability, team, and community. I hope you do understand that we do not have bandwidth to maintain everything (I know your case is not that huge in terms of maintenance, but I'm talking in general)
anyway I'll let @jdubois decide this

**Comment by jdubois** [comment]
For me, as I wrote earlier, we can't change this at the moment. We have so much work, including Angular 4, that changing something like this is just not possible right now.
I have no idea when things will settle down, but at the moment this works for *most people*, and changing this would be a big re-write, so this is mainly an issue of us (including me) not being available at all.

**Comment by tezcane** [comment]
OK no problem guys.  Thanks for considering it.

**Comment by pascalgrimaud** [comment]
What can't be done in the main generator, can probably be done in a module. 
Playing with some regexp/replace can work.

If you decide to start a module for that, don't hesitate to ping us

**Comment by agoncal** [comment]
I was looking at customizing the `/api` path and stumbled on this issue (I know, the issue is closed ;o).

What we do is we change the JHipster APIs to `/internal` and do not use them in our applications (we just leave the JHipster gateway use `/internal`). Then we add `/api` for our business APIs consumed by our applications, and then `/public` that we expose for 3rd parties.

So I actually would love to be able to customize that (such as a variable on the JDL ?). If not, a module would do.
