### ISSUE TITLE
Deploying JHipster applications to Deis Workflow.

### ISSUE THREAD

**Issue by hivp** [jhipster/generator-jhipster#6040]
##### **Overview of the issue**

JHipster does not provide support to deploy apps to Deis Workflow.

##### **Motivation for or Use Case**

It would be great to have an option in JHipster to deploy to Deis Platform, similar to JHipster options for Heroku or OpenShift. Actually JHipster does not provide support to work with Deis Workflow (https://deis.com/workflow/).
Deis is a good alternative to Heroku and OpenShift.

##### **JHipster Version(s)**

Latest.

**Comment by jdubois** [comment]
Dokku and Deis were my original goals for deploying JHipster, before we had Docker support, etc. (I'm speaking something like 4 years ago!). I find the Heroku workflow so good, this is exactly what I like.

However, things have evolved a lot since that period - it looks like Deis was bought by Microsoft? And they switched to Kubernetes?

I don't think we can support all existing clouds, in fact our Heroku support is done by Heroku, Kubernetes by Google, Openshift by Redhat.... So unless Microsoft/Deis does the Deis support for us, I don't think we can do this by ourselves. It's just too much work, and it also costs too much money (this is not like a dev tool, here you usually need money to test).

**Comment by hivp** [comment]
Yes, Deis was bought by Microsoft and Deis version 2 (Workflow) works with Kubernetes.

Our company is using JHipster in several projects using web/mobile gateways and microservices, and plan to deploy to Deis. I was trying to deploy to Deis using the JHipster docker support.

In any case, Is there any type of short guide to do something like that? (Adding JHipster support to Deis) Maybe we could code that kind of things. We have experience in Deis and know how it works.

**Comment by cbornet** [comment]
@hvip maybe you could write a [module](https://jhipster.github.io/modules/creating-a-module/) for this ?

**Comment by hivp** [comment]
Yes, we could try to do that since we are working with JHipster and Deis in our projects for several customers.
I would need some help to find the OpenShift or Heroku subgenerator source code to look how the things works in JHipster code.

**Comment by xetys** [comment]
> (this is not like a dev tool, here you usually need money to test).

@jdubois what do you mean with that? Deis is open source and can run on a minikube AFAIK as well as any kubernetes and I'm sure it should also work on OpenShift, too, as OpenShift extends kubernetes. 
In that case, one could argue that it makes sense to support Deis, as we do support rancher, OpenShift or kubernetes, as you can test it without cost.

On the other hand, we already support kubernetes and OpenShift directly. Supporting stuff like Helm or Deis would be a too small additional benefit, and is more the case for a module.

**Comment by jdubois** [comment]
@xetys  Yes but if we want to do some real tests we need a real cluster.
Openshift tests were done by Red Hat, Kubernetes by Google... Only Rancher were done at Ippon, but that's because OVH gave us a cluster, so that's basically the same.
The problem here is that this costs a lot of time and money if we want something production-ready, and basically we have little time and no money at all (not that I'm complaining, I'm very happy with the way that works today).

@hivp if you want to look at the code it's [here](https://github.com/jhipster/generator-jhipster/tree/master/generators), each technology has its own repository. The Heroku code is really good, and it's actually maintained by Heroku.

Then @xetys is right, maybe that's too many systems for the project, and this better be a [module](https://jhipster.github.io/modules/marketplace/#/list) because we won't have the time to do code reviews or help on maintenance. Anyway, I'll have a look, I loved Dokku (and Deis) a few years ago.

**Comment by deepu105** [comment]
Since most of us think that it should be a module, I'm closing the ticket. But of course, if you need help when doing a module don't hesitate to contact us.
