### ISSUE TITLE
Merging all "docker" modules

### ISSUE THREAD

**Issue by stevehouel** [jhipster/generator-jhipster#6103]
Questions for Core team

Should we merge all "docker" modules into one. Yet we already have 4 modules which are doing same kind of work (generating specific export file for orchestrator) and soon we should have more (Swarm and Mesos marathon) so maybe we should merge all into a jhipster:docker module or something like that.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
That will be breaking change and unfortunately we can do it only during a
major release. On the other hand, we can add a new sub generator which will
just ask one question and based on answer will compose the appropriate sub
generator.  I prefer that approach as it will keep code less complex and
individual sub generators easy to maintain.

On 13 Jul 2017 9:14 am, "Steve HOUEL" <notifications@github.com> wrote:

Questions for Core team

Should we merge all "docker" modules into one. Yet we already have 4
modules which are doing same kind of work (generating specific export file
for orchestrator) and soon we should have more (Swarm and Mesos marathon)
so maybe we should merge all into a jhipster:docker module or something
like that.

   - Checking this box is mandatory (this is just to show you read
   everything)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/6103>, or mute the
thread

**Comment by pascalgrimaud** [comment]
agree with the approach proposed by Deepu

**Comment by PierreBesson** [comment]
I'm OK to simplify and refactor the existing code for docker subgenus but we should keep things straightforward to change. I also want to keep having separate subgenerator for docker, k8s...

**Comment by deepu105** [comment]
@stevehouel so if you are interested you can add a wrapper sub gen that will compose others based on the question you answer so it should make everyone happy.
