### ISSUE TITLE
Please add licenses to the other repositories, too

### ISSUE THREAD

**Issue by CodingSpiderFox** [jhipster/generator-jhipster#6231]
Like for example: https://github.com/jhipster/jhipster-sample-app

I want to be allowed to fork this repo and make modifications for learning and testing purposes

**Comment by deepu105** [comment]
It is an auto generated app and hence there is no specific license for it. You can use it freely as it is generated and would be exactly the same as if you would generate the config yourself so dont worry.

**Comment by jdubois** [comment]
In fact both of you are correct :

- we generate by default a project with no license (see inside the package.json for example), as our default projects are for private use (no license means copyright). That's good for our users.
- those are out default generated projects so we can't change them

Anyway they are very easy to generate (even easier with JHipster Online, https://jhipster.julien-dubois.com/#/ ) so that shouldn't be an issue.
