### ISSUE TITLE
Scala support for jHipster

### ISSUE THREAD

**Issue by vivekkothari** [jhipster/generator-jhipster#6294]
**Overview of the issue**

Scala code generation for jHipster. It can be implemented as a cli input, probably the first input which asks for language which can default to Java.

**Motivation for or Use Case**

There are a lot of enterprise project which are using Scala for developing RESTful services. (I work for a leading Investment Bank and jHipster for Scala would be really helpful)

I am willing to contribute if merge it back to this project given enough traction on this issue. If there are any previous attempts to port it for scala please let me know.
- [* ] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
I don't think it is a good idea for following reasons:

- It's hell lot of work given the humongous amount of options we support on server side
- We can not maintain one more language on the server side (we already have tough time maintaining multiple frameworks in front end)
- It is **Java Hipster** and we don't have an intention to change that any time soon :wink: 
- IMO I don't see much value in using Scala with spring boot
- IMO JHipster is very beginner friendly due to some of the simpler base tech we use, Scala I'm afraid is not very beginner friendly (We do use scala for gatling tests but its opt in).

Having said that you could try to do it as a module so that you can use your own backend Scala generator and use the front end and other resources from the here.

I don't think we will ever support this in the core generator especially due to the huge maintenance overhead it will bring along

This is the same reason why we are not supporting Kotlin, Groovy and so on.

**Comment by jdubois** [comment]
In fact, I did have some discussion with the Lightbend people, some time ago, to have a Play Framework backend for JHipster. For me, it would be possible, in the same way we support AngularJS/Angular/React - you need to recode nearly everything, but as it's porting some existing code that's not impossible. And to start, we could only provide Play Framework for microservices, which are simpler.

Anyway: as @deepu105 said, there hasn't been much interest (never heard any news from Lightbend BTW), and nobody seems to be ready to invest that much time. On our side, there's also a maintenance overhead, and would only do this if there was a big interest from the community.

**Comment by ganeshkrishnan1** [comment]
I write and use scala packages in jhipster application. The easiest way, IMHO, is to tweak build.gradle

add scala plugin
`apply plugin: 'scala'`

Then remove java compiler and add scala compiler by:
```
sourceSets.main.scala.srcDir "src/main/java"
sourceSets.main.java.srcDirs = []
```

I have scala code in jhipster working on my product.
For example at https://www.aihello.com/p/a/B01LYQ7HHQ the "Similar Products" and "Keywords"  is apache spark scala module

**Comment by unikzforce** [comment]
Think the blueprints are now forthis purpose.. It can be done in a separate blueprint
