### ISSUE TITLE
WEB-INF content is not added to the packaged prod war file.

### ISSUE THREAD

**Issue by ludoch** [jhipster/generator-jhipster#6311]
##### **Overview of the issue**

WEB-INF content is not added to the packaged prod war file

##### **Motivation for or Use Case**
 If I create a src/main/webapp/WEB-INF/foo.xml, the prod profile does not add it in the final or war.  I think somewhere in the pom.xml logic, a plugin is filtering out it.

It seems the prod profile pulls in WEB-INF/ content from target/www, which doesn't have the src/main/webapp/WEB-INF/ content.

##### **Reproduce the error**

create a src/main/webapp/WEB-INF/foo.xml and build the prod war. Inspect the content.

##### **JHipster Version(s)**

latest

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I'm taking this one as I know what @ludoch wants to do

**Comment by jdubois** [comment]
This is "normal" as the content comes from `target/www`, and there are 2 ways to solve this:

- Copy the files from `src/main/webapp/WEB-INF` to `target/www` using Webpack: this would work for both Maven and Gradle, but it would mix front-end and back-end stuff, which I'd rather not do (as there are lots of discussion for separating them)
- Add `src/main/webapp/WEB-INF` to the WAR file using the Maven WAR plugin. This wouldn't solve the issue with Gradle, but I know that @ludoch doesn't work with Gradle, so that should be good enough for his use case.

**Comment by atomfrede** [comment]
I can do it for the gradle build.

**Comment by jdubois** [comment]
Thanks @atomfrede !

- Yes it's important so we are consistent across build tools
- Then @ludoch is using this to deploy on Google App Engine and uses a specific Maven plugin for that, so he probably won't benefit from it
