### ISSUE TITLE
Cors should not be enabled in microservices

### ISSUE THREAD

**Issue by ganeshkrishnan1** [jhipster/generator-jhipster#6352]
Cors has to be enabled in gateway and not microservices (else browsers cannot pass through gateway)
However Chrome does not allow multiple CORS headers so we have to disable it in microservices else we get the CORS multiple header errors. 

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.aihello",
      "nativeLanguage": "en",
      "microservicePath": "../AiHelloMicroService"
    },
    "jhipsterVersion": "4.8.1",
    "baseName": "AiHelloGateway",
    "packageName": "com.aihello",
    "packageFolder": "com/aihello",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "AiHelloUaa",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "gradle",
    "enableSocialSignIn": false,
    "clientFramework": "angular1",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

git version 2.14.1

node: v7.9.0

npm: 4.2.0

bower: 1.8.0

gulp:
[15:28:39] CLI version 1.3.0
[15:28:39] Local version 3.9.1

yeoman: 2.0.0

yarn: 0.22.0

Docker version 17.06.0-ce, build 02c1d87

docker-compose version 1.13.0, build 1719ceb

OS: Linux spyderXPS 4.13.0-041300rc7-generic #201708272131 SMP Mon Aug 28 01:32:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- [ *] Checking this box is mandatory (this is just to show you read everything)

**Comment by ganeshkrishnan1** [comment]
![jhipster-multiplevalues](https://user-images.githubusercontent.com/11154261/30433708-8251aff6-99a8-11e7-955a-4c5ba0da828e.png)

**Comment by jdubois** [comment]
I don't have your issue, so I'm wondering if you do something specific...
But yes totally agree - having CORS in microservice is useless anyway, as the whole point is to go through the gateway. So this is good idea to remove it, let me do the PR.

**Comment by PierreBesson** [comment]
Not sure if it's such a good idea. There are some people that might have microservice without a gateway.
As far as I know CORS is disabled by default in JHipster. What I guess you did is activate CORS in your central-config application.yml file which is propagated to all apps. You will then have the double CORS headers issue. I suggest you had it only to gateway.yml.

**Comment by jdubois** [comment]
Oh yes sorry, @PierreBesson you are right - I find it bad people don't follow our recommended pattern here, but I know there is a need for this.
Then, I guess that if you develop microservices in `dev` mode, you will have this issue - and I only test them in `prod`, this is why I didn't see it. Let me check if that's correct.

**Comment by PierreBesson** [comment]
Oh I see, I forgot CORS is enabled in dev now (for angular) so indeed we would have this issue and the config should be  changed.

**Comment by jdubois** [comment]
I did some tests but I need more time to check, in fact it looks like Spring Boot is quite clever, and only send the CORS headers if your app is on a different host/port (so basically, only when they are needed). So when I test on my machine, everything works :-)

Anyway, I think we have 2 opposite use cases for microservices:

- People using the gateway should not have CORS enabled because of this issue
- People not using the gateway should have CORS enabled, otherwise they can't work

As the first point is our default approach, I would put this configuration by default (and remove CORS for microservices). Of course, this is easy to modify for people who want CORS back.

**Comment by jdubois** [comment]
So @ganeshkrishnan1 I'm sorry but I can't reproduce your issue - I really don't understand why, because what you write seems totally logical to me!

Anyway, I'll go with my previous point, as this is the most logical approach to me:

- In `dev` mode will have CORS enabled for monoliths and gateways, but not microservices. If you do microservices, the recommended way of working is to go through the gateway, so CORS shouldn't be enabled. Of course, I understand people might not want to do this, and in that case it's a simple solution to enable CORS again.
- In `prod` mode you don't have CORS by default, for security reasons.
