### ISSUE TITLE
CVE-2017-8046: RCE in PATCH requests in Spring Data REST

### ISSUE THREAD

**Issue by anjia0532** [jhipster/generator-jhipster#6429]
ref https://pivotal.io/security/cve-2017-8046

>**Severity**
> Critical

>**Description**
Malicious PATCH requests submitted to spring-data-rest servers can use specially crafted JSON data to run arbitrary Java code.

>**Affected Pivotal Products and Versions**
>_Severity is critical unless otherwise noted._

> - Spring Data REST versions prior to 2.5.12, 2.6.7, 3.0 RC3
> - Spring Boot versions prior to 2.0.0M4
> - Spring Data release trains prior to Kay-RC3

**Comment by jdubois** [comment]
We don't use Spring Data REST, could you explain why you think we are affected?

**Comment by jdubois** [comment]
I spent 15 minutes trying to have information on whatever that bug may be, but I couldn't find anything! I'd like to know what the exact issue is, and how to reproduce it....
From my understanding:

- This only affects Spring Data REST, which we don't use -> this is why I'm closing this
- This is only for people doing PATCH requests, which we don't generate (I'm against this because there are several proxy servers that don't support this verb, including in the big bank where I'm currently working)

Now maybe some users have coded the same thing as Spring Data REST: that shouldn't be hard to do, and wouldn't surprise me. It wouldn't be a "true" JHipster bug, but we should warn them and try to prevent it.
