### ISSUE TITLE
[Feature] Create new, small sub-generators for Spring Boot

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#6440]
Our "jhipster entity" sub-generator generates a complete CRUD entity: that's good for a lot of reasons, but sometimes you just want to create a simple REST service. Not everything is a CRUD :-)

If you want smaller components:
- We already have the "jhipster service" sub-generator, which generates a Spring service bean
- On the client-side, you can use Angular CLI to generate components, routers, etc...

I would like to:
- Add a new "jhipster spring-controller" sub-generator, which generates a simple Spring MVC REST controller
- Rename the "jhipster service" to "jhipster spring-service"
- Think about other use-cases: a "jhipster jpa-repository"?

This would be an easy work, which shouldn't have much impact elsewhere, but which could help a lot of people.

**Comment by atomfrede** [comment]
Could be a good thing for hacktoberfest

**Comment by deepu105** [comment]
@jdubois how about containing everything in a parent sub gen (Of course code wise each will be separate and we will just compose it from the parent) so that users don't have to remember every sub generator and it will be easier to advertise and drive adoption. 
I propose `jhipster component` which will ask the below question
```
What would you like to do?
1. Generate an entity
2. Generate a Spring service
3. Generate a Spring controller
```
Based on the answer we will just compose the appropriate sub gen and it will take it from there asking additional questions if any and generating the stuff

**Advantages of this**

- Easier for people to remember
- Easier adoption otherwise the option goes unnoticed like our Service generator which is rarely used
- Possible to add more complex options like `Generate a Spring controller with service` for which we will just compose the controller sub gen followed by the service sub gen
-

**Comment by jdubois** [comment]
@deepu105 Yes but that's just another sub-generator which is a "wrapper" of the others - no big deal here!
For my personal use-case, I'd rather have "jhipster spring-controller", I find it easier and quicker to use (and that would still be possible, so no problem).

**Comment by ramzimaalej** [comment]
I like the idea, this is similar to what Grails has and offers a good level of granularity of what will be generated. It happened to me to delete all the UI part for a given entity because it was not needed. 
I would prefer a different command than answering questions like @jdubois mentioned.

**Comment by jdubois** [comment]
Yes: at the beginning Grails (and RoR!!) where heavy sources of inspiration, we are going back to roots :-)

**Comment by clarenced** [comment]
Hi @jdubois I am interested in this feature !!!

**Comment by clarenced** [comment]
#6502

**Comment by jdubois** [comment]
Closing as we have a "spring-controller" sub-generator that was commited in the last release.
