### ISSUE TITLE
JHipster with Axon

### ISSUE THREAD

**Issue by simisoz** [jhipster/generator-jhipster#6562]
##### **Motivation for or Use Case**

Regarding JHipster microservice approach can we consider to align JHipster with to CQRS and Event sourcing using Axon Framework as an alternative approach for microservices.

**Comment by mraible** [comment]
If you'd like to contribute the code, we'd love to see how it might look and work. 😊

**Comment by PierreBesson** [comment]
This is a huge feature request with few details on what you want to do. You are free to create a module/fork the generator to demonstrate your idea (code speaks better than words 😄). We are welcoming collaboration with companies to support their frameworks/platforms. Sadly we currently have too much on our hands to tackle yet another integration work.

**Comment by mraible** [comment]
I'd like to see how this might work, so I'm putting a bug bounty on this.

**Comment by Blackdread** [comment]
this is huge work.
I use Axon framework, even if you can generate some boilerplate start code, you will be stuck with generating a CRUD version and you would probably end up to refactor all the CRUD because it is usually not the approach for CQRS/ES, furthermore when you have a process or saga that will modify multiple aggregates, crud cmd/event might not fit and often you want to be explicit about the cmd/evt which CRUD is not.

**Comment by mraible** [comment]
> this is huge work.

Closing. Please reopen if you're interested in working on this feature. It might need to be an alternative to the current CRUD feature.
