### ISSUE TITLE
Rename the Angular "modal" components to "popup"

### ISSUE THREAD

**Issue by agoncal** [jhipster/generator-jhipster#6611]
##### **Overview of the issue**

Most of the Angular components use the term "_popup_" but a few use "_modal_". It would be good to homogeinize the terms to the most commonly use: "popup"

##### **Motivation for or Use Case**

The modal approach in the Angular application is a bit intricate and not always easy to understand. When you are lost, you tend to see how the other components are coded so you can replicate the same behavior. Most of the modal components use the term "_popup_", but a few use "_modal_". So you get confused, thinking this is not the same. It would be good to use the term "_popup_" all over:

* `user-modal.service.ts` : could be renamed to `user-popup.service.ts` like all the generated entity popup services
* `login-modal.service.ts` : could be renamed to `login-popup.service.ts`
* `health-modal.component.html` and `health-modal.component.ts` : could be renamed `health-detail.component.html` and `health-detail.component.ts` because these components are giving the detail of the health, just like other detail components
* `metrics-modal.component` and `metrics-modal.component.ts` : could maybe be renamed `metrics-thread-dump.component.html` and `metrics-thread-dump.component.ts` as they deal with thread dumps.

##### **JHipster Version(s)**

4.10

**Comment by jdubois** [comment]
They are called "modal" because they are using [NgbModal](https://ng-bootstrap.github.io/#/components/modal/examples).
I haven't looked at the code, but for me they use [Bootstrap modals](https://v4-alpha.getbootstrap.com/components/modal/).

So calling them "modal" is quite logical - I guess "popup" comes from the Angular Router, right? For me it's more important to use the Bootstrap names, as this is what use for real, and as I hope we will also use the same stuff for React and VueJS, so it would be consistent.
