### ISSUE TITLE
[Proposal] Use standard structure for ejs

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#6683]
##### **Overview of the issue**

Today, it's kind of complicated to contribute to gen-jhipster, every pattern uses its own way for putting conditionals and loop so that patterns are hardly readable. I suggest to make a pass on every of them applying the same formatting standards

##### **Motivation for or Use Case**

This would ease pattern detection (to extract and reuse some code parts) as well as ease contribution. Also I think that this will ease modularization work.
Using a no-brainer approach to manipulate ejs will help to concentrate only on the added value of jhipster: the generated code (as opposed to code format, which I find difficult to deal with in some patterns.

##### **Reproduce the error**

Take a look at one pattern: some conditional are inlined (using `<% %>` and some other aren't, using `<%_ _%>`). There are some mental exercises to make in order to understand.
I propose to systematically put conditional and loops alone on a line (using the right indentation), and using a line slurp when code need to to be inlined (empty `<% -%>`)

##### **Related issues**

No

##### **Suggest a Fix**

I can take some time to (incrementally) format all the generator-jhipster code base in order to use the same pattern everywhere (see below)

##### **JHipster Version(s)**

4.10.2

##### **JHipster configuration**

Not concerned.

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

not concerned

##### **Browsers and Operating System**

Intellij on MacOs, but does it matter ;-)

- [X ] Checking this box is mandatory (this is just to show you read everything)

Let's take the entity/templates/server/src/main/java/package/common/delete_template.ejs as example
```
<% if (!viaService) {
    if (databaseType === 'sql' || databaseType === 'mongodb' || databaseType === 'couchbase') { %>
        <%= entityInstance %>Repository.delete(id);<% } %><% if (databaseType === 'cassandra') { %>
        <%= entityInstance %>Repository.delete(UUID.fromString(id));<% } %><% if (searchEngine === 'elasticsearch') { %><% if (databaseType === 'sql' || databaseType === 'mongodb' || databaseType === 'couchbase') { %>
        <%= entityInstance %>SearchRepository.delete(id);<% } %><% if (databaseType === 'cassandra') { %>
        <%= entityInstance %>SearchRepository.delete(UUID.fromString(id));<% } %><% }
} else { %>
        <%= entityInstance %>Service.delete(id);<% } %>
```
it will become:
```
<%_ if (!viaService) { _%>
    <%_  if (databaseType === 'sql' || databaseType === 'mongodb' || databaseType === 'couchbase') { _%>
        <%= entityInstance %>Repository.delete(id<% -%>// I volontary put the parenthesis and caret after the conditional to illustrate the case, but shouldn't be done like this
    <%_ } else if (databaseType === 'cassandra') { _%>
        <%= entityInstance %>Repository.delete(UUID.fromString(id)<% -%>
    <%_ } _%>);
    <%_ if (searchEngine === 'elasticsearch') { _%>
        <%_ if (databaseType === 'sql' || databaseType === 'mongodb' || databaseType === 'couchbase') { _%>
        <%= entityInstance %>SearchRepository.delete(id);
        <%_ } _%>
        <%_ if (databaseType === 'cassandra') { _%>
        <%= entityInstance %>SearchRepository.delete(UUID.fromString(id));
        <%_ } _%>
    <%_ } _%>
<%_} else { _%>
        <%= entityInstance %>Service.delete(id);
<%_ } _%>
```

Which is a little more verbsose, but IMHO easier to read.

Are you interested by this contrib?

**Comment by jdubois** [comment]
Indeed this is a pain, and it's mostly because of the project history: EJS only had `<% %>` at the beginning, the new  `<%_  _%>` stuff was in fact added by someone from the JHipster project (I don't remember who, please comment if you know who he is, he deserves a lot of respect!!).

So typically the `<% %>` is in all our old code.

On the personal side, I like `<%_  _%>` a lot, unless `<% %>` is needed (for method arguments, for example).

Now this is all complex to refactor, as we need to have a "perfect" output. This is why I wouldn't do this, until #6379 is done. This is going to simplify a lot our code, and also improve our output (Java imports for example).

-> so for me our top priority for generated code is #6379 - I would love to have someone do this

**Comment by Tcharl** [comment]
Prettier looks good, but, for example, it does not handle Java, Xml, Gradle scripts... So it will handle some pain but not all. Also, It could become confusing, even if it will speed up the development (Given a contributor, I can code an ugly thing while contributing to typescript, but not while contributing to the pom...)

Also, I don't think that this is a so complex refactor: using a systematic approach really lever the difficulty (for example `<% -%>`).

I also thought about kind of 'generation unit tests', where we would save a file containing a target generation of the code.
Then we'll be able to compare template evolution with expected result.

**Comment by jdubois** [comment]
XML and Gradle are not big issues: we don't have a lot of them, and using `<%_ _%>` is good enough for them.
My real issue with Prettier is that we need Java support, indeed. That's probably a lot of work, but that would be so useful for us.

**Comment by deepu105** [comment]
I thought of doing this multiple times and even refactored quite a bit of
it over the time, but to completely rewrite everything is just too much
effort as we have too many template files and the chance for a mistake is
very high.
As you said if we have a solid automated way of testing before and after of
the generated templates for various options then we could attempt this
otherwise I'll prefer to continue changing them gradually as today.


Thanks & Regards,
Deepu

**Comment by Tcharl** [comment]
So, I think we can close this issue, as it is covered by #6687 and #6379
