### ISSUE TITLE
invalid redirect url for gateway

### ISSUE THREAD

**Issue by magaton** [jhipster/generator-jhipster#6724]
##### **Overview of the issue**

I cannot login in the vanilla gateway with user/user or admin/admin using default jhipster realm in the OIDC (keycloak)

##### **Motivation for or Use Case**

Testing OIDC

##### **Reproduce the error**

Generate gateway from jhipster generator, run it in either dev or prod profile, doesn't matter.
Start keycloak with
docker-compose -f src/main/docker/keycloak.yml up
from the gateway root dir.
and you should get back.
WARN  [org.keycloak.events] (default task-6) type=LOGIN_ERROR, realmId=jhipster, clientId=web_app, userId=null, ipAddress=172.18.0.1, error=invalid_redirect_uri, redirect_uri=http://localhost:8200/login

##### **Related issues**

Couldn't find any.

##### **Suggest a Fix**

I don't really know. Tried with monolith and it works.

##### **JHipster Version(s)**
0.10.2

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.acme.gateway"
    },
    "jhipsterVersion": "4.10.2",
    "baseName": "gateway",
    "packageName": "com.acme.gateway",
    "packageFolder": "com/acme/gateway",
    "serverPort": "8200",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None.

##### **Browsers and Operating System**

Mac Osx Yosemite, JDK 1.8, Chrome

**Comment by jdubois** [comment]
You have an `invalid_redirect_uri`, have a look at the documentation, you need to do an alias on the keycloak host.
I know this is annoying, but with a local deployment and Docker we haven't found a better solution.

**Comment by magaton** [comment]
Sorry, could you be more specific? Which documentation & which alias?
I've tried before mraible's https://github.com/mraible/jhipster-oidc-example and that works.
Compared keycloak.ymls and realm jsons in both projects, they are very similar if not the same.

**Comment by jdubois** [comment]
You need to have an alias in your `/etc/hosts`:

    127.0.0.1	keycloak

This should be in the documentation (which I know is not good at the moment, we just don't have the time)

**Comment by magaton** [comment]
Sorry, I still don't get it because:
- It works with monolith (the same jhipster generator) without any /etc/hosts.
- It works in jhipster-registry with enabled oauth2 profile and prod (dev profile has a problem as explained in https://github.com/jhipster/jhipster-registry/issues/209
And I cannot find /etc/hosts mentioned anywhere in docs

**Comment by jdubois** [comment]
Yes the documentation will be updated when we have the time. We all do this on our free time, so it's when we have free time.

**Comment by magaton** [comment]
Sorry, I really don't want to annoy you. Actually this would be the last thing i'd want to do, since I have a huge respect for everything you've done so far. 
I am just reporting what I have found and try to do what you suggest.

**Comment by jdubois** [comment]
Oh yes, no worries.

In fact my real worry is that our documentation is not good, not that you ask about it (that's normal!).

**Comment by jdubois** [comment]
For example I'm pretty sure the `/etc/hosts` is documented, and it really should, but I can't find where :-((((
So that means everybody will fail at having this working at the beginning

**Comment by magaton** [comment]
ok, that's fine but how / why does it work with registry and monolith but not with gateway?

**Comment by MathieuAA** [comment]
@jdubois [here](http://www.jhipster.tech/docker-compose/), search for "Building and running a Docker image of your application"

**Comment by magaton** [comment]
I am running gateway through ./mvnw -Pprod, not in Docker Container
The same way I run monolith and registry which work with Keycloak without tweaking /etc/hosts.

I've added: 
127.0.0.1       localhost keycloak
in my /etc/hosts file
no help, the same exception after I try to sign in:
keycloak_1  | 15:43:59,989 WARN  [org.keycloak.events] (default task-4) type=LOGIN_ERROR, realmId=jhipster, clientId=web_app, userId=null, ipAddress=172.18.0.1, error=invalid_redirect_uri, redirect_uri=http://localhost:8200/login

**Comment by mraible** [comment]
@magaton Keycloak is configured to accept a redirect_uri of `http://localhost:8080/login` by default. If you want to change this, you'll need to login to Keycloak (http://localhost:8090) and add or change the redirect_uri.

**Comment by magaton** [comment]
@mraible thank you. That was it! Maybe jhipster-realm.json should be parameterised to handle the specified server.port during jhipster app gen? 
I put 8200 for gateway and default ports for monolith and registry, so that explains why gateway didn't work and latter two did.

**Comment by pascalgrimaud** [comment]
Maybe some work to do one these lines ?
https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/docker/config/realm-config/_jhipster-realm.json#L1079-L1085

**Comment by pascalgrimaud** [comment]
Reopening this, as there is something to do

**Comment by maznag** [comment]
I have the same issue when generating gateway with JHipster 4.11.0 and I cannot login:

- I tried with or without docker/docker-compose.
- I also tried with keycloak docker image and OKTA. 
- I added 127.0.0.1 keycloak in my /etc/hosts

In my case, I use Consul instead of JHipster Registry

it seems like it's a cross origin issue. With keycloak I have this error

Failed to load http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth?client_id=web_app&redirect_uri=http://localhost:8080/login&response_type=code&scope=openid%20profile%20email&state=dSg8Z6: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

I tried to add "*" to 'Web Origins' in Clients/web_app using keycloak UI without success.

Same error  with Okta:

Failed to load https://dev-XXXXXX.oktapreview.com/oauth2/default/v1/authorize?client_id=XXXXXXXXXXXXXXX&redirect_uri=http://localhost:8080/login&response_type=code&scope=openid%20profile%20email&state=5uBGXn: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

**Comment by mraible** [comment]
JHipster should be redirecting to this URL rather than trying to make an XHR request that requires CORS.

**Comment by maznag** [comment]
I think that it's a regression in JHipster 4.11.0 because it works well with JHipster 4.10.2 for me.

**Comment by maznag** [comment]
I upgraded JHipster to latest version 4.11.1 but I still can not login to gateway with keycloak or OKTA. I have the same problem that I described above regarding CORS.

Failed to load http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth?client_id=web_app&redirect_uri=http://localhost:8080/login&response_type=code&scope=openid%20profile%20email&state=dSg8Z6: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

Any help please !

**Comment by mraible** [comment]
I tried generating a gateway, using the JHipster 4.10.2 and the `.yo-rc.json` in the description of this issue. It worked fine with Keycloak once I changed the port to 8080 instead of 8200. 

I then upgraded to the latest release (`v4.11.1`) and re-generated the gateway app. I do see a CORS error in the logs, but I'm able to click on the "sign in" link and login just fine.

**Comment by mraible** [comment]
I downgraded back to `v4.10.2` and confirmed the CORS error happens there as well. I'm not sure where it's coming from, but it doesn't seem to affect the authentication behavior of the gateway.

**Comment by mraible** [comment]
This seems to be happening because a request is made to `/api/account` and a 302 is returned with a Location of `http://localhost:8080/login`. I'm not sure if we can (or need to) change this behavior.

![screen shot 2017-11-27 at 6 55 10 am](https://user-images.githubusercontent.com/17892/33270138-3e15d066-d340-11e7-8005-9cf0362f7e43.png)

**Comment by maznag** [comment]
thanks @mraible for your feedback.

I can finally connect to the gateway when I click "login" but only when I generate the gateway without the option "Clustered HTTP sessions using Hazelcast". When I generate the gateway with this option it doesn't work. So the issue happens when this option is chosen. Note that the error regarding CORS also appears when I directly access http://localhost:8080 on both cases.

Can you please confirm this issue by generating a gateway with and whithout option "Clustered HTTP sessions using Hazelcast". If the error is related to this option then I can declare this bug.

**Comment by mraible** [comment]
@maznag Please post your `.yo-rc.json` and I'll try to reproduce the problem.

**Comment by maznag** [comment]
- With the option "Clustered HTTP sessions using Hazelcast", I can't connect to gateway:
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "mycompany",
    "packageName": "com.mycompany",
    "packageFolder": "com/mycompany",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": "hazelcast",
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}

- Without the option "Clustered HTTP sessions using Hazelcast", I can connect to gateway:
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "4.11.1",
    "baseName": "gateway",
    "packageName": "com.mycompany",
    "packageFolder": "com/mycompany",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "hibernateCache": "hazelcast",
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "consul",
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "yarn",
    "applicationType": "gateway",
    "testFrameworks": [
      "gatling",
      "protractor"
    ],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ]
  }
}

**Comment by mraible** [comment]
@maznag I can confirm that when you choose clustered HTTP session with a gateway, login with Keycloak does not work. I tried both Eureka and Consul. Please open a new issue for this since this one is closed.
