### ISSUE TITLE
Sample apps not updated

### ISSUE THREAD

**Issue by DanielFran** [jhipster/generator-jhipster#6837]
By request of @jdubois , I open this ticket because some sample applications like jhipsterSampleMicroservice are not updated since Jul-19…!

**Comment by jdubois** [comment]
I will do this

**Comment by jdubois** [comment]
Thanks @DanielFran

**Comment by jdubois** [comment]
Consider it done. I'll also update all our samples, and add a React sample.

**Comment by pascalgrimaud** [comment]
@dubois : I wonder if all samples should migrate :
- from Angular1 to AngularX
- from session to JWT

You already did it for https://github.com/jhipster/jhipster-sample-app/

**Comment by pascalgrimaud** [comment]
I can PR if you're OK

**Comment by jdubois** [comment]
Yes @pascalgrimaud we should have AngularX everywhere (well, not for ng1 and react samples, of course), but I guess it's already mostly the case.
For security, JWT makes indeed much more sense, as this is what most people use.

**Comment by pascalgrimaud** [comment]
Ok, so I will do PR
Don't forget to `git pull` once all PR are merged, otherwise, you will have conflicts when you want to update all samples

**Comment by dubois** [comment]
Wrong @ mention

p📱

On Dec 11, 2017 11:16 PM, "Pascal Grimaud" <notifications@github.com> wrote:

@dubois <https://github.com/dubois> : I wonder if all samples should
migrate :

   - from Angular1 to AngularX
   - from session to JWT

You already did it for https://github.com/jhipster/jhipster-sample-app/

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jhipster/generator-jhipster/issues/6837#issuecomment-350965352>,
or mute the thread

**Comment by pascalgrimaud** [comment]
yes, sorry, I was on my phone :-p

**Comment by jdubois** [comment]
Sorry @Dubois !! I didn't know about Tilt Brush that looks awesome!
