### ISSUE TITLE
Routing admin app in /admin and frontend app in /app

### ISSUE THREAD

**Issue by superandrew** [jhipster/generator-jhipster#6839]
##### **Overview of the issue**
This is a feature request, I will try to explain my idea after spending many days trying to accomplish, and opening 2 [EDIT: 3] Stack Overflow questions on the subject. I hope that I'm not missing something really obvious.

In many cases jHipster comes handy when creating a mobile API backend. I'm not saying this is the only case, but of course it is one of the most preminent. In any case I suppose that for any of you that creates an application that can manage entities, there is the need to give a customer a frontend which is not the default bootstrap/angular frontend. 

For instance, you could give to a customer's admin the default jhipster frontend, while having a full fledged application with more rich layouts, while preserving the possibility to work with angular entities that have been created for the frontend, and avoiding to duplicate code in another application.

To reach that objective, I would like the generator to be able to update my admin frontend, while minimising the maintenance effort for the code updates to be used on the "rich" frontend.

I've tried two main approaches, to no avail. One is to have two distinct angular applications to be served in two "server side" folders, which use two different html files that have been generated by webpack, i.e. "admin.html" and "app.html". This approach is very complicated and while trying I found it very unpractical and breaking jhipster.

The second approach would be to simply have two navigator outlets with the same name (or even different, for what is worth), like
`app.route.ts`
```
export const navbarRoute: Route = {
    path: '',
    component: NavbarComponent,
    outlet: 'navbar'
};
export const playRoute: Route = {
    path: '',
    component: AppbarComponent,
    outlet: 'navbar'
};
```
then in `layout-routing.module.ts`
```
const LAYOUT_ROUTES = [
    { path: '', redirectTo: 'app', pathMatch: 'full' },
    {
        path: 'admin', children: [
        navbarRoute,
        ...errorRoute]
    },
    {
        path: 'app', children: [
        playRoute,
        ...errorRoute]
    }
];
```
With this approach I am able to have two different navbars, and while it seems to be fine, I have to change every url for every other router link, for example if I have an entity book, I will have to go to change in `book.route.ts` path to `admin/book`, and so on. Despite that, which I consider not good but still a minor problem, I can see the book entities, the navbar router outlet is there, but I can't see the bar. I must say I am learning Angular (2+) so I'm no expert, but despite reading the book, angular guide, stack overflow for days if not *weeks* I am still not able to reach a solution, which is frustrating, to say the least.

So I'm here trying to open a discussion on how it will be useful to add this functionality to the generator, and I'd love to help building it since my company believes in and it is actively using jhipster in its projects. But I need to understand *how* before :)

##### **Motivation for or Use Case**

I believe jhipster is missing this functionality which would be very common and useful. 

##### **Reproduce the error**

This is a feature request

##### **Related issues**

I've searched both here and stack overflow for a solution, to no avail.

##### **Suggest a Fix**

I would ask if a user wants to have more than the admin layout, and implement a stub.

##### **JHipster Version(s)**

v4.10.2

##### **JHipster configuration**

Using JHipster version installed globally
Executing jhipster:info
Options:
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
/Users/<user>
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

git version 2.13.2

node: v8.0.0

npm: 5.4.2

bower: 1.7.9

gulp:
[23:55:02] CLI version 3.9.0

yeoman: 2.0.0

yarn: 1.3.2

Docker version 17.06.2-ce, build cec0b72

docker-compose version 1.14.0, build c7bdf9e

Congratulations, JHipster execution is complete!
##### **Browsers and Operating System**

Mac OS 10.13, not relevant

- [x] Checking this box is mandatory (this is just to show you read everything)

I've also opened a stack overflow question, but I still consider this as an important feature.
https://stackoverflow.com/questions/47734215/another-app-layout-in-jhipster-generated-angular-application

**Comment by gmarziou** [comment]
Having 2 angular applications seems the way to go for me as you may not want having same CSS nor same HTML structure between the admin app and the customer app . Could you elaborate a little why you abandoned this way? What did you try and which problems you faced?

**Comment by thomastardy** [comment]
I recently had to bootstrap an application with similar requirements. We have a customer and and admin UI. We analyzed three approaches:
1. One Angular app using different routes for the admin pages like admin/xyz
2. Two Angular apps being built using one Webpack build using webpack's multiple entry points feature 
3. Two Angular apps being built with separate client side builds
    3.a Customer UI with Angular CLI (mentioned by @gmarziou in on Gitter)
    3.b Customer UI with jhipster generating only client side code and no entities

Important to notice, we don't have a lot of expertise when it comes to client side builds with webpack.
We ended up doing 3.b, because of
- having only one Angular app without extending the webpack build means, that customers will load the HTML, CSS, JS for the admin functionality as well. Especially on mobile networks, this could be a problem.
- building two entry points with webpack can be done, but the webpack build generated by jhipster must be changed drastically. E.g. you have to switch from webpack-dev-server to webpack-dev-middleware. In the end, the webpack build would be very different from what jhipster is generating and integrating future jhipster updates would not be easy.
- using a different webpack build for the two Angular apps, which would be the case if you use Angular CLI comes with some complexity as well. And I've seen a statement from @jdubois that the jhipster webpack build does more than the Angular CLI build.
- starting with jhipster client side code only gives us the benefit from having lots of base functionality like JWT authentication available. Furthermore, the webpack builds are the same and it should be possible to maintain them easily when it comes to jhipster updates.

We currently have a standard jhipster app used for the server and the client code of the Admin UI.  The only things changed are, that the output is stored in `www/admin` and not `www`. Then I have a sub-folder for the customer-ui, where we have another jhipster app,  but only the client code. This means to develop, you start `./mvnw` and `yarn start` in the project's root and `yarn start` in the customer-ui subfolder. We have to change some ports for that.
When it comes to the maven build, I just do the client stuff twice and copy both build web applications which will result in `/` being the customer UI and `/admin/` being the admin UI.

That's what I have recently setup. What do you think of that?

**Comment by superandrew** [comment]
@gmarziou the problems I found using the two applications were essentially related on conflicts between angular router and spring filters. To be completely honest, I'm not sure exactly what was wrong with that setup, however I can share one of the numerous branches I tried for this setup. Basically while I was able to generate two different html pages `administration/index.html` and `lab/index.html` based on two different html templates in webpack. It seems to be ok because all the two index.html were using  I was almost able to run the 'lab' application "which was based on ng-book's first chapter example, but the jhipster admin app was broken, no translation, no navbar and this error:
```
ERROR Error: Uncaught (in promise): Error: The specified modal container "nav" was not found in the DOM.
Error: The specified modal container "nav" was not found in the DOM.
```
 This was the point I've got to after that I surrendered. 

`webpack.common.js`

    new HtmlWebpackPlugin({
        filename: 'lab/index.html',
        template: './src/main/webapp/lab.html',
        chunksSortMode: 'dependency',
        inject: 'body'
        }),
      new HtmlWebpackPlugin({
          filename: 'administration/index.html',
          template: './src/main/webapp/index.html',
          chunksSortMode: 'dependency',
          inject: 'body'
       }),

result:

![screen shot 2017-12-10 at 08 44 27](https://user-images.githubusercontent.com/71364/33803028-83b76990-dd86-11e7-9c05-9d352336c38d.jpg)

`SecurityConfiguration.java`


    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
            .antMatchers(HttpMethod.OPTIONS, "/**")
            .antMatchers("/app/**/*.{js,html}")
            .antMatchers("/lab/**/*.{js,html}")
            .antMatchers("/administration/**/*.{js,html}")
            .antMatchers("/i18n/**")
            .antMatchers("/content/**")
            .antMatchers("/swagger-ui/index.html")
            .antMatchers("/test/**")
            .antMatchers("/h2-console/**");
    }

![screen shot 2017-12-10 at 08 51 34](https://user-images.githubusercontent.com/71364/33803070-5ae8cc74-dd87-11e7-8575-9b5c08ae82ba.jpg)

I was kind of lost at this point and began the "single angular application" way. I know java but I'm not a spring expert, so I haven't got enough knowledge to understand what might be missing.

I think that a "standard" way of doing this in jhipster would be a huge help building projects with it.

**Comment by superandrew** [comment]
@thomastardy I tried the two angular apps way based on the fact that angular-cli allows an array of apps inside the configuration, but I failed this way because I was able to run the application using ng serve but not with yarn. Besides I've had other configuration issues over there which honestly I don't remember as I dedicated less time to this approach than to others. Was this the way you created the setup? Or you generated another jhipster app in a subfolder generating only client code?

**Comment by thomastardy** [comment]
@superandrew I generated another jhipster app in a subfolder only with the client code and without entities. I used that only as a base and then customized it heavily. But doing so, the setup in the two applications is very similar. Later on, I want to remove duplicate client code and share them between the two apps, but that is not a priority at the beginning.
We went with this approach mainly because we want to not change the standard jhipster app much to make updates in the future easier and the two apps should be very similar, otherwise you have to deal with unnecessary complexity.

**Comment by superandrew** [comment]
@thomastardy it makes completely sense, but don't you think that the possibility to include a frontend app would be a useful inclusion in jhipster?

If you don't mind sharing, you created the app in `/webapp/app2` (for example) and did you need to do other changes to the spring configuration? or to webpack / configuration files?

**Comment by thomastardy** [comment]
@superandrew i didn't do `/webapp/app2`, I have a sub-folder in the project's root like `customer-ui`, where I executed `jhipster client --skip-entities` (or something like that). I decided to have that in the same project root to have the whole application in one git repository. But you could have two separate repos as well.

Regarding incl. this feature in jhipster. I agree, it is a common requirement. But depending on the suggested solution, I could imagine that this is not a feature of jhipster, but the scenario is documented on www.jhipster.tech.

**Comment by deepu105** [comment]
What you want to achieve is very specific for your usecase, generally it
shouldn't be difficult to have 2 client application talking to the same
REST server, you cannot have reusable code between the 2 apps easily but I
guess that shouldn't be the goal.

I don't think we can take up a feature like the one you request. I suggest
you explore possibility of building a module for that.

**Comment by superandrew** [comment]
@deepu105 I respectfully disagree with you about the specificity of the use case which in my experience has been practically omnipresent where I used or I observed using jHipster (which I personally reccomend to people), however I respect your decision to close the issue.

**Comment by superandrew** [comment]
@thomastardy to which documentation are you referring exactly? http://www.jhipster.tech/separating-front-end-and-api/ ? I'm not sure to understan where this scenario is documented.

**Comment by gmarziou** [comment]
Thanks @thomastardy for having shared some of your experience. 

@superandrew from your additional details I suspect you wanted to share too much between the 2 apps. My experience with this use case is that you have very little to share in frontend code: entities would likely be different between customer and admin apps, customer part is likely to have aggregates of entities so requiring different REST endpoints with adequate security rules. 

There is probably enough meat for an article, tutorial or book chapter rather than a tip.

**Comment by superandrew** [comment]
@gmarziou actually the main thing I want to share between two apps are two or three:
1. git repository
2. being included in the same war, so I don't need to follow two separate versions but everything is always aligned to its backend/testable
3. of course, entities, but it's not the real deal to me.

**Comment by gmarziou** [comment]
Then what @thomastardy presented covers all your needs.

**Comment by thomastardy** [comment]
@superandrew there is no documentation at the moment. But I could imagine something similar to http://www.jhipster.tech/separating-front-end-and-api/.

I totally agree with @gmarziou. The two apps share very few things. Even the entities don't need to be shared as the customer UI will use aggregates. And yes, having an article, tutorial or even a chapter in the book would be amazing and would help @superandrew a lot.

**Comment by superandrew** [comment]
@thomastardy I will try this approach. 

Starting from a fresh jhipster installation in which I have a few entities, I will move to another folder in my computer, generate a jhipster app
`jhipster --skip-server` withouth entities and responding with the same questions, more or less (I guess I could probably reuse the .yo-rc.json configuration)

Then I will copy the generated application into webapp/admin/*. Is that correct? 

Would you mind sharing how you configured spring/tomcat to serve both folders when you deploy the application in production? It might be interesting to build this as a module, if it makes sense. I will investigate this.

**Comment by thomastardy** [comment]
@superandrew I used `jhipster client --skip-user-management` in the folder `platform-ui`. I didn't move the app to webapp/admin, because if you do that, I expect quite some issues when you try to update jhipster in the future. In the webpack build, I changed `target/www` to `target/www/admin`.

Please find attached the patch file of the change i did. Not saying this is perfect and the way to go for everybody. It's what we did and it is working so far. One of the goals was to keep the admin app as standard as possible to keep the jhipster update process as simple as possible. Your feedback is appreciated.

[JHipster-6839.patch.zip](https://github.com/jhipster/generator-jhipster/files/1545686/JHipster-6839.patch.zip)

**Comment by deepu105** [comment]
Agree that this might be required usecase for some people, I personally
have never needed it or seen it so cant comment much, hence I suggest to
start as a module and if it gets traction we can put it on the main
generator. If its not something that can be a module then it could be a tip
on the docs website

**Comment by gmarziou** [comment]
> I didn't move the app to webapp/admin, because if you do that, I expect quite some issues when you try to update jhipster in the future. 

I have proposed to the team a [change  for JHipster 5](https://groups.google.com/d/msg/jhipster-dev/OMSXl8JIsBA/Jago1vvaBgAJ) that could help.

**Comment by thomastardy** [comment]
👍
