### ISSUE TITLE
[JWT] Remember me login option doesn't work with Social Login

### ISSUE THREAD

**Issue by rakeshkalra1983** [jhipster/generator-jhipster#6908]
##### **Overview of the issue**

If you login to your website (with social login enabled) using any of social login provider (google or facebook), then close the window and open website again, you have to Sign-In again. There is no Remember Me option for sign-in with social providers.

##### **Motivation for or Use Case**

User shouldn't have to login to website again if they close the website and visit the website back, if they have logged in once using any of social login provider.

##### **Suggest a Fix**

Remember Me should be default enabled if user are using Social login.

##### **JHipster Version(s)**

4.11.1

##### **JHipster configuration**
```json
{
"generator-jhipster": {
"jhipsterVersion": "4.11.1",
"baseName": "eachfit",
"packageName": "com.eachfit",
"packageFolder": "com/eachfit",
"serverPort": "8080",
"authenticationType": "jwt",
"hibernateCache": "ehcache",
"clusteredHttpSession": false,
"websocket": false,
"databaseType": "sql",
"devDatabaseType": "h2Disk",
"prodDatabaseType": "mysql",
"searchEngine": false,
"messageBroker": false,
"serviceDiscoveryType": false,
"buildTool": "maven",
"enableSocialSignIn": true,
"jwtSecretKey": "xxxxxxxxx",
"clientFramework": "angularX",
"useSass": false,
"clientPackageManager": "yarn",
"applicationType": "monolith",
"testFrameworks": [],
"jhiPrefix": "jhi",
"enableTranslation": false
}
}
```

##### **Browsers and Operating System**

Chrome OS, Windows

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
You are correct.

Please note that:

- There is code for a `social-authentication` cookie in the `CustomSignInAdapter` class
- And also the access token is saved in the table `JHI_SOCIAL_USER_CONNECTION`

-> so basically we have everything to have "remember me" authentication working

I guess it is because that was coded for session-based authentication, and here you are using JWT authentication: that would explain why we have nearly everything ready. It's just not finished yet.

As very few people are using this, this wouldn't be a very high priority issue - @rakeshkalra1983 would you have time to work on a PR for this?

**Comment by caffeinecoders** [comment]
I am still trying to understand sign-in related code which you suggested above.
Also, just regarding social-authentication cookie, are cookies supported by PWA also? 
I meant is if I enable PWA and use social login, everything related to social login will continue to work, right?

Thanks.
