### ISSUE TITLE
Cannot install modules from jhipster Marketplaces

### ISSUE THREAD

**Issue by calemdef** [jhipster/generator-jhipster#6935]
i can't install module's from jHipster Marketplace.
For example, i will install Bootswatch from marketplace. But i get allways following massage. 

>npm install -g generator-jhipster-bootswatch

>yo jhipster-bootswatch
(!) require('yeoman-generator').generators.Base is deprecated. Use require('yeoman-generator').Base directly
Composing JHipster configuration with module bootswatch
WARNING! DEPRECATED! The JHipster module sub-generator is deprecated.
WARNING! Please import the generator-base.js using commonJS require or ES2015 import.
WARNING! See http://www.jhipster.tech/modules/creating-a-module for more details.
Welcome to the JHipster Bootswatch Module! v1.0.2
Reading the JHipster project configuration for your module
? Would you like to enable Bootswatch themes? Yes

**There is nothing to install or update. Why?**

**Comment by jdubois** [comment]
I guess that module is using an older version of Yeoman: I just had a quick look and I see this was done by @deepu105 more than 1 year ago, so that looks that indeed this hasn't been updated. Anyway AngularJS 1 is dead, so that looks reasonable to assume this is not being maintained anymore.

-> this is specific to this module, so you should use the module's bug tracker at https://github.com/hipster-labs/generator-jhipster-bootswatch/issues and this is why I'm closing this (this bug tracker is only for main generator, not for the modules)

**Comment by CHRISTMardochee** [comment]
how can i do?

**Comment by gmarziou** [comment]
How can you do what ? Please give details

**Comment by CHRISTMardochee** [comment]
How i do to use -bootstrap-material-design for jhipster4

**Comment by gmarziou** [comment]
@CHRISTMardochee I replied to you on gitter, let's not pollute this issue here.
