### ISSUE TITLE
Keycloak service needs https for admin access on cloud

### ISSUE THREAD

**Issue by adnansenyurt** [jhipster/generator-jhipster#6936]
##### **Overview of the issue**

Jhipster deploys default jboss/keycloak docker image as part of its deployment. admin realm on this image has the settings that require ssl access for administration UI by default. 

Local deployment is not affected, but cloud deployment prevents admin panel access without ssl setup, and hence service configuration is not possible.

##### **Motivation for or Use Case**

Managing Keycloak server on cloud should be possible

##### **Reproduce the error**
Deploy:
cf push keycloak --docker-image keycloak

Admin access:
http://<keycloak-server-on-web>/auth/
choose 'Admin Console'
A message is displayed stating 'SSL Required'

##### **Suggest a Fix**

- Workaround is to connect to H2 database of Keycloak and edit the admin realm configuration and set 'require ssl' to 'none', but this is a manual task that needs to be done on every deployment instance.

- A custom Keycloak image for jhipster can be used which has this default config parameter set to 'none' for admin and jhipster realms.

##### **JHipster Version(s)**
4.13.1
##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@mraible does any of your recent PRs address this?

**Comment by mraible** [comment]
I'd recommend using HTTPS for everything in production, but we don't force that. I think it's expected that you might have to tweak some things for production. At the very least, we should document those things you need to change for a production deployment.

**Comment by jdubois** [comment]
Indeed, I wouldn't recommend to modify the config to suppress SSL, you should have SSL enabled in production, and for Keycloak this is even more important.

So you need to have an HTTPS front end, and for this you have 2 solutions:

- If you have the JHipster gateway, we have full documentation on setuping SSL with JHipster on https://www.jhipster.tech/production/#security (so for me this is already documented)
- Otherwise, a excellent solution is to have a front-end router that does SSL for you. As you seem to be using CloudFoundry, you should have SSL by default on your domain.

For me this is just a small documentation tip to add on https://www.jhipster.tech/security/#oauth2
