### ISSUE TITLE
Sign-In after Sign-out doesn't ask for username after password with Keycloak

### ISSUE THREAD

**Issue by rakeshkalra1983** [jhipster/generator-jhipster#6941]
##### **Overview of the issue**

I created Jhipster app with OIDC (Keycloak) integration, I signed in to application with admin account, then I clicked signed-out. Now when I click sign-in again, application doesn't ask me for username password, but directly sign me in as admin.

##### **Motivation for or Use Case**

If I want to sign-out and want to sign-in as different user, I am failing to do so.

##### **Reproduce the error**

Steps mentioned in overview of issue.

##### **JHipster Version(s)**

4.13.1

##### **JHipster configuration**

{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.fya"
    },
    "jhipsterVersion": "4.13.1",
    "baseName": "fya",
    "packageName": "com.fya",
    "packageFolder": "com/fya",
    "serverPort": "8080",
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "enableHibernateCache": false,
    "clusteredHttpSession": false,
    "websocket": false,
    "databaseType": "mongodb",
    "devDatabaseType": "mongodb",
    "prodDatabaseType": "mongodb",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSocialSignIn": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "applicationType": "monolith",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}

##### **Browsers and Operating System**

Safari, MacOS

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
Maybe the same ticket ?
https://github.com/jhipster/generator-jhipster/issues/6555

**Comment by javaScientist** [comment]
I can confirm the behavior. I'm having the same problem. I would expect that if i click on logout, i will logout from all applications and the keycloak server.
I would expect the behavior as with Google and Youtube. When i login to google, i am automaticly logged in to youtube.
And when I sign out of Google, I'm also logged out of youtube.
Further more it is complicated when we are in development mode and we use two different users for testing. It is not possible to change user.

It seams that [#6555](https://github.com/jhipster/generator-jhipster/issues/6555) is an similar ticket. But this ticket is closed and the issue is still there.
Can someone else confirm this or is it really the desired behavior?

**Comment by mraible** [comment]
Logging out of the IpP (Keycloak in this instance) is not the nature of single-sign on. When you log out of an app, changes are you don't want to logout of your IdP. If you logged into an application with Facebook, you wouldn't want logging out of that app to log you out of Facebook, would you?

Yes, it can be a pain for testing. That's why I recommend using incognito mode.

**Comment by mraible** [comment]
@javaScientist You might be able to use [this solution](https://stackoverflow.com/a/41080514/65681) to create a `LogoutHandler` that logs you out of the IdP as well.

**Comment by javaScientist** [comment]
@mraible Thank you for your feedback . I will try to implement a custom `LogoutHandler` .

**Comment by stieler-it** [comment]
Our behaviour is a little different:
1. Login as user 1
2. Logout
3. Click on Login again

Expected: The user is already signed in as the Keycloak login is still active
Actual: Keycloak shows a login form. If you try to sign in as another user, it says "You are already authenticated as different user 'ref711ma' in this session. Please logout first." There is no logout button, though.

Did we break the configuration somehow or does someone else experience the same behavior?

**Comment by stieler-it** [comment]
Ok sorry, I tried it with a vanilla keycloak - without our configuration changes the behavior is like described here before.

**Comment by Filson14** [comment]
@stieler-it have You noticed which config changes could be responsible for that behaviour? I deal with the same scenario as You described. Nethertheless, I think I should try custom logout handler to log user out from app AND keycloak.

**Comment by stieler-it** [comment]
We did not spend time investigating which (Keycloak?) configuration was responsible for our behaviour. I am pretty sure it was deterministic, though. And regarding the logout handler: We implemented ours in the frontend, so the browsers calls Keycloak's logout URL after app logout, which is probably not a very secure idea but it works for us.

**Comment by Filson14** [comment]
Thanks for your reply. I use  (mainly) logout method from keycloak js adapter (which redirect to logout URL; as recommended). But sometimes the keycloak session is still active and then I have the issue as you have described.

**Comment by deepu105** [comment]
Sorry to spam you today @mraible, just trying to clean up issues. Does any of your recent PRs address this?

**Comment by mraible** [comment]
No. [My comment](https://github.com/jhipster/generator-jhipster/issues/6941#issuecomment-360537185) is still valid. 

@jgrandja Any chance that Spring Security OAuth will provide global logout as a feature in the future?

**Comment by jgrandja** [comment]
@mraible It's a feature we can consider for the new OAuth support we're building in Spring Security 5.x.

Just to clarify, are you referring to [OpenID Connect Back-Channel Logout 1.0](http://openid.net/specs/openid-connect-backchannel-1_0.html)?

**Comment by mraible** [comment]
I'm not sure what it's called, but I'm guessing it'd be something that uses the `revocation_endpoint` or `end_session_endpoint` from `./well-known/openid-configuration`. Here's what those look like from my Okta tenant: https://dev-158606.oktapreview.com/oauth2/default/.well-known/openid-configuration

**Comment by jgrandja** [comment]
Gotchya. As mentioned, it's a feature we can consider implementing later on. There's just higher priority items going on now as we're heads down on the new Resource Server support and also adding more to Client support for 5.1

**Comment by mraible** [comment]
I recently learned that Okta doesn’t support OIDC Back-Channel Logout. I did [figure out how to do it using a redirect on the frontend](https://developer.okta.com/blog/2018/06/18/spring-boot-angular-auth-code-flow#logout-with-okta).

**Comment by jdubois** [comment]
I understand the issue (we have the same for a customer, and did a custom solution), but I'm closing this as:

- @mraible already answered why this is the case today. To me this is a limitation on OIDC, or a missing feature.
- There are some workaround like the one @mraible gives, but they are specific to a provider. At the moment, we do not do anything specific per provider, as the goal is to be neutral and work with as many providers as possible. I would love to have this working with Google, for example.
- Hopefully this will be solved with the next release of Spring Security OAuth2, like @jgrandja says, but that's a migration we will do once it's released, and it will be a specific ticket (with probably a lot of work!)

Besides, this has been opened for 8 months, and I even gave a $100 bounty on this, and this doesn't seem to interest any contributor.

**Comment by yelhouti** [comment]
Hey @jdubois :)

could you put the bounty back? I fixed it...

Thanks in advance

**Comment by deepu105** [comment]
@yelhouti could you link the PR where you fixed it? I didn't find any

**Comment by jdubois** [comment]
@yelhouti it depends on the fix as this isn't a trivial issue, can you tell us at least what you intend to do?

**Comment by yelhouti** [comment]
@jdubois , @deepu105 
I didn't make a PR, my fix is working locally but would need some rewrite to work for all IdPs.

Basically, what I do is use `GET` instead of `POST` for the jhipster `api/logout` endpoint and change the logoutSuccessHandler to do a redirect on the IdP URL, which in most IdPs (keycloak, Okta) the same as the user info endpoint (`XXX/userinfo` => `XXX/logout`).
I didn't find in the oauth2/oidc spec an endpoint for the logout feature (and don't I think there is one, since it's more of SSO feature than a oauth2 one).

So the cleanest way for me is to specify in the application.yml a new entry:
oauth2.slo.url and oauth2.slo.redirect-uri-query-param and use them for the redirect mentioned earlier.

**Comment by stieler-it** [comment]
Like @mraible already explained, I'm not sure if logging out should be the default behavior of JHipster generated apps. If you integrate your app into an existing SSO infrastructure in your company you probably don't want to be auto-logged out there. Thus, I think we don't need a fix here but a new feature so the developer can decide what happens on logout. If the user can't do an actual logout, I can also imagine it would be best to remove the logout menu item.

**Comment by jdubois** [comment]
OK so following @stieler-it advice I indeed think we should not change the default behavior. I understand many people want this (and I have a client who does), but that would be confusing for all other people who expect the "normal" behavior.

@yelhouti how about contributing a tip at https://www.jhipster.tech/tips/ ? This would indeed be helpful for many people

**Comment by maznag** [comment]
For OKTA, as @mraible already explained in one of his tutorials [Logout with OKTA](https://developer.okta.com/blog/2018/06/18/spring-boot-angular-auth-code-flow#logout-with-okta) we can modify the logout() method to send a logout URL and the ID token back to the client as follow (it works well for okta but i haven't tested for Keycloak). 

- AccountResource Api
<pre>
   private final UserService userService;
   private final UserInfoRestTemplateFactory templateFactory;

    @Value("${security.oauth2.client.access-token-uri}")
    String accessTokenUri;

    public AccountResource(UserService userService, UserInfoRestTemplateFactory templateFactory) {
        this.userService = userService;
        this.templateFactory = templateFactory;
    }
    /**
     * GET /api/logout : logout the current user.
     *
     * @param request http request (HttpServletRequest)
     * @return authentication the Authentication object
     */
    @PostMapping("/logout")
    public ResponseEntity<?> logout(HttpServletRequest request, Authentication authentication) {
        log.debug("REST request to logout User : {}", authentication);
        // send logout URL to client so they can initiate logout - doesn't work from the server side

        OAuth2RestTemplate oauth2RestTemplate = this.templateFactory.getUserInfoRestTemplate();
        String idToken = (String) oauth2RestTemplate.getAccessToken().getAdditionalInformation().get("id_token");

        // logout URI can be derived from accessTokenUri
        String logoutUrl = accessTokenUri.replace("token", "logout");

        Map<String, String> logoutDetails = new HashMap<>();
        logoutDetails.put("logoutUrl", logoutUrl);
        logoutDetails.put("idToken", idToken);
        request.getSession(false).invalidate();
        return ResponseEntity.ok().body(logoutDetails);
    }
</pre>

- Angular Service account.service.ts

<pre>
    // logout from the server
    logout() {
        this.logoutFromServer().subscribe((response: any) => {
            const logoutUrl = response.body ? response.body.logoutUrl : response.logoutUrl;
            const idToken = response.body ? response.body.idToken : response.idToken;
            if (logoutUrl && idToken) {
                location.href = logoutUrl + '?id_token_hint=' + idToken + '&post_logout_redirect_uri=' + window.location.origin;
            }
        });
    }

    private logoutFromServer(): Observable<any> {
        return this.http.post(SERVER_API_URL + 'api/logout', {}, { observe: 'response' });
    }
</pre>

**Comment by yelhouti** [comment]
@jdubois I can definitely do that, and I totally agree that when using OAuth2 this should be the default behavior.
@maznag what you mentioned definitely works and it was my first solution until I decided to use standard redirect and use get like in login instead of post.

@jdubois @deepu105 I want to mention that using OAuth2 instead of OIdC for authentication (instead of authorization) is wrong, and when external/malicious clients exist allows then to impersonate any user. In must simple app cases this not a problem but in big companies using the same keycloak realm for other purposes, this could create a serious vulnerability threat.
I also understand that with spring 1.X.X doesn have support OOTB (I think it is the case now with Spring 2).

I can help work on that but unfortunately I don't have the time/budget to do all that part on my own.

**Comment by mraible** [comment]
We do use OIDC for authentication. Spring Security handles it for us, even if it’s not obvious. I know how to upgrade to Spring Security 5.1 (which has even better OIDC support). It’s part of Spring Boot 2.1. I’m not sure if we want to upgrade sooner. Also, property names will change. This seems like a breaking change, so might to wait for JHipster 6.

**Comment by yelhouti** [comment]
@mraible I just rechecked the code, the part responsible for checking the token is:
```
OAuth2Authentication result = tokenServices.loadAuthentication(accessToken.getValue());
```
in the SSOConfig,
which in turn use the OAuth2 `userinfo` endpoint that checks that token is valid. the endpoint doesn't/can't check the audience field since it doesn't know against what to check it (and it's not it's job).
the endpoint returns a json without this `audience` info and the info is lost and never checked after that.

So unless you can show me where is this field checked (and according to OIDC spec it should be) I maintain my point that this is an issue.

I can link to the spec part if you need that, but I think you are familiar with it.

**Comment by mraible** [comment]
userinfo is part of OIDC, not OAuth. 

I’m not sure is the issue you mention is cause by Spring Security or code we’re missing. Any improvements are most welcome!

**Comment by yelhouti** [comment]
@mraible the part of Spring security we are using has implmented OAuth2 not OIDC. It's implemted correctly for the authorization use case, and we are using it for the authentication use case.
PS: this is exactly what OIDC is supposed to fix.

**Comment by mraible** [comment]
A PR to use it the right way is most welcome!

**Comment by yelhouti** [comment]
Unfortunately, I just don't have time for that these days, as soon as I can I will do it.

**Comment by darkguy2008** [comment]
Any news on this? I don't think this should be closed, I'm a new keycloak user and I'm facing this after integrating it with Seafile and Outline. Logging out from those apps don't seem to log out from keycloak, and I get that stupid error.

I mean, it would be **just great** if the page would have a "Okay, log me out" link/button or something, instead, we're locked in without a way to sanely log out. This kinda sucks.

**Comment by mraible** [comment]
@darkguy2008 A JHipster app will log you out as expected these days. Please don't comment on an issue that is closed and has nothing to do with JHipster.

**Comment by darkguy2008** [comment]
> @darkguy2008 A JHipster app will log you out as expected these days. Please don't comment on an issue that is closed and has nothing to do with JHipster.

Oh whoops, my bad, I commented thinking this was the Keycloak repo, or part of the organization, sorry!
