### ISSUE TITLE
VM is not generated based on the DTO

### ISSUE THREAD

**Issue by ddm7** [jhipster/generator-jhipster#7093]
Hello,

Your sample project
[https://github.com/jhipster/jhipster-sample-app-dto](https://github.com/jhipster/jhipster-sample-app-dto)

Why [BankAccount](https://github.com/jhipster/jhipster-sample-app-dto/blob/master/src/main/webapp/app/entities/bank-account/bank-account.model.ts) is not generated based on [DTO](https://github.com/jhipster/jhipster-sample-app-dto/blob/master/src/main/java/io/github/jhipster/sample/service/dto/BankAccountDTO.java) ? It seems it's generated based on the [domain class](https://github.com/jhipster/jhipster-sample-app-dto/blob/master/src/main/java/io/github/jhipster/sample/domain/BankAccount.java).

I'm using JHipster for a complex project and I have a lot of warnings in Eclipse related to this issue. Also the code completion is not working correctly (e.g. line 17 from [bank-account-detail.component.html](https://github.com/jhipster/jhipster-sample-app-dto/blob/master/src/main/webapp/app/entities/bank-account/bank-account-detail.component.html)), userLogin is not declared in the [BankAccount](https://github.com/jhipster/jhipster-sample-app-dto/blob/master/src/main/webapp/app/entities/bank-account/bank-account.model.ts)

Thank you,
Dan

**Comment by jdubois** [comment]
It's not generated using the JPA entity or the DTO, it comes directly from the JDL. But it's true that the code we use is the domain model - in fact the DTO isn't as stable and widely used, it's considered an "advanced use case". Which doesn't mean you shouldn't use it, many people use DTOs and are right to do so.
The DTO is supposed to be mapped automatically on the domain model, so it shouldn't change anything for you - what kind of warnings do you have? If you could list them, we could have a look at solving those.
Code completion for Typescript should work - you mean it doesn't work with Eclipse? Do they have some kind of plugin for Typescript?

**Comment by jdubois** [comment]
I'm closing this because this is more a question, so that should go to Stackoverflow.
Besides, the guidelines are not followed: we need to know what the errors are, what your config is, etc.

**Comment by ddm7** [comment]
Hi Julien,

I cannot give you the context of my project, because the discussion it's about the [JHipster sample project](https://github.com/jhipster/jhipster-sample-app-dto) :)

I'm using the Webclipse plugin for Eclipse.

One example of warning is "Identifier 'userLogin' is not defined. 'BankAccount' does not contain such a member". Line 17 from [bank-account-detail.component.html](https://github.com/jhipster/jhipster-sample-app-dto/blob/master/src/main/webapp/app/entities/bank-account/bank-account-detail.component.html).

Thank you,
Dan

**Comment by jdubois** [comment]
Well, Visual Studio Code looks OK, but indeed that's a "userId" not a "userLogin". Let me check with Intellij IDEA. Maybe it's **my** tool which is broken.

**Comment by jdubois** [comment]
Well, that's really strange.

- the code compiles, so the method should be good
- it also runs very well, I get the user login

But, to be honest, I don't understand where the "userLogin" property comes from. So I'm lost like "Webclipse", but we should both be wrong, because it compiles and runs correctly :-)

**Comment by ddm7** [comment]
userLogin property comes from the [DTO](https://github.com/jhipster/jhipster-sample-app-dto/blob/master/src/main/java/io/github/jhipster/sample/service/dto/BankAccountDTO.java), which is used by the REST service.

The [TypeScript class BankAccount](https://github.com/jhipster/jhipster-sample-app-dto/blob/master/src/main/webapp/app/entities/bank-account/bank-account.model.ts) does not contain the userLogin property, because is generated using the JDL/Domain definition, not the DTO.

Yes, the code compiles and run.

I have a problem of productivity in terms of development. Code completion does not help me ... I have a project with more than 50 entities.

Thank you
Dan

**Comment by jdubois** [comment]
Yes, basically the DTO "flattens" some parts of the domain entity, to remove relationships (as you don't have lazy loading). So that's "normal", in the sense that on the server-side this is what is meant to be done.
Now, on the client side, I guess that the person who coded this didn't know there was a difference with DTOs (and please note that DTOs are still marked BETA, because of this kind of issues, so maybe the person didn't even take them into account). Then it's working, which is great, but I would like first to understand why - I don't know this part of the code very well.
This could be easily corrected because we have very few of them.

**Comment by ddm7** [comment]
Since JHipster is generating also the client side, it would be nice to follow the DTO definition.

JHipster has two **options** regarding the return type of the REST service:
- domain class;
- DTO;

Right now the client side is always generated using the domain class regardless the chosen **option**.

**Comment by gmarziou** [comment]
I confirm the issue and the reason why compiler does not warn about it is because default configuration is not strict enough.
I added `"skipMetadataEmit" : true` to angularCompilerOptions and it detected the missing userLogin property:

~~~
yarn run ngc
$ ngc -p tsconfig-aot.json
src/main/webapp/app/admin/audits/audits.component.html(11,93): : Expected 0 arguments, but got 1.
src/main/webapp/app/admin/audits/audits.component.html(16,93): : Expected 0 arguments, but got 1.
src/main/webapp/app/admin/health/health-modal.component.html(21,25): : Expected 2 arguments, but got 1.
src/main/webapp/app/admin/metrics/metrics.component.html(165,17): : Expected 2 arguments, but got 1.
src/main/webapp/app/admin/metrics/metrics.component.html(200,17): : Expected 2 arguments, but got 1.
src/main/webapp/app/admin/metrics/metrics-modal.component.html(25,22): : Expected 2 arguments, but got 1.
src/main/webapp/app/admin/metrics/metrics-modal.component.html(15,22): : Expected 2 arguments, but got 1.
src/main/webapp/app/entities/bank-account/bank-account-detail.component.html(16,13): : Property 'userLogin' does not exist on type 'BankAccount'.
src/main/webapp/app/entities/operation/operation-detail.component.html(22,78): : Property 'bankAccountName' does not exist on type 'Operation'. Did you mean 'bankAccountId'?
~~~

**Comment by gmarziou** [comment]
@ddm7 could you test on your real project ?
