### ISSUE TITLE
Add support for SSE (Server Sent Events)

### ISSUE THREAD

**Issue by cmoine** [jhipster/generator-jhipster#7122]
##### **Overview of the feature**

Server Sent Events tend to be more efficient from a network perspective than WebSockets. For that reason, it would be nice to add an example. In my situation I have added a module to show the application logs in real time. I think it would be very useful to integrate it out of the box (unless I missed an option ?)

##### **Motivation for or Use Case**

1. Add an example of SSE which can be copy/pasted for other purposes
2. At the same time, add a useful screen to visualize logs

##### **Reproduce the error**

[N/A]

##### **Related issues**

None

##### **Suggest a Fix**

I am currently implementing it, but I can share it with you with a PR.

##### **JHipster Version(s)**

4.13.3

##### **JHipster configuration**

I have used the online generator

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

None

##### **Browsers and Operating System**

Windows 10 & Chrome

**Comment by jdubois** [comment]
We do have an option for Websockets, but not for SSE... [A tip](http://www.jhipster.tech/tips/) would be great, maybe even [a module](http://www.jhipster.tech/modules/marketplace/#/list)? For an example, we can't do this at the moment: you would need to support AngularJS, Angular, React... And I don't know how it works for security (but I'm not sure I want to look for that!). So that would be too much trouble.

**Comment by deepu105** [comment]
as @jdubois said we cant support everything hence plz consider building a module. we will support you in all possible ways

**Comment by cbornet** [comment]
I think there is a problem with SSE + JWT or Oauth2 because you can’t add the Authorization header in EventSource

**Comment by cmoine** [comment]
> I think there is a problem with SSE + JWT or Oauth2 because you can’t add the Authorization header in EventSource
That is a very good point !
> plz consider building a module.
A module... for JHispter ? Do you have more info on that please ?

**Comment by deepu105** [comment]
This feature is more suitable to be built as a [JHipster module](https://jhipster.github.io/modules/marketplace/#/list) so that it can be evaluated first. If the module ends up being very popular we could consider integrating it into the main project here. Please refer the documentation on [how to build modules](https://jhipster.github.io/modules/creating-a-module/) and look at some of the [existing modules](https://jhipster.github.io/modules/marketplace/#/list) for inspiration. Reach out to us if you need any help like clarification on how the module system works, adding/exposing new methods for the API etc.
You can use the [JHipster module generator](https://github.com/jhipster/generator-jhipster-module) to scaffold a module.

**Comment by cmoine** [comment]
Thank you very much for the help. I feel a bit clumpsy :( I will try to dig into it, and hope I could provide a descent module for Log visualization. Please be patient ;)
