### ISSUE TITLE
Swagger returns unauthorized in microservice + UAA configuration when using yarn

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#7185]
##### **Overview of the issue**

When using a microservice + UAA configuration, swagger always returns a 401 when using livereload (yarn start).
`{
  "error": "unauthorized",
  "error_description": "Full authentication is required to access this resource"
}`

##### **Motivation for or Use Case**

I want to test or demonstrate my APIs call in dev mode! It's minor, but at least the documentation should mention it

##### **Reproduce the error**

Instantiate a microservice architecture with UAA, GW and a uService.

- ./mvnw -Pdev,swagger all of them

- Yarn start gw

- Log in as admin, test a swagger get call

##### **Related issues**

N/A

##### **Suggest a Fix**

I really don't know: this looks related to JWT 

##### **JHipster Version(s)**

4.14.0

##### **JHipster configuration**

Any UAA + Gw + ms configuration

##### **Browsers and Operating System**
N/A

- [ x] Checking this box is mandatory (this is just to show you read everything)

Yes, I love it! You're all the best <3

**Comment by lukasw44** [comment]
The same error when you are using jhipster-register

**Comment by PierreBesson** [comment]
I think this might be caused by the fact that with uaa the auth is done with cookies and somehow  the webpack proxy is not configured to forward them to the backend server. With JWT it currently works fine by forwarding the token.

**Comment by ruddell** [comment]
This issue also affects OAuth2 apps when using the webpack proxy

The issue here is that requests are using the host header which uses port 9060 instead of port 9000.  
 - One fix that seems to work for both ports 8080 and 9000 is to add `headers: { host: 'localhost:9000' }` to the webpack.dev.js proxy configuration (this overrides the `host` header).  I'm not sure if this would have adverse effects, I didn't see any issues and it only would affect `dev`.  The 301 redirects for OAuth2 work fine.
 - You can hardcode `host: localhost:9000` into the JHipster swagger settings but then it stops working on 8080.   
 - The third way is to configure this is in the Swagger docket somewhere.  The `/api-docs` endpoint is the one returning 9060 based on the host header from the dev proxy.

JWT gateways and regular apps also use port 9060 but as @PierreBesson mentioned the JWT token works fine.  It's cookies which are causing an issue.

I can PR the solution if it sounds good
