### ISSUE TITLE
Remove Spring Social Facebook

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#7201]
- It has been broken for several months, see #6809
- I don't think this is widely used - people are reluctant to use Facebook for this kind of things, and nobody looks interested in maintaining this part
- That's more work, for instance for the React support, and we mostly give a squeleton for other integration, so for me Twitter & Google are enough

**Comment by ruddell** [comment]
@jdubois The issue is supposed to be resolved in Spring Boot 2, spring-social-facebook already has a milestone released that works correctly (3.0.0.M1).  The only effect on the React side is the Facebook login button and login scope (one line).

I wish I had time to comment before you removed it.  I spent a lot of time implementing Social Login for IgniteJHipster and removing Facebook reduces that utility.  I've also had several people register via the sample IgniteJHipster Android app using JHipster's Facebook login.

I plan to open in an issue in the near future about social login improvements (mainly, instant registration rather than having to register and then log in again).  I can add the workaround for Facebook if we can't wait for the normal Spring release cycle but in my opinion, I don't see the value in removing Facebook

**Comment by jdubois** [comment]
Oh sorry -> @ruddell I'm reverting my commit then, and I'll try to take that milestone in our BOM

**Comment by jdubois** [comment]
Reverted at https://github.com/jhipster/generator-jhipster/commit/bc1c0a5074947442f5f37a07a4dafe51cdc6a2db

I'll refactor the unit tests as I did in my changes, as we had Keith Donald written everywhere (I love Keith, but that's weird to have his name everywhere)

**Comment by jdubois** [comment]
@ruddell everything is done, I hope that's OK for you!

**Comment by ruddell** [comment]
Thank you, I appreciate it.  Feel free to tag me with any social login issues as I'm really familiar with that code

**Comment by jdubois** [comment]
Thanks for telling me - I had no idea you knew that part well, and it's hard to maintain for me!
