### ISSUE TITLE
Blueprint enhancements / fixes [ the future ]

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster#7238]
After playing a lot with blueprints, I feel few things are missing or good to have. Here is a set of things which would be super awesome to have it in the blueprint.

- [ ] `-b` shortcut for blueprint
- [x] create a blueprint generator (that helps to generate a blueprint)
- [x] the arguments passed to the jhipster commands is kind of flaky and it is not properly passed on
- [x] rework needed on the server files
- [ ] option to override the path for the files. This will be extremely helpful in the context of blueprint
- [x] Add blueprint support to the missing modules [only supported for client, server, entity, entity-client, entity-server, spring-controller and spring-service)

**Comment by deepu105** [comment]
@sendilkumarn I moved these 2 out as we need to discuss them, as I don't agree with them. See reasons below
- [ ] remove `generator-jhipster` from the blueprint completely
Maybe we can remove jhipster from the name, but you still need the generator in the name otherwise yeoman will not be able to identify it during composing in legacy mode. I'll see what can be done here but cannot promise this
- [ ] Option to add a separate command for `blueprint` to work. Something like `khipster` (this removes the need of jhipster) in the client machine (however the blueprint will still need the generator as a dependency) ⚠️ (just an idea)
I dont agree with this, even if there is a way to do it, as this would hijack JHipster, it is impirtant that people know thet they are using JHipster. If a blueprint wants to become independent it should implement its own CLI and release it, in the CLI it could integrate with JHipster CLI

**Comment by sendilkumarn** [comment]
> but you still need the generator in the name 

wasnt this removed in the new version. We can wrap or add them inside the base generator if needed. I feel it is redundant.

> as this would hijack JHipster,

I would argue not. (that is the reason why I added warning symbol). Technically, if we add blueprint support to all the generators it is completely doable. But all they will need the base generator, without that they cannot use it. It is like adding aliases. But it is pretty arguable on both the sides. Let us discuss this. But it is not mandatory.

**Comment by deepu105** [comment]
1. Do you mean yeoman removed the need to have generator in the name? i'm not aware of that, the yeoman website still says its needed.

**Comment by deepu105** [comment]
some work done in #7437

**Comment by sendilkumarn** [comment]
@deepu105 after this PR, the blueprint is not working any more. now the blueprint is going in a loop

**Comment by deepu105** [comment]
ok, i'll take a look

Thanks & Regards,
Deepu

**Comment by sendilkumarn** [comment]
@deepu105 you working on this?

**Comment by deepu105** [comment]
Not yet, need to find some time next week

**Comment by deepu105** [comment]
Closing this. The two outstanding items are tricky and there are workarounds for those anyway
