### ISSUE TITLE
No translation for min and max validation errors

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#7305]
From https://github.com/mraible/21-points/issues/33

**Comment by Dufgui** [comment]
Since you migrate to angular 5, the message no more appear because validator min max don"t work. I test is with the current master of 21 points. See #7514. 
I wait core team return to choice a way and do a PR.

**Comment by ruddell** [comment]
Validation returns the exact annotation that the validation failed on as the translation key, so this is broken for `Min`, `Max`, `DecimalMin`, and `DecimalMax`.  You don't normally see this issue because the client-side validation usually prevented it from happening until Angular broke min/max, but it affects very old versions (reproduced with v4.7.0)

This simplest fix would be to change the code to `Size` if it ends in `Min`/`Max` ([here](https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/web/rest/errors/ExceptionTranslator.java.ejs#L93)).

        String code = f.getCode();
        if (code.endsWith("Max") || code.endsWith("Min")) {
            code = "Size";
        }

This would make the translation use:

        "Size": "Field {{ fieldName }} does not meet min/max size requirements!",

The other option I can think of is to add translation keys to all languages for `Min`, `Max`, `DecimalMin`, and `DecimalMax`.  Any others?
