### ISSUE TITLE
Mongeez requires admin privileges

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#733]
Mongeez (used to populate MongoDB) does not work on cloud providers like https://mongolab.com/ as it requires admin privileges.
See https://github.com/secondmarket/mongeez/issues/27

We might consider another option soon, as this is a blocker issue with CloudFoundry + Mongodb, which would be a great combo!

**Comment by d0x** [comment]
Do you have a plan to move to another solution?

**Comment by jdubois** [comment]
Yes I want to use another solution. I just haven't worked on it yet -> if you are interested you can take the lead on this!

**Comment by franciscocpg** [comment]
@jdubois
I think the solution here is not to use another solution, but to patch Mongeez because the problem here is just the following  code at [MongeezDao.java](https://github.com/secondmarket/mongeez/blob/master/src/main/java/org/mongeez/dao/MongeezDao.java):
```java
public void runScript(String code) {
        db.eval(code);
}
```
Besides the fact that eval requires admin privileges, it was deprecated in version 3.0 and future releases will remove it according to this thread:
https://jira.mongodb.org/browse/SERVER-17453
I see two options at this moment:
1. Instead of writing javascript codes in mongeez changesets xml file, should write java code and execute it using [bsh](http://www.beanshell.org/).
2. Parse javascript code and create a wrapper for java using mongodb java driver.
For example:
The code
```javascript
db.test.insert({
   "name" : "MongoDB",
   "type" : "database",
   "count" : 1,
   "info" : {
               x : 203,
               y : 102
             }
})
```
should execute
```java
DBCollection testCollection = db.getCollection("test");
BasicDBObject doc = new BasicDBObject("name", "MongoDB")
        .append("type", "database")
        .append("count", 1)
        .append("info", new BasicDBObject("x", 203).append("y", 102));
testCollection.insert(doc);
```
For this option, maybe some project like [jongo](http://jongo.org/) could help.

**Comment by rreitmann** [comment]
Is there any workaround at the moment? I also want to deploy to cloudfoundry (Pivotal Web Services) using mongodb...

**Comment by jdubois** [comment]
The only workaround is to update the database manually.

**Comment by rreitmann** [comment]
:-) This is exactly what I am doing currently.

**Comment by rreitmann** [comment]
I guess I will have a look at this https://github.com/goodeggs/grunt-mongo-migrations and manage the mongo migrations with mongoose...

**Comment by jdubois** [comment]
Yes I've heard it could be a good solution : please send feedback, and even a PR if you can !

**Comment by hyuan** [comment]
I think @franciscocpg's suggestion one - use bsh to write scripts - is doable. I submitted a PR https://github.com/mongeez/mongeez/pull/55 to mongeez

**Comment by franciscocpg** [comment]
@hyuan, great news! But I think mongeez is a little bit "inactive". The last appoved PR was on 4 Aug 2014 and the last closed was on 12 May 2015. 
Let's pray for they approved your PR. :)

**Comment by sreeshas** [comment]
@jdubois  I have an alternative solution for this problem. Instead of using mongeez, i stumbled upon mongobee. I tried it out and it worked as expected. 

You can find more details here. 
http://sreeshas.github.io/2015/12/10/using-mongolab-in-jhipster/

Let me know if you would like me to submit this fix.

**Comment by jdubois** [comment]
Looks indeed like a better solution, but the project doesn't seem very active either.... And I don't want to have the same kind of issue again. What do people use with MongoDB???
