### ISSUE TITLE
Setup Kubernetes with non-default JHipster Registry password doesn't work

### ISSUE THREAD

**Issue by stephanj** [jhipster/generator-jhipster#7365]
##### **Overview of the issue**

When you use the JHipster Kubernetes generator and enter a non-default password (not "admin") for the JHipster Registry authentication, the generated gateway/microservices are unable to connect to JHipster registry.

##### **Reproduce the error**

$ jhipster kubernetes
Using JHipster version installed globally
Executing jhipster:kubernetes
Options:
⎈ Welcome to the JHipster Kubernetes Generator ⎈
Files will be generated in folder: /tmp
? Which *type* of application would you like to deploy? Microservice application
? Enter the root directory where your gateway(s) and microservices are located ../

? Which applications do you want to include in your configuration? admin
JHipster registry detected as the service discovery and configuration provider used by your apps
? Enter the admin password used to secure the JHipster Registry (admin) notadmin

##### **Related issues**

Don't think so because Ray Tsang was not aware of this. 

##### **Suggest a Fix**

Test with non-default JHipster Registry password.

##### **JHipster Version(s)**

4.14.1

##### **Browsers and Operating System**

MacOS

**Comment by PierreBesson** [comment]
Hi @stephanj, I think I have located the problem which relates to the new registry which has been migrated to Spring Boot 2. What version of the JHipster Registry are you using ?

**Comment by pascalgrimaud** [comment]
oh yes, it should be resolved. I merged the PR https://github.com/jhipster/generator-jhipster/pull/7372

**Comment by stephanj** [comment]
I'm using Jhipster Registry 3.2.4

**Comment by PierreBesson** [comment]
Okay, then the issue was not with the Spring Boot 2 migration it seems this was broken in the k8s subgen for some time :cry:. Having a look at the source for the Registry 3.2.4, I see that `admin` is hardcoded in the `security.user.password` property and is not overwritten in the k8s manifest.
The `jhipster_registry_password` property is only useful for the Registry clients so it's useless to set on the Registry itself.

Thanks a lot @stephanj for your feedback !
