### ISSUE TITLE
ArangoDB support

### ISSUE THREAD

**Issue by hberndt** [jhipster/generator-jhipster#7411]
##### **Overview of the issue**

We want to use JHipster in conjunction with ArangoDB.

##### **Motivation for or Use Case**

ArangoDB is a noSQL database with support of documents and graphs. The annotation is much like a combination of MongoDB and Neo4J. We tested Arango manually with a JHIpster generated app and want to integrate this feature.

This issue is a feature request and we want to know if anyone else is interested in this feature. Will a future pull request successful.

**Comment by jdubois** [comment]
We already have Cassandra (that less than 1% of people use) and Couchbase (that less than 0,1% of people use). ArangoDB is even less well-known than Couchbase (see Google Trends: https://trends.google.fr/trends/explore?date=all&q=couchbase,arangodb ), so I am against it: this will add a lot of maintenance overhead, and lots of tests, for nearly nobody using it.

This is absolutely not an opinion on the technology, it's just that I know that options that are not widely used are a pain to maintain, because nobody works on it. To give you another number: we have less than 1 contributor for 1,000 users, so that gives you an idea of how a technology has to be successful before reaching the "tipping point" and can be easily integrated and maintained.

This is a good use case for a module, or maybe a blueprint (a new feature of JHipster 5), if you or ArangoDB are interested in doing it. Also, if you or ArangoDB are ready to do this module and support it, we will also gladly spread the word (by Twitter, etc). We do everything we can do help module owners have their project working.

**Comment by hberndt** [comment]
Good argument. We will have a look on modules/blueprints. 
Thanks for your reply

**Comment by jdubois** [comment]
Thanks! For the moment, modules are the only stable option - in the future I hope blueprints will be much better, but it's not stable yet.
