### ISSUE TITLE
Entity is being created when using `@PutMapping`

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#7425]
##### **Overview of the issue**

_This is not a bug but rather an opinionated point._

For any entity generated by jhipster, `@PutMapping` code include to create the entity if the id is null.

##### **Motivation for or Use Case**

1. By using HTTP PUT, we assume that the underlying resource will be updated. For creating a new resource, HTTP POST should be used. Currently in jhipster, PUT is also creating a new resource which also results in an another following issue.

1. Consider we do not want the user with role `ROLE_USER` to create a new resource. So we do `    @Secured(AuthoritiesConstants.ADMIN)` on `@PostMapping`, but this will not restrict a normal user from creating a new resource because he/she still can create using `@PutMapping`.

##### **Reproduce the error**

- start application
- using dev tool, change id of an entity to null before save method call.
- a new resource will be created

##### **Related issues**
-
##### **Suggest a Fix**

Remove method call from `@PutMapping` to `@PostMapping`.
And if client sends id as null, return some error message.

##### **JHipster Version(s)**

v4.x.x, v5.0.0-beta

##### **JHipster configuration**

-

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

-

##### **Browsers and Operating System**

-

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Yes that was discussed at the very beginning of JHipster (and I don't have to look for the ticket, sorry). So that's supposed to be correct from a REST point of view, at least it was decided to do it that way after reading http://restcookbook.com/HTTP%20Methods/put-vs-post/ (as far as I remember).

Then your argument on security looks very good to me, and we can always have architecture discussion here.

**Comment by deepu105** [comment]
I also agree that security is more important and hence may be we can change this. @jhipster/developers anyone think we shouldnt change it?

**Comment by gmarziou** [comment]
+1 to change

**Comment by jdubois** [comment]
This is going to break a lot of existing apps, so we either change it now, or it will be next year for JHipster 6...
At the moment we only have 1 article on the subject, and it's against this change, so this is a logical change, but this should be further studied.

**Comment by gmarziou** [comment]
I'm not sure it will break a lot of apps because our angular services do not use this "feature".

**Comment by jdubois** [comment]
At least with AngularJS we were using it (I coded it), not sure what happens today.
Anyway, reading https://stackoverflow.com/questions/630453/put-vs-post-in-rest we can indeed create resources with a PUT, but if we already know the ID of the entity we want to create. This never happens in JHipster, as the ID is generated in the database - I mean, it doesn't happens by default, of course it would be a good practice to use a business ID here, but as it's a business ID we can't generate it.
So when we create a PUT with a null ID, we in fact do an operation which is not idempotent, and that's wrong: PUT operations should be idempotent.

So +1 from me to change this, but there are tests to do on Angular and React.

**Comment by jdubois** [comment]
OK let's do it then! @pmverma would you be ready to do the PR? We'll help you, of course

**Comment by pmverma** [comment]
I will be happy. Thanks.

**Comment by pmverma** [comment]
I have followed https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md#-generator-development-setup

One more thing, in order to see everywhere that my local modified version is being used, I have modified `package.json` by increasing jhipster version to `5.0.0-beta.1`, only for local testing purpose.

If I run `./mvnw verify -Pprod` I am getting following error.

```
[INFO] --- frontend-maven-plugin:1.6:yarn (yarn install) @ jh-5 ---
[INFO] Running 'yarn install' in /Users/sierra/github/jh5
[INFO] yarn install v1.5.1
[INFO] [1/5] Validating package.json...
[INFO] [2/5] Resolving packages...
[ERROR] warning Lockfile has incorrect entry for "generator-jhipster@5.0.0-beta.1". Ignoring it.
[ERROR] error An unexpected error occurred: "Couldn't find any versions for \"generator-jhipster\" that matches \"5.0.0-beta.1\"".
[INFO] info If you think this is a bug, please open a bug report with the information provided in "/Users/sierra/github/jh5/yarn-error.log".
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.925 s
[INFO] Finished at: 2018-04-09T23:12:23+06:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (yarn install) on project jh-5: Failed to run task: 'yarn install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

```
Can someone please help?

**Comment by pmverma** [comment]
@pascalgrimaud thanks your point solves my error.

**Comment by jihlee** [comment]
Hi guys. I have an additional suggestion related to this update.
After @pmverma 's PR, entities generated from Jhipster cannot be created using PUT, but it would be possible if users changed their entities' ID generation strategy from auto-generated to others.

What I want to suggest is that controllers return 201 instead of 200 when some entities were generated from PUT request to follow RFC-4.3.4(https://tools.ietf.org/html/rfc7231#section-4.3.4).

**Comment by jdubois** [comment]
@jihlee indeed, but then we would need to support different generation strategy, which we don't do at the moment... There has been several times people asking to support UUID, and I was definitely against it, but time has passed and now I think this could have been a good idea for some specific use cases.
So that would be a specific question when generating an entity, and it might be a bit complex to implement (typically for handing the relationships with that entity). We can't do it at the moment as we have 50+ opened tickets, but it's totally worth discussing in the long term.
