### ISSUE TITLE
When I use JWT, token can support auto-refresh?

### ISSUE THREAD

**Issue by gemron** [jhipster/generator-jhipster#7509]
##### **Overview of the issue**
Jwt contains the expiration time. When the user login to the system for the first time, the expiration time is set to jwt. When the user selects “remember me”, the token will be stored in the browser, but if the token is not automatically refreshed, After some time, the user still needs to enter the user name and password to login.

##### **Motivation for or Use Case**
user login

##### **Reproduce the error**
the expiration time 

##### **Related issues**
no

##### **Suggest a Fix**
add jwt token auto-refresh

##### **JHipster Version(s)**
4.14.3

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
No it doesn't support auto-refresh, for this you need something like OAuth2. Or, indeed, use the "remember me" feature, which does something a bit like the OAuth2 refresh token (but less secured).
The token is supposed to last several days, so that shouldn't be an issue.

This is why OAuth2 would be a more secure solution (but it's also far more complex to set up).

**Comment by gemron** [comment]
@jdubois Thank you for your reply, because in our business scenario, the user does not want to enter the username and password multiple times. Now I have implemented automatic refresh of the token. Thanks again
