### ISSUE TITLE
Speed up start-up time by making liquibase & swagger optional

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#762]
Start-up time takes 10s on my machine:
- 1.5s is taken by Swagger
- 1s is taken by Liquibase

Besides, I have reports from people with very big projects that Swagger slows down start-up time dramatically (one project went from 60s to 10s just by removing Swagger).

My idea is to create 2 Spring profiles:
- "no-liquibase" and "no-swagger" -> if you have better names, feel free to comment!
- they wouldn't be set up by default -> nothing changes, and "normal" users have Swagger and Liquibase
- but advanced users could select those profiles to speed up their builds

**Comment by egiovanni85** [comment]
Hi this method worked form me with jhipster to make swagger very fast!!! I found it after 2 weeks :-D
The problem is jhipster without mapstruct dto.... 

Dto * with mapstruct   ------ is required
Add this  dependencies    

1-------------------------------------------------------------------------------


<dependency>
    <groupId>io.springfox</groupId>
    <artifactId>springfox-swagger-ui</artifactId>
    <version>2.9.2</version>
</dependency>

2------------------------------------------------------------------------------------


<dependency>
    <groupId>com.github.caspar-chen</groupId>
    <artifactId>swagger-ui-layer</artifactId>
    <version>1.1.3</version>
</dependency>


Update progect and restart!!!
You can find swagger ui at:
http://localhost:xxxx/swagger-ui.html#/
