### ISSUE TITLE
Forbid oauth option when no database

### ISSUE THREAD

**Issue by Tcharl** [jhipster/generator-jhipster#7669]
##### **Overview of the issue**

OAuth integration requires a database to persist user and authority info: jhipster should prohibit this option when no database is selected (otherwise, generation is not correct).

##### **Motivation for or Use Case**

The generated app contains code that is not functional!

##### **Related issues**

see jhipster info

##### **Suggest a Fix**

deactivate option when no database

##### **JHipster Version(s)**

5.0.0-beta.1

##### **JHipster Version(s)**

```
monitoring@0.0.0 /Users/charliemordant/Code/Sources/THALES/com.thalesgroup.ods.ecwp/com.thalesgroup.tce.service.monitoring
├── generator-jhipster@5.0.0-beta.1 
├─┬ generator-jhipster-elasticsearch-reindexer@1.1.0
│ └── generator-jhipster@4.14.4 
└─┬ generator-jhipster-enterprise-pom@0.0.5
  └── generator-jhipster@4.14.4 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.test",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.0.0-beta.1",
    "baseName": "monitoring",
    "packageName": "com.test",
    "packageFolder": "com/test",
    "serverPort": "8196",
    "authenticationType": "oauth2",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "no",
    "devDatabaseType": "no",
    "prodDatabaseType": "no",
    "searchEngine": "elasticsearch",
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "replaced-by-jhipster-info",
    "enableTranslation": true,
    "applicationType": "microservice",
    "testFrameworks": [
      "cucumber"
    ],
    "jhiPrefix": "jhi",
    "nativeLanguage": "en",
    "languages": [
      "en",
      "fr"
    ],
      "otherModules": [
          {
              "name": "generator-jhipster-enterprise-pom",
              "version": "0.0.5"
          },
          {
              "name": "generator-jhipster-spring-cloud-stream",
              "version": "0.0.2"
          }
      ],
    "clientPackageManager": "yarn",
    "skipClient": true,
    "skipUserManagement": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

git version 2.17.0

node: v8.11.1

npm: 5.6.0

yeoman: 1.8.5

yarn: 1.5.1

Docker version 18.03.1-ce, build 9ee9f40

docker-compose version 1.21.1, build 5a3f1a3

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
No need for entity

##### **Browsers and Operating System**

Any

- [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
Totally agree with your analysis, then I'm sad we can't have OAuth2 + no database. @mraible how about having the "user sync" feature optional, so you could use OAuth2 with no database? Of course there could be a performance hit if the user is needed, but that's not always mandatory.

**Comment by mraible** [comment]
The “saveUserSnapshot” logic is easy enough to change in the entity generator, it’s just one line of logic:

https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L674 <https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L674>

context.saveUserSnapshot = context.applicationType === 'microservice' && context.authenticationType === 'oauth2' && context.hasUserField;

The harder part would be updating all the app generation logic to not create tables, the User entity, etc. The UserResource and UserService would need quite a bit of updating since they just look at the authenticationType.

https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs <https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/web/rest/UserResource.java.ejs>

https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/service/UserService.java.ejs <https://github.com/jhipster/generator-jhipster/blob/master/generators/server/templates/src/main/java/package/service/UserService.java.ejs>

How does the entity generator and jdl-import work when no database is selected? Do they fail fast?

This seems like a lot of work. How often is the “no database” feature used?

**Comment by jdubois** [comment]
@mraible on JHipster 4, you couldn't run `jhipster entity` or `jhipster import-jdl` when the "no database" option was selected.

This is a very important option for a lot of people, as they use microservices to access lots of old/weird/unusal systems, so they don't need a database for those. Last year, my stats show that 5% of all generated applications where "no databases", so it's far more popular than Cassandra or Couchbase.

**Comment by MathieuAA** [comment]
I've added an issue in JCore to make sure selecting this option wouldn't make the JDL import fail.

**Comment by jdubois** [comment]
For me this is still a very important feature, but we clearly don't have the bandwidth to do it, so sadly I'm closing this.
