### ISSUE TITLE
Font awesome icons stuck to the text for Angular

### ISSUE THREAD

**Issue by ctamisier** [jhipster/generator-jhipster#7692]
**In the master branch (v5.0.0-beta.1), with an Angular generation: the font awesome icons are stuck to the text:**
<img width="537" alt="screen shot 2018-05-27 at 21 15 01" src="https://user-images.githubusercontent.com/766263/40589768-8e3ad63a-61f3-11e8-866b-c23606548750.png">

**Everything is fine in v4.14.4:**
<img width="555" alt="screen shot 2018-05-27 at 21 15 50" src="https://user-images.githubusercontent.com/766263/40589769-9a084e7a-61f3-11e8-9722-064b59448df9.png">

I think this happened since the use of `angular-fontawesome` or `fontawesome-svg-core`/`free-solid-svg-icons`.

**Comment by deepu105** [comment]
It used to have a fa-fw class tonfix width of icons. May be its changed now

**Comment by jdubois** [comment]
Yes indeed, thanks @ctamisier

**Comment by kaidohallik** [comment]
I don't know, is this best solution, but I fixed this in my project by:
* adding to `global.css`:
```
fa-icon {
    padding-right: 3px;
}
```
* in `navbar.component.html` adding property `[fixedWidth]="true"` to every `fa-icon` element.

**Comment by wmarques** [comment]
Yep we need to use the fixedWidth attribute to fix this. Can you do a PR @kaidohallik ? I'd be glad to review it :)

**Comment by ctamisier** [comment]
It’s not only for fa-icon actually. In the home page the title (top left) and some texts are also “stuck”

**Comment by kaidohallik** [comment]
Angular 6 changed default `preserveWhitespaces` value from `true` to `false`.  
Changing
```
.bootstrapModule(JhipsterAppModule)
```
to
```
.bootstrapModule(JhipsterAppModule, { preserveWhitespaces: true })
```
fixes all described stuck problems.  
Then no need for `fa-icon { padding-right: 3px; }` in `global.css` any more.

Is switching to `preserveWhitespaces: true` in global application level good idea?

To align items in admin menu, must also add property `[fixedWidth]="true"` to every `fa-icon` element in `navbar.component.html`.

**Comment by deepu105** [comment]
I think it should be ok to preserve whitespaces. can you do a PR

Thanks & Regards,
Deepu

**Comment by kaidohallik** [comment]
OK, doing PR.

**Comment by kaidohallik** [comment]
The production build currently generates .war without spaces. For the production build must also add line
```
        "preserveWhitespaces": true
```
under the section `angularCompilerOptions` in the file `tsconfig-aot.json`.

I'm not sure that setting `preserveWhitespaces: true` was right choice, because:
* it's against Policy 1 in https://www.jhipster.tech/policies/
* some new library versions working on top Angular 6 and expecting `preserveWhitespaces` to be default `false` value (for example PrimeNG 6) are looking weird with `preserveWhitespaces: true`

From the other side: some old libraries can look weird with Angular 6 default `preserveWhitespaces: false`.

In JHipster, alternative option to `preserveWhitespaces: true` is to add a special Angular pseudo-entity `&ngsp;` to all these places where there must be the space between the HTML elements.

**Comment by gmarziou** [comment]
Alternatively, couldn't this be addressed using CSS only?

**Comment by kaidohallik** [comment]
There are different places where space between elements is missing.  
If CSS then maybe:
* add CSS class for case `fa-icon` is left from main element and add this class to relevant `fa-icon` elements
* add CSS class for case `fa-icon` is right from main element and add this class to relevant `fa-icon` elements
* in other places add `&ngsp;` or` &nbsp;`
