### ISSUE TITLE
Kubernetes Generator sets imagePullPolicy to IfNotPresent, should it the policy use default?

### ISSUE THREAD

**Issue by saturnism** [jhipster/generator-jhipster#7709]
##### **Overview of the issue**

Currently, Kubernetes generator generates deployment YAML w/ `imagePullPolicy: IfNotPresent`. However, this doesn't work well when using using `latest` images, which is by default, what we use as the image tag (actually, we didn't tag, so it defaults to latest). 

Should we simply remove `imagePullPolicy`? It'll default to `Always` when using `latest` tag, and `IfNotPresent` when image is properly tagged.

##### **Motivation for or Use Case**

Redeployment of development `latest` images is hard w/ `IfNotPresent`

##### **Reproduce the error**

1. Run `jhipster kubernetes`

##### **Suggest a Fix**

Remove `imagePullPolicy: ...` line from deployment template.

##### **Browsers and Operating System**

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by saturnism** [comment]
I think this was done for minikube use case, where image may be built directly in minikube's docker daemon, so it shouldn't repull.

**Comment by eosimosu** [comment]
The isn't really an issue ... The generated deployment files are meant to be a template/starting point so just change it to whatever suits.

**Comment by mraible** [comment]
Whatever works best out-of-the-box with minikube is the option I support.

**Comment by PierreBesson** [comment]
This was already talked about a year ago https://github.com/jhipster/generator-jhipster/issues/5172. I think I had actually implemented a solution to add the proper docker tag when packaging images but @pascalgrimaud rolled back my change :smile: because it was less stable. However I would be ready to do this again. Basically we should tag docker images with latest + build version (defined in maven/gradle) + git version (git-describe).
Then when generating kubernetes/docker-compose files we should fill in the version corresponding to the current sources of the app (this can be read from places like `target/docker-info.jar`).

**Comment by saturnism** [comment]
i've been trying to find a good balance here as well. Thinking through the use cases:

If minikube:
1. use docker daemon in minikube
1. no push required, and if we don't set `imagePullPolicy`, the latest tag should still work

If on cloud:
1. use local docker daemon
1. push to registry
1. if we don't set `imagePullPolicy`, the latest tag should still work since it'll default `imagePullPolicy` to `always`

For [my project](https://github.com/saturnism/spring-petclinic-gcp/blob/master/pom.xml), I try to always build w/ a tag, but also tagging the latest build as `latest` for convenience. I use `git-commit-id` plugin. I do recommend this one as well, since the build info can be picked up by Spring Actuator, and also works w/ GCP's Cloud Debugger agent :)

**Comment by xetys** [comment]
Just my fifty cents on this, as I'm operating a JHipster microservice architecture with about 30 unique services, replicating to over 100 instances of I sum up from all clusters. 

I'm doing it like @saturnism told, forcing CI to make a unique tag for all relevant builds. With relevant I mean master and tag pushes. 

As I'm using gradle, I built 2 simple tasks printing out the projects version. The version string is usually 0.0.1-SNAPSHOT and the second task replaces that to 0.0.1-RELEASE. whenever a push on a master branch happens, I build a new latest image and do a tag on project:0.0.1-SNAPSHOT-${CI_COMMIT_SHA:0:8} and push it to the registry. If I then tag the project in git, The pipeline makes a new stable image and it corresponding release tag. So for convenience I always can pull the latest or the stable image instead of the version numbers. 

I'm doing all that using GitLab and it's CI. As of using Netflix stack, we don't really need the kubernetes advanced functions on service discovery etc, so we all develop using docker compose and not minikube. So when on kubernetes, the default configuration of the yaml files perfectly fit or versioning strategy

**Comment by PierreBesson** [comment]
I have added support for tagging the docker image created with maven in https://github.com/jhipster/generator-jhipster/pull/7734 and yes @saturnism it is using the git-commit-id plugin that I have added to jhipster a few months back 😄.

After thinking about it I think we can safely remove the `imagePullPolicy`from our k8s deployments as it really depends on how people are using kubernetes and the default seems OK. If nobody object then @saturnism please go ahead and remove it in your PR.
