### ISSUE TITLE
Feature Request - Cassandra with ELasticsearch 

### ISSUE THREAD

**Issue by JinnaBalu** [jhipster/generator-jhipster#7733]
##### **Overview of the feature request**
Suppoting Cassandra with Elasticsearch will be more usefull for the the products to have NoSQL databases with Indexing

##### **Motivation for or Use Case**

Elasticsearch and cassandra allows distributed, masterless, peer-peer communication between node, provides fault tolerance. Both support Nested Documents

##### **Related issues or PR**

[#7732](https://github.com/jhipster/generator-jhipster/issues/7732)
- [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
That would be a huge work and I don't think anybody is interested in doing this (and I'm definitely not interested in maintaining it). I did a lot of work to have Cassandra support, but the option isn't popular at all, unfortunately.

**Comment by pascalgrimaud** [comment]
You could have a look to this project https://github.com/strapdata/elassandra with near 1000 stars, you'll see there are a lot of work to do, for integrating Elasticsearch+Cassandra to JHipster.

You could create a module too, have a look at: https://www.jhipster.tech/modules/creating-a-module/ but not sure it will be popular.

As Cassandra is not a popular option in JHipster, I don't think we will add support for Elasticsearch + Cassandra: that's why I'm closing this ticket.
But we can still discuss here.
