### ISSUE TITLE
Advise also to use `npx` in Documentation

### ISSUE THREAD

**Issue by JulioJu** [jhipster/generator-jhipster#7805]
##### **Overview of the feature request**

Actually a linux newbie can't know than `npm` doesn't need `sudo`.  

##### **Motivation for or Use Case**

@MathieuAA you said it's a well-known issue at https://github.com/jhipster/generator-jhipster/issues/7775#issuecomment-398070474… But in my University all teachers and students believe that `npm` needs sudo. And as `npm` has a very bad reputation (that's why `yarn` was borned) we havn't looked an other solution… Each time we asked to the admin sys to install npm package globally ! 

At https://www.jhipster.tech/installation/ we could advise to use `npx` like https://reactjs.org/docs/add-react-to-a-new-app.html..

In CONTRIBUTE.md we could add a link to https://docs.npmjs.com/getting-started/fixing-npm-permissions. In https://github.com/jhipster/generator-jhipster/issues/7775#issuecomment-398070474, @MathieuAA, I suppose you reference that?

If you are ok, I could make the PR ;-). 

- [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
@JulioJu NPM doesnt always need sudo, it depends on your machine config. I understand shared PCs on university and stuff might have problems. Yes indeed you can do a PR to add more docs about this, buit dont change existing instruction for NPM, just add on saying if you cant use NPM due to such issues NPX might be an option. Ping me once you do a PR for review

**Comment by deepu105** [comment]
I'm closing the issue as its really not needed to be open, just do the PR thats ok
