### ISSUE TITLE
WebSocket support in (non-gateway) microservice

### ISSUE THREAD

**Issue by AlexandreCassagne** [jhipster/generator-jhipster#7838]
##### **Overview of the feature request**

WebSocket support in (non-gateway) microservice. At the moment, it seems that Zuul is stripping the Upgrade/Connection headers after being relayed by the gateway.

##### **Motivation for or Use Case**
Implementation of a feature that requires Websocket. 
In keeping with the microservice architecture, I do not believe it would be right for the gateway to serve the feature.

At the moment, I am using the gateway to server the Websockets, meaning my microservice which performs the logic is calling the gateway (via feign requests). However this is unclean, inefficient and, indeed, may –and sometimes does– time out.

##### **Related issues or PR**
Zuul does not support web socket (Zuul 2 should eventually; see #7665, though the current release does not support that). Perhaps in the meantime, a filter on the gateway could be used to force propagation? I am not sure what the best method would be at this point.

- [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by AlexandreCassagne** [comment]
```
2018-06-22 17:03:22.789 ERROR 30423 --- [  XNIO-2 task-2] c.n.b.f.config.WebsocketConfiguration$1  : Handshake failed due to invalid Connection header [Keep-Alive]
2018-06-22 17:03:22.795 DEBUG 30423 --- [  XNIO-2 task-2] c.n.b.f.config.WebsocketConfiguration    : Post-handshake ExceptionWebSocketHandlerDecorator [delegate=LoggingWebSocketHandlerDecorator [delegate=SubProtocolWebSocketHandler[StompSubProtocolHandler[v10.stomp, v11.stomp, v12.stomp]]]] org.springframework.http.server.ServletServerHttpRequest@2415786f org.springframework.http.server.ServletServerHttpResponse@56c28aba 
```

Above is the log in the microservice receiving incorrect headers. Refactoring this code to the gateway works perfectly.

**Comment by jdubois** [comment]
As you say, this isn't supported by Zuul for the moment, so we're basically stuck.

Anyway, I'm not sure it would be a good idea to have a Websocket opened that goes from through the gateway, in terms of network issues and efficiency. I'm usually using Kafka to send messages between my microservices and my gateway, and then the gateway is the only one doing Websockets. I'm pretty sure this scales better, with less issues.

Another solution, which I haven't tested, is to replace Zuul by another solution like Traefik (which is supported since something like 1 year) or Istio (inital support has just been merged).

I'm closing this as with Zuul 1, there is just no solution at the moment.

**Comment by PierreBesson** [comment]
I think our best bet to achieve that would be to use Spring Cloud Gateway which advertise websocket support. But we would still need to run some tests to see if performance is acceptable.
