### ISSUE TITLE
Better naming strategy 

### ISSUE THREAD

**Issue by ludoo0d0a** [jhipster/generator-jhipster#7974]
##### **Overview of the feature request**

I used a lot [generator-jhipster-db-helper](https://github.com/bastienmichaux/generator-jhipster-db-helper) project, plus a few personal scripts, to help me to map **existing database schema** on JDL or json entities (and then java entities).
Since the project [won't be maintained anymore](https://github.com/bastienmichaux/generator-jhipster-db-helper/issues/59) - and I understand the reason because it could be difficult to maintain a such parallel plugin compliant with all jhipster evolutions, I hope that JDL could be extended; or at least a way to set a custom naming strategy.
I remember seeing this in a few discussion (but don't remember where anymore).

### Idea 1)
Main first idea is to plug a simple naming strategy.
[The one in place](https://github.com/jhipster/generator-jhipster/blob/8af14a7893b6db0eed868643f1df91017df0a2ef/generators/entity/index.js#L548) actually could be provided as default. And a user could replace it with its own external strategy. 
The actual entity generation relies on a compatibility with spring naming strategy (and not Hibernate naming strategy), but this solution could be used (only needed on server part) to define clearly the rules to map names.

### Idea 2)
Like dbhelper did, integrate new fields in JSON entities files, to set table and column name. It does not rely on naming strategy anymore. Up to json entities author to set its own proper values.

### Idea 3)
Extend JDL language to support this db table and column names (and may be more like sequence or identity)...  

##### **Motivation for or Use Case**

We could plug a jhispter project against existing database ; and allow more customization around db schema.
Integration with blueprint could be easier.

**Comment by pascalgrimaud** [comment]
The project [generator-jhipster-db-helper](https://github.com/bastienmichaux/generator-jhipster-db-helper] is perfectly what you need and did the job. Unfortunately, you said the project won't be maintained because of lack of time by the authors.

I saw the ticket https://github.com/bastienmichaux/generator-jhipster-db-helper/issues/59 and it should be very easy to fix it, as it is related to a path which has been changed in JHipster 5 -> why don't you try to fix it directly as asked by the author ? Why don't you help them if you needed this ?

I'm a bit reluctant to add this to the main generator-jhipster as it will provided a lot of additional work for our team. But I'm not the expert on this part, that's why it is just my opinion.

**Comment by ludoo0d0a** [comment]
I understand your point of view. but a simple fix in this helper implies a lot of tests for a lot of scenarii + compatibility with previous version should be kept. 
I see this as : "the fluttering of a butterfly's wings can unleash a storm"

And this ticket is just one amongst other limitations.
The idea was to treat the problem at is source.

**Comment by deepu105** [comment]
@pascalgrimaud is right. I have worked with this part of the generator a lot initially and really complex to maintain, so I wouldn't be interested in making it even more complex at this point.

**Comment by deepu105** [comment]
@ludoo0d0a to add on to it, JHipster was never meant to be used with existing DB, and hence for the core team, this is not reasonable as it adds a lot of maintenance hell. Adding column names alone via JDL might be doable(only via JDL not via entity generator) so if you are willing to contribute that part then maybe we could consider it. Then you would have to convince @MathieuAA to add support for this or contribute that as well

**Comment by gmarziou** [comment]
Column names in JDL would help also users who are forced to use naming conventions defined by DBAs even for greenfield projects.

**Comment by pascalgrimaud** [comment]
@gmarziou : do you suggest adding the table-name option to JDL ?
https://github.com/jhipster/generator-jhipster/blob/master/generators/entity/index.js#L51

**Comment by deepu105** [comment]
Table name is already supported by JDL, the suggestion is to add colum names

**Comment by xsalefter** [comment]
@ludoo0d0a another alternative is you fork the generator-jhipster-db-helper and make change for your own project and to support JHipster 5+. Even better, contact the original project owner to add link to your project in readme with words like, " .... if you need use this in JHipster 5+ project, use <link_to_your_project_name> instead .... ".

**Comment by jdubois** [comment]
I'm not sure if that's so complex to change in JHipster - I'm the one who originally coded that, but it was a long time ago. Reading @pascalgrimaud @deepu105 and @AdrienHorgnies it looks everybody agrees this would be very complex, and that it's probably easier for you to fix generator-jhipster-db-helper.

Anyway: I'm very, very happy that something like generator-jhipster-db-helper could be done, as this has never been the goal of the project. It's very clever, and I understand it's very useful for a lot of people. Then the main project also has to keep its focus: we're generating a new project, using our naming conventions, as it's much easier for us to do it this way. Then, it's not that hard to customize it to your needs, for example if you have annoying DBAs.

I'm closing this as for me this is going out of our core focus, but also because it looks like it's a lot of work ( @AdrienHorgnies says "it would be hell to make"). I would need more time to study how difficult this is, but I believe he knows that part better than me, now!
