### ISSUE TITLE
Server side tests failures when running all the tests together

### ISSUE THREAD

**Issue by Akuka** [jhipster/generator-jhipster#8099]
##### **Overview of the issue**

Hello,
I have a working application (Monolitic) which is currently based on JHipster 4.14.5.
I tried to generate the same application with the entities (without my custom logic) with JHipster 5.1.0 (and also 5.2.0) and got 'BUILD FAILURE' on the server side (tests failure)

Im not sure this is a bug in the tests or a real bug, but if Im running all the tests together some of them failed, but if Im running those failed test alone they are green.

I think its related somehow to the fact that I have two ManyToOne relationships. 

```
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BookResourceIntTest.createBook:113 Status expected:<201> but was:<400>
[ERROR]   BookResourceIntTest.updateBook:213 Status expected:<200> but was:<400>
[INFO] 
[ERROR] Tests run: 153, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
##### **Motivation for or Use Case**

Upgrade to JHipster 5

##### **Reproduce the error**

1. Generate application (--with-entities) with the following information I provided by ``jhispter info``
2. Run ``./mvnw clean test``

##### **JHipster Version(s)**

5.1.0
5.2.0

##### **JHipster configuration**

→ jhipster info
Using JHipster version installed locally in current project's node_modules
Executing jhipster:info
Options: 
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
myapp@0.0.0 /Users/akuka/dev/jhipster/core_five_two_from_scratch
└── generator-jhipster@5.2.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.2.0",
    "applicationType": "monolith",
    "baseName": "myapp",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": false,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "mysql",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "clientFramework": "angularX",
    "useSass": false,
    "clientPackageManager": "yarn",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity Author {
  firstName String required maxlength(63)
}
entity Book {
  title String required maxlength(63)
}
entity Award {
  auditDate ZonedDateTime required,
  comment String required maxlength(63)
}
relationship OneToMany {
  Author{book} to Book{author(firstName) required},
  Author{award} to Award{author(firstName) required}
}

paginate Author, Book, Award with pagination
service Author, Book, Award with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

git version 2.15.2 (Apple Git-101.1)

node: v8.11.3

npm: 5.6.0

yeoman: 2.0.5

yarn: 1.9.4

Docker version 18.06.0-ce, build 0ffa825

docker-compose version 1.22.0, build f46880f

Congratulations, JHipster execution is complete!

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

JDL:
```
LABEL_MAX = 63

entity Author {
    FirstName String required maxlength(LABEL_MAX)
}

entity Book {
    Title String required maxlength(LABEL_MAX)
}

relationship ManyToOne {
    Book{author(firstName) required} to Author{book}
}

entity Award {
    AuditDate ZonedDateTime required,
    Comment String required maxlength(LABEL_MAX)
}

relationship ManyToOne {
    Award{author(firstName) required} to Author{award}
}

service all with serviceClass
paginate all with pagination
```

##### **Browsers and Operating System**

Mac OS X
- [V] Checking this box is mandatory (this is just to show you read everything)

**Comment by PierreBesson** [comment]
@Akuka Does the issue arise only because you are doing an upgrade or are you able to reproduce it on a newly geneated app ?

If it is only linked to the upgrade, I don't think we can justify investing the team time on this issue as upgrade problems can be overly complex and specific (and most of the time caused by the user's custom code).

**Comment by Akuka** [comment]
Newly generated app

**Comment by Akuka** [comment]
@PierreBesson Please remove the 'upgrade' tag, as this issue is not related to upgrade, but for newly generated app

**Comment by jdubois** [comment]
I confirm the issue

**Comment by jdubois** [comment]
Oh, it fails when you run all the tests, but works if you only run the failing tests!!

**Comment by jdubois** [comment]
I just can't find what "pollutes" the test. There should be something running before `BookResourceIntTest` that causes the issue, but I have no idea what.
Definitely a very interesting bug, but I'm giving up at the moment.

**Comment by duderoot** [comment]
I was able to narow down to the following facts:

- all the tests are passing when running them over IntelliJ run all test in folder
- when executing over mvn `mvn -Dtest=AwardResourceIntTest,BookResourceIntTest
` the test are failling
- maven will log the following:

`  INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 174.501 s - in com.mycompany.myapp.web.rest.AwardResourceIntTest
[INFO] Running com.mycompany.myapp.web.rest.BookResourceIntTest
2018-08-25 01:15:55.039  WARN 47941 --- [           main] o.z.p.spring.web.advice.AdviceTrait      : Bad Request: JSON parse error: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.mycompany.myapp.domain.Book["author"]->com.mycompany.myapp.domain.Author["awards"])
2018-08-25 01:15:55.142  WARN 47941 --- [           main] o.z.p.spring.web.advice.AdviceTrait      : Bad Request: JSON parse error: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.mycompany.myapp.domain.Book["author"]->com.mycompany.myapp.domain.Author["awards"])
2018-08-25 01:15:55.500  WARN 47941 --- [           main] o.z.p.spring.web.advice.AdviceTrait      : Bad Request: JSON parse error: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.mycompany.myapp.domain.Book["author"]->com.mycompany.myapp.domain.Author["awards"])
2018-08-25 01:15:56.647  WARN 47941 --- [           main] o.z.p.spring.web.advice.AdviceTrait      : Bad Request: JSON parse error: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.mycompany.myapp.domain.Book["author"]->com.mycompany.myapp.domain.Author["awards"])
2018-08-25 01:16:01.085  WARN 47941 --- [           main] o.z.p.spring.web.advice.AdviceTrait      : Bad Request: JSON parse error: (was java.lang.NullPointerException); nested exception is com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: com.mycompany.myapp.domain.Book["author"]->com.mycompany.myapp.domain.Author["awards"])
[ERROR] Tests run: 10, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 15.787 s <<< FAILURE! - in com.mycompany.myapp.web.rest.BookResourceIntTest
[ERROR] updateBook(com.mycompany.myapp.web.rest.BookResourceIntTest)  Time elapsed: 0.974 s  <<< FAILURE!
java.lang.AssertionError: Status expected:<200> but was:<400>
        at com.mycompany.myapp.web.rest.BookResourceIntTest.updateBook(BookResourceIntTest.java:213)

[ERROR] createBook(com.mycompany.myapp.web.rest.BookResourceIntTest)  Time elapsed: 4.337 s  <<< FAILURE!
java.lang.AssertionError: Status expected:<201> but was:<400>
        at com.mycompany.myapp.web.rest.BookResourceIntTest.createBook(BookResourceIntTest.java:113)

2018-08-25 01:16:01.912  WARN 47941 --- [       Thread-6] o.s.b.f.support.DisposableBeanAdapter    : Invocation of destroy method failed on bean with name 'inMemoryDatabaseShutdownExecutor': org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-197]
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   BookResourceIntTest.createBook:113 Status expected:<201> but was:<400>
[ERROR]   BookResourceIntTest.updateBook:213 Status expected:<200> but was:<400>
[INFO] 
[ERROR] Tests run: 21, Failures: 2, Errors: 0, Skipped: 0

`

**Comment by duderoot** [comment]
In Germany there is a saying : 

> who can read, is clearly at an advantage (wer lesen kann, ist klar im Vorteil). 

Not always, but this time the logs told the truth 😃 : the JSON could not parse the Book JSON payload. The JSON parser it was waiting trough Author for awards.
Solution of the test is just to add in the entity Book the JSON properties that need to be ignored i.e. instead of
`@JsonIgnoreProperties("books")
    private Author author;`
one should put
`@JsonIgnoreProperties({"books", "awards"})
    private Author author;`
I will have a look to provide a PR fo the generator.

**Comment by jdubois** [comment]
Thanks a lot @duderoot 

In fact we are ignoring the one-to-many property to avoid to have circular references, which would just break. So in JSON format, a book has an author, but you don't "see" that the author has many books. Otherwise we would just run in circle until the server breaks.

But you have an interesting use case here, as there is the same issue with awards: an award has an author, but you don't "see" that the author has many awards, to avoid the same circular reference.

And now for the tricky part: with those 2 one-to-many relationships, you still end up with a circular reference. A book has an author, who has several awards which have one author which have several books, which have one author, etc etc... So I'm afraid we have a bug here! And not an easy one to solve. I don't understand we only find out about this now.

**Comment by jdubois** [comment]
Thanks @duderoot this is very helpful, this ticket is really hard!

**Comment by jdubois** [comment]
Got it. Let me do the fix.

**Comment by jdubois** [comment]
Reopened as the fix was reverted, it caused other issues!

**Comment by duderoot** [comment]
@jdubois I am glad that you manged to find a quick fix. Nonetheless, I have a question: do you know why in the Book entity  @JsonIgnoreProperties only one property of entity Author has and not bout:

```
@ManyToOne(optional = false)
@NotNull
@JsonIgnoreProperties("books")
private Author author;
```


Is a reason why only one  property of the [otherEntityRelationshipNamePlural](https://github.com/jhipster/generator-jhipster/blob/master/generators/entity-server/templates/src/main/java/package/domain/Entity.java.ejs#L243) is added to JsonIgnoreProperties. In order to be consistent with the model we should have 

```@ManyToOne(optional = false)
@NotNull
@JsonIgnoreProperties({"books", "awards"})
private Author author;
```

Or I miss something? I see that this change was introduced in #6793 
@Dufgui  and @ruddell  can you give me some hints on this? 10x

**Comment by ruddell** [comment]
@duderoot The purpose of that annotation is to prevent infinite recursion when mapping the entity to JSON (so a `Book` maps the `Author` to JSON excluding the `books` field, otherwise you get a stack overflow error).  

The `Award` entity isn't added to the annotation because there's no connection between `Book` and `Award`.  Plus, when fetching a `Book`, the `Award` field of `Author` is not (eagerly) loaded so there's no issue other than an empty attribute in the response.

I'm not sure how you would get the list of the related entity's relationships other than parsing the related entity's JSON file and looping through the relationships, which could be an issue depending on which order you generate the entities.

**Comment by duderoot** [comment]
@ruddell thank you for the explication. I was/am not quite aware on how loading with regard to lazy loading of relations is controlled. I understand now the issue that can arise because of the order of the generated entities.
