### ISSUE TITLE
Generate a self-signed SSL certificate for developement

### ISSUE THREAD

**Issue by jdubois** [jhipster/generator-jhipster#8134]
This has been discussed with @PierreBesson - we should generate a self-signed certificate by default, so we can help people use SSL (and HTTP/2) in development.

As I just saw we already did that for UAA, I'm going to generalize that code. Please note it won't be perfect yet, as it will also need to be configured for Webpack and BrowserSync.

**Comment by jdubois** [comment]
Update, here is how to do it with Webpack dev server:

```
proxy: [{
            context: [
                /* jhipster-needle-add-entity-to-webpack - JHipster will add entity api paths here */
                '/api',
                '/management',
                '/swagger-resources',
                '/v2/api-docs',
                '/h2-console',
                '/auth'
            ],
            target: 'https://127.0.0.1:8080',
            secure: false,
            changeOrigin: true,
            headers: { host: 'localhost:9000' }
        }]
```

To be more precise, you need to use https in the `target`, and add `changeOrigin: true`. Then Webpack dev server uses unencrypted HTTP, so that also works with BrowserSync (it's the same for BrowserSync, in the end).

I'm not going to configure this now, as that means we would need to have HTTPS by default, and at the moment I'm just helping people configure it.

**Comment by PierreBesson** [comment]
@jdubois, Some tools like Mkcert (https://github.com/FiloSottile/mkcert) are able to automatically import the certificate in the browser. That would be super cool to have.

I had the idea of creating an ssl spring profile to start the server in "ssl mode" (I have the code somewhere on my machine). We could create a specific `yarn start-ssl` for the frontend as well.

On the keystore generation code, will this keystore be commited to the sources ? It doesn't seem like a good idea to share this outside your local machine as it contains the private key to a trusted certificate.
And maybe it should be named devkeystore so that people don't confuse it with their prod keystore. Also maybe we should name the folder `config/tls` because SSL is the name of the old protocol.

**Comment by jdubois** [comment]
@PierreBesson  as this is just a dev certificate, which is not validated by a third party (it is only self-signed), I don't think there could be a security risk in storing this into the app, but maybe some users will find that what we do is a great idea and will replace it with a real certificate... I'm not sure about that. Do you think there is another, higher risk?

And for TLS you are right, I just renamed it in https://github.com/jhipster/generator-jhipster/commit/4184304ddc5f04beb0adebe7aa8f70c545b23608
