### ISSUE TITLE
Administration dashboards for consul

### ISSUE THREAD

**Issue by blling** [jhipster/generator-jhipster#8153]
`jhipster-registry` has `Administration dashboards`, but consul do not, is there any plan to add `Administration dashboards` for consul ?

**Comment by jdubois** [comment]
No, we can't do our own fork of Consul.
As Consul users are "advanced" users, you might be more interested by the JHipster Console. It's not exactly the same thing, but for monitoring it's much more powerful.
Otherwise you can still use the JHipster Registry in parallel to Consul. It won't be used for service discovery, but the rest should work.
