### ISSUE TITLE
How to config to use jsp in jhipster?

### ISSUE THREAD

**Issue by blling** [jhipster/generator-jhipster#8316]
I have searched a lot, but not find the answer, any one know how to config to use jsp in jhipster?

**Comment by jdubois** [comment]
That's normal, it's just not possible by default. JSP are not supported in Undertow. You would need to migrate to Tomcat instead (it's probably not that hard), and after that it should probably work.
As far as I know JSP isn't pushed by Oracle anymore since a long time: it's not really deprecated, but I don't think it's even in the latest docs anymore.
And for this kind of feature, JHipster uses Thymeleaf: it's documented and works very well, and I believe it is a far superior technology, that I of course recommend.
