### ISSUE TITLE
How to test resources with security context

### ISSUE THREAD

**Issue by c0nscience** [jhipster/generator-jhipster#835]
Hi JHipster Team,

I wonder how can I test my resources, where I use the SecurityUtils to get the logged in user. I thought the easiest way might be to mock the static method `SecurityUtils.getCurrentLogin()`, but for that I need PowerMock wich uses an own junit runner to preparing the bytecode and there I get stuck, because I can't use two runners.

Any toughts on that how to solve this problem?

**Comment by andredebuisne** [comment]
Hi! I just had this issue and I used:
`@WithMockUser(username="user@localhost",authorities={"ROLE_USR"}, password = "user")`
You can place this annotation on a specific test or a class of tests, so that all tests benefit from this MockUser! 
Then all my Ressources using `SecurityUtils.getCurrentLogin()` work, the user is found with all of his information.
