### ISSUE TITLE
[documentation] Update liquibase documentation for Gradle

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#8350]
##### **Overview of the issue**

The [documentation](https://www.jhipster.tech/development/#using-a-database) currently says:

If you use Gradle instead of Maven, you can use the same workflow by running `./gradlew liquibaseDiffChangelog`, and change the database configuration in `liquibase.gradle` if required.

The `liquibase.gradle` file doesn't exist anymore. I believe the command should be `./gradlew generateChangeLog`.

##### **Motivation for or Use Case**

Because I'm updating the JHipster mini-book and this seems like outdated documentation.

**Comment by atomfrede** [comment]
@mraible Oh yes, I forgot. Will update it hopefully today.

**Comment by mjj55409** [comment]
It's not clear what is the new process for updating the database using liquibase and gradle.

Running `./gradlew liquibaseDiffChangeLog` complains that `referenceUrl` is missing, because as pointed out above, `liquibase.gradle` no longer exists.

Running `./gradlew liquibaseGenerateChangeLog` complains that `liquibase/master.xml` already exists.

How do you now generate change logs with liquibase?

**Comment by atomfrede** [comment]
I will update the documentation during the weekend. But in short, you need to provide a runlist as the plugin just proxies commands to the liquibase cli. When you give the cli a parameter that is not allowed for that specific command (e.g. referenceUrl for validate) it will fail. 

So try `gradlew liquibaseDiffChangelog -PrunList=diffLog` to create a difflog.
