### ISSUE TITLE
import org.zalando.problem.validation.ConstraintViolationProblemModule

### ISSUE THREAD

**Issue by jiangzhixiao** [jhipster/generator-jhipster#8357]
jhipster verstion:5.3.1
In  JacksonConfiguration,the generated import has wrong path???

![image](https://user-images.githubusercontent.com/7273487/45660585-06182180-bb2c-11e8-9915-82d1e29a9bef.png)

**Comment by ruddell** [comment]
This is fixed in the latest release ([code](https://github.com/jhipster/generator-jhipster/blob/70c0551b6ae1fa97907201bf70fa552cb8d3a2c6/generators/server/templates/src/main/java/package/config/JacksonConfiguration.java.ejs#L31)).  In the future please follow the issue template.

Related issue here https://github.com/jhipster/generator-jhipster/issues/8349

**Comment by jiangzhixiao** [comment]
@ruddell ok.thanks
