### ISSUE TITLE
Make PostgreSQL the default in JHipster 6

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster#8384]
Because it’s awesome and we know it.

http://www.craigkerstiens.com/2018/09/20/postgresql-11-a-first-look/

**Comment by atomfrede** [comment]
+1 Maybe we can also get rid of dev/production separation. We use testcontainers already for e.g. couchbase, why not use it postgres etc. too? We already rely a lot on docker(compose) so it is not a big problem imho.

**Comment by deepu105** [comment]
We could but only problem is then in dev you need one more step to start
the app. Also h2 is much better when you are prototyping something and want
to recreate db all the time.

**Comment by atomfrede** [comment]
That's right. We should gather some statistics how many choose same production and development databases.

**Comment by agoncal** [comment]
@deepu105 I like the idea of @atomfrede to gather some statistics. In the past I had so many issues with having different DBs in dev/prod that now I always use Postgres in dev/prod (much easier now with containers)

**Comment by atomfrede** [comment]
And if we use test containers for unit tests we have the same experience as before except removing/clearing data during development. But I am sure we can e.g. always reset the date in dev profile for example or provide a special flag when starting the application.

**Comment by sendilkumarn** [comment]
@atomfrede with `h2` as a default option, I think that will win hands down 👍 

But I agree with @deepu105 here that we need to have `h2` to make sure that in `prototyping` it is always a single step to get started

**Comment by jdubois** [comment]
For production -> I think we all agree here. I'm closing this as there's no need to keep the ticket opened for months, just to remember this. Let's use the "v6" tag as @deepu105 did, and we'll need to read the issues when we start v6 (maybe next spring?)
For dev I'm quite happy with H2, at least it provides a great "out of the box" experience for developers, which is our #1 goal. Then, we can't expect everyone to have Docker - most of my customers, including those speaking at lot about Docker in conferences and in the press, can't use Docker on their dev machines as they are locked, and with old Windows versions. So that's just not possible at the moment.
