### ISSUE TITLE
Use Helm templates for Infrastructure instead of our templates

### ISSUE THREAD

**Issue by deepu105** [jhipster/generator-jhipster#8592]
Currently, we create and maintain Kubernetes manifest templates for Databases, ELK, Keykloak and so on. The problem with that is we don't have the bandwidth to keep up with upstream changes and end up with outdated config often, happened with MongoDB config recently and our ELK is flaky as well.

I had a discussion with @srinivasa-vasu yesterday and he proposed to use [Helm](https://helm.sh/) charts instead of our templates for those as those are more stable and maintained. 

Pros:

- We don't have to maintain those templates
- Always updated
- More stable

Cons:

- Means users will have to install Helm along with Kubectl (we can document this and I don't think its a big deal as they already have to install Kubectl, gcloud etc)

@saturnism @PierreBesson @jdubois @pascalgrimaud WDYT?

**Comment by deepu105** [comment]
@jhipster/developers please :+1: or :-1: on the issue description

**Comment by deepu105** [comment]
I think @srinivasa-vasu's idea was to generate the infra manifests using Helm CLI when JHipster Kubernetes sub gen is run, so user will get the final output(plain yaml files) so for end users it will be same as today

@srinivasa-vasu correct me if i'm wrong

**Comment by srinivasa-vasu** [comment]
@deepu105 @PierreBesson 

Obviously, will generate proper helm chart with its recommended package structure
**Two approaches:**

1. We point database and other services like elk, prometheus to helm stable/incubator package depending on wherever it is available. Hopefully, we can pass our variable customisation to those packages as well. Those will be specified as dependent sub-charts in requirements yaml, so that they will be downloaded and composed along with our app specific generators. In this approach we can reuse the existing k8s sub-generator (with our templates), but the output will be a proper helm package.

_Pros_
- Re use of existing templates
- Minimal changes
- leverage existing k8s sub-gen

_Cons_
- Customisation won't be provided through helm as the template will be ours, but in helm structure.

2. In this, we can use our template to provide customisation through helm files (by enriching values, and charts yaml with more properties) and the actual app templates would use helm syntax, so once generated they will be able to play around with the helm files for customisation

_Pros_
- Customisation through helm

_Cons_
- More effort
- Limited reuse of our template files

**Comment by deepu105** [comment]
We really need this. I was doing a demo at Heapcon/Changecon and I have a new issue, ELK starts up fine but the Kibana dashboard doesnt find any indexes, I haven't digged into it yet

**Comment by PierreBesson** [comment]
@deepu105, this is not part of ELK, this is probably because the import-dashboard container was started before elasticsearch/kibana. You can restart the import-dashboard job manually to fix it. Anyway when I have the time, I will create an helm chart for Console reusing an external Elasticsearch helm chart (the hard to operate part of the stack).

**Comment by DanielFran** [comment]
@deepu105 @srinivasa-vasu Should we close this issue since https://github.com/jhipster/generator-jhipster/pull/8630 has been merged, or it is missing something?

**Comment by PierreBesson** [comment]
As a first step, it's ok.

**Comment by deepu105** [comment]
This needs to be documented

Thanks & Regards,
Deepu
