### ISSUE TITLE
Liquibase fails when running as a standalone spring-boot jar

### ISSUE THREAD

**Issue by gzsombor** [jhipster/generator-jhipster#860]
Steps to reproduce:
 1, create a new jhipster app, with SQL
 2, mvn install
 3, java -jar target/jhipster-0.0.1-SNAPSHOT.war

It will throw a : 
_liquibase.exception.ServiceNotFoundException: liquibase.exception.ServiceNotFoundException: Could not find implementation of liquibase.logging.Logger_

It seems, that the addLiquibaseScanPackages() method, which I guess, should solve this issue, doesnt work as expected.

**Comment by gildegoma** [comment]
I'm not sure the problem is the same as #588, because I also was bitten by this 

> liquibase.exception.ServiceNotFoundException: liquibase.exception.ServiceNotFoundException: Could not find implementation of liquibase.logging.Logger

when running with liquibase v3.1.1. I guess that the problem was still present in 3.2.x, but **upgrading** to liquibase 3.2.3 or 3.3.1 solved the problem for me.

@jdubois What about a patch for the 1.x maintenance branch that bumps liquibase to 3.3.x?

**Comment by jdubois** [comment]
@gildegoma you shouldn't have the issue on 1.x
For the v2, I'm currently working on SNAPSHOT releases of Liquibase because of other issues, but this all should be solved this week -> we'll see depending on what we get in the end

**Comment by gildegoma** [comment]
@jdubois you can reproduce the reported issue (application startup failure due to *Could not find implementation of liquibase.logging.Logger* error):

1.  create a new jhipster v1.x app, with MySQL for dev and prod (or even simpler, use https://github.com/jhipster/jhipster-sample-app/tree/v1.10.2)
1. `mvn clean install; mvn -Pprod package`
1. `java -jar target/jhipster-0.0.1-SNAPSHOT.war --spring.profiles.active=prod` (or `dev` profile)

this is easily fixed by bumping liquibase version.

**Comment by gildegoma** [comment]
@jdubois created PR #949 (could you reproduce the issue locally?)

**Comment by jdubois** [comment]
@gildegoma hang on, I'm currently testing 3.3.2-SNAPSHOT -> it also corrects some other issues, so I'd rather use 3.3.2 when it's ready

**Comment by gildegoma** [comment]
@jdubois Ah thanks, good to know!
