### ISSUE TITLE
Multiple OneToMany relationship with same entity

### ISSUE THREAD

**Issue by initfusion** [jhipster/generator-jhipster#8643]
Hi,

My requirement is to generate tables like below code 

```
class A{
 list<B> listOne;
 list<B> listTwo;
}

class B{
 int fieldOne;
 int fieldTwo;
}
```

My .jh file looks like this

```
entity A{}

entity B{
	fieldOne Integer, 
    fieldTow Integer
}

relationship OneToMany{
	A {listOne} to B,
    A {listTwo} to B,
}

```

but the generator is not able to generate proper code. there are lots of errors in code.

Thank you.

**Comment by ruddell** [comment]
Because you have two relationships to the same entity, you need to provide names on both sides (otherwise you get duplicate identifiers).

```
relationship OneToMany{
    A {listOne} to B{aOne},
    A {listTwo} to B{bOne},
}
```

In the future please follow our guidelines and post questions to StackOverflow or Gitter.

-----

This is not a **bug** or **feature request** and hence this is not the correct forum for this.
**If you have a question** please use Stack Overflow, and tag the question with [jhipster](http://stackoverflow.com/questions/tagged/jhipster). This helps the project to keep the issue tracker clean. Also, Stack Overflow will give your question a larger audience:

- This will increase your chances to get an answer
- Answers will be of higher quality, as there is a voting system
- This will also help other users who might have the same issue, as questions are tagged and easily searchable
