### ISSUE TITLE
Jhipster prod Error

### ISSUE THREAD

**Issue by andresetevejob** [jhipster/generator-jhipster#8705]
Hi All,
I have an error when i execute this command jhipster for the production :  ./mvnw -Pprod

this the error : 
[INFO] --- git-commit-id-plugin:2.2.5:revision (default) @ jhipstermono ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.324 s
[INFO] Finished at: 2018-11-01T10:20:51Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.5:revision (default) on project jhipstermono: Could not complete Mojo execution...: Error: Could not get HEAD Ref, are you sure you have some commits in the dotGitDirectory? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by andresetevejob** [comment]
Hi ,
I don't have a git repository
My Version of jhipster is 5.5

**Comment by atomfrede** [comment]
Can you please post the output of `jhipster info`? If you do a `git init` and `git commit` the build will work.

**Comment by deepu105** [comment]
@andresetevejob please follow our issue guidelines, else ticket will be closed

Tickets must follow our [Guidelines](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md), as mentioned in:

1. our [Readme file on the front page of the project](https://github.com/jhipster/generator-jhipster/blob/master/README.md),
2. the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) and
3. our [Help page](http://jhipster.github.io/help/)

We have also created a template on the ["create a new ticket" page](https://github.com/jhipster/generator-jhipster/issues/new) to help you follow those guidelines.

**If this is indeed a JHipster bug**, please open a new issue with proper details or update this issue with all details and request to reopen.
Issues opened without proper details will be closed without explanation.

**If you have a question** please use Stack Overflow, and tag the question with [jhipster](http://stackoverflow.com/questions/tagged/jhipster). This helps the project to keep the issue tracker clean. Also, Stack Overflow will give your question a larger audience:

- This will increase your chances to get an answer
- Answers will be of higher quality, as there is a voting system
- This will also help other users who might have the same issue, as questions are tagged and easily searchable

**Comment by deepu105** [comment]
If you update all required info we will reopen this

**Comment by mabliedana** [comment]
Edit pom.xml and add <failOnUnableToExtractRepoInfo>false</failOnUnableToExtractRepoInfo> in the plugin pl.project13.maven

**Comment by mabliedana** [comment]
Overview of the issue
In prod packaging, compilation failed due to this issue:
[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.6:revision (default) on project test: Could not complete Mojo execution...: Error: Could not get HEAD Ref, are you sure you have some commits in the dotGitDirectory? -> [Help 1]

It seems to be solved by adding in the pom.xml the properties <failOnUnableToExtractRepoInfo>false</failOnUnableToExtractRepoInfo> under pl.project13.maven plugin 

Reproduce the error
jhipster
./mvnw clean package -Pprod -DskipTests 
Then it does not finish the compilation and .war generation

JHipster Version(s)
6.1.0

JHipster configuration, a .yo-rc.json file generated in the root folder
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "6.1.0",
    "applicationType": "monolith",
    "baseName": "test",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "YjA0YjFjMzc0NjU3MDcwZTllMWMxMjRiMzAzZGY3ODYyYTNhYWFiZmRhNGQ1MjkwY2NlODM3NDg0MjZjN2JlNGU3NDM1ZjdiNThlM2JhYjc0YjhkN2M0M2RmYTZjOGU5YWU2NGY5MGI4ZTY5MjYxZmU2NDZjNGE4ZTY2MjgyMjc=",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}

JDL for the Entity configuration(s) entityName.json files generated in the .jhipster directory
No entities have been added


Environment and Tools

Machine
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

Java
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)


git version 2.7.4

node: v10.16.0

npm: 6.9.0

yeoman: 2.0.6

yarn: 1.16.0
