### ISSUE TITLE
Update current logged-in username is not reflecting in authentication

### ISSUE THREAD

**Issue by mgazzarm** [jhipster/generator-jhipster#8734]
##### **Overview of the issue**

The principal object contains the current login, if the logged in user changed his username, change will not be reflected in the authentication until you logout and login with the new login

##### **Motivation for or Use Case**
User login 
Auditing

##### **Reproduce the error**
If you are using @createdBy for example to log the changes and user changes his login it will not be tracked because SecurityUtils will return the login from the authentication principal 

Login with default admin User
Go to User management screen
Click Update for the admin profile
change the username
Save
The new username is not reflecting in principal

##### **Related issues**
na

##### **Suggest a Fix**
Refresh the JWT token with the new details

##### **JHipster Version(s)**
5.3.4

##### **JHipster configuration**
Default Configurations

##### **Browsers and Operating System**

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
I don't know what to say.... That's how Spring Security works, as well as all security frameworks I know. If you were checking the username all time, the performance would be horrible.

So we're using the current username of the person, and if that was changed (which is probably a bad idea, but that's indeed possible) then you have the older name (the one which is currently used, so that's not totally false).

**Comment by deepu105** [comment]
Yes its quite common, if you change login name it won't be reflected until you logout and login again. If you prefer a different behaviour you have ro customize it yourself
