### ISSUE TITLE
Merge #8596 breaks UAA authentication

### ISSUE THREAD

**Issue by brunnels** [jhipster/generator-jhipster#8761]
##### **Overview of the issue**
Login/Logout when using UAA throws null principal object error

##### **Motivation for or Use Case**
Cannot login/logout with UAA auth

##### **Reproduce the error**
Generate UAA and gateway and attempt to login
@ruddell verified

##### **Related issues**
none found

##### **Suggest a Fix**
Replacing the removed Injector and JhiEventManager provider dependencies in `app.module.ts` that were removed in https://github.com/jhipster/generator-jhipster/pull/8596 resolves the issue for me.

##### **JHipster Version(s)**
5.6.0-5.6.1

##### **JHipster configuration**
Example gateway with uaa

##### **Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**
none

##### **Browsers and Operating System**
Windows Chrome

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by fleboulch** [comment]
Hello @brunnels,
I tried to reproduce your issue with jhipster v5.6.0 but I couldn't reproduce it.

Here my several .yo-rc.json

- uaa directory
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.6.0",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "NDgyOWFjOTEzYTNhMTllNjdlMmFlMjQ4NTA3NTJlMWMwYWY1NTYwM2I4M2EwMjg0N2NhN2IzYmI4NDVkMzgzZmRkZTdhODdhMmE3YmRlMjI4NDViNDJhZTNkN2Y5ZDY5YWNmMjFkZDM2MDk2MmU1NzYyZDZhMmQ3MzE3NjAxN2M=",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "skipClient": true
  }
}
```
- ms1 directory
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.6.0",
    "applicationType": "microservice",
    "baseName": "ms1",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8081",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "ZmFmNTViN2U5MzIzMzM0YWMyNDcxM2JhZjkzZTRjZThjNWNhMDVjMmRiNTBlNjQyMjc1YTM3OTA0MDg1NmIyMzcxM2VmODY4OTA0NDYzMGFiNTJjNDM3MzI1OTIzMzA4NGVlNTI0MzEwMGMxMWUyYmVlZDRmYjU0NGYxMzc5Yjg=",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false,
    "clientPackageManager": "npm",
    "skipClient": true,
    "skipUserManagement": true
  }
}
```
- gateway directory
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp"
    },
    "jhipsterVersion": "5.6.0",
    "applicationType": "gateway",
    "baseName": "gateway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": false
  }
}
```
Here a screenshot of my JHipster Registry with both instances up
![gateway-rework](https://user-images.githubusercontent.com/9569081/48100509-dd570300-e223-11e8-8e17-f753ca191238.png)

Login working on localhost:8080
![gateway-8080](https://user-images.githubusercontent.com/9569081/48100701-a1706d80-e224-11e8-885c-18a425bf37e0.png)

Could you give more information/details (e.g: .yo-rc.json) on your issue in order to help to reproduce please?

**Comment by ruddell** [comment]
@fleboulch It only fails when translation is enabled.  Here's my UAA and gateway `.yo-rc.json` files (same as yours except the translation):

#### UAA
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.6.1",
    "applicationType": "uaa",
    "baseName": "uaa",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "9999",
    "authenticationType": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "Y2NlMzg5YjA2ZjMwZDM5NzA4ZTlmYTg3Yzg5Y2E0MjRlYzE0ZDY0YzhhODNmMGIyMzhmYTM5NGU2Y2ViMTlkMmVmMDlhZDRhY2RlOGRkZDA2ZTkxMTEwZDRmZjg3OWJiN2Y4NTQwMjk5NTM1YzFhZWYwZWYwYzU0MzJkM2E2NGE=",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "en",
    "languages": [
      "en"
    ],
    "skipClient": true
  }
}
```
#### Gateway
```
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "com.mycompany.myapp",
      "nativeLanguage": "en"
    },
    "jhipsterVersion": "5.6.1",
    "applicationType": "gateway",
    "baseName": "gway",
    "packageName": "com.mycompany.myapp",
    "packageFolder": "com/mycompany/myapp",
    "serverPort": "8080",
    "authenticationType": "uaa",
    "uaaBaseName": "uaa",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "useSass": true,
    "clientPackageManager": "npm",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "enableTranslation": true,
    "nativeLanguage": "en",
    "languages": [
      "en"
    ]
  }
}
```

**Comment by brunnels** [comment]
I had translation enabled too so that tracks.

**Comment by fleboulch** [comment]
Ok, I will have a deeper look into it.

**Comment by fleboulch** [comment]
I generated a gateway project with `"enableTranslation": false` on a master `branch`. The login/logout is working fine as previously mentioned.
Then I re-generated this project with `"enableTranslation": true` on an `enable-i18n` branch. The login/logout is failing.

Here is my PR showing the diffs between the two branches: https://github.com/fleboulch/gateway-no-i18n/pull/1/files.

I can't figure out what is causing this issue. Maybe someone else will have any clue to fix it

**Comment by ruddell** [comment]
@fleboulch Here's a smaller diff showing just the files that cause this issue https://github.com/ruddell/jhipster-examples/commit/6051760f3e2984c8c114eec3e57fceb16961396d, the error logged to the browser console is `ERROR TypeError: Cannot read property 'identity' of undefined`

**Comment by fleboulch** [comment]
@ruddell I got the same error as you in my Chrome console.

There is a smaller diff which explains this issue caused by #8596. This is only due to the `auth-expired.interceptor.ts` file. But this is not the root cause.

Indeed there is another error on browser refresh:  
`GET http://localhost:8080/uaa/api/account 401 (Unauthorized)`. This 401 error with the `AuthExpiredInterceptor` will logout **all the time** the user. This new behaviour is a side effect of the #8596 but I didn't think it will be a problem.

In v5.5.0 and previous versions
- We manually injected angular services. The error could appear before the service was properly injected and at this time the error will be lost.

In v5.6.0+
- We can be sure all needed services will be up before been used, as we rely on angular DI (@Injectable() )

**Comment by ivan86to** [comment]
Hi, I have the same problem. Does anyone have a solution even temporarily?

**Comment by feverdog** [comment]
> Hi, I have the same problem. Does anyone have a solution even temporarily?

Yes, probably it is not the best, but finding the files on the diff I have provided below and and rolling them back works fine for me.

Here's the link:
https://github.com/ruddell/jhipster-examples/commit/6051760f3e2984c8c114eec3e57fceb16961396d?diff=split#diff-c489e39e9c292cf2a461c4d76534e2bf

**Comment by carrotagileit** [comment]
I have the same problem, too.

**Comment by xetys** [comment]
update on this one: the root cause is DI Problem. The principal service is not getting injected at all, as it doesn't resolve `JhiLanguageService`, so also `Principal` isn't resolved, so also the Interceptor and much more stuff get affected.

One quick workaround is to remove `JhiLanguageService` as a dependency in `principal.service.ts`

Still investigating

**Comment by xetys** [comment]
ok after further investigating I can summarize the issue. It is somewhere in the Angular DI.

The interesting parts are: `Principal` < `JhiLanguageService`

This dependency has two paths:

... > `LoginService` > `Principal`
app > `AuthExpiredInterceptor` > `Principal`

The second path doesn't inject the language service, so `Principal` is undefined. The funny point is, if you inject the language service into `AuthExpiredInterceptor` (which has no sense, I know), the bug is away, but half of the app shows translation not found.

However, I analyzed the need of the Principal service doing language stuff, and it turns out, that it is only needed to switch to the users' preferred language when logging in. This can be moved into the login Service. I'll PR this today.
