### ISSUE TITLE
Callback in ng-jhipster/data-util.service.ts

### ISSUE THREAD

**Issue by juanpmarengo** [jhipster/generator-jhipster#8772]
##### **Overview of the feature request**

I'm using JhiDataUtils.setFileData and I need to pass a callback function or, in the best case, that it returns a promise.

##### **Motivation for or Use Case**

I could make my own setFileData (and I will), but I think this is something that it needs to be out of the box.

##### **Related issues or PR**

None.

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by deepu105** [comment]
please provide a sample usecase with code example, for the generated app its not needed but ofcourse the if the usecase makes sense you are welcome to PR that

**Comment by juanpmarengo** [comment]
> please provide a sample usecase with code example, for the generated app its not needed but ofcourse the if the usecase makes sense you are welcome to PR that

```
setFileData(event, entity, field, isImage) {
        entity.name = event.target.value.substr(event.target.value.lastIndexOf('\\') + 1);
        this.dataUtils.setFileData(event, entity, field, isImage);
        // this.save();
}

save() {
        this.isSaving = true;
        this.subscribeToSaveResponse(this.agentService.update(this.agent));
}
```

this.agent has a file inside and I need to save it once the file data is set. Also I would like to set the name once I know the data is set whithout errors.

Apart from this use case, I don't understand why you shouldn't have a callback or promise in this.dataUtils.setFileData.

**Comment by deepu105** [comment]
@juanpmarengo are you willing to do the PR? if so don't hesitate to do it directly and refer this ticket. I'm closing the ticket since we won't be doing this. If you do the PR i'll review it

**Comment by deepu105** [comment]
If you can PR without breaking current method signature its fine

**Comment by vivekmore** [comment]
For the original request ( from @juanpmarengo ) I believe the signature will be 
`setFileData(event: any, entity: any, field: string, isImage?: boolean, cb?: Function)`
This is not a breaking change

For what I'm proposing, the signature further changes to:
`setFileData(file: File, entity: any, field: string, isImage: boolean, cb: Function)`
 which is a breaking change (If we end up agreeing on this, I'll make sure all references within jhipster code are updated)

A less destructive alternative would be (and I'm presenting only for the sake of completeness of analysis from my end here)
`setFileData(eventOrFile:any, entity: any, field: string, isImage: boolean, cb: Function)`
where we check the type of first parameter and take action of extracting data from it accordingly.
This will ensure existing code works and new code can pass a File instead of an Event.

Let me know what you think.

**Comment by deepu105** [comment]
@vivekmore its not about updating all reference alone. I'll like to follow sem ver and not introduce breaking changes unless in a major version. If you really want to change signature we can do it only for JHipster 6. 
For me the change to file is not that important.

**Comment by vivekmore** [comment]
I understand and agree that breaking change should be a part of next major release. 
Having said that, I can submit 2 PRs
1. now where we just add a callback function to existing signature
2. later for JHipster 6 (with a more refined signature) when it's time

**Comment by deepu105** [comment]
ya ok

Thanks & Regards,
Deepu
