### ISSUE TITLE
The server time zone value 'CEST' is unrecognized or represents more than one time zone.

### ISSUE THREAD

**Issue by tibistibi** [jhipster/generator-jhipster#8896]
##### **Overview of the issue**

With the fix of this issue:  #8284 i could not connect to my database any more.

##### **Motivation for or Use Case**

I upgraded jhipster which included the  #8284 fix and after that could not connect getting this error:

> Invocation of init method failed; nested exception is liquibase.exception.DatabaseException: java.sql.SQLException: The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

##### **Reproduce the error**

Deploy the application to a maria database. There probably will be certain reason why i get this and not everyone does so it could very well be a problem for only my situation but i wanted to have this fix here if others have the some problem.

Besides it could be more stable to add the timezone to the connection string, just making it more clear.

##### **Related issues**

#8284
##### **Suggest a Fix**

This can be fixed by adding this to the connection string to the application-*.yml files:

`&serverTimezone=UTC`

so it would look like this:

`url: jdbc:mysql://localhost:3306/jhipster?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC`

##### **JHipster Version(s)**

5.7.0+

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
@avdev4j : can you have a look and confirm the fix plz ?

**Comment by tibistibi** [comment]
yes seems so, i'm no expert i jsut noticed it and this fix helped me ;) on my dev machine i have a myssql db and on my server i have mariadb. on the maradb i got the error. i quickly looked to see if there was some obvious difference but i did not see any.

**Comment by avdev4j** [comment]
So i have just generated a new project with mariaDb and run it with docker-compose with the prod profile. I did not have an error like you.
Maybe because I run them on the same server and so with the same JVM and Maria time zone config.

Then I changed my configuration by adding "serverTimezone=UTC" and everything seems to be ok.

Could you please check both JVM, Mysql and mariaDb timeZone config for me ?

Since it has no border effect we could add "serverTimezone=UTC" but I want to be sur it will not do some regressions.
