### ISSUE TITLE
No question about relationships

### ISSUE THREAD

**Issue by iuricmp** [jhipster/generator-jhipster#901]
The questions concerning the relationships are never made when I use de command:

`yo jhipster:entity author`

I'm using the option: _java8 + mongoDB_.

**Comment by omrzljak** [comment]
support for embedded documents and dbref in MonogDB projects would be very useful.

**Comment by vw98075** [comment]
+1
For the current limited MongoDB domain object modeling support, you only can do some sort of hack for embedded documents so that you can get a better code structure to work on. .

**Comment by astik** [comment]
+1 for supporting embedded documents and dbref in MongoDB =)

**Comment by suryatejaswi89** [comment]
+1 for supporting embedded documents and dbref in MongoDB =)

**Comment by swilimo** [comment]
+1000 for supporting embedded documents and dbref in MongoDB =) 

Actually, i'm implementing that manually, but it would be wonderfull if it was supported "natively"

**Comment by jdubois** [comment]
Can you open up a new ticket for this? And contributions on MongoDB are really welcome!

**Comment by swilimo** [comment]
My pleasure, i will shoot when i'll have some bandwith this week (short delays & close deadlines on a project)

**Comment by loul42** [comment]
+1

**Comment by mouadtk** [comment]
+1 for supporting embedded documents and dbref in MongoDB =)

**Comment by jdubois** [comment]
There's no need saying "+1" on this old ticket: we all agree it would be a good feature (I even told it yesterday on the core dev mailing list, see https://groups.google.com/forum/?hl=en#!topic/jhipster-dev/KytDq6GGzyQ ). Nobody has ever coded this, and when there's no contribution, it just doesn't happen...
I'm sorry but I won't do it myself, as I don't have the need, and I'm not investing time in MongoDB.
So instead of saying "+1", please tell me you'd like to work on this, and the ticket is yours.

**Comment by mouadtk** [comment]
lol, actually, I have added the comment, then I noticed there is an open Feature request, 
I'll see what I can do on that.

**Comment by jdubois** [comment]
Excellent ! +1 for the PR :-)

**Comment by daibertdiego** [comment]
How can I contribute to this part? Because I have a project using SpringBoot, SpringSecurity, MongoDB, ZullProxy and a lot of other technologies that JHipster works too. But now, my database is full of DBRef relationships because I use Morphia as Mongo Framework and I'm very excited to migrate my project to JHipster and I would like to improve this functionality. Thanks

**Comment by jdubois** [comment]
@daibertdiego [here is our contributing guide](https://github.com/jhipster/generator-jhipster/blob/master/CONTRIBUTING.md) - we all agree that would be a great feature, but we have never found anyone to do it...
Please note that we might refactor the MongoDB support soon, as with Spring Boot 2 we might introduce the MongoDB reactive support.
