### ISSUE TITLE
Need to auto populate system columns

### ISSUE THREAD

**Issue by nitinpatel811** [jhipster/generator-jhipster#9164]
##### **Overview of the feature request**

Every entity will have below mentioned four columns in almost every use case.
- CreatedBy
- CreatedDate
- LastUpdatedBy
- LastUpdatedDate

I am proposing a new feature to add these four columns by default with every entity as we do with ID column. Also, logic to populate these columns, like auto populate **CreatedDate** and **CreatedBy** when "**create**" action is called and similarly for **LastUpdatedDate** and **LastUpdatedBy**.

##### **Motivation for or Use Case**

This is very common requirement for any UI based project. I feel this will be very handy and very welcomed feature for almost everyone around.

##### **Related issues or PR**

I could not find any related PR or issue regarding this.

-   [ x] Checking this box is mandatory (this is just to show you read everything)

**Comment by nitinpatel811** [comment]
sure, I will have a look on this. Thanks @deepu105

**Comment by jdubois** [comment]
The problem here is that I have at the same time people telling me this is super-important (like you) and people who want to get rid of it because it generates "bloat"...

As @deepu105 said the best is to have a module for this, and this is why I'm closing it, but this is a discussion we should have more globally: should have audits at all when generating the project? We could have it as an option or as a module.
