### ISSUE TITLE
Does jhipster have any plan to support spring cloud gateway?

### ISSUE THREAD

**Issue by KingZxx** [jhipster/generator-jhipster#9417]
##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by jdubois** [comment]
No, have a look in previous issues it's already discussed

**Comment by mrts** [comment]
Spring Cloud Gateway is getting more traction now, see https://mobile.twitter.com/andreasevers/status/1181965422784126976 

I did search issues, but didn't find discussions regarding this - @jdubois, can you point to the relevant issue please?

**Comment by gmarziou** [comment]
See https://github.com/jhipster/generator-jhipster/issues/7665

**Comment by jdubois** [comment]
I use it for my Azure Spring Cloud training at https://github.com/microsoft/azure-spring-cloud-training

So I'm just speaking here on a pure JHipster perspective.

It looks *a lot* like our current gateway. In fact, I'm having a good laugh at all the people on Twitter saying it's such a great idea to have a gateway which is just a Spring Boot app, as we've been having this for nearly 5 years, and we have thousands of people using it already in production :-)

Anyway, Zuul is dying, and I believe this is a great approach, as we've had a huge success with it over the last years. But everything isn't perfect:

PROs:
- Basically the same idea as our current gateway. So migrating would be really easy.
- Performance/scalability would be better than Zuul.

CONs:
- There will be an "enterprise" version of the product. For JHipster, I prefer to use "full OSS" products like ours, as otherwise we might hit some limitations that can only be solved by paying (which is a blocker for us, as we can't force all our users to pay).
- Being fully reactive means you need to use Spring Webflux everywhere, which adds a lot of constraints for our users.

-> please note, once again, that I'm giving those "cons" from a JHipster perspective. If this was only for myself, I wouldn't mind both of those, and in fact I would see them positively. That's why I use it for my Azure Spring Cloud training.

For me it's still early to consider: Zuul works really well, scalability isn't a big issue (performance is awesome, and you can scale nodes easily if needed), and on the opposite Spring Cloud Gateway is very new and I haven't seen anyone using it in production yet. So I'd rather wait, or provide it as a separate, simple option, like we have with Traefik.

**Comment by mrts** [comment]
Excellent analysis, thank you! Agreed, it's a bit early to consider, let's wait, and I fully agree that using "full OSS" in JHipster is preferable.
