### ISSUE TITLE
Generate OIDC realm name same as with app name

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#9502]
##### **Overview of the feature request**

Currently, JHipster generates all the realm settings with the name `jhipster`. This FR is to change the realm name to app name.
 

##### **Motivation for or Use Case**
This will unify the names across app and OIDC provider.

##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by vishal423** [comment]
this wouldn't be feasible in micro-services architecture.

**Comment by avdev4j** [comment]
Is this really an issue because teams will automatically change oidc config to match with theirs ?

**Comment by vishal423** [comment]
instead, i would prefer to rename `web_app` client with appname (assuming no conflict in naming rules)

**Comment by pascalgrimaud** [comment]
As @vishal423 said, it would not be easy to find the correct realm for microservices.
And because you can have different gateway applications, we can't choose 1 name for all.

It could be possible but we need to do the same thing we do with UAA, add another question, keep the value in `.yo-rc.json` etc.

Keycloak + realm files are provided here as default config, to quick start all projects. All the end-users should customize this config or use their own Keycloak.

Unless some else has another idea, let's close this as I don't think we should change the current behavior.
