### ISSUE TITLE
Improve all test automation project generation for travis CI to use jdl

### ISSUE THREAD

**Issue by pmverma** [jhipster/generator-jhipster#9651]
##### **Overview of the feature request**

Improve all test automation for travis CI to use jdl rather than having individual `.yo-rc.json` and many `EntityXXXXXX.json`. 

##### **Motivation for or Use Case**

Current setup for travis is working fine but I believe this can be improved to be a little easier to manage them.

This way newly added question/options/keyword can be also generated automatically without having to keep updating the entity json file manually. Entities relationship can also be seen clearly in the jdl file.

The idea is like following.

- Have 10 test jdl file which contains everything including app and entity options.
- Then from ci file, loop through those file generating the projects.
- Rest of the things such as front-end, backend testings and all other things will remain same.

@pascalgrimaud What do you think?
##### **Related issues or PR**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by pascalgrimaud** [comment]
I'll do long answer when back from vacations :-)

**Comment by pascalgrimaud** [comment]
@pmverma : thanks for your proposal. Here my point of view:

Our CI can already test JDL file. See this [config](https://github.com/jhipster/generator-jhipster/blob/master/azure-pipelines.yml#L44-L54) and the generation [here](https://github.com/jhipster/generator-jhipster/blob/master/test-integration/scripts/12-generate-project.sh#L14-L33)
Currently, I'm working on generating multi app with the same JDL, so we will be able to test microservices / docker-compose / Kubernetes.

Using the `jhipster` cli and `jhipster import-jdl` are 2 different workflows with common methods and I think it's better to test both.

About optimization.
- there are 51 entities in this [folder](https://github.com/jhipster/generator-jhipster/tree/master/test-integration/samples/.jhipster)
- if we add a new type, we need to check all these 51 entities

- the [daily builds](https://github.com/hipster-labs/jhipster-daily-builds) test more than 79 configs [here](https://github.com/hipster-labs/jhipster-daily-builds/tree/master/test-integration/samples)
- if we convert these configs to JDL and if we add a new type, we need to update 79 JDL

- by keeping the entities instead of moving to JDL, I can choose which entities I want to test, using `JHI_ENTITY` value - for [example](https://github.com/hipster-labs/jhipster-daily-builds/blob/master/azure-pipelines-elasticsearch.yml#L47)

So today, on my personal roadmap:
- update and finish my [ci-multi-app](https://github.com/pascalgrimaud/generator-jhipster/commits/ci-multi-app) branch
- rework all entities, as I think we can reduce the total number
- add full tests with JDL at [jhipster-daily-builds](https://github.com/hipster-labs/jhipster-daily-builds), as you suggested

To resume:
- I'd prefer to keep the current entities, as it is used by different configs (MySQL, PostgreSQL, etc)
- Moving to JDL means duplicate entities

Let's discuss

**Comment by ruddell** [comment]
>Moving to JDL means duplicate entities

You can group the entities in a single JDL file per group, then import multiple JDL files with a single command (you can pass a list of JDL files).

For example, we could create groups like `FieldTest.jdl`, `OptionTest.jdl`, `MapsIdTest.jdl`, `MicroserviceTest.jdl`, `Bank.jdl`, etc

**Comment by pascalgrimaud** [comment]
Seriously ? I didn't know that ! Looks very interesting. Thanks @ruddell 
The only problem today is I don't know if our users prefer use JDL or directly the sub gen entity. And we should focus on the use case which is the most used

**Comment by ruddell** [comment]
The current workflow (copy the entity.json files, then run entity generator) is similar to how JDL works (generate the entity.json files, then run entity generator).  ([jdl entity code](https://github.com/jhipster/generator-jhipster/blob/9fcec8181a8a4f8087f719d6548df0b182022334/cli/import-jdl.js#L191), [`with-entities` code](https://github.com/jhipster/generator-jhipster/blob/5c8181e5094d1c9c34209148bcd0e386b891b7d9/generators/app/index.js#L454-L467)).  We aren't actually testing the prompts so I don't see much of a difference.

You can see the same output at the end for both `jhipster import-jdl foo.jdl` and `jhipster entity Foo` (with existing Foo.json):

<details>
<summary>import-jdl vs entity generator output</summary>

`jhipster import-jdl foo.jdl`
```
INFO! Using JHipster version installed globally
INFO! Executing import-jdl foo.jdl
INFO! Options: from-cli: true
INFO! Found .yo-rc.json on path. This is an existing app
INFO! The JDL is being parsed.
INFO! Found entities: Foo.
INFO! The JDL has been successfully parsed
INFO! Generating 1 entities.
Found the .jhipster/Foo.json configuration file, entity can be automatically generated!
The entity Foo is being updated.
```
`jhipster entity Foo`
```
INFO! Using JHipster version installed globally
INFO! Executing jhipster:entity Foo
INFO! Options: from-cli: true
Found the .jhipster/Foo.json configuration file, entity can be automatically generated!
The entity Foo is being updated.
```

</details>

You can also pass [`--json-only`](https://github.com/jhipster/generator-jhipster/blob/9fcec8181a8a4f8087f719d6548df0b182022334/cli/import-jdl.js#L404-L406) to `import-jdl` which only generates the entity JSON files  (so you don't have to migrate apps to JDL yet).  This would let you keep the current workflow of copy `.yo-rc.json`, generate entity JSON from JDL (currently copy entity JSON), then `jhipster --with-entities`

In the end, it seems "cool" but I'm not sure how much value we would actually gain from this.  The main benefit I see is what @pmverma mentioned in the first post:
>This way newly added question/options/keyword can be also generated automatically without having to keep updating the entity json file manually. Entities relationship can also be seen clearly in the jdl file.

**Comment by pmverma** [comment]
Thanks @pascalgrimaud and @ruddell .
My main concern was keeping `.yo-rc.json` or `entitty.json` up-to-date is hard.
For eg, you can see not all `.yo-rc.json` contains followings which has been in main generator since previous version.
```
 "entitySuffix": "",
 "dtoSuffix": "DTO",
```
And also same for:
```
"useSass" : false,
.
.
"clientTheme": "none",
"clientThemeVariant": "",
```
I know this won't bring much value but we will have a consistent config file.

**Comment by pascalgrimaud** [comment]
The work is already in progress by @Hawkurane :
See the branch : https://github.com/Hawkurane/jhipster-daily-builds/tree/local_modifications?files=1

It won't be finished before weeks / months and I will help him to achieve that.

I'm closing this, as the work will be done at hipster-labs first and if necessary, we'll do the improvement directly in generator-jhipster.
