### ISSUE TITLE
Groovy language support

### ISSUE THREAD

**Issue by BhawaniSingh** [jhipster/generator-jhipster#9767]
##### **Overview of the feature request**
I would like to add the support for the groovy language via blueprint, since its jvm based language and spring has support for it, I think it would be easy to implement

Moreover there would be 3 languages to choose in jhipster for the backend

##### **Motivation for or Use Case**
It would add 3rd language to the server code generation

##### **Related issues or PR**

-   [x] Checking this box is mandatory (this is just to show you read everything)

Sorry for my bad english

**Comment by pascalgrimaud** [comment]
Hi @BhawaniSingh,

Maybe it's easy for you, but I think it will be a lot of work.
It would be similar to what it has been done with Kotlin: https://github.com/jhipster/jhipster-kotlin

Then, I don't understand your ticket here. Maybe for feedback ?
In that case, I think you should use Twitter instead of here. You'll have more feedback there, and see if the community is ready to help you or not.

**Comment by BhawaniSingh** [comment]
@pascalgrimaud I don't have big following on twitter that's why I asked here,
Even if I post it on twitter I don't think it will outreach to intended audience (as I haven't posted anything on the twitter)

I know creating a blueprint is a very lengthy process, but I'm ready for it
And yes I opened this issue for the feedback

**Comment by pascalgrimaud** [comment]
@BhawaniSingh : you don't need to have a lot of followers. Just mention `@java_hipster` and your message will be retweeted :)

**Comment by BhawaniSingh** [comment]
@pascalgrimaud Thanks :)

**Comment by pascalgrimaud** [comment]
As it can go to blueprint, let's close this.
Don't hesitate to tweet once you start the project!
