### ISSUE TITLE
Images at some marketplaces are broken

### ISSUE THREAD

**Issue by Tonterias** [jhipster/generator-jhipster#9859]
##### **Overview of the issue**

Mike @Tonterias 19:59
Hi Jon, All the images in the marketplace ( for example: https://www.jhipster.tech/modules/marketplace/#/details/generator-jhipster-banner ) are broken but there is no issues in the https://github.com/jhipster/jhipster.github.io and I do not know how to tell Pascal.

Jon Ruddell @ruddell 20:10
I think that's more of an issue with generator-jhipster-banner - the image is referenced in the readme as image.png which doesn't exist on jhipster.github.io, you can see line 6 https://raw.githubusercontent.com/PierreBesson/generator-jhipster-banner/master/README.md
Example of working images that use full URL: https://www.jhipster.tech/modules/marketplace/#/details/generator-jhipster-vuejs
I think you can open an issue on generator-jhipster for doc issues.

PD: is this the generator-jhipster for doc issues?

##### **Browsers and Operating System**

-   [X] Checking this box is mandatory (this is just to show you read everything)

**Comment by ruddell** [comment]
The images for `generator-jhipster-banner` don't load because it references a local image in the repository, instead of an image via URL.  You can see working images referenced via URL here: https://www.jhipster.tech/modules/marketplace/#/details/ignite-jhipster

So in this case, I think it's an issue to raise with the module and not the docs website.

Slightly related, the download count does not show in the marketplace anymore because npmjs does not support bulk lookup of stats for scoped packages [so the API request fails](https://api.npmjs.org/downloads/point/last-month/ignite-jhipster,generator-jhipster-vuejs,generator-jhipster-multitenancy,generator-jhipster-kotlin,generator-jhipster-docker,generator-jhipster-primeng,generator-jhipster-swagger-cli,generator-codegen,generator-jhipster-standalone-profile,generator-jhipster-swagger2markup,generator-jhipster-spring-cloud-stream,generator-jhipster-ionic,generator-jhipster-ci,generator-jhipster-coverb,generator-jhipster-bootstrap-material-design,generator-jhipster-primeng-charts,generator-jhipster-db-helper,generator-jhipster-pages,generator-jhipster-circleci-2,generator-jhipster-audit-helper,generator-jhipster-electron,generator-jhipster-angular-material-integration,generator-jhipster-elasticsearch-reindexer,generator-jhipster-entity-snowflake,generator-jhipster-leaflet,generator-jhipster-stripe-payment,generator-jhipster-leafletmap,generator-jhipster-uaa-security-authority,generator-jhipster-ff4j,generator-jhipster-database-backup,generator-jhipster-administration-database,generator-jhipster-quota,generator-jhipster-paypal,generator-jhipster-translation,generator-jhipster-transasia,generator-jhipster-swagger-api-first,generator-jhipster-database-helper,@xiges/generator-jhipster-siddhi,generator-jhipster-elasticsearch-reindexer-2,generator-jhipster-primeng-entity,generator-jba,generator-jhipster-feign-client,generator-jhipster-obfuscation-at-rest,generator-jhipster-testcontainers,generator-jhipster-kutilang,generator-jhipster-siddhi,@xiges/generator-jhipster-firebase,generator-jhipster-jgitver,generator-jhipster-vmware-clarity,generator-jhipster-apiutils,generator-jhipster-kaas,generator-jhipster-social-login-api,jhipster-ignite,generator-jhipster-string-converter,generator-jhipster-enterprise-pom,generator-jhipster-pace,generator-jhipster-compodoc,generator-jhipster-entity-audit,generator-jhipster-sample-blueprint,generator-jhipster-grpc,generator-jhipster-entity-audit-and-delete,generator-jhipster-postgresuuid-converter,generator-jhipster-helloworld,generator-jhipster-mssql,generator-jhipster-dbsequences,generator-jhipster-spring-social-connectors,generator-jhipster-fx,generator-jhipster-darktheme,generator-jhipster-skipserverweb,generator-jhipster-basic-auth,generator-jhipster-debian-packager,generator-jhipster-blockchain,generator-jhipster-angular-ui,generator-jhipster-fortune,generator-jhipster-google-analytics,generator-jhipster-angular-datatables,generator-jhipster-stormpath,generator-jhipster-gitlab-ci-build-status,generator-jhipster-cockroachdb,generator-jhipster-clevercloud,generator-jhipster-hatch-entitlements,generator-jhipster-bootswatch,generator-jhipster-nav-element,generator-jhipster-chatbot-rasa,generator-jhipster-aeropost,generator-jhipster-banner,generator-jhipster-entity-point-field,generator-jhipster-hatch,generator-jhipster-file2url,generator-jhipster-activiti,generator-jhipster-uuid-converter,generator-jhipster-google-maps,generator-jhipster-clarity,generator-jhipster-elasticsearch-rest-client,generator-jhipster-botw-theme)

**Comment by PierreBesson** [comment]
It's been a really long time no one has touched the code of the marketplace at [jhipster.github.io/modules](https://github.com/jhipster/jhipster.github.io/tree/master/modules). As we want to push people toward modules and blueprints more, maybe it's a good time to revisit it and make it nicer and more central to the website. Anyone interesting in doing this fun project ? @jhipster/developers @Hawkurane @Shaolans @clement26695

**Comment by pascalgrimaud** [comment]
Agree with Jon Ruddell.
If the authors of module want their image to be displayed in this section, they need to take care in their project (using url instead of local). It would be the easiest solution

As suggested by Pierre, It would be cool to improve our modules section, but I don't think it's a must have. We have a ton of tickets and this one doesn't deserve to spend more time
